### ISSUE TITLE
Crash when Rainbow Tree catches fire with no Mystcraft installed

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#1018]
https://gist.github.com/Haggle1996/4dd9dfe81a005794e16bbb34ca09c9c3

Really easy to replicate. Set fire to a rainbow tree. Other trees burn down just fine.

**Comment by Haggle1996** [comment]
In the interim, doing `/gamerule doFireTick false` at least prevents the crash. :P

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ghost** [comment]
Hm, I see that this bug is marked as "Fixed". Waiting for new build :-)
Also, @Haggle1996 thanks for tip.

**Comment by Aivech** [comment]
You'll have to wait for v16.

**Comment by TheGuyRunningSouth** [comment]
Do we have any estimated release date on v16? Between gamebreaking bugs
like this one and the flywheel bug, it makes doing a legit (read no item
spawning) playthrough nearly impossible, and the challenge of a legit
playthrough was the only reason I wanted to play with these mods. I've been
hearing "it's fixed in v16" for months now, and it honestly feels like
people asking about the state of the mod are just being snubbed at this
point, because the fix is being dangled in front of their noses and there
is no indication when, if ever, they can have it.

As a computer engineering major, I understand good software takes time, and
I don't wish to try and rush Reika's Dec process. My only request is
something along the lines of "V16 is 62% done, there are  two more features
and five major bug fixes before it's  ready for release." just to know that
the v16 update is not dead.

**Comment by Haggle1996** [comment]
As pretty much every mod maker will tell you, this is a hobby, not a paid
career. The exact release date is 'when it releases'.

**Comment by TomeWyrm** [comment]
@TheGuyRunningSouth 

Much like Haggle1996 said. "When it's done"

You obviously haven't done your research on the mods, because Reika has a standard release cycle, and that cycle hasn't changed since I've been aware of his mods. He releases a mod, then spends a few weeks fixing bugs and releasing patches, then he starts designing new features and systems on at least one of his mods, and then releases stop (barring true emergency-level bugs. No neither of these are emergency-level, they're not even game breaking. You can work around this bug quite easily, and there is no need to use flywheels when playing RotaryCraft (they're certainly amazingly helpful in some cases, but FAR from required). 

Also asking for ETAs is INCREDIBLY bad form in the modded community, and waving the "I'm like you so I'm entitled" card just makes you less likely to get an answer because that's a worse card than just plain entitled. Thanks to the community being a bunch of toxic entitled demanding jerks giving an ETA and then not holding to it like it's a law of physics (or doing better, and even doing better actually) will get you yelled at by people that ought to know better... in fact interacting with this community at ALL will get you yelled at, as will not interacting, interacting a bit, in limited ways, in some ways but not others, and just generally any and every decision you'll make as a modder in this community will piss SOMEONE off. In Reika's case, he doesn't coddle the entitled or stupid and this has soured some of the people with enough popularity (some deserved and others undeserved) to have actual ideological followers. As anyone that's studied psych or history should be able to tell you, followers often give up some of their reasoning and critical thinking when dealing with that subject, and so can often be much worse than their leaders. Which means his best bet to get something resembling peace and quiet and yet still release new content (because he does actually like parts of this community, by some miracle) is to maintain his personal rules and routines with the utmost strictness. This includes his release schedule, and methodology.

Oh that reminds me, one of the reasons he releases, bugfixes, and then goes into Dev Mode instead of just periodically releasing fixes is because of half-implemented new systems and features. Releasing these to the public would be a Bad Idea, so once he starts Dev Mode it takes an extreme circumstance to warrant breaking the normal release track.

**Comment by TheGuyRunningSouth** [comment]
@TomeWyrm, thank you for addressing my question in an educational manner. I
can understand why Reika wouldn't want to give updates. My question was
ill-informed, and I apologize for any offense I may have caused.
(Now to figure out how to charge a coil fully without a flywheel.)

**Comment by TomeWyrm** [comment]
Use gearing and a bigger engine
