### ISSUE TITLE
[CC] Crystal Bees cannot be collected with a Scoop

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1020]
Tested with both a normal Scoop from Forestry, and a Manasteel Scoop from Magic Bees, it takes a long time to break then gives me nothing.

**Comment by Ariaxis** [comment]
You don't use a scoop with Chromaticraft hives, you use a pickaxe.

**Comment by ReikaKalseki** [comment]
Scoops tend not to be very good at breaking rocks.

**Comment by TomeWyrm** [comment]
I inquired one time why, and I can't remember much other than doing that would involve something that makes it not-worth-it for one tiny feature. For example (not saying this is the actual reason, I really can't remember the why, just that his answer made total sense) making the hives require scoops would involve making Forestry a hard dependency for ChC or DragonAPI (I think DragonAPI... That's where basically anything that could be useful cross-mod gets put). Which is extremely undesireable for obvious reasons.

It is intentional that you need to break them with a pickaxe... and I wish there was an easy way... Ooohh, I just had an idea. Reika, the toast notifications on the right-hand side of your screen that give info about ChC blocks... the ones that come up every time you look at the block in question?

The ones localized here: https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Resources/hover.xml

Could you add one to Crystal Hives? Make it reference the durability or hardness and poke a bit of fun at using a bug net to break beehives?

**Comment by ReikaKalseki** [comment]
I like that idea.

**Comment by ReikaKalseki** [comment]
Done.
