### ISSUE TITLE
Crash with geostrata and Chisel

### ISSUE THREAD

**Issue by ray10k** [ReikaKalseki/Reika_Mods_Issues#1031]
When trying to launch MC with Geostrata and Chisel - Venerable (both the most recent versions) the game crashes during initialization.
The most recent versions of all mods involved are used.

Gist with the logs:
https://gist.github.com/ray10k/8a463d170e29a24e3eff48445cfb9b75

Additionally, this issue resembles issue #214 except in reverse, but with the same exceptions in the log.

**Comment by Keyarose** [comment]
Chisel has been picked up by another developer since the version you are using.  The new one is still being supported and (for me at least) works with the current version of Geostrata.  It should be fully compatable and be able to replace the old version without starting a new world.
Here's a link to the curse page for the new one: http://minecraft.curseforge.com/projects/chisel

**Comment by ray10k** [comment]
Thank you for the information, will rectify my mistake.
