### ISSUE TITLE
RotaryCraft: Powering Flywheel causes all blocks broken to not drop items, causes client to hang on "Shutting Down Internal Server" when quitting game.

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [ReikaKalseki/Reika_Mods_Issues#1046]
Game does not freeze and flywheel behaves as expected, but no items drop from broken blocks. Saving to title causes client to hang, and upon restart client has been reset to last save before flywheel was placed.

Log (or as much as I could get from the launcher): https://gist.github.com/TheGuyRunningSouth/885e65ac9f611d7a14600c695042ede3

**Comment by Builderb0y** [comment]
[Already fixed for v16.](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/734#issuecomment-227864390)

**Comment by TheGuyRunningSouth** [comment]
@Builderb0y are you referring to v15a or a version not yet released? Because I thought the fix you're referencing was implemented in v15a, which I am running.

If it's fixed in an as-yet unreleased version that's fine. I only reported it because it was something I hadn't encountered since the v15a update (which was after the referenced issue was closed) and I wanted to make sure the flywheel issue is good and dead.

**Comment by Builderb0y** [comment]
I did specify v16, not v15. It's technically possible for there to be a v15b version (in which case it will be fixed then), but given that v15 was a comparatively stable release, it is far more likely that the next version will be v16.

Regardless of which version is released next, the point is that this issue has already been fixed in code, so the next version to be released will not have this issue.
