### ISSUE TITLE
(ReactorCraft) Fusion Reactor will not bend plasma

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#1050]
To start, I swear that if this is user error, it's the most obscure error of all time.

Ok, now that that's out of the way. I have (attempted to) built a fusion reactor, but it is not working correctly. Upon being injected into the tokamak in a way that would cause it to travel counter-clockwise (along the same direction as the solenoid's spin), the plasma immediately goes in a straight line. There is NO bend to the plasma, which means that the toroid immediately after the injector is failing to create any effect at all. OneM_Industries and @DaMachinator from the #RotaryCraft IRC have assisted in person, but have failed to uncover user error.

Here's some pictures of the reactor: http://imgur.com/a/vUQUO
If you need any information, let me know. If you want to come on the server to inspect the reactor in person, let me know, or join #yuonsurvival in irc.esper.net

**Comment by redelman** [comment]
Double check all the toroids are facing in the right direction, and the charge on them from the VDGs.

**Comment by MajorGeneralRelativity** [comment]
@redelman The toroids all have blue arrows pointing into the center, and the charge is always over 20,000 kV (they also all have purple lightning)

**Comment by zemerick** [comment]
In the dragonapi config, set the config option to true to show NBT data, and hold tab on the Toroid. There are 4 things that matter.

Next: Should be 1b, this is the check that the ring is complete
Solenoid: Should be 1b, this is the check the solenoid is powered and correctly placed
Charge: Anything over 1,000 works, so you're at overkill levels there.
Coolant just needs to be over 0mb, so I'm betting you're fine there.

If it's the Next or Solenoid, one thing you can do is go to the east injector, and starting at the toroid just north of there, spin it all the way around to trigger an update. Check again to see if Next and Solenoid are 1b. If not, you probably have something wrong. If it is, but others are not, you can repeat this for the others and it will eventually get them all.

I can pretty much guarantee this will work ( quite a few tokamaks have been built that work fine ), and that it's not an issue. I will close it for now, but you should be able to post still. ( If not for some reason, just PM me. ) If anything changes and some issue is indeed found, I will reopen it.

For future reference though, you should post this to the MCF unless an actual issue is known.

**Comment by ReikaKalseki** [comment]
You built it wrong.

**Comment by MajorGeneralRelativity** [comment]
@zemerick So, I tried what you said, and both my Next and Solenoid are 0b. I tried breaking a block and replacing it to cause the solenoid to re-assemble, and it is till 0b even while spinning. 
Imgur of NBT data (I apologize for all the GUIs) http://imgur.com/gallery/nByR0G9
While Charge and Coolant both seem to be OK, Next and Solenoid are 0b.

As mentioned above, I tried breaking and reforming the solenoid, with no luck. I went to the toroid north of my east injector block and tried slowly spinning it around, but nothing changed.

**Comment by zemerick** [comment]
Start by placing the tokamak blueprint back down and double checking all of the placements then, especially paying attention to the height of the solenoid. Next, double check the solenoid power: At least 256r/s and 32,768 NM. That's really all there is to getting the solenoid working.

Next typically won't update unless you have the solenoid working, so don't worry about then until after.

**Comment by MajorGeneralRelativity** [comment]
@zemerick 
Alright, so I found one issue. My solenoid was at the wrong height, and now my NBT data does show solenoid 1b, which is a plus, because now I'm half way :) After re-constructing and powering the solenoid, I attempted to rotate the toroids at the east injector block 360 degrees, and then checking for Next 1b. Unfortunately, my toroids are stubbornly stuck at Next 0b and Solenoid 1b. I then placed down the tokamak highlighter again, and verified that all toroids and injector blocks were in the correct position. As far as I can tell, they are. I then verified that all toroids are pointing in to the center. They are.

Imgur album with detailed toroid pictures and NBT data: http://imgur.com/a/jXtlm

So, I'm halfway there, but I need a little help getting the other half :P
EDIT: The NBT data was still the same with the injector fully assembled

**Comment by zemerick** [comment]
Looking at your second and third image, it seems you have injectors pointed in opposite directions. They must go in the same direction.

**Comment by MajorGeneralRelativity** [comment]
@zemerick That fixed it! My fusion reactor is now operational! All citizens of the Global Empire thank you for your assistance zemerick. You're welcome on my server any day!

I'm also going to make a fusion reactor tutorial series so people won't make the same mistakes I did :)

**Comment by llMADNESSll** [comment]
I don't know if anyone here will answer me, but I have a similar problem. The reactor is not working properly. 1 of the 4 injectors is connected to the reactor and supplies plasma. The toroid magnets are arranged in the right order and are powered by a Van de Graf generator, (output speed: 65536 rad/s, output torque: 1024 Nm). The solenoid is also powered by a Van de Graf generator, output speed:1024 Nm, output torque: 65536 rad/s. I don't know if this is important, but I was able to find DragonAPI, RotaryCraft and ReactorCraft only in version 7f, because attempts to find all these mods in the latest version were not successful, they are simply not in the public domain no matter how much I searched! Some of them will always be a version higher or lower, so this is the only version I could use. I have already tried to break the solenoid and build it, in this version it just us, so this is an extremely useless task. What could I do
![2021-09-23_11 45 55](https://user-images.githubusercontent.com/91251730/134480710-163fe389-c69d-4d50-b484-467dbe0e5609.png)
![2021-09-23_11 46 48](https://user-images.githubusercontent.com/91251730/134480715-55aa0997-7051-4c7a-8ba3-0b1bff827565.png)
?

**Comment by zemerick** [comment]
This is definitely not the correct place for this kind of help. It has been years since I've kept up with this stuff, but the minecraft forum thread should still be a good place to ask for general help.

I believe the only places to get Reikas mods are Curse Forge and his website ( and he only ever has the most current version available. Older versions are purged. ), and v7f is well over 5 years old. You aren't really going to get any help with that old of a version, because things will be incredibly different. Also, depending on where you got that old version, it could easily have a virus in it, since it clearly was not from a legitimate source. You really shouldn't run executable code from illegitimate sources.

I recommend you remove those files, run virus checks, download and use the current version. There's a high chance you'll need to create a new world too, as that world likely won't survive the update.

**Comment by ReikaKalseki** [comment]
Also, that reactor is visibly incorrect.

**Comment by llMADNESSll** [comment]
> Also, that reactor is visibly incorrect.

What exactly is wrong with it?

**Comment by ReikaKalseki** [comment]
Missing pieces, to start with.
