### ISSUE TITLE
ChromatiCraft Error V.15a

### ISSUE THREAD

**Issue by Daminer5** [ReikaKalseki/Reika_Mods_Issues#1061]
[Crash Report](http://pastebin.com/jt36LcXM)
looked through the crash report and found this and googled it, and found nothing that worked. any ideas?

Reika.DragonAPI.Exception.InstallationException: DragonAPI was not installed correctly:
Could not add sound category CHROMA! Use the Sound HashMap config!

**Comment by HellFirePvP** [comment]
"Could not add sound category CHROMA! Use the Sound HashMap config!" - I'd suggest looking into DragonAPI's config and looking for the config option "Use Sound HashMap" or something like that, as the exception already suggests.

**Comment by DracoScythem** [comment]
Go to config/Reika/DragonAPI.cfg and change
`B:"Use HashMap for Sound Categories - Only use if necessary"`
to true

**Comment by Daminer5** [comment]
it fixed that issue but i now have another one [Crash Report](http://pastebin.com/SJVcdR3e)
is it something in the configs?

Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
CONFLICT: Biome IDs: biomesoplenty.common.biome.overworld.BiomeGenChaparral@6ca73b64 @ ID 48 (BiomeGenChaparral & BiomeRainbowForest)

**Comment by HellFirePvP** [comment]
Biome ID conflict. Again the exception already tells you what's wrong. one biome id of biomesOPlenty is conflicting with the chromaticraft rainbow forest id. Change one of the id's in one of the mod's configs to a free id.

**Comment by Daminer5** [comment]
Going into the Configs for ChromatiCraft and changing it to a different ID fixed it
Thanks guys! :+1:  :)

**Comment by ReikaKalseki** [comment]
If you are that unwilling to read, you are **not** going to enjoy ChromatiCraft.

**Comment by YaoiSenpai** [comment]
I need help with this I'm having the same issue but there's one problem while I understand that I need to change the config setting for  B:"Use HashMap for Sound Categories - Only use if necessary"  but I have no config in my config folder  because the game crashes before the mod can create one. I've also been checking in side the mod itself and I can't find it. Can somebody please help

[EDIT] I was an idiot and I found the config file, sorry...
