### ISSUE TITLE
The play for doesn't with help

### ISSUE THREAD

**Issue by tomatocracker** [ReikaKalseki/Reika_Mods_Issues#1069]
:(

**Comment by HellFirePvP** [comment]
Could you please add some information? The headline doesn't really imply which one of Reika's mods this is related with, nor does it say what exactly went wrong or didn't work the intended way. Issue reports should at least include what exactly went wrong/didn't work and how to reproduce it. Also keep in mind to use the latest version of his mods, since outdated versions could contain bugs/exploits that are already fixxed.

Unless this issue is related to something that was discussed somewhere else and Reika or one of his collaborators are informed about this, please add the necessary information.

**Comment by ReikaKalseki** [comment]
Not to mention it should be _coherent_.
