### ISSUE TITLE
DragonAPI/Chromaticraft chat spam using casting table

### ISSUE THREAD

**Issue by blindmoomoo** [ReikaKalseki/Reika_Mods_Issues#1080]
@ReikaKalseki Hello I have this error popping up on my server(in the chat) everytime I craft Crystalline stone using the Elemental Manipulator on the casting table with Chromatic Craft. The error do not show when I'm sneaking while clicking with the elemental manipulator.

http://pastebin.com/uPaNSbg0

Mods installed on my server : ae2stuff 0.5.0.56, Applied Evergistics 2 rv3 beta 6, Bdlib 1.9.4.109, Chromatic Craft V15a, Code Chicken Core 1.0.7.47, CoFHLib 1.1.2-182, DragonAPI V15a, Electricraft V15a, Enchanting Plus 3.0.2-d, ExtraCells 2.3.14b197, Fastcraft 1.23, IGW 1.1.12-34, Inentory Tweaks 1.59 dev 152, Iron Chest 6.0.62.742, Journeymap 5.1.4p1, mcjtylib 1.8.1, Not Enough Items 1.0.5.120, Reactor Craft V15a, Rftools 4.23, RotaryCraft v15a, Territory Zone V15a, Waila 1.5.10, Worldedit Forge 6.1.1

**Comment by HellFirePvP** [comment]
Related to #958  

According to what reika said not too long ago "It happens because the table 'forgets' the player who placed it down" for some reason. It
1) does not affect the result of the crafting,
2) is probably client-side only and
3) can be/should be solved by picking it up and placing it down again (apparently?)

**Comment by blindmoomoo** [comment]
First i wanna thank you for answering but how can we be "sure" it's client side only and second...this might sound noob but how do i break the casting table because i tried alot of thing and nothing breaks it lol

**Comment by HellFirePvP** [comment]
"popping up on my server(in the chat)" - it only does that on clientside.
(as you can see here: https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/IO/ReikaChatHelper.java#L92 )

If you're the "owner" of the casting table, aka the one player that placed it down, you can break it. If you're not, well then you can't break it. As i do lack knowledge on how exactly this works or how this is implemented, i can't provide exact information on that regard, i'm sorry.

**Comment by blindmoomoo** [comment]
Thank you for the quick anser

**Comment by blindmoomoo** [comment]
So, it doesnt have any effect on the server? Is it just an anoyance or does it have any severe effect?

**Comment by HellFirePvP** [comment]
As far as i'm aware it only happens clientside and doesn't have any effect on the item crafted. Thus it might only be clientside annoyance. It could have a sideeffect on the server i'm not aware of, but it never caused any issue to be besides the annoying message.

**Comment by jsrfuture** [comment]
I'm the server owner. Here a couple more info :  the server was created in online-mode=false. The chat log error only happen in online-mode=false. We can't break casting table, item casting stand and chroma collector when in online-mode=false. Everything worked normaly when I switched it to online-mode=true.

Hope this help.

**Comment by ReikaKalseki** [comment]
Nothing that works on a per-player basis works in offline mode.

**Comment by jsrfuture** [comment]
okey, thank for the info. I think you should add to the faq or somewhere that chromaticraft so not support offline-mode. I'm probably not the only one who took way too long to figure out why we couldnt remove some item, even when just placed.

And we still have the chat spam, but it's not systematic now. Thanks for your time.

**Comment by TomeWyrm** [comment]
@jsrfuture Honestly that should cross your mind when you turn **player authentication** off :-p

**Comment by Aivech** [comment]
@TomeWyrm For some people, "locked to player" != "when player auth is off, mod does not work"
Notably, Thaumcraft research seems to be tied to player name and not UUID.

**Comment by ReikaKalseki** [comment]
> Thaumcraft research seems to be tied to player name and not UUID.

Yes, which means you lose all of it if you change your account name. This is dumb.

**Comment by Aivech** [comment]
> Yes, which means you lose all of it if you change your account name. This is dumb.

Agreed, would you like to know how I found out?

**Comment by ReikaKalseki** [comment]
...By changing your name?

**Comment by Aivech** [comment]
Yes. In addition to that, I lost my baubles and IIRC my Tinker's inventory stuffs.

**Comment by TomeWyrm** [comment]
Welcome to people being silly/lazy in the wake of a systems change. Your name is not unique in offline mode, and tying anything to a spoofable value like username is ASKING to get that whatever-it-is usurped. They need to change it to "nickname" because that's what it is now, it's a handle, a nickname, a transient identifier.

That being said, for those people that don't think turning username/account verification off might interfere with user-related things really ought to re-examine their assumptions and brush up on deductive/inductive reasoning. They also ought to be looking into what the flags actually do... but I can see how that's a crapton of work for someone without familiarity with programming concepts. Like the No Flight gamerule, I bet it doesn't work like you think it does (unless you've looked at the code. I obviously wasn't talking to you Reika :-))

**Comment by ReikaKalseki** [comment]
I fixed something else that was triggering the same apparent issue.
