### ISSUE TITLE
Crash: java.io.UTFDataFormatException: malformed input around byte 122

### ISSUE THREAD

**Issue by Yamakaja** [ReikaKalseki/Reika_Mods_Issues#1083]
Disclaimer: I'm not even sure if this was caused by one of your mods, but i was told to just go for it and ask for help here ;)

I was playing with ReactorCraft when suddenly something at my reactor started trying to create malformed packets which crash the server: http://hastebin.com/ojosenofeh.1c

Any ideas?

(It doesn't happen when i'm not near the reactor)

**Comment by ReikaKalseki** [comment]
This is chunk corruption, not packets.

**Comment by Yamakaja** [comment]
Are you sure? Because like i said, everything works as long as i'm not nearby :/

**Comment by HellFirePvP** [comment]
Pretty much, i'd assume something in that chunk was not saved correctly or simply contains malformed data. Once it needs to load and send said data, the server (more or less is forced to) notices that and well. crashes.

As long as you're not nearby there's no reason to load or send the data, thus the server behaves normal.

**Comment by Yamakaja** [comment]
Oh sorry, i forgot to mention that the chunks are chunkloaded and my reactor works fine as long as i'm not nearby

**Comment by HellFirePvP** [comment]
That doesn't change anything regarding the fact. The corrupted data might not cause an issue immediately, for example if a tileentity, whose data is malformed, is not touched by anything serverside and thus it never reaches a state where it could notice the data corruption and crash. In case you go near the chunk, the whole data regarding that chunk has to be serialized and sent to the client.

Additionally, a line in your crashlog does suggest it is not chunkloaded:

L20: at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121)

That's normally only called in case a chunk needs to be loaded from disk. If that only happens if you go near the chunk it can't be chunkloaded or it'd crash once the chunkloader tries to load the chunk which would normally be when the server starts (or the world loads, not so sure on that regard) which would then be much earlier before you could even get close to successfully log in to the world.

EDIT: The part of the chunk that's malformed seems to be the "Entities"-tag - That tag is a vanilla minecraft tag which contains the data of all entities inside the chunk.

**Comment by Yamakaja** [comment]
Thats very interesting. Does that suggest that something NEAR my reactor is causing that?

**Comment by HellFirePvP** [comment]
No that simply suggests a chunk contains corrupted data.

**Comment by Yamakaja** [comment]
I guess i will have to play around with mcedit a bit, thanks for your help anyway

**Comment by HellFirePvP** [comment]
Wiping all entities from that world might help since it seems to be entity related.

**Comment by Yamakaja** [comment]
What tells you that?

**Comment by Yamakaja** [comment]
Nvm, saw it

**Comment by HellFirePvP** [comment]
Your crash log. It tells you the subtag it failed to read, which is the Entities tag. (Seen in L44+)

**Comment by Yamakaja** [comment]
There was indeed a nearby chunk that got unreadable (mcedit actually showed me an error when trying to read it). Just deleting it fixed it (There was nothing but normal terrain in it)

Edit: Very well diagnosed by reika :D
