### ISSUE TITLE
[CC] Request: Restrict Chroma Resets until later progression

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1122]
It makes no sense to have it constantly resetting on world unload/load if I haven't even started the mod yet, let alone approached that level of progression. It just makes it take longer to exit the world. I get if this isn't possible, just a suggestion.

A way to make it stop resetting at all would be great, but I doubt that's going to happen.

**Comment by ReikaKalseki** [comment]
And if someone else on the server _does_ have progression?

**Comment by ghost** [comment]
It has been talked about to prevent it from loading if a player times out but there has never been a good solution that could also cause a problem.

**Comment by TomeWyrm** [comment]
I understand the request, but it's just not possible without worse performance hits for some form of check than you get from the dimension being itself while still maintaining the required properties of the dimension.

**Comment by Shahelion** [comment]
I was thinking either until at least one person on the server has reached appropriate progression, or at least one person has visited Chroma at least once. No need to keep loading and unloading it until then.

**Comment by Builderb0y** [comment]
It should never be loaded unless someone actually goes there, which can never happen unless someone has the progression to do so. Additionally, all the calculations for placing the structures is done in a separate thread on startup, so that shouldn't cause any lag either.

As for preventing it from resetting when a player times out, there are currently 2 problems with that. Problem 1: actually preventing the dimension from unloading; the only way to do this is by force-loading a chunk there. The forge chunk loading system uses tickets to load chunks, and reika essentially trashes ALL tickets in the chroma dimension. While it is theoretically possible to not do so or make exceptions for his own tickets, the tickets themselves do not contain enough information to distinguish "player lagged out" tickets from any other ticket from chromaticraft (as there are other blocks in chromaticraft that need to load chunks). A hidden chunk loader in the chroma dimension could prevent EVERYONE on the server from being able to complete it, which is why it trashes tickets and resets on unload in the first place.

Problem 2: the logic behind when to prevent resets. This obviously can't be a block or item that you use to temporarily prevent resets, as it would then have the same problem as any other chunk loader; even if you have to keep it fueled, like the railcraft one. There will always be a mod capable of force-feeding it fuel even if it doesn't connect to conduits (think routers, for example). Additionally, the player never knows when they might lag out, so they cannot simply place it just before then. This means that it would have to last long enough for the player to complete a structure, which has the side effect that as soon as one player places one, another player that enters could find the structure they need either already completed, or un-completeable, which would be quite frustrating if you just spent the last 10 minutes flying out to it.

Ideally, the best solution would be to have a chunk magically load if a player times out while in the dimension, though it is currently unknown if it's even possible to distinguish "player logged out" from "player timed out"; as intentionally relogging is a good way to get out of a structure if you're stuck on it, or re-shuffle the structure locations if everything you need is too far away from you. Even if you could distinguish them though, there's also the issue of how long to keep it loaded. If this timer is too short, the dimension could still reset before the player gets a chance to log back in. This is especially true if the player crashes while in the dimension, as my own client takes 20 minutes to launch my instance last time I timed it. If the timer is too long, then it has the exact same problem that fueled chunk loaders do.

Having it be player-specific and reset anyway if another player enters is also not an option, as then it wouldn't be accomplishing its main goal of preventing resets for the first player. And then what happens if 2 or more players are working together to solve it at the same time? If a lag spike kicks both of them, they'd need to know who the server is "holding" the dimension for, and communicate to each other who should log back in first, which isn't always possible either.
