### ISSUE TITLE
[CC] Worldgen Structures Interfering

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1146]
Not sure if it's possible to make worldgen structures check for others nearby, but if so, it should definitely be done. At the very least, just the ones from this mod and vanilla. These were both generated after updating to v16d.

Pylon and Sandy Burrow
![2016-10-12_10 50 23](https://cloud.githubusercontent.com/assets/6917535/19321475/02302228-906a-11e6-969f-15ec51afa8cb.png)
Pylon, Sandy Burrow, AND Desert Temple
![2016-10-12_10 50 41](https://cloud.githubusercontent.com/assets/6917535/19321476/02365918-906a-11e6-88ca-6c38b41bf529.png)

**Comment by HellFirePvP** [comment]
"Structures" are like Trees: A collection of 'random' blocks in the world without any connection.

Sure, some of reika's structures (like the sandy burrow, ocean temple, ...) do have a structure controller that could potentially remember all offset positions of the blocks involved in the structure, but as for world generation, checking for those is mostly too computationally expensive to be done. In addition to that, structures are generally kinda rare and thus it's really unlikely that 2 structures generate on top of each other or generate right through another structure. Generally that only happens if very certain and more rare conditions are met or one of the structures (namely the one that generates on top of the other) doesn't do enough block checks to validate if the terrain/blocks meet the structure requirements.

As far as your 2nd screenshot goes: i'd say the pylon and the sandy burrow don't intercept/invalidate each other at all. i do suspect the minecraft pyramid to be at fault here (can easily be seen by the fact that it just replaced the pylon parts with sandstone).

Going back to the actual question: No i don't think you can check for other structures reliably since they are essentially just random blocks in the world. There's nothing that says "this block is part of a structure of that mod".
