### ISSUE TITLE
[Electricraft] Superconducting wires melt in complex networks

### ISSUE THREAD

**Issue by Eb-** [ReikaKalseki/Reika_Mods_Issues#1167]
When pulling and splitting power off of a turbine via electricraft, superconducting wires are prone to melting if the electricraft network's complexity is too high. This makes it very difficult to fully utilize a turbine for multiple smaller systems.

**Comment by ReikaKalseki** [comment]
The alternative is the server freezing for a minute at a time every time you change the network topology. That said, the melting mechanic is intended to be temporary, until I can think of a better solution.

**Comment by DracoScythem** [comment]
[Assuming the problem lies within path-/connectivity-finding]
Maybe use mechanics similarily to HexCraft?
(Have some type of controler or item that needs to be used to initialize the connection)
(Perhaps a voltmeter that needs to be clicked on the cables directly connected to the machine/battery)
[Although that might require a partial rewrite of the E-Net and could scratch the image of having a 'real' Elecricity Network]

**Comment by LordOOTFD** [comment]
I have had this problem in my Revolution 3 mod pack game with melting wire in a rather simple network, how can you tell if your network is too complex?

The setup I have is a gas turbine running a generator connected to about 8 motors using relays and resistors. The network is usually stable but melts occasionally when I remove a wire, or reliably when I unload the chunk then return.

**Comment by ReikaKalseki** [comment]
Having dug into the code for other reasons, the limit is 500 paths and/or 500 inter-wire connections. So a 12x12 grid of wire will exceed that (central 10x10 has 4 each, four 1x10 edges have 3 each, and four corners have two each, so 10x10 * 4+1x10 * 4 * 3+4 * 2 = 400+120+8 = 528 > 500).

**Comment by Builderb0y** [comment]
> the limit is 500 paths and/or 500 inter-wire connections

Neither of which are particularly hard to exceed. Remember my [original report](http://i.imgur.com/iEK3u7f.png) on this all the way back in 1.6? That MASSIVELY exceeded the 500 path limit, with only 6+6\*5+12\*4+8\*3 = 6+30+48+24 = 108 connections. On the other hand, 500 connections can be exceeded with only 1 path, simply by transmitting power more than 250 blocks.

Additionally, that's not the end of the issue. Several people have now reported their networks melting with relatively simple setups. In one case, a single wire connecting a battery to a motor. I know things attached to generators are considered part of the network, but unless things attached to the battery or the motor are also considered part of the network, I fail to see how such a setup could exceed either of these limits.

Remind me again why you use a depth-first search system to find paths? A breadth-first one could easily find every motor connected to a given generator, and its taxicab distance, without tripping up over networks with loops in them. Plus, it's guaranteed to always find the shortest possible path between generator and motor*. Is there more information you need about the network topology than that?

*Only finds one of the shortest paths. If multiple paths of equal length exist, one is effectively chosen at random.

**Comment by ReikaKalseki** [comment]
The problem is not in finding the paths, but in calculating the properties of *all* of them. This has nothing to do with a depth-first search.

Also, simpler networks might be melting due to a now-fixed issue where clearing a network did not reset the "interwire connections" counter.

**Comment by Builderb0y** [comment]
Fewer paths (one per motor, per generator) means less properties to calculate though, unless I'm misunderstanding what you're describing. My point was that for networks with lots of loops in them, a depth-first system would, if I understand correctly, find LOTS of paths between every generator/motor, due to the fact that paths can go backwards. Breadth-first does not have this problem.

**Comment by ReikaKalseki** [comment]
The algorithm *needs* to find every path, not just the shortest.

**Comment by Builderb0y** [comment]
What about paths like these?
![](http://i.imgur.com/4BSPGJL.png)
If neither of those are needed, then the search algorithm can be optimized massively, and I already have an idea on how to do so in a way that still finds all paths equal in length to the shortest one. If red is needed but yellow isn't, it can still be improved, though the logic for doing so is a bit more complicated.

**Comment by Aivech** [comment]
IIRC electricity always takes the path of least resistance. For non-superconducting wires, this is the shortest path (unless there is a resistor in the way). For super-conducting wires, it can be assumed to be the shortest path, unless there is a resistor in the way.

**Comment by ReikaKalseki** [comment]
Again, *all* paths are needed.

**Comment by svipthedrunk** [comment]
Why are all paths for a single source/sink pair needed?

Digging through the code, it seems to me that only the shortest path between a source and sink is used.
(the method getCalculatedPaths from the class PathCalculator is never used)

**Comment by ReikaKalseki** [comment]
> Digging through the code, it seems to me that only the shortest path between a source and sink is used.

Untrue. To get accurate - and (arguably) more importantly, *balanced* (i.e. exploit free) - point voltages at every position requires knowing all paths.

Resistors notwithstanding, at every point, the voltage is the lowest voltage of all paths passing through that point, where a path voltage is source voltage less the resistance accrued by that point. Current is the sum of that of all paths through that point, with a path's current being the source current divided by the number of paths originating at that source.

And since it was asked last time I explained this, the aforementioned calculational intensivity is **not** due to calculating point voltages or currents; that is only done on demand (this is the source of the "changing power input = lag" behavior). It is on calculating the various paths at all.

If I start ignoring paths, and only use the shortest, certain points along a wire network will have zero current, which is nonsensical and unrealistic; others may have overly large voltages and/or currents that allow for exploits, i.e. more total power out of a network than in.

Additionally, most people's solutions to this problem - often involving balancing or voltage/current "creep/bleed" (think RC pipes) - are both unrealistic and assume superconducting wires; with nonzero resistances, those ideas break down entirely.
![](http://i.imgur.com/XT3sRw5.png)

**Comment by svipthedrunk** [comment]
**As is State (v16d; commit Update 176 - v16d):**
> the voltage is the lowest voltage of all paths passing through that point, where a path voltage is source voltage less the resistance accrued by that point. Current is the sum of that of all paths through that point, with a path's current being the source current divided by the number of paths originating at that source.

I created a simple network in creative and got the following result:
```
---0----     - : air
--0034--     digit: platin wire (voltage = digit * 16)
M000256G     M/G : Motor/Generator (generator gets 12 rad/s from industrial coil)
--0010--     up=north
---0----
```
```
---0----     - : air
--0111--     digit: platin wire (current= digit * 125)
M111111G     M/G : Motor/Generator (generator gets 1000Nm from industrial coil)
--0110--     
---0----
```
Compared to what I understood from your text, it seems to me that a few paths were not found or not considered. In fact it seems only one path was used.
This behaviour matches my previous statement 

> Digging through the code, it seems to me that only the shortest path between a source and sink is used.

To get the Point voltage in the method `calcPointVoltage` you go other all the paths inside `Collection<WirePath> paths`. For the current it is similiar. This Collection is only populated inside the method `recalculatePaths` with the following code:
```
PathCalculator pc = new PathCalculator(src, sink, this);
pc.calculatePaths();
WirePath path = pc.getShortestPath();
if (path != null) {
	paths.add(path);
	dimIDs.addAll(path.getDimensions());
	loadedDimIDs.addAll(dimIDs);
	this.validatePathLimit();
}
```
**Proposal 1**, a (partially) new algorithm.
All voltages are calcutlated together:
```
method calcVoltages(){
  i=0
  foreach source in network {
    i++
    fillNetworkFrom( (Wire)source.output , i )
  }
}

method fillNetworkFrom( (Wire)w, int i){
  nu = w.volt[i] - w.dv // calculate new voltage = previous voltage - voltage drop from cable
  foreach x in w.connected(){
    if( !x.volt[i] && x.volt[i]<nu){
      x.volt[i] = nu;
      fillNetworkFrom( x , i )
      // optional/additional logic to generate sub networks
    }
  }
}
```
**Proposal 2** works best together with proposal 1
Divide the network into groups. Elements inside a group share the same current. Now calculate the current like you described in the previous post, and treat each group as a single wire tile entity. Good seperators would be Motors, Generators, Batterys, Fuses, Resistors etc. Long simple lines of wire could be seperators/own groups as well, but detection could be a little mor difficult.

**Eval of Proposal 1 and 2**
I'm not an expert regarding optimization, but I think depending of network type this could lead to performance improvments.

**Proposal 3** if you do not like proposal 1 and 2
Get your code and what you say about your algorithm in line. Sadly this does not fixes performance issues.

**Proposal 4** "hiding" the problem
Off load the bulk of the calculation to another thread. This hopefully prevents the server from freezing if implemented right.
If a change to the network is registered set all the values (current/volatges) to not defined, stop all poweroutputs and kill threads calculating the affected network. Then wait a certain time (configurable?) for more changes to the network. Each change resets the timer. Once the timer finishes, create a copy of the network. Hand this copy to a thread outside of the game loop. Once it has finished, validate the copy against the live version and then apply the new values.

**Comment by OvermindDL1** [comment]
I'm about to reach Electricraft on my Reika-pack I built for my family, but if I read it correctly then Electricraft uses real-world calculations for power, in which case every path is needed to be known, however have you thought of using a standard electrical matrix solver to solve the calculations instead of tracing paths?  It would involve caching the locations of not necessarily the wires themselves by end-to-end connections (unless the wires have a natural resistance that is not based on distance but rather based on per-block, in which case each block would be a node on the matrix, though pre-calculating can ameliorate that cost) then use standard electrical simulation solving on the matrix.  Adding/removing things to/from the energy network would become significantly faster as it would involve just shuffling the matrix in a linear way while having an entirely accurate-to-real-world energy network.  If you do some ASM magic at runtime you could even bake the network as it is changed into an optimized code path as well, although that would involve significant work and the matrix solver would be fast enough in most cases, especially if you add costs to complex energy nets to dissuade their use (other than frying cables, although complex networks in an electrical matrix solver do not go up exponentially in calculation cost with circuit size so it would not be much of an issue anyway).

**Comment by ReikaKalseki** [comment]
I have never heard of what you are talking about.

**Comment by OvermindDL1** [comment]
Basically how the SPICE-like programs work, they emulate a sparse matrix, here is a quick read that can get started:  http://www.ecircuitcenter.com/SpiceTopics/Overview/Overview.htm
You can see one running in javascript (so you can see the source) here, it is the algorithm's that are useful:  http://www.falstad.com/circuit/
The solutions work with both AC and DC circuits as well.

**Comment by ReikaKalseki** [comment]
I am not about to implement a thing I have no understanding of and thus will never be able to troubleshoot.

**Comment by OvermindDL1** [comment]
Heh, sorry, I'm an electrical engineer and programmer in real life, I tend to forget which domains I need to focus on at times.  ^.^

It is well worth learning though, and the algorithms are nicely succinct, it would not only allow the energy representation to be accurate and fast but could help to develop more in the future though.  :-)

**Comment by ReikaKalseki** [comment]
A fully-realistic simulation is actually undesirable, because 99.9% of players will get extremely unintuitive results that often make no sense unless you actually analyze the network (like "add a generator next to a machine and get lower current into it" nonsensical). It is also *far* more difficult to verify in realtime without resorting to complex manual calculations (contrast with my system where it is very easy to check with simple arithmetic).

**Comment by OvermindDL1** [comment]
> A fully-realistic simulation is actually undesirable, because 99.9% of players will get extremely unintuitive results that often make no sense unless you actually analyze the network (like "add a generator next to a machine and get lower current into it" nonsensical). It is also far more difficult to verify in realtime without resorting to complex manual calculations (contrast with my system where it is very easy to check with simple arithmetic).

True true.  :-)

Redpower back in the day was building an energynet that was this kind of weird pseudo-mix of A/C and D/C, it used a cellular automata model to handle it, it worked very well, and was entirely non-recursive.  That was a fun setup (melting wires were disabled in the release version since the energynet was technically incomplete until certain blocks were finished).

**Comment by ReikaKalseki** [comment]
I tried Blutricity back in 1.1; I gave up on it in less than an hour for that exact reason; I could not figure out why doubling the number of solar panels on my roof (in a big grid) more than halved the current into my battery.

Also, ElC actually had a more realistic model for a few days; I discarded it for exactly the reasons described above. That and performance.

**Comment by OvermindDL1** [comment]
Lol, it would have probably burned the wires if that was enabled.  If you
added more wires in parallel it would have fixed it.  😜

**Comment by sk1tt1sh** [comment]
is it possible to change the config to disintegrate the wire from the source rather than having a large lake of lava form in my base?

**Comment by ReikaKalseki** [comment]
After a long discussion with half a dozen veteran ElC users on @sentinalhmc's discord server, the somewhat unorthodox but functional solution of preventing grid arrangements of motors from being placed, which is almost always the cause of a gridded - and thus overcomplex - network.

Related to this, motors now have heat fins, which are purely visual but there to explain why cannot be placed vertically adjacent.

![https://i.imgur.com/eMYPgQc.png](https://i.imgur.com/eMYPgQc.png)
![https://i.imgur.com/DfLucfL.png](https://i.imgur.com/DfLucfL.png)
![https://i.imgur.com/KKGvYFR.png](https://i.imgur.com/KKGvYFR.png)
![https://i.imgur.com/2MSl5QJ.png](https://i.imgur.com/2MSl5QJ.png)

**Comment by waterlubber** [comment]
> IIRC electricity always takes the path of least resistance. For non-superconducting wires, this is the shortest path (unless there is a resistor in the way). For super-conducting wires, it can be assumed to be the shortest path, unless there is a resistor in the way.

For posterity, this is a misconception and is fake news. It takes all paths, proportionally to the resistance of each. Two resistors in parallel, one two ohm, the other four, the power will be split 33/66% between them. It's why you can be electrocuted in water.

**Comment by OvermindDL1** [comment]
Indeed, that is why a matrix solver could handle it properly.  Just cache the network matrix in memory and run a solver over it on tick all at once.  ^.^
