### ISSUE TITLE
Centrifuging Clay returns "item.null.name" from Industrial Craft Classic

### ISSUE THREAD

**Issue by MaxineBean** [ReikaKalseki/Reika_Mods_Issues#1187]
https://puu.sh/s3qb6/4290826954.png
https://puu.sh/s3qcW/22a44a409e.png

**Comment by ReikaKalseki** [comment]
@Speiger IC2 classic removes biochaff?

**Comment by Speiger** [comment]
@ReikaKalseki IC2Exp added that item in 1.7.10. Classic starts from the 1.4.7 area what you see there is my Compat to IC2Exp so that mods like yours do not have any crashes.
So i am not removing the item. I am just not adding it.

**Comment by Speiger** [comment]
The item.null.name is a bug from my side...
Edit: You can use i think a compressed Plantball since that one is the simply what biochaff got replaced with. The only use of that in Ic2Classic is to create biofuel with so its not an item with much use either.
And its created by compressing a plantball. Almost the same steps as a biochaff...

**Comment by Speiger** [comment]
^^" I think i change the items in my Exp compat that BioChaff gets automaticly to compressed plantballs.
I tell when its done. At the moment mostly focusing on 1.10.2 because its so close for beeing done^^
