### ISSUE TITLE
[CC] Missing Crystalline Recipes

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1209]
Recently realized that NEI redirects to the Lexicon when checking recipes, however there are a couple of items that redirect to a page that does not actually contain their recipe. Energized Crystalline Stone Beams and Crystalline Energy Stabilizer redirect to the entry for crafting Crystalline Stone, however there is not a page for either of these.

**Comment by Builderb0y** [comment]
Those can only be made in the item fabricator (and maybe the transmutation flame, haven't checked). Both of which have "standard" NEI integration. The problem is that crystalline stone in general hooks into NEI to show the book instead of the recipe list, and does not have exceptions for variants that can't be made in the casting table.

**Comment by Shahelion** [comment]
Is there supposed to be a page in the book somewhere that says this, though?

Otherwise the logical conclusion is that a player would have to dismantle pylons to get them.
