### ISSUE TITLE
[CrC] Teleportation Pump GUI missing

### ISSUE THREAD

**Issue by Eb-** [ReikaKalseki/Reika_Mods_Issues#1262]
Right clicking the Teleportation pump does not bring up its GUI. Attempted in both Survival and Creative mode.

CrC V16d
Forge Version 10.13.4.1614

**Comment by ReikaKalseki** [comment]
This used to work, and I changed nothing...

**Comment by ReikaKalseki** [comment]
[It works fine](http://i.imgur.com/Gz7gej6.png). Did you wait for it to finish scanning?

**Comment by Eb-** [comment]
That was the issue, Thanks!

You may want to add to the lexicon that the GUI is inaccessible until scanning is complete.

**Comment by ReikaKalseki** [comment]
Maybe, but I do not want to make explicit references to ingame concepts like clicking or GUIs.

EDIT: IT *is* there: "Needs to scan the area after being placed"

**Comment by Builderb0y** [comment]
"Needs to scan the area after being placed" does not imply that it is unusable until it finishes scanning. I would have expected it to work like the mineral extractor and update the results of its scan in real-time in the GUI.

**Comment by ReikaKalseki** [comment]
The Mineral Extractor has to finish scanning before it scan do anything either.

**Comment by Builderb0y** [comment]
Yeah, but you can still open the GUI while it's scanning.

**Comment by ReikaKalseki** [comment]
Sure, but the telepump GUI does not show progress like the extractor GUI goes, nor does it allow for locking action until the scan is finished (the extractor is not even triggered via the GUI).

**Comment by Builderb0y** [comment]
Correct me if I'm wrong on either of these points, as it's been a very long time since I've used it; but presumably it has a list of every block it finds that's a liquid, and adds to this list as it scans. Why then is it not possible to make it show scan progress by telling the client each time it finds a new block? (only while the GUI is open, obviously). As for locking action, the trigger mechanism is presumably a single action somewhere, weather it's redstone/GUI/rightclick activated (I don't remember). Either way, why can't it simply check to see if it's done scanning upon being triggered, and if it is done then start outputting fluid?

**Comment by ReikaKalseki** [comment]
The structure of the internal cache is different.

**Comment by Builderb0y** [comment]
I don't see why "list of positions and ores at those positions" needs to be different from "list of positions and fluids at those positions".

**Comment by ReikaKalseki** [comment]
Their data structures are different because they work differently internally.

**Comment by Builderb0y** [comment]
I don't see why "mine blocks at a bunch of positions and output them as items" needs to be different from "drain fluids at a bunch of positions and output them as fluids". The only difference that I see is that one needs to check the ore dictionary and the other needs to check the fluid dictionary, and that has absolutely nothing to do with how it stores the list of positions it needs to mine/drain.
