### ISSUE TITLE
[Question][reactorcraft] Purpose of checkCompleteness in TileEntityToroidMagnet.class?

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#1275]
I remember that sometime ago you have said that the fusion reactor can be built in many ways.
However the structure integrity check in toroid magnet is preventing any non-standard builds.
So what's the purpose of this check? Is it there to prevent some sort of exploit?

**Comment by zemerick** [comment]
Yes, it is there to prevent some super cheap designs. ( Reika likes different designs, but does not want them to perform better than the standard reactor, without also requiring more resources. )

non-standard builds absolutely still work though. It does have to be some form of ring though, and due to the way things work, you can't have a concave curve anywhere. I have built many different reactors, and worked with Reika to try and get some exploits under control, while maintaining variability.

**Comment by wormzjl** [comment]
ok thx

**Comment by wormzjl** [comment]
btw, would you mind showing me some other design that can be made?

**Comment by zemerick** [comment]
I don't think I have any pics of the current stuff, but here's a few older pics I've done:

http://imgur.com/a/sBy0j

https://forum.feed-the-beast.com/threads/reactorcraft-fusion-reactor-experiments.61319/

Has a couple more older designs. Again, some specific things might not work currently, but you can kind of get the idea. Main things you can adjust are the size larger or smaller, and the positions of the injectors.
