### ISSUE TITLE
Shaft Power Buses not saving/loading torque/speed information

### ISSUE THREAD

**Issue by svipthedrunk** [ReikaKalseki/Reika_Mods_Issues#1301]
I have a shaft power bus network, some outputs are translated via 16x bedrock gears in speed mode (omega visible). After restarting the server all outputs have changed to the default torque mode (tau vissible).

With kind regards
Svip

**Comment by ReikaKalseki** [comment]
Try again in v17.

**Comment by ReikaKalseki** [comment]
Did v17 fix it?

**Comment by svipthedrunk** [comment]
Sadly not, original issue persists.
I noticed another weirdness with the shaft power bus (do not know wether this is new or existed already prior):
1. I start server and log in ( due to the already mention bugged it operates in torque mode)
2. open the GUI and change to speed mode
3. i get high rpm checked with dynamometer
4. log off and log in again
5. i still get high rpm checked with dynamometer
6. looking into shaft bus gui --> shows torque mode

**Comment by MrWisski** [comment]
Can confirm, on server start, shaft power bus goes back to default torque mode. This kills the liquid nitrogen production for my fusion reactor, and uranium centrifuges for my fission reactors...and actually cripples most things in my base since it's 80% RC/ReC powered by turbines. This was not an issue in v15. I skipped v16 and went straight to v17 (after removing bukkit, and moving to just pure forge server).

**Comment by ReikaKalseki** [comment]
Use ElC for now.

**Comment by ReikaKalseki** [comment]
I found the problem....literally a missing variable assignment, not some elaborate syncing issue.
