### ISSUE TITLE
bet you feel stupid

### ISSUE THREAD

**Issue by whiskeyshot** [ReikaKalseki/Reika_Mods_Issues#1327]
how those immigrants turning out now, you braindead hippie?

**Comment by ReikaKalseki** [comment]
People - innocent people, possibly including children - die and **this** is how you react? A terrorist attack is a cause of *celebration* for you, so that you can try - and like everything else in your miserable life, fail - to prop up your own worldview which essentially reduces to "f$%^ other people, I like me better"?

Let's ignore for the moment that with the - admittedly as-yet incomplete - information we have the attack reeks of a hate crime by bigots emboldened by recent political events and pretend it really IS what you so deeply hope it to be: A couple followers of a religion you base your life around the concept of hating decide to act violently against others for irrelevant reasons.

One, innocent people *still died* needlessly. Even if your twisted ideas were defensible, the ethical reaction would be something along the lines of "maybe some good can come of this tragedy" not what is basically "YEAH F$%^ THE OTHER GUY I LOVE IT WHEN $%^&#^ DIE".

Two, you turn around and attack me as if I am to blame simply because I do not recoil in fear when seeing skin tones slightly darker than "uncooked chicken" or hear words in a foreign language, as if the only rational way to view the world is to despise those who are different. Well, guess what? You are different from me, and - though not for this reason - I actually do hate you. Really great to be on the other side, isn't it?

Now, to be fair, I have probably wasted ten minutes writing all of this, as you will no doubt refuse to read most of it, call me a 'cuck' or the like, and go off to f#$% your sister or something. How about you make history by performing a good act for once in your life and go drink bleach or something else that has the same effect.

**Comment by metnavman** [comment]
http://www.theglobeandmail.com/news/national/quebec-city-mosque-attack-suspect-known-for-right-wing-online-posts/article33833044/?utm_source=twitter.com&utm_medium=Referrer:+Social+Network+/+Media&utm_campaign=Shared+Web+Article+Links

Dude wasn't even an immigrant. Turns out, he's a shithead Donald Trump supporter. What a fucking piece of work; both this useless waste of life that thinks murdering innocents is worthwhile and whoever the PoS who made this OP is.

**Comment by ljfa-ag** [comment]
This is not the place to discuss this is it.
