### ISSUE TITLE
[DragonAPI] SoundPitchEvent NPE

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#1389]
The Game sometimes crashes randomly with an NPE in a SoundPitchEvent (relevant code: https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Event/Client/SoundPitchEvent.java ; crashlog: https://gist.github.com/Leguan12/f488df3ce156a6c34a62b4d2aeeb74cf). There's no exact way to reproduce it as it happens randomly when a Sound should be played. Easiest way around this would be a not-null check before firing the event (how those null sounds come to be still baffles me though)...

**Comment by ReikaKalseki** [comment]
Someone is trying to play a null sound; the proper response to this is not to make other code ignore it.

**Comment by Saereth** [comment]
You're not wrong that they shouldnt be trying to play a null sound. That being said this is a super annoying edge case that rarely occurs out of hundreds of mods with literally no way to track it down or even reliably reproduce it. Removing mods one by one doesn't even guarantee you'll find it because well, edge case and inconsistent to reproduce. You obviously dont have to include a null check here in Dragonapi, but you would be doing a favor to people in a similar situation if you could.

**Comment by ReikaKalseki** [comment]
I would much rather ASM a verification into `SoundHandler.playSound` to catch the null there, and hopefully identify the offending mod.

**Comment by Saereth** [comment]
That would actually be amazing

**Comment by ReikaKalseki** [comment]
Upon further investigation, `SoundHandler.playSound` simply delegates to `SoundManager.playSound`, which already filters null sounds. Which means whoever is f---ing up is doing it even worse, because they must be *directly injecting* the entry into the active sound list (`SoundManager.tickableSounds`).

I have an idea for this too; I will change the list type of that variable to one I control, which will make the list itself the enforcer.

This approach would also catch any calls to playSound that added null (forgetting its null check for the moment).

**Comment by ReikaKalseki** [comment]
Done. ![](http://i.imgur.com/kjjuEgJ.png)

**Comment by AssasinAsha** [comment]
Is this fix present in v17c? I'd guess so, because of dates, but I just got [this crash](https://gist.github.com/AssasinAsha/14d56fb008be38cbb6abe2b908516125).

**Comment by DracoScythem** [comment]
Have you enabled ` B:"Use HashMap for Sound Categories - Only use if necessary"` in the DragonAPI.cfg?

**Comment by AssasinAsha** [comment]
It is indeed set to true. Should it not be?

**Comment by ReikaKalseki** [comment]
> Have you enabled B:"Use HashMap for Sound Categories - Only use if necessary" in the DragonAPI.cfg?

This has no relevance.

**Comment by Turmfalke2** [comment]
@ReikaKalseki what is the status on this? I am playing with v18b and I am still randomly crashing with that stack trace. I suspect it might be Dynamic Surrounds, but I have no way of proofing that.  

DynamicSurroundings only seems to have it's code for 1.10+ public, but at least I can see that it is touching tickableSounds.

https://github.com/OreCruncher/DynamicSurroundings/blob/b15f82f40a1b4658b03bad94341d212a6827fffa/src/main/java/org/blockartistry/DynSurround/client/sound/SoundManagerReplacement.java

**Comment by ReikaKalseki** [comment]
We are seeing it in Dynamic Surroundings on the server as well, and the code linked is almost certainly involved.

**Comment by Turmfalke2** [comment]
Alright, barring a good workaround I am willing to throw DynamicSurrounding under the bus. I am find my self playing with sound turned off quite often anyway.
