### ISSUE TITLE
How to share Chromaticraft Progression ?

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1403]
I want to share my Chromaticraft Progression with other player or even more i want it to be the same for all players on my private server. I know there is a command for giving progression to players but i want to copy my progression and overwrite someone elses.
Is there a way to do this because i cant finde something related in the configs or commands and if not im requesting this as a Feature, it would make playing together with friends a lot better.
Example: I discover something and my friend gets it too, my friend discovers something and i get it.

**Comment by ghost** [comment]
Currently, this is not possible. There were ideas circulating, but it was never finished due to several issues.

**Comment by ReikaKalseki** [comment]
> i want it to be the same for all players on my private server. 

*That* is never going to happen.

**Comment by LukaPix** [comment]
Is it not possible or is it because it woud be too easy or breaking the concept ?

**Comment by ghost** [comment]
Co-op progression is one thing, but for _everyone_ is essentially "removing" a big part of the mod.

**Comment by Rubyheart** [comment]
Maybe a system similar to Thaumcraft?  The person with a higher progression could copy their info fragments to the person with lower progression.  A "fragment of shared knowledge" type thing.  They could even still gate by just unlocking the fragment, but the next info fragment they actually find still needs to fill the book before they can move on, so they still end up needing the same numbet of fragments.

For things shared that aren't info fragments, maybe something to do with the ritual altar?  Higher progression starts the ability, gets infused first and heavily damaged, since copying parts of your brain is a very physically and mentally exhausting task, then the second player stands on the altar, and after being infused, dies because they couldn't handle the rush of knowledge all at once and only unlock parts of what the first player knows.

**Comment by ReikaKalseki** [comment]
My biggest problem with "free" progression sharing is that the progression system is not only a balancing factor: It is also the way players are intended to learn the mod. Giving a player progression gives them the ability to do things without having acquired the prerequisite understanding.

**Comment by OvermindDL1** [comment]
Eh, sometimes it stalls pretty bad though, took weeks before we found a desert temple after travelling for more than 80k blocks in all directions, and even then only found one so far, nearest pylon is 800 blocks away (that was painful for wooden repeaters...), plus every time the game loads I have to go out to near each and every single pylon to get it to load in to memory, though once loaded it works until the next restart.  Consequently I'm the only one out of my family that has progressed through ChC, and it was not entirely pleasant, though they know how it all works from watching me (we all play in our computer room) but they cannot do it themselves because of such issues.
