### ISSUE TITLE
Config option to disable corium/radiation (or some of its effects) [Reactorcraft] (Suggestion)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1406]
![2017-04-09_16 07 24](https://cloud.githubusercontent.com/assets/10777735/24840669/131292e4-1d3f-11e7-9a84-fec9acb76c5f.png)

![2017-04-09_16 28 04](https://cloud.githubusercontent.com/assets/10777735/24840759/8da171d6-1d41-11e7-99ad-8f7e8966b401.png)

Looks like it is just the radiation so far.

**Comment by zemerick** [comment]
If you're talking about the lag caused after a meltdown, it's a known bug where the flowing corium continues to spawn radiation beyond the limit it is supposed to have. No config would be needed once that is fixed.

Additionally, since it is a fairly key part of the reactors, I highly doubt Reika would want to allow them to be disabled.

**Comment by ReikaKalseki** [comment]
#1190
