### ISSUE TITLE
Hydrokinetic engine power not affected by height of falling water

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#141]
In v7d, the height of water falling on a hydrokinetic engine isn't affecting the output of the engine.

http://imgur.com/a/kw6ea

In the series of photos in this album, you can see water at 5 blocks above the engine produces as much output as water 64+ above the engine.

**Comment by TomeWyrm** [comment]
That has been fixed... um... as of version... 7f?? Really recent update, try again with the latest.

**Comment by Haggle1996** [comment]
Sure. When v7x releases. :)

**Comment by Xavion3** [comment]
This isn't actually a bug, you just set it up wrong. Hydrokinetics only rotate counterclockwise, as you've got the output of the engine towards the right the water column should be on the front, what's actually happening is that little fall as the water flows over the top and front of the engine is powering so the height of the water column doesn't actually change between pictures. If you rotate the hydrokinetic 180 degrees you'll see it actually does change with the height of the column.

The reason it's 147kW from just that tiny fall is due to the poor balance in 7d which was a separate bug and has apparently been fixed in the next release to be more in line with the original values. Currently a mere 14 block fall will give full power with water.
