### ISSUE TITLE
*Question-not issue* Adding ElectriCraft to server & pack

### ISSUE THREAD

**Issue by sk1tt1sh** [ReikaKalseki/Reika_Mods_Issues#1410]
I would like to add electricraft to my pack that has dapi, rotarycraft and reactorcraft already among some other tech mods. Is there anything I should look out for when adding it or should it be ok?

Also according to reddit things can turn to lava randomly, is there a way to mitigate that?

**Comment by OvermindDL1** [comment]
> Also according to reddit things can turn to lava randomly, is there a way to mitigate that?

It is not strictly 'random', but it is not really expected in all cases.  Basically just don't overload your wires, and don't make wire setups 'too complex', those are the cases where perfectly fine set up wires turn to lava 'randomly' and 'too complex' seems very random as it's happened here with as few as 6 wires and 2 machines in a specific setup...  >.>

But no, no way to disable it because the random lava parts are the system preventing itself from recursing too much (it really really badly needs a new algorithm...).

**Comment by sk1tt1sh** [comment]
Interesting. Could it be switched to causing a fire instead? Seems like lava is a bit extreme. Is it a source block or is it a small lava or something like that? A small lava that decays after a moment would be reasonable.

**Comment by zemerick** [comment]
This is the Issue Tracker. If it's not an issue, it shouldn't be here.

I recommend the MCF for discussions, but there are a number of other places Reikas mods are discussed, such as the FTB forums and Reddit. The MCF thread is:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more
