### ISSUE TITLE
DragonAPI and AE2 CrashLog

### ISSUE THREAD

**Issue by reddvilzz** [ReikaKalseki/Reika_Mods_Issues#1412]
Hi there, I'm having crash on startup when I installed DragonAPI only
and here is the [log](https://pastebin.com/izXjbBnH).

The crash happened only when I enabled DragonAPI, I was trying to add Geostrata to my private pack.

**Comment by ReikaKalseki** [comment]
It works for us, and the crash is coming from Refined Relocation.

**Comment by reddvilzz** [comment]
Oh I thought it was AE, what are your suggestions then?
Thank you

**Comment by OvermindDL1** [comment]
> Oh I thought it was AE, what are your suggestions then?

```java
Caused by: java.lang.NoClassDefFoundError: Could not initialize class appeng.core.Api
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at appeng.api.AEApi.<clinit>(AEApi.java:49)
    at com.dynious.refinedrelocation.compat.AE2Helper.addAERecipes(AE2Helper.java:12)
```

As per in the log you posted, refinedrelocation is trying to access an invalid part of the AE API, either the API is out of date (which should *NOT* happen as a mod author would be quite a moron to include an API internally), or there are duplicate API's found (which should also not happen, due to above same reason).  Since the crash happens within the AE2 API call it is unlikely it is just an out-of-date call to an up-to-date API, but also possible.

Regardless, this is a 'refinedrelocation' bug.

**Comment by reddvilzz** [comment]
Weird though the crash only happens when DragonAPI is included, but when I remove it the crash is gone.

Should I post an issue on refined relocation github issue too?

**Comment by BlayTheNinth** [comment]
Refined Relocation is accessing a [valid part of the API](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv3-1.7.10/src/api/java/appeng/api/AEApi.java#L73). The crash occurs during loading of that class, because it fails to load  [appeng.core.Api](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv3-1.7.10/src/api/java/appeng/api/AEApi.java#L49) via Reflection.
Note that it's not a `ClassNotFoundException` but a `NoClassDefFoundError`, which means the class should be there, it just fails to load. This is usually the result of ASM transformers doing incorrect things.
Whether it's an issue in DragonAPI or Applied Energistics, I don't know, but nothing points towards this being Refined Relocation's fault (other than it being the victim of breakage that happened earlier).

I'm not familiar enough with either codebase, but a quick look shows that DragonAPI is forcing `AppEngHandler` to load on the classloader that `ReikaJavaLibrary` was loaded on, which then results in the reflection calls to the AE2 API also [causing the AE2 API to be loaded](https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/ModInteract/ItemHandlers/AppEngHandler.java#L113) on that class loader (see `Class.forName()` documentation). 
`ReikaJavaLibrary` itself is loaded in `CoreModDetection` or earlier, which is loaded by `Patcher`, which means all of the above is loaded on the coremod class loader. I think that might cause them to not be passed through ASM transformers. However, AE2 heavily relies on their ASM transformers working on their own classes. So I'd guess this is the issue, and could be fixed by passing the correct class loader [during the reflection in AppEngHandler](https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/ModInteract/ItemHandlers/AppEngHandler.java#L113).

For reference, here's a Twitter thread of cpw explaining that loading APIs/mod classes on the coremod classloader is wrong: https://twitter.com/voxcpw/status/776927032437538816

**Comment by reddvilzz** [comment]
Bump?

**Comment by ReikaKalseki** [comment]
Class.forName can specify an explicit classloader, but which should I use? The only classloader I have ever seen active in the game is the LaunchClassLoader - despite repeated claims of others' existence and use on classes I have proven to be actually loaded by Launch.

**Comment by BlayTheNinth** [comment]
It does look like it's loading all classes through the LaunchClassLoader, but exclusions are added for coremod classes, which causes it to just delegate the call to its parent class loader, which is why they'll be loaded from the system class loader instead of the LaunchClassLoader (and thus all classes loaded from within will not even try to go through the LaunchClassLoader):

```java
Iterator e = this.classLoaderExceptions.iterator();
String untransformedName;
while(e.hasNext()) {
    untransformedName = (String)e.next();
    if(name.startsWith(untransformedName)) {
        return this.parent.loadClass(name);
    }
}
```
(from LaunchClassLoader.java#111)

So yes, just passing the `Launch.classLoader` in `Class.forName()` should solve the issue.
(but to prevent future issues you may want to move things around to ensure only absolutely necessary classes get loaded within your coremod classes)

**Comment by reddvilzz** [comment]
So I guess you'll implement the fix in the next build @ReikaKalseki ?

**Comment by ReikaKalseki** [comment]
It has already been fixed for v17.

**Comment by reddvilzz** [comment]
Thank You!

**Comment by reddvilzz** [comment]
I'm guessing version 17 won't be backported to 1.7.10? Because I'm having this issue on 1.7.10

**Comment by Aivech** [comment]
I've never heard any indications that it wasn't for 1.7.10.

**Comment by reddvilzz** [comment]
Yeah I've misinterpreted that.
