### ISSUE TITLE
Rotarycraft Strange clicking/hitbox issue

### ISSUE THREAD

**Issue by jamesb6626** [ReikaKalseki/Reika_Mods_Issues#1414]
It seems there are some very strange issues with some of the blocks. So far the blocks I have seen do this are the Cave Scanner, Chunk Loader, Player Detector, EMP Machine, Sprinkler and Reservoir.
It looks like these blocks continue to use the clickable shape of the last one of these to be looked at (highlighted with cursor) or touched (e.g. stood on) until they themselves are highlighted by looking at the space where they would be if they were the other block (e.g. after looking at the sprinkler, must look at where the detector would be if it were a sprinkler) at which point the block will be highlighted and its clickable shape restored (so in the example before if the point looked at was on the shape of the sprinkler but not on the detector's clickable shape the detector is highlighted quickly then imediately unhighlights again and the detectors clickable shape is restored, if the point was in both clickable areas the detector will remain highlighted). Also, calling one of these block 1 and the other block 2 (where block 1's clickable shape doesn't take up a full block's space) if the space where block 2 would be if it were block 1 is looked at through the empty space surrounding block 1 then the highlight will flicker (alternate, seems to be each frame) between block 1 and block 2's clickable space, though if the point looked at is on block 2's clickable shape but not on its shape if block 2 were block 1 then neither block is highlighted (not looking at block 1's clickable shape). Now, taking instead that block 1 can be a full block, if block 2 is looked at while standing on or touching block 1 then block 2 will act as though it had the clickable space of block 1, highlighting only if the space it would have had if it were block 1 is looked at (mostly without flicker, though looking at a third block through block 2 I may have managed to cause flicker while standing on a cave scanner, though I can't reproduce it now). The only block of these which is different is the reservoir, as getting this to highlight will not restore its original clickable shape, and it also will not flicker when looked at through the empty space around another one of these blocks. For all of these, the memory of which block was last looked at seems to persist through the saving and quiting then reloading of the save, an F3+T reload, a change of resource pack, and with Advanced OpenGL on and off. A restart of the game will reset it. Though the clickable shape changes for these blocks, the highlight box when they are highlighted is always the correct one for the block looked at, and I have yet to notice any effects of this on the collision shape of the blocks.
The issue is worst with the reservoir, as it doesn't correct its clickable shape, making placing things and destroying them difficult (breaks/places stuff behind them). I first noticed it while using sprinklers and reservoirs in building an ethanol farm in creative (with agricraft and other mods, though the screenshots are all from reproducing this with only your mods, latest versions through curse). Not knowing it was caused by looking at the sprinkler, I nearly reported the reservoir issue seperately, until I noticed a restart temporarily fixed it, and further testing lead to all this.
This was all tested in single player creative. 

After looking at detector, no flicker (works with normal blocks opposite too, and detector)
![Reservoir through reservoir](https://cloud.githubusercontent.com/assets/7932999/25194885/cf3f8098-2533-11e7-9c50-3ecd15a7ffbe.png)

Looking at where the detector would be if it was a sprinkler through the air space around a sprinkler (flickering, works with all mentioned here except reservoir)
![Detector through sprinkler 1](https://cloud.githubusercontent.com/assets/7932999/25194988/23fe31a6-2534-11e7-99c2-f83dbaa56799.png)
![Detector through sprinkler 2](https://cloud.githubusercontent.com/assets/7932999/25219972/2c862012-25a8-11e7-8368-820ec3579146.png)

Flickering here
![Cave scanner through detector](https://cloud.githubusercontent.com/assets/7932999/25194306/f0e5d064-2531-11e7-805d-33bbbc7409c0.png)

Three way flicker (standing on cave scanner)
![3 way flicker 1](https://cloud.githubusercontent.com/assets/7932999/25221376/d51fb928-25ac-11e7-95d9-6fc0cd2a5bf6.png)
![3 way flicker 2](https://cloud.githubusercontent.com/assets/7932999/25221390/e17e846a-25ac-11e7-9228-a0dc4e0d43d0.png)
![3 way flicker 3](https://cloud.githubusercontent.com/assets/7932999/25221406/ee561c3e-25ac-11e7-91ee-b39007c52aa5.png)

Settings
![Settings](https://cloud.githubusercontent.com/assets/7932999/25221719/08b047ca-25ae-11e7-845e-8b204b5a7400.png)

A log and crash report in which the reservoir-sprinkler issue is reproduced with an F3+C crash at the end (to list mods, system specs, java args and get crash report) (renamed latest.log to latest.txt for github)
[latest.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/941825/latest.txt)
[crash-2017-04-20_10.02.20-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/941832/crash-2017-04-20_10.02.20-client.txt)

Hope this is enough info and all correct, I have another couple of (unrelated) bugs to report later, one for Rotarycraft and one for Chromaticraft, these should be seperate issues right?

**Comment by OvermindDL1** [comment]
Ah hah!  This perfectly describes some odd issues I saw with the selection AABB as well!  I confirm this happens as described.  Likely the selection AABB is not returned properly from a cached value perhaps, hmm, let's follow.

So for the above blocks it looks like their selection is all called from the same place:
https://github.com/ReikaKalseki/RotaryCraft/blob/11729fc09ecf0b3a71994e9205a13566aa250d11/Base/BlockModelledMultiTE.java#L121
```java
	public final AxisAlignedBB getSelectedBoundingBoxFromPool(World world, int x, int y, int z)
	{
		return this.getCollisionBoundingBoxFromPool(world, x, y, z);
	}
```

Which of course defers to:
https://github.com/ReikaKalseki/RotaryCraft/blob/11729fc09ecf0b3a71994e9205a13566aa250d11/Base/BlockModelledMultiTE.java#L104
```java
	public final AxisAlignedBB getCollisionBoundingBoxFromPool(World world, int x, int y, int z) {
		MachineRegistry m = MachineRegistry.getMachine(world, x, y, z);
		if (m == null)
			return ReikaAABBHelper.getBlockAABB(x, y, z);
		RotaryCraftTileEntity te = (RotaryCraftTileEntity)world.getTileEntity(x, y, z);
		if (m == MachineRegistry.RESERVOIR) {
			return ((TileEntityReservoir)te).getHitbox();
		}
		AxisAlignedBB box = AxisAlignedBB.getBoundingBox(x+m.getMinX(te), y+m.getMinY(te), z+m.getMinZ(te), x+m.getMaxX(te), y+m.getMaxY(te), z+m.getMaxZ(te));
		if (te.isFlipped) {
			box = AxisAlignedBB.getBoundingBox(x+m.getMinX(te), y+(1-m.getMaxY(te)), z+m.getMinZ(te), x+m.getMaxX(te), y+(1-m.getMinY(te)), z+m.getMaxZ(te));
		}
		this.setBounds(box, x, y, z);
		return box;
	}
```
So, it gets the machine from this location in the world, if null it returns `ReikaAABBHelper.getBlockAABB(x, y, z)`, which is just calling `AxisAlignedBB.getBoundingBox(x, y, z, x+1, y+1, z+1)`, so this is not the machine cached value at all.  If it is not null then it gets the te from the world position.  It then tests if it is a reservoir (yay special casing), and returns its TE's hitbox call if so, since this is one of the affected blocks in the first post, let's look at it right quick:
https://github.com/ReikaKalseki/RotaryCraft/blob/2fe52b194a377c48d35b3861dfdab07077c07cb7/TileEntities/Storage/TileEntityReservoir.java#L382
```java
	public AxisAlignedBB getHitbox() {
		if (isCovered || this.isEdgePiece(worldObj, xCoord, yCoord, zCoord))
			return ReikaAABBHelper.getBlockAABB(xCoord, yCoord, zCoord);
		return AxisAlignedBB.getBoundingBox(xCoord, yCoord, zCoord, xCoord+1, yCoord+0.0625, zCoord+1);
	}
```
So it ends up making a call to `AxisAlignedBB.getBoundingBox` either directly or via the `ReikaAABBHelper.getBlockAABB` helper.

Back to the parent big function above of `getCollisionBoundingBoxFromPool`, it then grabs an AABB of the coordinates and so forth, then ends up calling setBounds on it, which ends up calling:
https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/BlockTEBase.java#L80
```java
	protected final void setBounds(AxisAlignedBB box, int x, int y, int z) {
		this.setBlockBounds((float)box.minX-x, (float)box.minY-y, (float)box.minZ-z, (float)box.maxX-x, (float)box.maxY-y, (float)box.maxZ-z);
	}
```
Which calls `Block.setBlockBounds` on the main minecraft class, which sets the extant variable on the block class, so this is only set in 'some' cases first of all, only when all the if conditionals are false, so this is odd first of all, however this should not be much of an issue unless not all the other collision and selection callbacks are overridden, which if I remember properly (been a while since I've touched the horrors that is Minecraft code) is `getSelectedBoundingBoxFromPool` (it is), `getCollisionBoundingBoxFromPool` (it is), `collisionRayTrace` (it is not!), `isVecInsideXZBounds` (it is not!), `isVecInsideXYBounds` (it is not!), and `shouldSideBeRendered` (it is not!), \*or\* if the block is always a full block \*or\* setBounds is called on block instantiation and there is always only one world-size of the block (which it definitely will not be unless it is centered in the block and/or is not placeable on different edges).

The above would not necessarily cause any issue (though it is likely to, that really needs to have a unified path...) and certainly is not causing 'this' issue as the selection box itself is always correct, it is the actual 'selecting' part of the selection box that is the issue, not the drawn part, and this path goes through the `Block.collisionRayTrace` function, a ray is traced that hits the fullblock, the `Block.collisionRayTrace` function is called, which passes the ray 'through' the block, testing the extents that are in it (and the mod author can override it to do very complex ray testing, like being able to select through an open hole for example), so we see these being tested here.  However, the selection aabb may not always be called before the ray is traced, and if the block is 'resizable' (I.E. it can be in different shapes in different places or angles or whatever) then a certain function has to be called to get the current extents, that function is `Block.setBlockBoundsBasedOnState`, which does nothing by default, however any block that does not have a single set shape for \*all\* possible variants of the block needs to override it and call `this.setBounds` inside of, so let's see where `Block.setBlockBoundsBasedOnState` is being overridden in the mods, hmm, a few places, but I'm not seeing it on the blocks with the issues listed above, so I am now about 70-90% certain that this is the issue.  At the very *very* least the `Block.setBlockBoundsBasedOnState` needs to be overridden to call `this.setBounds` properly based on the state of this block,  and it probably needs to be overridden on the `BlockModelledMultiTE` class at https://github.com/ReikaKalseki/RotaryCraft/blob/11729fc09ecf0b3a71994e9205a13566aa250d11/Base/BlockModelledMultiTE.java and probably other places as well.

Just remember, if a block is not a full-block and it is not always the same shape (like the enchantment table is a full block, but it always has the same shape in world, you cannot place it upside on a ceiling for example), then you **MUST** override `Block.setBlockBoundsBasedOnState` and call `this.setBounds` within it.  If you wish to do more complex 'click-through' testing then override `Block.collisionRayTrace` as well and use the tracing ray from the screen cursor to do specific things (you can do things like let you click through a 'hole' in the block, or highlight specific 'buttons' on a machine and react to those instead of the full extents (think of that shared contents chest from that one mod with the 3 colors you can assign on top of it), etc...  It is a very useful function).

There are definitely a few bugs in the code that are obviously visible from my perusing over it, but they seem to stem from not knowing some of the really-nasty MC internals, but they will cause issues, like this one.

Also, @jamesb6626 never ever put `I'm using the latest version` or anything like it, you must must must always put the specific version that you are using.

**Comment by jamesb6626** [comment]
All the mod versions (in jar names) are in the debug crash report (another reason I thought it would be a good idea). It should also list which specific mods of Reika's I was using when testing this (though I've checked and it happens with only DragonAPI and Rotarycraft as well). Would it be enough to say the mod versions are in there for the other issues, or should I put them in the comment in future?
Edit: I also didn't check all machines (forgot to mention that), so there may be others that do this than those listed. If you've reproduced it and found the causes I'll leave it, but I can check more if needed.

**Comment by ReikaKalseki** [comment]
[Done](http://i.imgur.com/QhORPkr.png).
