### ISSUE TITLE
Items travel outside itemduct

### ISSUE THREAD

**Issue by ianleeder** [ReikaKalseki/Reika_Mods_Issues#1433]
I imagine this is known and/or reported somewhere, but I couldn't find a report for it.  Sorry if it's a dupe.  This is version V16d.

Some items, if viewed from the correct perspective, travel outside of an itemduct.  I installed a GIF recorder to demonstrate, this is my first try using it so it's not going to win any film awards.
(Wait a few seconds for GIF to load, it's 7.5MB)
![itemduct](https://cloud.githubusercontent.com/assets/8241300/26227176/04bb0614-3c74-11e7-8b18-59d3258bb706.gif)

Definitely happens for sludge and ethanol crystals.  I tested throwing another Rotarycraft item into the mix (a bedrock breaker), and it travelled fine regardless of the viewing angle.

**Comment by ReikaKalseki** [comment]
Not fixable.

**Comment by OvermindDL1** [comment]
Looks like the item renderer might be rendering with an offset 'up', interesting...

**Comment by ReikaKalseki** [comment]
It is a side-effect of my custom IItemRenderer (which is what is used to still use spritesheet images). The transforms required to render it end up having some effects like this depending on the implementation of the calling renderer (in this case the duct TESR).

**Comment by OvermindDL1** [comment]
Any reason a custom IItemRenderer for generic items like that?

**Comment by ReikaKalseki** [comment]
Again, for [spritesheets](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Textures/Items/items.png).

**Comment by OvermindDL1** [comment]
Ooo, wow, the old style spritesheets, I did not know those were still in use...  o.O

**Comment by ReikaKalseki** [comment]
They are much easier to work with.

**Comment by OvermindDL1** [comment]
> They are much easier to work with.

In my non-MC engines I tended to work with singular textures that used a packing pass at compile-time.  I always found spritesheets much harder to deal with.  Different textures, animation, packing, etc... all increase the difficult of handling them.  Such as it is much easier to just do something like `tilesheet->getTexture("blah1.png")` or `tilesheet->getAnimTexture("blah#.png")` and just use that instead of trying to remember to keep a list in sync between some coordinate mapping and a name (or worse, hard-coding coordinates into the source directly).  I was actually quite happy when MC included that processing step internal to the engine (even though it increases loading time and was not as efficient as mine was) as that removed some steps for me.  I may have to take a look at your process to see if it's easier (though I don't really touch MC's code anymore, blegh...)

**Comment by ReikaKalseki** [comment]
Few of my textures are animated, and most are derivatives of one another, or have batch operations applied. Plus this way I get to choose the texture folder.

**Comment by OvermindDL1** [comment]
> Plus this way I get to choose the texture folder.

Yeah that bugged me, ended up writing a gradle task to copy from an assets folder to the proper place in the output jar (images, meshes, default config file, etc...).  I left it open in such a way so I can modify the files on-copy (post-processing the images or something or mutating the text files) but never ended up using that functionality for anything but `sed`ing some `{{VERSION}}` and such things in text files...  The whole build system for MC mods rather sucks...
