### ISSUE TITLE
Error when updating ChromatiCraft to V17c something to do with a repeater lamp?

### ISSUE THREAD

**Issue by JammerFTW** [ReikaKalseki/Reika_Mods_Issues#1450]
Hiya Reika! i have... well a bit of an issue, with the lastest version of ChromaticCraft, version 17c, and if its something obvious, Im sorry, because im not that good a java yet. But it said something about contacting you immediately, so, here have a look:

https://pastebin.com/sH5pjs8n

**Comment by ReikaKalseki** [comment]
Check your OC/CC versions.

**Comment by JammerFTW** [comment]
ok if you mean OpenComputers and ComputerCraft, then those were both updated, so i just removed them and i still have the issue

Edit: all of your mods that i have installed, are up to date as well.

**Comment by ReikaKalseki** [comment]
OK, try removing other mods.

**Comment by JammerFTW** [comment]
ok. will do. i will let you know what the issue is once i figure it out, that way it helps others. 👍

**Comment by JammerFTW** [comment]
ok i have tried for like 2 hours, changing mods around, but since i have 200+ mods, and not enough patience to do this, i need a bit of assistance if you can. and of course if you cant, thats ok too, as im just that kind of guy. XD

**Comment by OvermindDL1** [comment]
You should remove half of the mods, startup, if same crash then put those back and remove half of the other half, else put half back, etc...  Likely some mod has an API that is out of date, which is precisely why no mod ever should include the API from another mod, when mis-matched duplicates like this happen then crashes happen.

**Comment by JammerFTW** [comment]
now that is a thought, which i might do, however all my mods are up to date, which i did via the Curse Client, by hitting the arrow next to all of them. i though it might fix the issue by updating them, but sadly no

**Comment by JammerFTW** [comment]
btw i could send you my mods if you want to help. that way, we could have a team of people, plus me, working on this, and when we figure it out, send the mods back to me, and then post a comment here saying what the error is. its just an idea.

P.S. i have google drive so i can upload my mods there, and get the link so you guys can download. if you want.

**Comment by JammerFTW** [comment]
fixed it! the chromaticraft mod appears to be incompatible with CD4017BE_lib, and his other mod, inductive automation. put those in there together, and they will crash the game at stage 2 of loading.

**Comment by JammerFTW** [comment]
except now its crashing my server, which is getting the same error report as i originally had with the repeater lamp. and i put IDENTICAL mods on the server as what i have on my client. and my client works gangbusters, (in other words really good XD), and yet the server crashes with identical setup to my client? minus the client side only mods of course. but can i get some help around here? XD

**Comment by ReikaKalseki** [comment]
> inductive automation

Does this ship an old version of the RF API?

**Comment by JammerFTW** [comment]
how do i check? im not an expert with .jar files or java in general. XD

**Comment by DracoScythem** [comment]
Inductive Automations Core/Library (CD4017BE_lib) does ship a RF API, although I never had problems with it running alongside your mods... (same versions as here).
Maybe it's something load-order dependent?

**Comment by ReikaKalseki** [comment]
> Maybe it's something load-order dependent?

Most classloading issues are.

Try opening the jar in an archive editor like winRAR and deleting its copy of the RF API.

**Comment by JammerFTW** [comment]
now this is interesting. i installed the following mods, (along with chromaticraft), thaumcraft, thaumic energistics, and baubles, which is the core mod for thaumcraft, and it crashes due to a reapeater lamp! but the thing is, chromaticraft supports thaumcraft, with features that help thaumcraft progression, and besides that, thaumcraft doesn't even use RF! now what... im rambling im sorry, but i would like some help XD

**Comment by JammerFTW** [comment]
and i dont have inductive automation installed. only the three i mentioned above

**Comment by DracoScythem** [comment]
Could you provide the updated crashreport? (A full List of all Mods and APIs loaded (including Versions) is quite important here)

**Comment by JammerFTW** [comment]
its the exact same crash report as mentioned orignally. funny enough

**Comment by DracoScythem** [comment]
It won't be the same if you switched out mods - it contains a List of all Mods and APIs loaded along their respective versions ;)

**Comment by ReikaKalseki** [comment]
So....

**Comment by bakaawful** [comment]
I hope this is helpful information, not necroposting.
Issue:
I've had this issue with Chromaticraft v22d (2018-12-22). The weird thing was that the client was loading just fine (including starting a local game), but the server was throwing the above error.

Faulty mod:
After much .jar grepping, I found the culprit mod as: 
SGCraft (SGCraft-1.13.3-mc1.7.10.jar), the Stargate mod. 

Solution:
After deleting the OpenComputers API within the SGCraft .jar, it worked.

Addendum:
It seems likely other outdated APIs could cause this; however, most mods have a straightforward internal structure, with cofh or dan200 as top folders within the .jar. However, SGCraft had the OC API further down the directory tree, and it made it harder to track by hand. Thus, grep.

**Comment by OvermindDL1** [comment]
@bakaawful Useful info that SGCraft is including an API as well.  ^.^;

Any mod that includes any API that is not from and of 'that' specific mod is inherently broken, don't know *why* or even *how* they are doing this, because it just wouldn't happen if they were using proper dependency management like they **should** be using, like via gradle or maven or sbt or whatever.

**Comment by bakaawful** [comment]
@OvermindDL1 I've seen utility/lib mods actually recommend other devs the source inclusion of their API in the dependent mod. I'm a C++ coder, not a Java coder, so I don't know how bad a practice it is, but it seems like a memetic spread of a bad practice, because it is simpler, or easier or the way modding newbies are advised to do things.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I've seen utility/lib mods actually recommend other devs the source inclusion of their API in the dependent mod. I'm a C++ coder, not a Java coder, so I don't know how bad a practice it is, but it seems like a memetic spread of a bad practice, because it is simpler, or easier or the way modding newbies are advised to do things.

Back when I worked on Forge I... 'advised' those people to quit that crap.  ;-)

But yeah, in the java ecosystem that is a sure way to breaking crap.  The Java ecosystem is 'almost' as horrifying (but not near as much) as the C++ ecosystem, that's why things like building your own build system for java programs (like reika does) is a very very bad move, and why including API's breaks things, and why not using dependency management is a sure-way to break things (Reika's 1.7.10 mods were using a *LOT* of old 1.7.2 and even some old 1.6 mods API's that didn't work on 1.7.10 before I opened up a lot of issues about them when I whipped up a gradle build system to do things properly).

But still, it's not easier either.  Quite literally, would you prefer someone to take your API, like SGCraft did with OC, have to unpack it into their system, make sure they keep it updated with any changes you do to do (or things break, as happened with OC in SGCraft), or just have them do something like add `compileOnly "li.cil.oc:OpenComputers:MC1.7.10-1.7.2.1204:dev"` to their dependencies list and everything 'just work'.  ;-)

If you really absolutely must include another things code in your project then you should change its namespace, that's trivial to do in gradle (not so much in custom build systems, or even maven directly for that matter) so there are no conflicts or access from anything else anywhere else and make sure nothing can call it (obviously not useful for API's).
