### ISSUE TITLE
Minecraft crash on Villager death

### ISSUE THREAD

**Issue by favvvvvvv** [ReikaKalseki/Reika_Mods_Issues#1466]
Hi, Reika, I've encountered the following issue with latest Chromaticraft version (v17c) in combination with [Gravestone mod](https://mods.curse.com/mc-mods/minecraft/gravestone-mod-graves) on Villager's death:
[Error description.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1049522/Error.description.txt)
This issue definately wasn't present in v16d as I remember having a huge collection of Villager Corpses from Gravestone.

**Comment by Kannei** [comment]
Any kinda villager? Because form what I can see this is caused by none vanilla villagers that mods mistake as players so they get errors on  fake player NBT data functions. as it tries to handle it as a player. 
There is no other reason why Chromaticraft progression handler whould trigger. (That I know about)

There is also Ars Magica 2 and wichery errors referansed, Is Reikas mods the only update that was done?

**Comment by ReikaKalseki** [comment]
....Why is it asking for whether a trade is valid with a null player, when the entity is dying? That very much seems incorrect.

**Comment by ReikaKalseki** [comment]
Oh, I see what is going on. It is trying to write the villager's trades to NBT so it can preserve it.
