### ISSUE TITLE
[CrC] Some Images are broken since v18a in the Lexicon, also one suggestion

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1545]
I am not sure if this is a real bug or if I can solve this on my own but after the update to v18a some images are a bit confusing:

![2017-08-08_10 14 47](https://user-images.githubusercontent.com/340106/29062613-a4f46c5e-7c22-11e7-9a9f-bcba0c02ad2d.png)

![2017-08-08_10 15 15](https://user-images.githubusercontent.com/340106/29062614-a50d5fc0-7c22-11e7-94e9-82ec2636cf2b.png)

As you can see, some blocks are no longer shown as blocks and also the Name for the Redstonepod are not declared in the langauge file.

May it also be possible to overhaul the progression page? Sometimes this page confuses me every time:

![2017-08-08_10 17 31](https://user-images.githubusercontent.com/340106/29062685-e57846f6-7c22-11e7-9e99-a9c507d1827d.png)

I think it would be much better to regroup it (not the progression self only the progression tree) so that the progression tree looks a bit cleaner (also the randomized order of the progression should be stopped).

And last but not least I found those missing or eventually not needed page again in the Lexicon:

![2017-08-08_10 19 54](https://user-images.githubusercontent.com/340106/29062816-80ac1832-7c23-11e7-9de1-4b84f6080419.png)

**Comment by ReikaKalseki** [comment]
The heat lamp and redstone pod never were full blocks.

**Comment by chaos234** [comment]
Ah ok. But then I wonder why sometimes they are shown as full blocks and not *thinking*

**Comment by ReikaKalseki** [comment]
Because of the same thing that makes vanilla wireless redstone work. I cannot explain in detail unless you understand OO programming.

**Comment by chaos234** [comment]
A bit of OOP I understand. Sure, I must look also at the code source to get a better understanding but at last why not givin it a try? ;)

**Comment by ReikaKalseki** [comment]
Unlike most things in the game, each "visual/apparent object" of which (each individual mob, each individual machine, etc) are different "actual" objects, blocks and items are not, instead being all pointers to the same singleton object (to save memory). This means that with there being only one instance, every property of a block instance behaves as if it were `static`, and as a result changes all blocks in the world simultaneously. Vanilla has a behavior where blocks take on the selection/hitbox of the currently selected/collided block (and where the box is determined for that particular location (`getCollisionBoundingBoxFromPool(world,x,y,z)`/`getSelectionBoundingBox(world,x,y,z)`)). This, however, also changes every other block in the world in the same manner, though normally not visibly.

Heat lamps and similar [change their bounds depending on what they are attached to](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Base/BlockAttachableMini.java#L100). This also changes any other copies of the block, including during rendering.

Normally all blocks start with full-block bounds; I recently changed heat lamps and similar to start with the bounds of a random orientation, since they are never full blocks.

**Comment by OvermindDL1** [comment]
There is a callback you should override that is called prior to render of an itemblock which is where you set your collision bounds.  If that is overridden then it will render properly everywhere (as long as mod things render a block via the correct itemblock render path, otherwise they need to call that callback themselves).  I forget the name of it off-hand, but it is on the Block class itself (I think the default implementation does nothing).

**Comment by ReikaKalseki** [comment]
I fixed the missing localization, and added the item render hook. Nothing else is a bug.

**Comment by chaos234** [comment]
Thanks :)
