### ISSUE TITLE
CC v17 Lumen incineration button does not move with inventory window

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1547]
When NEI moves the inventory window to the side, the lumen incineration button stays in an awkward spot.

![image](https://user-images.githubusercontent.com/1106888/29163659-6ceb5bfa-7dbd-11e7-86d1-c4966171db11.png)

**Comment by chaos234** [comment]
Have this to in v18b. After a bit time of playing the incineration button will be back at his original position, also the FTBU-Buttons are at there respective position.

For the incineration button it is eventually possible to overwrite the GUI so that the position for it can be fixed? It's an idea which I have had since a few days.

**Comment by Barhandar** [comment]
It happens because NEI forces inventory to be _actually_ centered, but the button expects it to have moved to the right, as per vanilla center-combined-inventory-and-effects-instead-of-just-inventory dumbness.

Might it be possible to have the button's position be relative to crafting-output slot, rather than absolute? Then it'll stay under said slot no matter what player does.

**Comment by ReikaKalseki** [comment]
I developed it *with* NEI installed. Also, there is no such thing as "relative" in GUIs.

**Comment by OvermindDL1** [comment]
MC's GUI's are the very definition of p***-poor immediate mode GUI drawing.  Everything is absolute coordinate in that you cannot introspect other things that you do not explicitly control or are exposed in any other way.

There was a push to get a real GUI system into Forge years ago (NUI or something like that?), which would have fixed these issues once things were properly converted, but you know how forge things go the past few years ("do it wrong or don't do it at all").

So yeah, things like that button would have to be special-cased by detecting state of all sorts of things, and it would inevitably break if mods start moving elements around more...

**Comment by ReikaKalseki** [comment]
This might have been fixed for v19.
