### ISSUE TITLE
Blaze not interacting with Bait Box

### ISSUE THREAD

**Issue by Tefatika** [ReikaKalseki/Reika_Mods_Issues#1568]
Any Blaze entity seem to ignore a Bait Box properly powered and containing either a Fire Charge or a Water Bucket.

Just to check any fault on my part, I tried providing a Golden Apple, a Stick, some Wheat, some Glowstone Dust; they all interact as intended with the proper entities.

I also tried spawning a Blaze from different sources: the egg, the vanilla spawner, a controlled spawner.

**Comment by ReikaKalseki** [comment]
This could be because Blazes do not have "follow" AI, in which case the only fix would be Ghast-style "forced movement", i.e. literal pushing.

**Comment by OvermindDL1** [comment]
You can add an AI element to the entities handlers that will force them to follow like that.  Pretty trivial to do (I've made a lot of custom ai elements to put on to things in a variety of ways a while back).

**Comment by ReikaKalseki** [comment]
Show me.

**Comment by OvermindDL1** [comment]
I'm at work currently but as I recall it is something like (maybe pseudo-code, should be fairly accurate if I remember properly, I may have some names slightly wrong or misspelled or something of course):

* `EntityLiving` has a field on it called `tasks` (public as I recall), it is where all the AI tasks sit.
* `EntityLiving.tasks` should be of type `EntityAITasks`, which is a container for `EntityAIBase`'s.
* All AI tasks are implementations of `EntityAIBase`, you would make a new implementation of that to do whatever you want (like you'd probably have a single field on it of the coordinates of the lure, and on it's tick update (or once every 20 ticks or so) you check if it still exists, if not then you disable yourself (see the `EntityAIBase` callbacks on how to do that, or better yet just remove the task completely).  On your tick you will also set the target that the lure is (you could optionally ignore pathing to lure if they already have a target for example, and only path if their target is `null`) by calling on the entity it is attached to something like `this.theEntity.getNavigator().getPathToXYZ(x, y, z)` of the block coordinates or so to get the navigation path, then on your execute you'd run it via updating the entity's navigator.  You should look at `EntityAIAvoidEntity` for an example (though instead of storing an entity type to avoid, instead pass in the constructor the coordinate of the lure or so).
* You will have your lure scan living entities nearby however often you want it to tick (so once a second or once every 30 seconds or whatever) and add that task to the entity.  You will want to add it to a specific place depending on the 'priority' that you want it to run at.
* I did precisely this with my Campfire block in one of my old mods (Alpha days, back when the task system was still new).  A Campfire would 'scare' mobs that were within 32 blocks diameter (cube) to go straight away from the campfire (pathed down to the nearest ground level to them), but they'd still chase players into the range, but it was nice enough to keep things far away and it worked well.  The campfire added the task to the mobs if it did not already exist (check for that) and the task checked if in range of the campfire that added it (or any other campfires in range that added themselves to the coordinate list inside) and it pathed away if it was not already pathing away, then once far enough way the task deleted itself off the entity.
* And a note, tasks will not serialize on world reload so your block will just find the mob again and add it again if necessary.
* (I did a *LOT* of things with AI tasks on entity creation hooks and all such, everything from making animals drop valuable dung of various sorts as they ate to having hunger and having to eat to dying off if they were not fed in way too long if not 'wild' and so forth.)

I can check in detail when I get home tonight though if the above is not detailed enough.  In about 5.2 hours from the time of this post you can ping me on irc or something and I can walk you through it.  :-)

**Comment by ReikaKalseki** [comment]
Blazes do not properly handle lateral motion AI, so I just implemented a weak magnetic effect, which does not look any different than "walking" would anyways.

**Comment by OvermindDL1** [comment]
> Blazes do not properly handle lateral motion AI, so I just implemented a weak magnetic effect, which does not look any different than "walking" would anyways.

Indeed, which is why an AI task can override it, either pathing directly or manually moving them on-tick.  ^.^
