### ISSUE TITLE
Void Monster causes a permanent darkened sky/distance fog

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1579]
When I returned from my first trip to the Twilight Forest (where I accomplished absolutely nothing) it was like this: http://imgur.com/a/0wBRN. The same thing happens in the Nether and the TF.

Previously, in both the Twilight Forest and the Overworld, it was normal. Absolutely no idea what triggered it but it persists across worlds.

Creating a new test world had the same issues from the start, no TF trip required.

Removing the mod resulted in this: http://imgur.com/a/4gIo1.

Config is set to whitelist for overworld, nether, and twilight forest.

**Comment by DracoScythem** [comment]
Do you have FastCraft installed (and its culling feature enabled)?
If yes, this is probably related to #1455

**Comment by ReikaKalseki** [comment]
I am wondering if it might be a good idea to check FastCraft's config and force users to disable that feature...

**Comment by DracoScythem** [comment]
Maybe... especially since world culling doesn't increase performance all that much in more heavily modded environments (TESRs and Entities are culled anyways and ISBRs shouldn't pose a real problem). Also the most important feature of FC are the improvments to light calculation and chunkloading which aren't impacted by that setting.
Still: Some prompt or warning to the user might be a good idea - not everyone fancies having performance related configs changed magically 🔮 ...

//Offtopic: Talking of warnings: Is there a specific reason for DragonAPIs Forge version requirement still being 1558 even though some of the World hooks only work on 1614 (and people repeatedly post crashes on MCF as a result)?

**Comment by ReikaKalseki** [comment]
> //Offtopic: Talking of warnings: Is there a specific reason for DragonAPIs Forge version requirement still being 1558 even though some of the World hooks only work on 1614 (and people repeatedly post crashes on MCF as a result)?

Yes, namely being my dev environment not loading in 1614 for some stupid reason.

**Comment by OvermindDL1** [comment]
> Yes, namely being my dev environment not loading in 1614 for some stupid reason.

What is the complete log of the error?

**Comment by ReikaKalseki** [comment]
I do not have it on hand, and do not want to have to completely rebuild my workspace again just to get it.

**Comment by ReikaKalseki** [comment]
I put the ASM into a different part of a different class; it still works, including with FastCraft; we will see if culling breaks anything.
