### ISSUE TITLE
[CC] [TF] Sky Ember does nothing to Dark Forest's canopy

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1602]
Boo, zero stars.

Chroma V18b, TF 2.3.7.

**Comment by ReikaKalseki** [comment]
I have fixed this multiple times...

**Comment by ReikaKalseki** [comment]
Turns out that it *does* burn the forest, but it was slow and mostly happening below the canopy.

That is now fixed. Gloriously.
![https://i.imgur.com/m8a9ln9.jpg](https://i.imgur.com/m8a9ln9.jpg)
![https://i.imgur.com/ZeNeLmg.png](https://i.imgur.com/ZeNeLmg.png)
![https://i.imgur.com/Er8ZYX6.jpg](https://i.imgur.com/Er8ZYX6.jpg)
![https://i.imgur.com/Gl0ndqD.jpg](https://i.imgur.com/Gl0ndqD.jpg)
