### ISSUE TITLE
[RoC] [GT5U] Some ores (brown and yellow limonite, banded iron, possibly more) process to nothing in the Grinder

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1605]
The recipe for their processing exists, but yields empty slot. 'U' for them shows iron ore on Extractor tab, so they're probably usable in that.

These ores don't have oreIron OD, but they yield iron ingot when smelted - they're oxides that, if dusted, require more processing in GT machinery.

Oops, played too much Chroma.

**Comment by ReikaKalseki** [comment]
The console should log grinder recipes; what does it say for these?

**Comment by Barhandar** [comment]
I see no mention of either of the limonites or banded iron (MatID/damage values 930, 931 and 917 respectively) [in the relevant part of log](https://gist.github.com/Barhandar/7ac581a42d4454cd0bbbf5c70f8c52b8).

**Comment by ReikaKalseki** [comment]
I see a lot of "gt.blockores".

**Comment by Barhandar** [comment]
Those are Greg's metaitems, damage value determines the ore and underlying stone. The "pure" ones are registered (presumably based on OreDictionary) correctly, for example, tin: `[20:21:40] [Client thread/INFO] [FML/RotaryCraft]: ROTARYCRAFT: Adding 3x grinder recipe for Tin ore 1xgt.blockores@57` which has oreTin entry. Some of the impure-but-still-same-material are also correctly registered, like oreCassiterite, `[20:21:40] [Client thread/INFO] [FML/RotaryCraft]: ROTARYCRAFT: Adding 3x grinder recipe for Tin ore 1xgt.blockores@824` - well, at least somewhat, because Greg's cassiterite yields two ingots when smelted, not one like pure tin, and so should probably have 6x recipe - or oreTetrahedrite, which correctly processes into copper (damage 840). Limonite would show up as gt.blockores@930, but it does not.

Additionally, none of the empty-output recipes show up in NEI's list of all Grinder recipes.

**Comment by ReikaKalseki** [comment]
I will look into the GT ore handler.

**Comment by ReikaKalseki** [comment]
How large is the full list of GT ores?

**Comment by OvermindDL1** [comment]
Heh, full list, hmm, probably well over 100k different variants...  >.>

You really should use his API to get the information based on the itemstack (it can give you results, even specific from grinding, and all sorts of things) as it is *way* efficient to get this information (statically calculated), let me see if I can poke him.  ^.^

**Comment by ReikaKalseki** [comment]
Are there functions for what I would need, which is basically "get equivalents to X ore, optionally with yield multiplier"?

**Comment by GregoriusT** [comment]
A few HUNDRED lines worth of individual Materials, resulting in about 100000 OreDict Entries according to the amount of Lines I saw in my RotaryCraft Log, that one time I complained to you about that.
Why do you ask? Oh right because of the Grinder Handler, well that will be fun.
Lemme count: 1, 2, 3, ... 520, 521, 522, yeah thats all the Materials that have Ores assigned to them. You can substract the amount of Ores that you handle from that easily since I literally handle all the Ores you handle already.
Pseudo-Edit-Because-I-Took-Too-Long:
Iterate over "gregapi.oredict.OreDictMaterial.MATERIAL_ARRAY" (may contain nulls)
Then check if the iterated OreDictMaterial Object has "if (iteratedmat.contains(gregapi.data.TD.ItemGenerator.ORES))"
If the aforementioned clause is true, then it is a valid Material that does create OreBlocks. "iteratedmat.mNameInternal" would be the official Material Name, it would be "Gold" for "oreGold"
phew that took a while aswell, but I will just post it now before it gets too long. ;)

**Comment by GregoriusT** [comment]
There is also a yield Multiplier
"iteratedmat.mOreMultiplier"
It's for things that are dropping multiple items like Lapis or Redstone Ore.

**Comment by OvermindDL1** [comment]
> phew that took a while aswell, but I will just post it now before it gets too long. ;)

Oh you are not used to my long posts.  ^.^;

**Comment by Barhandar** [comment]
> If the aforementioned clause is true, then it is a valid Material that does create OreBlocks. "iteratedmat.mNameInternal" would be the official Material Name, it would be "Gold" for "oreGold"

Bonus: that would probably make stone variant ores compatible with RoC processing too.

**Comment by ReikaKalseki** [comment]
Where is this class? The closest I have found is [this](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/enums/Materials.java), which does not have any of the internal members you describe.

**Comment by Barhandar** [comment]
>Where is this class? The closest I have found is this, which does not have any of the internal members you describe.

Wrong GregTech. There's two: GT5U run by @Blood-Asp and GT6 run by Greg. The relevant class should be in [this](http://files.minecraftforge.net/maven/com/gregoriust/gregtech/gregtech_1.7.10/6.02.07/gregtech_1.7.10-6.02.07-sources.jar).

**Comment by GregoriusT** [comment]
GT6 isnt on Github, you would need to just download the src jar and unpack it to get the Files with the Link Barhandar gave you.

**Comment by OvermindDL1** [comment]
> GT6 isnt on Github, you would need to just download the src jar and unpack it to get the Files with the Link Barhandar gave you.

You really need to get unlimited internet like the rest of the civilized world so you can actually start using the programmers full toolset.  ;-)

**Comment by GregoriusT** [comment]
Hey I would probably use Git if I start a new Project (including having a proper setup of everything), it's not like I knew how to make it work properly when I started modding (because I didn't know). Also technically everytime I compile I also autoupload the changelog, so I doubt bandwidth is the reason to not use Git. :P

**Comment by OvermindDL1** [comment]
> Hey I would probably use Git if I start a new Project (including having a proper setup of everything), it's not like I knew how to make it work properly when I started modding (because I didn't know). Also technically everytime I compile I also autoupload the changelog, so I doubt bandwidth is the reason to not use Git. :P

Lol, it actually compresses *very* well (text with a lot of repeated words), and it should upload compressed as I recall.  But yes, using git would be cheap for you, however the github interface is less so if you started touching it 'that' much then.  ^.^

EDIT:  Also, no better time to start using `git` then right now!  Just go to your root project directory, run `git init`, then make a `.gitignore` file leaving out build artifacts and such, then remember to `git add ... && git commit` on occasion (usually your IDE can do that for you), you don't even need to upload it to github, even just keeping it locally can truly save your butt in ways you would not expect (or use bitbucket if you want a free private git or so).  :-)

**Comment by ReikaKalseki** [comment]
I imported the code into my dev environment and it has 347 errors, mostly due to not finding classes, some in code I do not have (some core mod code, and some APIs), some visibility differences, and some that look like actual code errors (eg "method must return of type X").

I do not want to have to fix this manually; can I strip out everything except the material-related code?

**Comment by GregoriusT** [comment]
Oh shit I forgot that setting up GT6 in the Dev Environment is a real hassle to do. (because I have a rather broken Dev Environment too because of the tons of compat that I am doing)

I think it is possible to strip all other classes except the OreDictMaterial one and then just delete the Stuff that Errors from the OreDictMaterial Class so that you can access the Array containing all OreDictMaterial instances and the String and Integer Fields that you need to access.

**Comment by OvermindDL1** [comment]
> I imported the code into my dev environment and it has 347 errors, mostly due to not finding classes, some in code I do not have (some core mod code, and some APIs), some visibility differences, and some that look like actual code errors (eg "method must return of type X").

GT6's API has support for a *LOT* of mods (and at dev time he requires their API's linked in as well, but not at runtime, that restriction allows it to work without ASM).

However you do not need to link in or include the source yourself (plus you could just grab it from maven then, you don't only need to not drop in source but you should not drop in source, only the gradle link should be done if you want to link in).

To use his classes without linking in other mods you can just reflectively grab the class ID's then cache the function pointer objects.

> I think it is possible to strip all other classes except the OreDictMaterial one and then just delete the Stuff that Errors from the OreDictMaterial Class so that you can access the Array containing all OreDictMaterial instances and the String and Integer Fields that you need to access.

And that is the alternate way, just keep what you want to access (but again, don't include the source or compiled class files of the GT6 API in the compiled output).  I just grab via reflection myself though, simple enough and FML has helpers specifically for such use.

> Oh shit I forgot that setting up GT6 in the Dev Environment is a real hassle to do. (because I have a rather broken Dev Environment too because of the tons of compat that I am doing)

And yes, I keep poking greg to fix this, but it is difficult for me to help to do so until he, oh, get's on github (or bitbucket if you want it private) or whatever.  ^.^

**Comment by Blood-Asp** [comment]
A GT6 Dev enviroment is likely still much easier to set up as an Rotarycraft Dev enviroment. I still remember that pain... Not at all similiar to default forge setups.

**Comment by OvermindDL1** [comment]
> A GT6 Dev enviroment is likely still much easier to set up as an Rotarycraft Dev enviroment. I still remember that pain... Not at all similiar to default forge setups.

I have a github pre-built workspace for making GT6 mods on my github (and it's linked from the GT6 download page), I probably need to update it again though but it should work?  ^.^

**Comment by ReikaKalseki** [comment]
OK, I have it set up; how do I go from a material to determining what vanilla/mod ore it corresponds to (if any)? Examples like "gold" are obvious, but what if the name is "limonite" or something?

Also, how to fetch the ore block ItemStack(s)?

**Comment by GregoriusT** [comment]
someOreDictMaterial.mNameInternal gives you "Gold" for Gold, "Iron"
for Iron etc. Just prefix the "ore" in front of it and boom, oreGold
and oreIron, to give an example. ;)

**Comment by ReikaKalseki** [comment]
But again, what if the ore's internal name is something different, but it still is equivalent to a vanilla one (eg limonite)? "oreLimonite" is not any of my default entries.

**Comment by GregoriusT** [comment]
Dont worry about that, those names are DEFINITELY always right.
"Aluminium" will also work for "Aluminum" or "NaturalAluminium" as
there is an inbuilt OreDict Reregistration in GT6 that makes sure that
the proper Names are always definitely existing even if you use the
wrong name.

**Comment by ReikaKalseki** [comment]
Are you saying that the ores that do correspond to a vanilla one would have its oreDict tag as well? Because if that were the case, they would be processable already with no issues.

**Comment by GregoriusT** [comment]
This request was to make things that you dont know about processable,
like for example uhhm Bismuth Ore or Vanadium Ore and loooooots more.

I can understand if you dont wanna support that directly sicne its
just extra effort for something GT6 itself already does very well
within itself (even though I dont know how the hell I can add Recipes
to your Ore Extractor properly so I avoid that, since it doesnt have
an "itemstack input" variant last time I checked, only a string
input).

**Comment by OvermindDL1** [comment]
> only a string input

What the heck?  How on earth could that work well?!?

**Comment by ReikaKalseki** [comment]
> This request was to make things that you dont know about processable, like for example uhhm Bismuth Ore or Vanadium Ore and loooooots more.

No, what I am looking to do is add what are effectively aliases for vanilla ores, where you have an ore that is "close enough" to a vanilla one, like iron from limonite.

**Comment by OvermindDL1** [comment]
@GregoriusT I think what he wants is the command needed to be able to get a list of outputs and amounts from a specific processing of a specific itemstack?  That was one of your odd 2-character named classes wasn't it?  ^.^;

**Comment by Barhandar** [comment]
>No, what I am looking to do is add what are effectively aliases for vanilla ores, where you have an ore that is "close enough" to a vanilla one, like iron from limonite.

Basically, getting whether the ore material results in a processable-by-grinder-when-pure material when smelted. Iron from limonites and pyrite, copper from chalcopyrite and tetrahedrite (with pyrites having sulfur flakes byproduct), tin from cassiterite and cassiterite sand, et cetera. In GT5U material config file it's the `S:MaterialDirectSmeltInto_X` property.  
Maybe with unique reduced duplication chance for ores where that property and `S:MaterialSmeltInto_X` do not match up (==ore is impure) unless `I:OreSmeltingMultiplier_X` is more than 1, in which case increase chance (e.g. cassiterite and cassiterite sand which have multiplier of 2).

**Comment by GregoriusT** [comment]
Oh then I need to make a manual List of things, because my Ores aren't very "vanilla friendly", since they are supposed to have some specialized Ore Processing to them.

Just DO NOT register those to the OreDictionary under those aliases, that will mess up a LOT of Stuff. Please just DONT do that, it would actually reduce compatibility by a lot. Do something internal for the aliases, and leave the OreDictionary out of the thing!
Those things are SUPPOSED to be different from normal Ores, and usually should not be processable by any random modded Machine in any typical way as it would wreck balance very hard.

I thought you just wanted to do Limonite Ore into a pile of Limonite Flakes with a Byproduct or something, and then just have Limonite be accepted in your large Furnace to refine the Iron out of it, what would be a perfectly fine way of doing it.
But Limonite itself isn't just "regular plain Iron Ore", you get like a 1/4th of the amount of Iron from it compared to Iron Ore, Hematite would be 2/5ths Iron, Magnetite 3/7ths Iron etc.

You actually even get much less out of most of those Ores compared to the vanilla Ores (that is why there is so many Ores per Vein in the first place).

But as promised, here a List of things that are close enough to the Ores your Stuff usually accepts:

for Tin:
"Cassiterite" x2 (yeah that one is special)

for Iron:
1/3rd "Pyrite"
1/4th "YellowLimonite", "BrownLimonite"
2/5ths "Hematite"
3/7ths "Magnetite"
3/14ths "BasalticMineralSand", "GraniticMineralSand"

for Nickel
"Garnierite" x1 (that one is special too)
9/17ths "Pentlandite"

for Copper:
1/4th "Chalcopyrite", "Kesterite", "Stannite"
1/5th "Malachite"
3/8ths "Tetrahedrite"

for Tungsten:
1/6th "Scheelite", "Wolframite", "Ferberite", "Huebnerite", "Stolzite"
1/7th "Tungstate"
1/9th "Russellite"
1/11th "Pinalite"

for Uranium:
"Uraninite" x1 (that one is special too)
3/5ths "Pitchblende"

for Silver
1/2 "Bromargyrite"

for Platinum
1/2 "Cooperite" 

There is also "Galena" for both Lead and Silver, and "Bauxite" for Aluminium, I think you already have processing for that.

**Comment by ReikaKalseki** [comment]
Implemented. This should take precedence over the `ModOreList` entries, for GT items.

That said, the grinder does not have the granularity for these ratios; I will multiply them against the x3, but most times, that will yield one flake (rounded up).

	@ModDependent(ModList.GREGTECH)
	private void loadGTOres() {
		for (CounterpartOres ore : CounterpartOres.oreList) {
			for (ItemStack is : ore.getAllOreBlocks()) {
				int n = Math.max(1, (int)Math.round(ore_rate*ore.yieldFraction));
				OreType base = ore.counterpart;
				ItemStack flake = base instanceof ReikaOreHelper ? ItemRegistry.EXTRACTS.getCraftedMetadataProduct(n, 24+base.ordinal()) : ExtractorModOres.getFlakeProduct((ModOreList)base);
				flake.stackSize = n;
				this.addRecipe(is, ReikaItemHelper.getSizedItemStack(flake, n), RecipeLevel.CORE);
				RotaryCraft.logger.log("Adding "+(n)+"x grinder recipe for GT ore "+ore);
			}
		}
	}

![https://i.imgur.com/wNqG9gu.png](https://i.imgur.com/wNqG9gu.png)
