### ISSUE TITLE
Pylon dies if you add too much crytallinestone to it

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1615]
Pylon dies if you add too much crytallinestone to it

![2017-10-09_15 55 25](https://user-images.githubusercontent.com/10777735/31355988-575ce43a-ad0a-11e7-9049-9b685b7c438a.png)

![2017-10-09_15 43 10](https://user-images.githubusercontent.com/10777735/31355941-2f28d5fa-ad0a-11e7-8e0a-733f0c098500.png)

![2017-10-09_15 55 40](https://user-images.githubusercontent.com/10777735/31355992-5ad90e18-ad0a-11e7-9d10-6f0a70eff5f6.png)

entering and leaving debug mode fixes it.

**Comment by ReikaKalseki** [comment]
...Does this surprise you?

**Comment by Barhandar** [comment]
It's not about _amount_ of crystalline stone, it's about breaking crystalline stone ~~on the floor level~~ _anywhere_ within the focal ring, exclusive, while central energy focal point is present. Which includes empty area between focal ring and broadcast ring, and the broadcast ring itself.

I guess what happens is that crystalline stone blockbreak ~~on y-9~~ (5 blocks away orthogonally, 4 diagonally) causes an erroneous structural check event for the PYLON structure (as opposed to PYLONTURBO), which fails due to focal point's presence, deactivating the pylon.
