### ISSUE TITLE
Modpack fireup issue with possibly DragonAPI?

### ISSUE THREAD

**Issue by bhodgins** [ReikaKalseki/Reika_Mods_Issues#1617]
I've been trying to track down a problem I've been having with somebody's modpack- I'm not sure exactly what's breaking here. from the most outward, quick glance it almost looks like some recursive function in DragonAPI is accessing memory out of bounds, causing a segmentation fault with Java. I've tried at least 3 versions of the JDK with no difference and I'm not quite sure what's happening here.

I have an error log gist here:[https://gist.github.com/bhodgins/a5f5e551633c31c64d5df1797e15f624]( https://gist.github.com/bhodgins/a5f5e551633c31c64d5df1797e15f624)

I have a load log available if requested, and can provide the core dump if needed..

Before DragonAPI was updated, it was causing a segmentation fault with stack overflow in the same area of code here. I don't have those logs, but it could be related.

**Comment by MajorGeneralRelativity** [comment]
As Modpack author, I can provide a modlist.
Modlist: https://gist.github.com/MajorGeneralRelativity/f8a16bc338ef5ab1529d7e642bdd5431

I have unfortunately been unable to reproduce this bug on a platform or OS that is not the one bhodgins is using (BSD).

**Comment by ReikaKalseki** [comment]
I saw this once many years ago. It is indeed OS and JVM specific, and is caused by that pairing unable to support recursion entirely, or it ignoring exception catching. Either way, it is so rare and probably unfixable that nothing can be done.

**Comment by MajorGeneralRelativity** [comment]
Thank you, I will keep this in mind if any of my other players report this. I suspected as such, but wanted confirmation.

**Comment by ReikaKalseki** [comment]
It is not specific to your pack; early during game load, DragonAPI probes the maximum recursion depth allowable to avoid StackOverflowErrors. This is done by recursing infinitely inside a try-catch so that it can know at what iteration the exception is thrown. However, in this particular case, instead of the aforementioned SOE, the JVM crashes and executes a core dump instead. This is outside my control.

That said, thinking further, I believe there was as JVM argument I added last time for manually specifying the allowable recursion depth, which would skip this check. A few thousand (~4000) is usually reasonable.

**Comment by MajorGeneralRelativity** [comment]
I didn't think it was specific to my modpack, but thank you for additional clarification. I just meant that if any other of my (small) group of users reported this, I would tell them to use a different OS.

**Comment by ReikaKalseki** [comment]
Confirmed: https://github.com/ReikaKalseki/DragonAPI/blob/master/DragonAPIInit.java#L319

**Comment by MajorGeneralRelativity** [comment]
*makes some recursion jokes*
