### ISSUE TITLE
Drop Processor GT Handler triggering a crash

### ISSUE THREAD

**Issue by ReikaKalseki** [ReikaKalseki/Reika_Mods_Issues#1659]
#1635 @Barhandar Any idea what I might have done wrong?

https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Processing/TileEntityDropProcessor.java#L897

**Comment by Barhandar** [comment]
Is GREGTECH the actual ID or is the source for magicstring using actual ID for GT5U? Is the create() run only when isLoadable() returns 'true'?

Looking up the recipes for the crate causes a small (~1 min) lookup freeze which is cached afterwards. Drop Processor does not show up in the result. Looking up usages for the crate also causes a lookup freeze, significantly more substantial (10 minutes, still hadn't unfroze). Either it's a subset of Chroma's GT-transmutation freeze, or these clientside functions are doing something not good. 

Otherwise, I have no idea what could go wrong.

**Comment by ReikaKalseki** [comment]
Apparently this only works on some GT versions:

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=30102

**Comment by ReikaKalseki** [comment]
@GregoriousT @Blood-Asp How might I tell the difference between them (GT6 vs GT5U) at runtime?

**Comment by Blood-Asp** [comment]
Not sure if it is still true but afaik GT6 loads in two mods. "gregtech" and "gregtechAPI" (or something like that) while GT5 only loads as "gregtech".

**Comment by ReikaKalseki** [comment]
"or something like that". Exactly what?

**Comment by OvermindDL1** [comment]
> "or something like that". Exactly what?

"gregapi_post" (To do stuff after the full gregtech6 api is loaded)

> https://github.com/OvermindDL1/gt6-new-workspace/blob/master/src/main/java/com/example/examplemod/ExampleMod.java#L20

**Comment by ReikaKalseki** [comment]
OK, fixed.
