### ISSUE TITLE
[v19b|request] Casting Temple/Complex not working anymore

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1673]
Hey Reika,

since I updated from v18b to v19b I can only do T1 crafting and I wonder why.

I asked arround a bit and it seems to be that a chest on top or besides the casting table is no
longer allowed and I ask you why?

I have never had any problems with a chest either on top or on any side of the casting table. So I request to allow chests arround the and on top of the casting table back. Would be nice, otherwise I must fall back to v18b to get it working again.

**Comment by ReikaKalseki** [comment]
No. This was done to prevent the almost-inevitable bug report when the chest turned out to block line of sight to the repeaters.

**Comment by Barhandar** [comment]
And now you get all the bug reports with this, instead, because setting up a logistic network is far more complex than plopping a chest down.

Also, @ReikaKalseki, instead of flat-out blocking, why not add visual feedback? Special function for the casting table that checks the structure repeater positions and displays a visual particle effect of a beam from the repeater "breaking against" the blocks in the way. Ditto for Casting Delegate, a pillar of light going down onto the table without interruption, which instead "splatters against" blocks in the way if one's placed between. Will therefore allow both error-less function of the late-game casting and convenience of an automatic chest output of the rest-of-the-game casting.
