### ISSUE TITLE
Iguana Tinker Tweaks tools gain experience when mobs are killed with the Mob Harvester

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#168]
As the title states, this is similar to issue #121 

When I was standing around in my base I saw my cleaver gain a level, after watching it I see that it is getting the exp from the mob harvesters wacking the blazemen in my farm. Nifty bug, but still a bug. Fault probably lies in the fact that mob harvest acts as the player.

**Comment by ljfa-ag** [comment]
Yeah, this one was actually not adressed in #121 at all

**Comment by ReikaKalseki** [comment]
This is because IguanaTweaks indiscriminately watches the deaths to see if a player is connected to it. Short of breaking the Harvester, the only fix is on their end.

**Comment by ljfa-ag** [comment]
Using a fake player rather than the player who placed it is not an option? Because I'm pretty sure this is not the only problem that a "wrong" damage source could cause.

**Comment by ReikaKalseki** [comment]
No, because that will break a great deal of other functionality, including drops.

**Comment by TomeWyrm** [comment]
So many mods check to see if a valid player killed something that the harvester's method really is the most future proof and least error-prone method. ITT should honestly be checking to see if the weapon held is dealing the killing blow, because seeing this bug report? I can almost certainly reproduce this bug with fire arrows and TNT, or splash potions.
