### ISSUE TITLE
Cave Control causes "Invalid Biome Id" crash after time spent in certain area

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#1712]
https://lunarshark.com/reikalog.txt is the log, it's too big to fit fully into pastebin.

So I'm standing in a single area chain-casting "Lumen Launch" to try to make my repeater blow up (which a read of the code indicates is *not* it, and I need to figure out what isn't a ritual table or relay source that I have access to) and the game consistently crashes after a few minutes. The Asveste pylon (which is some 32 or so blocks away) is drained, with about 6 Asveste trees supplying it (to give an idea of the "flow rate") while the Galazio pylon is some 400 blocks away (trust me, it's the shortest path that would allow me to cast an ability for the progression). This last log showed enough stacktrace to suggest Chromaticraft is asking Cave Control for something?

If you like, I can host a save for reproduction reasons. Optifine *was* installed, but was removed in an attempt to fix this (it did nothing, I only mention it in case there's extra behavior left over)

**Comment by ReikaKalseki** [comment]
You have corrupt chunk data somewhere. That or (less likely) something messing with world threading.

**Comment by Barhandar** [comment]
This seems to be the same mineshaftgen crash I used to have with slightly different stacktrace before reaching CaveControl's code (plus actually telling what the error is as opposed to "lol, figure it out, irrelevant string as reason"). Mine was biome-dependent (happened in Jade Cliffs), though you don't have BoP so it must also happen in other biomes OR have a not real biome-related crashpath.

The crash is reproducible by me on completely new world, so either one of the mods involved corrupts the world immediately, or it is NOT world corruption. A few mods you have can be ruled out as the cause (OCMOS, OpenSecurity, Thistle), leaving AE2, NEI, and Reika's mods as the overlapping ones. The dates involved mean it's not a recent issue; it's not even exclusive to the pack I was having as that was assembled a year later than this issue.

P.S. To clarify, I've stopped having this crash because I had to move out of Jade Cliffs, not because it actually stopped crashing in them.
