### ISSUE TITLE
DragonAPI/ReactorCraft - Client NPE while rendering liquid in NEI

### ISSUE THREAD

**Issue by LemADEC** [ReikaKalseki/Reika_Mods_Issues#1713]
As of V19c, client crashes when checking for usage of Quicklime.
https://gist.github.com/LemADEC/2a99f368cb3bef71f979c37840e567d0

It's a quick custom modpack, not much configuration change whatsoever.

**Comment by ReikaKalseki** [comment]
You have an invalid fluid registered to the game.

**Comment by LemADEC** [comment]
How would I know witch one is invalid?

**Comment by LemADEC** [comment]
Issue is reproduced with only your mods, CoFHCore and NEI, as seen here: https://gist.github.com/LemADEC/3c79d91fcf0b3a28a08e0785273f08f6

**Comment by LemADEC** [comment]
Also reproduced without CoFHCore nor Geostrata.

**Comment by Mamotromico** [comment]
I am having the exact same crash. Only mods present are Rotary, Reactor, Electric and NEI

Crash Log: https://pastebin.com/3z0PDiAa

**Comment by straelok** [comment]
The same problem. I removed all other modes, the problem remained. On the Internet I found the old version DragonApi/ReactorCraft and other, there is no such problem. I decided to try to remove the recipe from the game so that players do not have crash from NEI, but I found out that this is not possible using minetweaker3. Reika, you seriously did not fix the problem for a month and Do not let them fix it to the players themselves ?!!!
