### ISSUE TITLE
[CC] Walking too much above a Ritual Altar does not Reset GUI

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1715]
By mistake I walked too much over the Ritual Altar after it charged and while it did stop the ritual, the items hotbar was gone even after a change perspective (which was on 3rd person).
Silly little thing though.

**Comment by ReikaKalseki** [comment]
Does this happen reliably?

**Comment by TsumiHokiro** [comment]
I can reproduce it quite easily on my side:
Wait for the table to charge and walk over it -> Keep walking and slide out of the table. You'll have the change perspective and can change it with F5 (Or other button of your choice) and when back to First Person you won't have the hotbar displayed.
You can have the hotbar fixed once you walk back on the table and it ends the ritual properly.
PS: If you open the Menu screen you'll see the hotbar, but leaving it you lose the hotbar.
PS2: I do have to be ubber fast to be able to leave once Locked (100%+ speed) but the first time, by accident that is, I had only 40% speed movement upgrade and skidded over it.

**Comment by waterlubber** [comment]
I've reproduced this bug by mistake a few times. You can get the hotbar and first person back with F1 and F5, of course. I think it's caused by not being on or near the table when it completes -- I've personally done it because my RoC jetpack glider kicks in and I fly away from my base (as I typically AFK during the ritual.)

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
