### ISSUE TITLE
Ender Quarry causes crash with Chromaticraft 

### ISSUE THREAD

**Issue by captchainy** [ReikaKalseki/Reika_Mods_Issues#1718]
a

**Comment by lawl281** [comment]
I am also getting this crash it appears with any chromaticraft ore it hits.  I have yet to find anyway way to make the quarry usable without crashing the server.

**Comment by ReikaKalseki** [comment]
Is the player entity the quarry is using null?

**Comment by lawl281** [comment]
how does one set a player entity?

**Comment by ReikaKalseki** [comment]
It is internal to their code, unless they have an explicit "act as player Y" mechanic.

**Comment by lawl281** [comment]
so if it is internal to their code how do I check the player entity or do anything about it

**Comment by ReikaKalseki** [comment]
I would have to check the internal ExU code, unless there is some other way to expose it (for example by testing Ender quarries in protection zones).

**Comment by Aivech** [comment]
What I want to know is why a quarry needs to use a fake-player at all.

**Comment by ReikaKalseki** [comment]
Blocks are harvested with players, and this is used by CC for progression-specific drops.

**Comment by I-Enderlord-I** [comment]
You Change this line [here](https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/BlockTieredResource.java#L88) into this  `boolean tier = (player instanceof FakePlayer) ? false : this.isPlayerSufficientTier(world, x, y, z, player);` 
where FakePlayer is `net.minecraftforge.common.util.FakePlayer`

Because ExtraUtilities uses `FakePlayer fakePlayer = FakePlayerFactory.getMinecraft((WorldServer)this.worldObj);` to create a FakePlayer for harvestBlock().

**Comment by ReikaKalseki** [comment]
I already check fake players inside the CC progression, deeper in the stacktrace.

**Comment by Ratione** [comment]
I have also experienced this issue, but my java is super rusty, and my server is now borked until further notice. Any help would be greatly appreciated.

**Comment by ReikaKalseki** [comment]
Well, deleting the quarry is a temporary fix.

**Comment by Ratione** [comment]
I got that much, thanks :P

**Comment by ReikaKalseki** [comment]
I think this got fixed by other unrelated changes.
