### ISSUE TITLE
crash Galacticraft DragonAPI

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#1734]
1.7.10
DragonAPI 1.7.10 V19c.jar
Galacticraft-Planets-1.7-3.0.12.502.jar
GalacticraftCore-1.7-3.0.12.502.jar
MicdoodleCore-1.7-3.0.12.502.jar

in the logs I see that associated with the asteroid from the GC (dimension -30)
occurs either immediately after launch. or galactic maps flying to an asteroid. the game crashes to the main menu and no longer go to the SSP

is there a way to solve annoy problem?
without DragonAPI everything is OK
crash:
https://gist.github.com/ec89dbb1dac2b878ac78c51b5c319330
fml-client-latest.log
https://gist.github.com/52bfc8db88d59838c40e3266a8d29e7b
latest.log
https://gist.github.com/b4930dc79b495bd2dc510f3135f98696

There is an attempt to load a chunk (14,17) in dimension -30 that is already being loaded. This will cause weird chunk breakages.

**Comment by ToastedEggplant** [comment]
I can confirm I'm getting the same issue.

**Comment by Geminiquasar47** [comment]
I've encountered this one, And I know how to work around it.  Basically, the crash happens when _generating_ chunks in the asteroids dimension.  What you have to do is pregenerate the chunks for that world.  to do that, first make a complete copy of the world you wish to pregenerate chunks for.  now remove or disable dragonAPI and all other mods that use it (rotarycraft, chromaticraft, etc.), and install the IDfixer  (look for the link [here](https://sites.google.com/site/reikasminecraft/home) so things won't get scrambled.  Then, you can launch minecraft, travel to the dimension in the copy of your world, and just generate the chunks by moving around them.  that process is pretty time consuming, but worth it.  when you are done pregenerating the chunks, exit the dimension, save the world and quit.  now, go into the saves, copy the entire Dim30 folder, and put it in the original world.  after that, replace the mods you removed from your folder earlier, and you can launch with your original mod setup.  

sorry that explanation was a bit long winded.  Keep in mind that if you go near the edge of the chunks you have pregenerated, the game WILL crash as it tries to generate a new chunk.  Hope that helps!

**Comment by ReikaKalseki** [comment]
Fixed in #1838
