### ISSUE TITLE
crash in minecraft forge

### ISSUE THREAD

**Issue by tfrrft** [ReikaKalseki/Reika_Mods_Issues#1752]
i have a problem when i go to play some minecraft.I recently downloaded pixelmon 1.3.1 but when i had the 1.2.1 version nothing was wrong.Can you help me???

https://pastebin.com/SVShfHvm

**Comment by Duckfan77** [comment]
Not related to any of Reika's mods. Can't even be any residue from previous presence, as you're running 1.10, and Reika's are only up to 1.7.10.

**Comment by tfrrft** [comment]
where can i put this???

**Comment by OvermindDL1** [comment]
Where can you put what?

The issue is that these mods only work on MC 1.7.10, not 1.10.  No clue what pixelmon is.

**Comment by Duckfan77** [comment]
That's not the issue either. He doesn't have any of Reika's mods installed in the first place, based on the log. 

If you do have one of Reika's mods installed, the as Overmind said, you can't use them in MC 1.10.
Otherwise, the issue is caused by one of your other mods, and you should report it to them.

**Comment by ReikaKalseki** [comment]
> where can i put this???

Perhaps somewhere it is actually relevant?
