### ISSUE TITLE
Clicking on a gearbox containing lubricant with an empty bucket removes all lubricant but does not fill bucket.

### ISSUE THREAD

**Issue by SayethWe** [ReikaKalseki/Reika_Mods_Issues#1759]
This also applies when there is more than one bucket of lubricant in the gearbox. All of it disappears.

**Comment by arceus179** [comment]
Are you clicking on it with multiple buckets in a stack, or just one bucket? Because I found that having more than one bucket in one inventory slot likes to screw up rotarycraft liquid holding blocks sometimes.

**Comment by SayethWe** [comment]
A single bucket. Last time I tried, using an ItemStack of multiple Buckets does nothing.

**Comment by ReikaKalseki** [comment]
This is intentional, to allow uncrafting of the gearboxes.

**Comment by SayethWe** [comment]
Interesting. This feature has been the number one cause of lost/damaged gearboxes for me then, just by virtue of accidentally clicking in the wrong place.

Is there a config for it that I missed, such that to remove the lubricant you can only put the gearbox in a crafting table?

**Comment by ReikaKalseki** [comment]
Putting the gearbox in a table is how you uncraft it.

**Comment by redelman** [comment]
If there's more than one bucket of lubricant in the gearbox, why return a bucket full of lubricant instead of voiding it? Then void only when less than a bucket remains? Then again, lubricant is really cheap.

**Comment by ReikaKalseki** [comment]
> Then again, lubricant is really cheap.

Exactly, and requiring bucketing out the lubricant by hand would actually be very irritating.

**Comment by Kobra331** [comment]
Am i missing something? Im not able to uncraft any Gearboxes. Neither Bedrock gearboxes nor emptied steel gearboxes. I tried the normal Craftingtable, the Rotarycraft Worktable and the inventory crafting grid.


edit: ok the worktable works but only if i activate it by a lever and not everytime. Is it a new bug or a strange mechanic?

edit2: ok you have to put it in the middle slot and than apply a Redstone Signal. This would be a nice information for the Handbook! Because neither the NEI nor the Worktable gives information about an uncrafting possibility.
