### ISSUE TITLE
[CC] Wardedglass placed by Construction star unbreakable

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1764]
Hi,

If you place warded glass from thaumcraft with the construction star you can't harvest them with your Wand.

**Comment by ReikaKalseki** [comment]
That would be because it does not set the placer data, as it has no way of knowing that the block even *has* such data. Short of an ugly hack of reflection, which is liable to break any time TC updates, there is not really much I can do; The proper fix for this is for "invalid" warded stone to either pick up its neighbors' data, be breakable for everyone, or fail to place entirely.

**Comment by OvermindDL1** [comment]
> The proper fix for this is for "invalid" warded stone to either pick up its neighbors' data, be breakable for everyone, or fail to place entirely.

Or use the player as the placer and use the standard item placement callbacks of the blockitem itself to let it place itself as it expects?

**Comment by ReikaKalseki** [comment]
Calling that code would also cause a number of other unwanted side-effects, some of which are not easy to undo. Additionally, they require specifying additional information that may not apply to the specific block being placed (eg direction, which may influence other behaviors).

That is, depending on the implementation of that ItemBlock's placement code, it might make incorrect assumptions based on the information fed in because it assumes that this placement code is only ever called from "direct" use. For example, imagine placing the block reads, then clears an NBT tag from the ItemStack, and the ItemBlock only allows placement if the NBT tag exists. The first placement would succeed, and the next might well crash, because the Construction star has no way of knowing that placement should now fail, nor that the data on the ItemStack has changed in a meaningful way. Another example is where the ItemStack data is used in a case where it is assumed to be unique (eg a link coordinate, like World Rifts). Causing several blocks to be placed with matching data could cause crashes, exploits (eg power from nothing), or any of a host of other issues.

One intermediary fix I can do is to simply blacklist warded glass from the star, but I am unsure if that is desirable.

**Comment by OvermindDL1** [comment]
Indeed, those are the issues, though they are surmountable (see all the FakePlayer block-placing TE's, many work fine in such a way, even with TE's warded blocks).

Though honestly I'd probably just blacklist it.  If the player has TC then they can place it with cobblestone or so then use transmutation wand to replace it with warded glass (that's what I do with such setups).

**Comment by ReikaKalseki** [comment]
> (see all the FakePlayer block-placing TE's, many work fine in such a way, even with TE's warded blocks).

Every single one of those has the capacity to and I have experience with crashing servers due to certain blocks not tolerating how they chose to run the placement code. They are not an example to look to for stability.

**Comment by OvermindDL1** [comment]
> Every single one of those has the capacity to and I have experience with crashing servers due to certain blocks not tolerating how they chose to run the placement code. They are not an example to look to for stability.

I'm mostly referring to the RP2 one as that's the one of who's code I've seen.  It's best to test if if the itemblock is of precisely one of the vanilla or other known instances, if it is not then refuse to use it unless you can give full information to it.  If it is a subclass of something you do not know, then you should not use it otherwise.

**Comment by ReikaKalseki** [comment]
No vanilla ItemBlock has (important) special behavior like this.

**Comment by OvermindDL1** [comment]
> No vanilla ItemBlock has (important) special behavior like this.

Precisely!  Hence why easy to just class-check.  ^.^

**Comment by ReikaKalseki** [comment]
My point is that, sure, it is safe to call the ItemBlock code on vanilla ItemBlocks, all of the vanilla blocks can also be safely placed "directly", making it a redundant effort.

**Comment by OvermindDL1** [comment]
It unifies the call code for use with a whitelist however.
