### ISSUE TITLE
Crash on Server Launch involving Ender Quarries, yet nobody has even made one..?

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#1802]
My server was up and running fine until I walked into one player's RotaryCraft area, in which the server crashed. I couldn't tell what gave the error while I was in-game because it was just as I was approaching the area. By looking at the error log I can see it has something to do with a gearbox and ExtraUtilities, but I find it strange that it refers to the Ender Quarry; all of the players on the server have never even made one, let alone place and interact with it. The server is suddenly unplayable because of this; even setting the world a few hours before I went near it doesn't fix the crash on server launch.

Error Log - https://hastebin.com/latunajoca.sql

EDIT: Even removing the world files causes it to not work. Crappy April Fools joke?
EDIT 2: Tried deleting both the Extra Utilities and the Reika Mods jars (DragonAPI, Rotary/Electri/ReactorCraft, Void Monster, ChromatiCraft) and replacing them but to no avail.

**Comment by ranger135xp** [comment]
I'm suddenly having this exact same crash with the same stacktrace! I've been trying to see what the issue is and it's driving me insane. Even making a new world does not work and the server generates this error before getting to world gen.

I found that removing either ExtraUtilities or Reika's mods (for me, dragon api, RoC, ReC, ElC) stops this issue from happening and the server works again.

I've also been searching this for the past 2 hours. Also, my server was running before this crash happened and it happened while it was running and no users were online. Is something for these mods supposed to be available online and suddenly not? It's very odd that this suddenly happens when it's been working fine for months and months.

**Comment by Mettymagic** [comment]
@ranger135xp I doubt there would have to be something online, otherwise the mods wouldn't work on offline mode.

**Comment by nullifiedcat** [comment]
Change your date to 5+ april. It's april fools crash.

**Comment by Mettymagic** [comment]
@nullifiedcat do you mean April 5th or higher? So the April Fools joke is to make the server unplayable for 4 days? Can't say anything but Reika got us good.

**Comment by nullifiedcat** [comment]
@ShayminKeldeo421 Yes, April 5th or higher. I had the same crash on my server, changing date fixed it.

**Comment by nullifiedcat** [comment]
Crash probably isn't intentional, just weird mod interaction.

**Comment by nullifiedcat** [comment]
Found a config option to disable april fools:

set `B:"[E36A0F795] Enable Temporally Dependent Amusement Behavior"=false` in Reika/DragonAPI.cfg

**Comment by ReikaKalseki** [comment]
#1800
