### ISSUE TITLE
[Electricraft] Single-source induction motor generating heat

### ISSUE THREAD

**Issue by calvin-devogel** [ReikaKalseki/Reika_Mods_Issues#1826]
<img width="1440" alt="screen shot 2018-05-25 at 1 18 28 pm" src="https://user-images.githubusercontent.com/15314544/40560035-5efd8bfa-601e-11e8-9371-86e63e673e95.png">

As in the image, I have an induction motor without upgrades receiving power from a single battery, but the motor is still generating heat and losing 3/4 of its power. I believe this is a bug, but it's entirely possible that I've set something up wrong.

**Comment by calvin-devogel** [comment]
Installing inductive and tungsten upgrades causes the motor to output the correct amount of power, but it still is fed by one source, so this shouldn't be required. Also, I am running ElC v19b, and DragonAPI v19c.

**Comment by Kobra331** [comment]
the sources which charges the battery counts as sources as well. So a battery feeded by 3 dc energys counts as 4 sources. This is to prevent the abuse of batterys as source a possibility to decrease the sources.
In my opinion this is not necessary because the battery has a progress item in their recipe. So if i can build a  Auroral battery i have bedrock..

**Comment by calvin-devogel** [comment]
Ok this makes sense. Thank you.

**Comment by ReikaKalseki** [comment]
The heat is a function of power output, not anything else. It exists purely to explain the new cooling fins.
