### ISSUE TITLE
[RoC] Item Vacuum mod interaction

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1829]
I found that the wooden pipe from buildcraft will not drain the XP from the item vacuum when powered with a redstone engine. On its own not a big problem (max 60mb\t due to pipe limitations), it can be quite exploitable when used with another item.

I am able to produce about a bucket or more of free chroma every second with just 1 pipe and engine.

**Comment by ReikaKalseki** [comment]
So the problem is the draw rate; 10mB, which is the rate of a wooden pipe, is actually less than one unit of XP in value.

I can think of two solutions for this, neither of them good:

Option one is to round the ratio up, so that even though 10mB/t should equal 0.5xp/tick, make it draw 1 (and thus halve your XP amounts).

Option two is to only allow extraction in "packets" over 20mB/t, which would prevent the wooden pipe from doing the extraction entirely.

**Comment by ReikaKalseki** [comment]
I went with the latter for now.
