### ISSUE TITLE
[ElC V19b] Induction Motor cannot be placed vertically adjacent, unlike pretty much all RoC engines

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1849]
It can be placed horizontally adjacent, it can be placed under ceilings and in 1x1 holes, effectively in any position _but_ full vertical stack.

**Comment by ReikaKalseki** [comment]
This is an intentional change I made in v19, as it prevents grids of engines. This was the fix for the melting-wire-from-complex-networks issue.

**Comment by Barhandar** [comment]
I don't see how it fixes wire melting, considering it at most doubles size taken by engine array before it melts, without actually changing amount of engines it needs to melt; and interfering with any vertical setups (not that many are possible).

**Comment by ReikaKalseki** [comment]
Because it prevents any setup that looks like this, with gridded motors:
![https://i.imgur.com/WVodVZg.png](https://i.imgur.com/WVodVZg.png)

The number of engines was never a problem - the number of *paths* was. Now that a solid "sheet" of wire is no longer possible, noone builds grids of it either, as it is a waste of wires. They build something like this instead:
![https://i.imgur.com/joELP24.png](https://i.imgur.com/joELP24.png)
