### ISSUE TITLE
Chromaticraft NPE server crashloop

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#186]
Server crashed upon placing a new repeater for an Argai pylon and right clicking with an elemental manipulator. Had to roll back the world to a backup 15mins earlier. Running DragonAPI 7f and Chromaticraft 7e.

Server crashlog:
http://pastebin.com/Y9uASkXN

Let me know if you need any additional information (I did a full world backup of the broken world in case)

**Comment by ReikaKalseki** [comment]
Something is invalid about that world; someone added null to the player list. There is nothing I can do to avoid this, because the world is in an illegal state and that vanilla method throws an exception as a result. You might be able to recover the world somehow, perhaps by deleting all entities within it.

**Comment by TomeWyrm** [comment]
Reika, would it be in the level.dat, or the actual MCA files? Because there are a couple of ways to fix something like that, but all of them are quite likely to cause issues if used injudiciously.

My first idea by the way, is to delete the Playerdata folder. Warning: THIS WILL RESET EFFECTIVELY EVERYTHING TO DEAL WITH PLAYER DATA!! You will lose all Chromaticraft progress, you can lose access to your "private" ender storage channels, you will lose all Ars Magica progress, all inventories and special inventories like TiCo's inventory tab or Baubles will reset, your Blood Magic soul network could possibly reset and any rituals might treat you as a "new" player, your COFH friends settings will likely reset or you might lose access to them.

Some of these aren't TOO likely as a lot of stuff just uses your UUID to see if you're you or not. But that all depends on precisely where and how the mod author decided to store their data. BE CAREFUL!

If the problem is entity based, there are two approaches I can think of. MCEdit is probably your best bet if you don't care about ANY entity in the ENTIRE world. This includes minecarts, pictures, and a few other things you probably wouldn't think of. There's also a way that involves NBT editing that can be more precise, but I haven't tried deleting entities across entire worlds, only editing specific ones in tiny schematics (horses, hehe).

**Comment by Saereth** [comment]
I replaced the data folder in world with a backup from 15minutes prior and it worked without messing with any region/level or player data file. It then occured to me that there may be some data cross over and as to avoid any issues I just did a complete restore to 15 minutes earlier. Yay hourly backups. Still something I need to get to the bottom of but it doesnt seem like a CC issue, CC just happened to trigger the function that crashed in forge.

**Comment by ReikaKalseki** [comment]
The function is a vanilla one, "getPlayerByUUID". It works by iterating over the world's player list, and if that contains a null entry...

> Reika, would it be in the level.dat, or the actual MCA files? Because there are a couple of ways to fix something like that, but all of them are quite likely to cause issues if used injudiciously.

I do not know where entities get saved. I suspect the chunk files; the level.dat is for things like seed, time, and ID map.

**Comment by ReikaKalseki** [comment]
See the linked issue: Draconic Evolution is now the primary suspect. @Saereth, do you have that mod?

**Comment by Saereth** [comment]
I don't have Draconic Evolution but I did look through his list of mods from the crashlog and compare against our pack, (his is a tech/ks pick, our is a mostly magic pack so there cross over was a bit more limited) These are the mods we have in common:

ae2, codechickencore, mobiuscore, nei, playerapi, Thaumictinkerer, witchingGadgets, Thaumcraft, Baubles, aura cascade, Mantle, Naura, BOP, Extrabees/trees/binniescore, Awwayoftime (bloodmagic), Botania, chickenchunks, Twilightforest, Waila, MagicBees, ProjectRed, Enderio, Extracells, Extrautilities,  Fastcraft, Opis, Sanguimancy, thaumicenergistics, translocator, traveller'sGear, ttCore

If you can knock off the ones you know to be working on your server it might help narrow it down. Good luck, issues like these are never fun -_-

**Comment by ReikaKalseki** [comment]
We have every one of those except Botania, Aura Cascade, Traveler's Gear, ttCore, witchingGadgets, and PlayerAPI.
