### ISSUE TITLE
[RC] Boring machine and Bedrockbreaker produces massive amount of lag

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1880]
Hi,
I used the bedrock breaker in the nether with 1 tick per operation and this produced some massive lags on the entire server after a while.  So i stopped it.
Another issue occurs when i used the boring machine for a long time (not at one tick per operation). Even after i stopped it, it produced massive lags and framedrops but only in the near of them.
After i disabled the chunkloader we can't even join the nether in the near of them. The server simply freezes kicks out all players and doesn't react to any commands. It doesn't crash so there isn't any crash log.

btw in the nether isn't anything else, only the boring machine, the bedrock breaker and a chunkloader

After teleporting to an other place in the nether and walks slowly to them we could harvest them and destroyed all pipes in the near. Now everything works fine without lags and framedrops.

**Comment by cheesealmighty** [comment]
"If your issue is lag or FPS related, include some form of profiling data; "it lags" is worthless for support."

**Comment by ReikaKalseki** [comment]
These machines have to force worldgen as they go into new chunks. That will cause lag.

**Comment by Kobra331** [comment]
but even if they aren't powered?

**Comment by ReikaKalseki** [comment]
No - Are you sure they are the cause? Unpowered machines do nothing.

**Comment by Kobra331** [comment]
The only other things in the near is a world rift to my turbines (which are not activated), a tesseract to power the magnetostatic and an enderchest. I doubt that the tesseract or enderchest causes this lags i placed dozen of this in the overworld without any issues.
But maybe the unchunkloaded World rift causes the server kicks on joining the nether?

**Comment by OvermindDL1** [comment]
What kind of lag is it?  TPS lag or FPS lag?

If it is purely serverside and it affects *all* clients even ones very very far away from the source than it is TPS lag.  If it effects players nearish to the source (<=10 chunks away) only then it is FPS lag.  Or look at the debug information.  And if possible, how much is it dropping by?

**Comment by Kobra331** [comment]
both kinds.
TPS lags if i run the bedrock breaker on 1 tick per operation and FPS lag if i am in the nether in the near of the machines. If the chunk is unloaded and both machines unpowered i even can't join the nether with the nethergate in the near, the entire server freezes and kicks out all players except me, for me it looks like the world needs extreme long to load but it never loads (the entire nether looks like a void world and i fall constantly)


If i run the bedrock breaker and the boring machine in the same direction shouldn't it only need one time for world gen? The boring machine access to the generated chunks from the bedrock breaker.

**Comment by Kataiser9** [comment]
Actually, I once had a similar issue with a 1-tick borer in the Nether - after a certain point, even after I turned it off, it would make TPS drop lower and lower until the game was completely unplayable. I used Opis to try to diagnose the cause, and it reported tens of thousands of the same tile entity, with an ever-increasing number, piling up somewhere in the nether. (Furnaces, I think? It's been awhile, IDR.) I never reported it here because I was not at all confident that it was an issue with Reika's mods and not some unrelated worldgen bug, but since you brought it up I figured it was worth mentioning.

Of course, I'm not 100% sure we're describing the same issue, but it seems plausible. Perhaps you could try using Opis too and see what that tells you. I could also try reproducing it again; I'm still playing on the world I had the issue with, I just haven't been using borers in the Nether.

**Comment by ReikaKalseki** [comment]
I suspect the issue is somewhere in chunkloading.

**Comment by Kobra331** [comment]
I reset the nether completely and started the bedrock breaker on LOW speed. It lags on the entire server. not extreme lag but lag.
BUT i have V20 because v21 don't works at the moment on my server.

**Comment by T5UN4M1** [comment]
I'm not sure about the TPS problem (I don't have any with my setup but I'm not running 1 o/t), but the FPS problem seems to be caused by the very long rotating parts in the case of the bedrock breaker.
I have 16 bedrock breakers that have been running for quite a while and I have 50 fps when I'm far away enough so that those parts aren't rendered (screen 1), when I get closer however, my fps drops to 10 (screen 2).
I tried removing the bedrock breaker and the FPS goes back to 50 (screen 3), and remains at 50 after I replace them. But after a while -once they reach a certain size : ~50 blocks-  then my fps already drops to 30-35 (screen 5).




I have also noticed that when you use multiple bedrock breakers, they tend to de-sync with eachothers, some will mine faster than others and this can cause the setup to load multiple chunks. My 16 bedrock breakers is mining in 2 different chunks after ~500 blocks (screen 4).

This is with V21B, my computer is an I5 4690, radeon RX 470.

![screen1](https://user-images.githubusercontent.com/12467635/45592539-cc4eeb80-b970-11e8-94ed-e1b2b5efae3d.jpg)
![screen2](https://user-images.githubusercontent.com/12467635/45592540-cc4eeb80-b970-11e8-8ba3-5b2528be95cb.jpg)
![screen3](https://user-images.githubusercontent.com/12467635/45592541-cce78200-b970-11e8-8133-52a34213f580.jpg)
![screen4](https://user-images.githubusercontent.com/12467635/45592542-cce78200-b970-11e8-8436-dcb7db8e2279.jpg)
![screen5](https://user-images.githubusercontent.com/12467635/45592543-cce78200-b970-11e8-9eb3-399be61f18b1.jpg)

**Comment by OvermindDL1** [comment]
The `Information Never Provided` tag?  I thought the pictures were pretty descriptive in the most recent comment that seemed to have been ignored, it showed a jagged pattern that definitely could not be caused by each block being in a different chunk as chunks are 16 wide.  Was that accidental?

**Comment by ReikaKalseki** [comment]
Kobra never supplied any further information regarding his apparent chunkloading issues.

**Comment by OvermindDL1** [comment]
Ah, different people, @T5UN4M1 should have opened a new issue!
