### ISSUE TITLE
Suggestion: the Centrifuge should make the player spin when they stand on it

### ISSUE THREAD

**Issue by Bluberry-Kat** [ReikaKalseki/Reika_Mods_Issues#1943]

**Comment by ReikaKalseki** [comment]
This has been suggested before and is not really compatible with MC server/client camera code.

**Comment by OvermindDL1** [comment]
Eh, back with one of my old ancient mods from the early beta days that used gearboxes that you placed gears on to make connections and axles and so forth (all of it very animated, all of it *very* efficient in rendering costs, especially compared to these mods as a hint) if you or an item fell on to the 'end' of an axle or on a gearbox with a gear attached to the top and they were powered/rotating then the player rotated in perfect sync with the axle, although if you weren't *perfectly* centered (not possible as I added offsets) then it would end up throwing you off the edge pseudo-randomly (it was a mod based heavily on using water item transportation so this was a useful design aspect).

And yes, it worked perfectly in multiplayer, no jankiness or anything like CC's infusion alter thing causes, all perfectly smooth.  So it is fairly easily possible.

![screenshot](https://overminddl1.com/minecraft/screenshots/2012-04-06_02.50.19.png)
\<off-topic-but-eh\>Axles are on the left, these were early graphics for it before it got refined a bit more, and yes, if curious, the mod did indeed have many things that were larger than a block in size, but properly form-fitting, efficient, selection boxes were the correct size, could build 'adjacent' to, etc..., windmills that seemed to be like a single large block for anything that looked at them that were 9x9x1 (of any axis) or granary wheels that were 3x3x3 or whatever else, you held the entire thing in hand and it was placed all at once (with a bit of a particle display on anything that was in the way when you tried to place it), this was all pretty trivial stuff to do that had no overhead, even the TESR's didn't do any rendering or OpenGL state changes except only once for all my blocks in a chunk, unlike some mods that do hundreds upon *thousands* of transforms sometimes in a single block (\*cough\*turbine\*cough\*...).

But still, it's all an aspect of proper interpolation.

**Comment by OvermindDL1** [comment]
Heh, and apparently GT6's electric motors will rotate a player standing on them when they are at the correct orientation, in multiplayer and all without any reported issues to date.

**Comment by ReikaKalseki** [comment]
Show me.

**Comment by OvermindDL1** [comment]
Should just need to do something like:

```java
if (SIDES_TOP[mFacing] && mActivity.mState>0) {
  if (isClient() || !isPlayer(aEntity)) {
    aEntity.rotationYaw = aEntity.rotationYaw + (mCounterClockwise?-5:+5) * (mConverter.mFast?2:1);
    aEntity.rotationYawHead = aEntity.rotationYawHead + (mCounterClockwise?-5:+5)*(mConverter.mFast?2:1);
  }
}
```

Should just need to rotate the entity on the authorative side for that given entity, which is the server for for all non-player entities and is the single client that owns the player entity for a given player, as well as interpolate it on the clients (I.E. run on client always, and run on server only if not a player entity).  I forget if an entity sync call belonged in there somewhere or not (maybe only for players?)

**Comment by ReikaKalseki** [comment]
That is exactly how the CC Ritual Altar works, and look how smooth that is the moment the TPS drops.

The problem is that the server is constantly sending updates regarding the player rotation, and if the client is ticking at a different rate, it 'gets ahead' of the server.

**Comment by OvermindDL1** [comment]
Two issues there:

1. Precisely, they are both getting overridden by set's on the server side.  The server should not be setting player's movements at all except only when they are doing something that they shouldn't be doing, rotation is not such a thing, 'flying' is, hence why the server has to be told that it is okay for them to be in a flying state (not touched the ground in a greater than certain amount of time among a few other checks).

2. The ritual altar is a whole bag of issues, even it's issue of sometime not resetting the view back to have the hud and by in first person again is implying the server is doing things it shouldn't (Mis-set checks?  No checks?).

I've never bothered looking to closely due to inability to setup an easy dev environment (even the recently open-sourced GT6 with it's **22** hard dependencies and over *40* soft dependencies is still a simple `git clone ...` and `./gradlew ...` away, showing there is no reason whatsoever for *any* mod to have a garbage build system... especially smaller unnamed ones (not your mods, I was fighting with some people's stupidity a few days ago and it's bugged me)).

_/me may be slightly biased as @OvermindDL1 is the one that built GT6's build system..._

**Comment by ReikaKalseki** [comment]
> The server should not be setting player's movements at all except only when they are doing something that they shouldn't be doing, 

That is not my doing. Vanilla server code forcibly syncs position and rotation data every tick (or few ticks).

**Comment by OvermindDL1** [comment]
> Vanilla server code forcibly syncs position and rotation data every tick (or few ticks).

It's done via comparison of what is expected, just need to override that assumption, not trivial to do but is doable for the ritual alter.  For rotating while standing it's pretty trivial though.

**Comment by ReikaKalseki** [comment]
>  just need to override that assumption

Meaning what? ASM?

**Comment by OvermindDL1** [comment]
There was a fairly easy non-asm way of doing it (at least on version 1.5 of MC, when I last wrote such code that did that), but it's been so many years that I can't recall what it was.  I remember it being not 'too' hard to find but just had to look through the callpaths of all possible setters for that data.

**Comment by ReikaKalseki** [comment]
There are dozens.
