### ISSUE TITLE
Breaking Tall Botania Flowers With Bedrock Shears Causes Them To Drop A Different Type Then The One Broken

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#196]
When breaking a tall mystical flower from botania with the bedrock shears they often but not always drop a different type of flower than the one broken for example breaking a tall red will sometime drop a tall grey.

I have tested with other shears even the HSLA shears but they work fine.

versions I'm using

Botania r1.7-208

DragonAPI 1.7.10 V7f

RotaryCraft 1.7.10 V7f

**Comment by ReikaKalseki** [comment]
The RC bedrock shears drop the plant block itself. There currently is no system to stop mod plants from being obtained directly.

**Comment by ljfa-ag** [comment]
I think someone else had this problem with sugar canes, where they didn't get the regular sugar cane item but the ItemBlock for sugar cane (which WAILA branded as DragonAPI)

**Comment by ReikaKalseki** [comment]
That is already fixed. Mod plants, however, are much harder to handle.

**Comment by ReikaKalseki** [comment]
I had an idea. Are all the plants the same class (or block ID)?

**Comment by RoloEdits** [comment]
yes all same id just different meta data.
and i'm not a modder but someone suggested  to query damageDropped but im not sure what this even means.

**Comment by Braidedheadman** [comment]
I can confirm this is happening. The report in the OP, however, is unfortunately, not worded very well. Specifically, we aren't getting different flowers, but rather differently colored "tall mystical [color]" Botania flower items that don't match the [color] of the parent tile entity.

Let me provide a brief overview so that we're clear about what's happening. If I for instance bonemeal a regular Botania mystical red flower, it will grow into a "tall red mystic flower". The intended behavior from there is to use shears to clip the plant in order to obtain the tall flower as an item of the same color (using anything else destroys the plant without producing an item), which can then either be replanted or used to produce four petals of that color to be used in Botania recipes and/or ground into correspondingly colored dyes. This route is intended as a means of doubling the petal output of the regular flowers, which can be harvested by hand but produce only two petals each.

When using the bedrock shears, however, the color data of the tall flower item obtained in this manner doesn't match the color data of the parent tile entity.

When comparing tall flower tile entities of a given color, white for instance, it appears as though the metadata of the flower item collected by the bedrock shears is being offset by +2 compared to that collected by a pair of vanilla shears (item IDs 866 and 866:2 respectively). This behavior is not consistent, however. Some flowers, purple and blue for instance, appear to be collected properly (item ID 867:2 and 867:3 respectively). There's an oddball one with lime green flowers shifting the metadata to orange (866:5 to 866:1). I haven't tested all the flowers so there may be others but the general pattern appears to be a +2 offset.

---

## CAVEAT:

My server admin has not updated to the latest versions of your mod yet so the data collected here was obtained in v7f. Which brings me to the following question: 

Regarding the line in the change log for v8,

"RotaryCraft: Bedrock shears no longer harvest some plants directly,"

Does this mean that the shears will no longer harvest Botania's tall flowers at all? Or was the above data anomaly accounted for and corrected? Is this a mod interaction without a solution on your end?

As always, hope this proves to be useful!

Cheers! :)

**Comment by ReikaKalseki** [comment]
Hopefully fixed (?).

**Comment by Braidedheadman** [comment]
I've been out of town since mid September and won't be back for several more weeks yet. I believe that our server was updated to your most recent version in that time, so I'd be happy to retest just as soon as I get back, unless someone else picks this up before I do. 

Peace!

**Comment by Braidedheadman** [comment]
Ok, sorry this has taken a while to get back to, my free time has been limited of late. I've tested this and the bedrock shears continue to drop incorrect plant metas when used on "Tall Mystical [color] Flowers" to harvest them. These are the regular botania flowers _after_ they've been bonemealed to their "tall" versions.

Do note that this entry in the change log for v9b states, "Fixed bedrock _scythe_ dropping wrong plant metadatas." It was probably just a typo, but the issue is for the bedrock _shears_.

[Edit] The bedrock scythe merely destroys the flowers as they are meant to be collected with shears.

**Comment by ReikaKalseki** [comment]
> Do note that this entry in the change log for v9b states, "Fixed bedrock scythe dropping wrong plant metadatas." It was probably just a typo, but the issue is for the bedrock shears.

The two use the same code.

**Comment by Braidedheadman** [comment]
Oh, ok that makes sense then. Most of the flowers, except for a couple of outliers, still appear to be dropped by that +2 offset in the meta data I mentioned earlier.

**Comment by ReikaKalseki** [comment]
Now there is a problem. I have no way to fetch the "intended drops", as I have no desire to change the bedrock shears to normal shears logic.
