### ISSUE TITLE
[RoC] Gearbox and Lubricant bucket issues

### ISSUE THREAD

**Issue by Jonius7** [ReikaKalseki/Reika_Mods_Issues#2001]
Rotarycraft currently has a few issues with how gearboxes are intended to behave, and their actual behaviour in-game.

1. Lubricant can be removed from gearboxes on right click using an empty bucket - when intended behaviour is Shift-right-click.

2. You can waste gears on 0% damaged gearboxes.

3. You are unable to use a Lubricant bucket "stack" to fill gearboxes (just opens up gearbox GUI). #1759 comment 3 mentions this. Intended behaviour would be to click with the lubricant bucket stack to deposit 1000mB of lubricant at a time into the gearbox.

Lubricant bucket stack is obtained by clicking a stack of empty buckets on a reservoir of lubricant (same behaviour as water buckets).

**Comment by ReikaKalseki** [comment]
So it turns out (1) was an intentional change, though I no longer remember for what reason. My guess is likely something along the lines of shift-clicking with buckets failing to register.
![https://i.imgur.com/ls9SWHU.png](https://i.imgur.com/ls9SWHU.png)

(2) was a stupid mistake and is fixed.

(3) looks intentional again - see the above image - but I can expand it to allow stacked buckets in some cases.
