### ISSUE TITLE
Electricraft machines (non-wires) are invisible

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#2019]
Relevant log: https://paste.ee/p/AhAru

All my Electricraft machines (the Induction Motor, Electric Meter, and Induction Generator) are not rendering at all in-world. Everything renders just fine in my inventory and NEI, just placing it in-world causes it to not render.

The machines work perfectly fine (and the selection box still works), so it's not *that* big of a deal, just find it a very weird bug.

**Comment by ReikaKalseki** [comment]
Your log contains no errors - does this persist after a game reload?

**Comment by thePalindrome** [comment]
Yes, newly-taken screenshot: https://imgur.com/a/3jCTg0i

I'm baffled that there's nothing in the log, and there's nothing that should be interfering with it (I unloaded Optifine for verification purposes, and the only thing that fixes is some log spam regarding the ReactorCraft turbines)

**Comment by ReikaKalseki** [comment]
Try removing other mods.

**Comment by thePalindrome** [comment]
I have removed every mod but DragonAPI, RotaryCraft, and ReactorCraft, and the issue still persists.

Here's a log that will *hopefully* be of use: https://paste.ee/p/BPRS0

**Comment by ReikaKalseki** [comment]
It still contains no relevant errors. Try redownloading ElC.

**Comment by thePalindrome** [comment]
Redownloading EIC did nothing, and the md5 hashes of the old and new files were the same.

If you want to just call this a "java bug" or a "user bug," at this point I'm willing to let it go, since I'm not familiar enough with java debugging to do much on my own :/

If you want to try to replicate this, I'm using openjdk (built with icedtea 3.9.0) for 1.8.0_181, and I'm using the mesa amdgpu driver. (The log says it somewhere I believe, but probably easier to put it here)

**Comment by ReikaKalseki** [comment]
The fact it only affects ElC blocks means there must be some cause that is not OS or JVM related.

**Comment by ReikaKalseki** [comment]
So this was not just affecting you, but everyone, which allowed me to find the issue and fix it.

**Comment by rkane31174** [comment]
I have this issue too in the latest version of Electricraft. The weird part is that it works fine when I first start the game. I'm on the server for about 15 minutes and then the minecraft launcher crashes. I can still play the game after that so it seems to be of little consequence, but then maybe 15 minutes after that the server boots me with the "existing connection forcibly closed by remote host" error. When I reconnect, the Electricraft machines are all invisible. The only way to see them again is to restart the game.

I don't know what kind of logs you'd want for this since the game itself doesn't crash, but request and I shall provide.

I'm not sure what the etiquette is for re-reporting this. If I'm posting in the wrong place (or shouldn't be posting this at all) then please let me know.

**Comment by thePalindrome** [comment]
I think that issue is different from the original one, so you should post your entire minecraft log up to the disconnect (go ahead and close the game afterwards) and put it up on pastebin. Then make a new issue
