### ISSUE TITLE
Casting table will use more resources than it crafts if unable to create a whole stack

### ISSUE THREAD

**Issue by SayethWe** [ReikaKalseki/Reika_Mods_Issues#2062]
While creating some Crystalline Stone Groove, I noticed that crafting more than a stack at once will only create 63. that's expected. however, it will use 66 crystalline stone, as if it subtracts the items, then check if the output overflows the stack limit.

**Comment by ReikaKalseki** [comment]
I noticed this myself with the glass.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Barhandar** [comment]
chroma casting crafting table temple crafting full stack partial unfinished

The result of the fix for this is that the table no longer crafts up to a full stack, i.e. when the output would match stacksize exactly, it crafts one less item instead (so for example, crafting lumen repeaters will be done 56 at a time, enrichment vines 62, et cetera even though their stacksize is 64).

Everyone who complained about overflowing stacks in the output is _quite welcome_.

**Comment by ReikaKalseki** [comment]
@Builderb0y
