### ISSUE TITLE
About Rotary Craft v22d

### ISSUE THREAD

**Issue by HiroRittsu** [ReikaKalseki/Reika_Mods_Issues#2065]
Nice to meet you. Suddenly I am sorry.
Attempting to run the environment (language: Japanese) that introduced Rotary Craft on Windows 10 will crash. The crash log is as follows. It seems to be caused by the character code, can you handle this? Thank you.
![dypmit5vyaejjdq](https://user-images.githubusercontent.com/33301907/52162834-db1a1d00-271c-11e9-8084-074f5416b137.jpg)
![dypmz6ev4aavbto](https://user-images.githubusercontent.com/33301907/52162835-db1a1d00-271c-11e9-9761-1cee184ceea1.jpg)

**Comment by Rewyn** [comment]
If it's the character code thing, then here's the solution.
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2021

As a note for the future, please do just paste the crashlog to pastebin, or upload it in some form, screenshots are a pain to work with (and yours might even lack relevant info, due to not showing the entire crashlog).
