### ISSUE TITLE
Latest Version - Entering Chroma Dimension crashes using Java 8

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#208]
The Title says it all, I am using latest version of Chromaticraft. Mods installed - Forge, DragonAPI, Chromaticraft, and Mystcraft (for ease of /tpx). Java 8 version 51. Works perfectly using Java 7. The strange thing is that it doesn't generate a crash-log and for servers it just times users out and goes down. I would assume this is a known issue, (and if it is, I apologize) but I'd rather report it than not. Thanks!

**Comment by bpwhelan** [comment]
Full Console Log from just loading and /tpx 60: http://pastebin.com/xiCWMgNB

**Comment by Duckfan77** [comment]
This is, in fact a known issue, though I don't believe it is yet on the issue tracker. Passing this:  
-XX:MaxMetaspaceSize=512m
parameter to java may fix the issue, though I am not sure about that.

**Comment by ReikaKalseki** [comment]
This is known...and I have no idea as to the fix. Also, if the above works, can I inject java arguments at runtime? If not, I can just force a crash with a "add this JVM argument" message for J8 users.

Also, some googling suggests running MC as administrator. Try that.

**Comment by Duckfan77** [comment]
I haven't received enough progress to access the chroma dimension in any of my worlds, so I haven't tested it. If there is a way using commands to give myself full progress in a test world I would be happy to test if the argument fixes the crash.

**Comment by Duckfan77** [comment]
It does not fix the error unfortunately.

**Comment by ReikaKalseki** [comment]
....#^$%

**Comment by bpwhelan** [comment]
iirc,  ae2 had issues with java 8 while entering it's dimension as well; im
not entirely sure if it was worked out or not. Im also not sure if a
correlation between that and this issues can be made,  but it could prove
to be a useful coincidence.

**Comment by ReikaKalseki** [comment]
Maybe it is a Forge issue...

**Comment by Zedrimar** [comment]
Although this is likely not part of the "main" issue, I did notice that the crash report does say that it failed to write a core dump, in this case disable User Account Control (UAC) in the control panel, that should minimize those sorts of crashes (I used to get them quite often). Read what little more there is from oracle's help section on the issue here: https://www.java.com/en/download/help/exception_access.xml

Why this happens, I have no freaking clue...

**Comment by Duckfan77** [comment]
I doubt that this would be the issue, as the error reportedly occurs in Linux as well, but I will test it. 

edit: Just checked, doesn't work either.

**Comment by Zedrimar** [comment]
it was just a suggestion to stop further issues

**Comment by redelman** [comment]
I did some testing and by just switching to the G1GC  GC collector, I no longer crash with Java 1.8 Update 65 when entering the Chroma dimension.

My full Java flags: -Xmx4G -Xms4G -XX:+UseG1GC

And my mod list:

Forge10.13.4.1448
CoFHCore-[1.7.10]3.0.3-303
DragonAPI 1.7.10 V9b
ChromatiCraft 1.7.10 V9b
RotaryCraft 1.7.10 V9b
ReactorCraft 1.7.10 V9b
mcjtylib-1.5.0
rftools-3.35

**Comment by redelman** [comment]
And because Reika asked, I tried with only using -XX+UseG1GC and it worked. 

I used the vanilla minecraft launcher for all tests. 

Detected Java args from the logs:

[22:22:25] [main/INFO] [FML/]: 3 Java arguments present: [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:+UseG1GC, -Djava.library.path=D:\Users\Rich\AppData\Roaming.minecraft\versions\1.7.10-Forge10.13.4.1448-1.7.10\1.7.10-Forge10.13.4.1448-1.7.10-natives-970246788666900]

**Comment by ReikaKalseki** [comment]
So I need to ensure the JVM args contains '-XX:+UseG1GC'.

**Comment by Duckfan77** [comment]
I can verify that the arg works, although a default arg, '-XX:+UseConcMarkSweepGC', must be removed or JVM doesn't start due to multiple incompatible collectors.

**Comment by redelman** [comment]
Removing any other GC flags was pretty much implied when I listed my complete Java flags. The CMS GC isn't the default Java GC either -- even in Java 8 the default is the known crappy throughput collector. Some launchers simply select the CMS GC because it's better, but including that flag by itself is still wrong in nearly 100% of cases.

**Comment by ReikaKalseki** [comment]
Implemented.

**Comment by ljfa-ag** [comment]
So '-XX:+UseG1GC' is now forced? That's unfortunate because I tried this garbage collector once and it would give me annoying freezes every time it collected. This could probably be tweaked with other options but I have no idea how.

Forcing a specific flag might not be a good idea, as it doesn't seem to happen on every machine. It's not really a fix, it only avoids the problem, which lies somewhere else.

**Comment by ReikaKalseki** [comment]
The alternative is forcing Java 7. (Which you can still use if you want to not use that GC).
