### ISSUE TITLE
crash ChromatiCraft+1.7.10+V22d

### ISSUE THREAD

**Issue by SlayDerss** [ReikaKalseki/Reika_Mods_Issues#2114]
when my minecraft initialize it's just not work i try to resolve but no result 

here the crash report : https://pastebin.com/hZnHqWTQ

**Comment by ReikaKalseki** [comment]
Do you have any mods registering the same armor twice?

**Comment by SlayDerss** [comment]
I have check and no

**Comment by lAimBotl** [comment]
"Boots has a recipe ID which conflicts with Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipes.Special.DoubleJumpRecipe@1c0941fc _ TEMPLE"

**Comment by ReikaKalseki** [comment]
Which should only be possible with the same item being registered twice.

**Comment by ReikaKalseki** [comment]
The new version should identify the duplicate item.

**Comment by aponywhotossescards** [comment]
it "finishes" only to pop up saying that a mod loading problem occured

heres the crash report https://pastebin.com/baVQqRkt

**Comment by OvermindDL1** [comment]
Do you have AE2 installed?  Because it looks like the tardis mod needs it but doesn't have it, either that or some really really bad coder/modder included another mod's API inside it, which *will* eventually break things, in which case deleting it from whatever mod included the AE2 API might also fix it.

**Comment by aponywhotossescards** [comment]
No i do not i hope the server thing we use has AE2

**Comment by OvermindDL1** [comment]
Does it work if you have AE2 installed?

**Comment by aponywhotossescards** [comment]
it loads into the game but not the world heres the prob https://pastebin.com/vB855PyB

**Comment by OvermindDL1** [comment]
Looks like https://github.com/ReikaKalseki/DragonAPI/blob/34f1be50b93be65a2aecccba839c7e700926bcee/ASM/Patchers/Hooks/Event/BiomeMutationEvent.java might be bugged.

**Comment by aponywhotossescards** [comment]
How do i fix

**Comment by OvermindDL1** [comment]
@aponywhotossescards I'm unsure if you could do anything short of finding the mod with the conflict.  Reika's mods use a lot of ASM and if anything else uses asm in the same areas it can cause issues like these.  I'm betting some other mod is ASM'ing here as well and since neither mod is handling it then it crashes, but if at least one of the mods becomes aware of the other and works around it when detected then it would work.  If you find the other mod causing that then that would help.  I don't think it's AE2 at all though, something else.

**Comment by aponywhotossescards** [comment]
I have witchery, tinkers, tardis mod AE2 and full throttle alchemist which
is stupid busted btw

**Comment by ReikaKalseki** [comment]
This ASM patcher is the thing which fixes the "MC assumes any biome with an ID of 128 more than another biome is a subbiome of it" issue.

That fix is *absolutely* mandatory, and so I am not willing to add cases to disable it.
