### ISSUE TITLE
Invalid mod jarsign fingerprint!

### ISSUE THREAD

**Issue by sanderbusch** [ReikaKalseki/Reika_Mods_Issues#2115]
I am trying to make a forge 1614 server with DragonAPI and Rotary craft but i keep getting this. 
`Reika.DragonAPI.Exception.InvalidBuildException: DragonAPI is an invalid JarFile:
/home/gs-41653/mods/DragonAPI+1.7.10+V22d.jar is likely not a valid compiled copy of the mod.
Invalid mod jarsign fingerprint!
If you are attempting to make a custom build of the code, consult Reika.
Note that not all mods permit this, or of distributed versions of custom code, for security reasons.
If you got this by editing the mod jar, you may have to redownload the mod. Consult the developer for further questions.`

i haven't edited the mod in any way, i downloaded it directly from curseforge

**Comment by ReikaKalseki** [comment]
The filename having `+`s in its name is one readily visible sign that something has gone wrong in file copying or transfer. Try a redownload.

**Comment by Rewyn** [comment]
I'm pretty sure that's just what curse does to spaces.

**Comment by EyeDeck** [comment]
I remember having this issue; at some point Reika switched his compiler from Java 1.7 to Java 1.8 (v18ish?), and for some reason, the hash checker is the first thing to throw an error, instead of the typical "unsupported major.minor version _x.y_" that you would get from almost anything else. Install Java 8, make sure your client is running in the Java 8 JVM, and try again.
