### ISSUE TITLE
[Suggestion] [CrC] Mid/Late Game Chroma Creation?

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2125]
(As far as I know) The only way to make chroma is to get xp and sit on top of a collector (or get some purple zam crystals, then can just afk on the collectors) which doesn't seem like a very fun thing to do for too long . . .

Maybe some thing that "detects" the amount of zambarau (purple) crystals around it (more zambs = more chroma made, possibly at a reduced rate, since its automatic.) ("advanced chroma collector"), or maybe a way to turn pylon energy into *liquid chroma?

**Comment by Rewyn** [comment]
There's various ways to make it easier.
1) You can simply convert your xp into liquid xp and pump it into the collector. Or use liquid XP from things like a mobfarm and an item vacuum/vacuum hopper etc.
2) There *is* already an alternative way to make chroma, though it's more of a byproduct.
3) Your suggestion of something that "detects" zambarau crystals already exists as well. Which can also be used to convert your xp into chroma, though I'm not too sure on the specifics.

**Comment by lAimBotl** [comment]
1. same "problem" as chroma collector.

2. Haven't heard of that before, guess I should check it out.
3. is that a block/other, or are you just talking about the "player"?

**Comment by Rewyn** [comment]
How does 1. have the same problem? Or I simply fail to see which "problem" you have with the collector.
By using, for example, an EnderIO xp obelisk, it takes a single click for your entire xp to be converted into liquid xp, which can then be automatically converted into chroma whithout any further input from you. Same for mob farms, you can get the liquid xp and completely automatically convert it into chroma, without you ever touching it after setting it up.
2. It's a machine/"consutruct" you'd usually want to use anyways when it becomes available. It does require a little extra for the chroma side-product, but that's hardly any work. Just sometimes overlooked, I guess.
As for 3; I do mean an actual "block", or "machine". Though I do have to correct what I wrote before, with the block I'm referring to being able to convert your xp into chroma; it's still the collector doing that. 
I'm very sure I remember reading about a setup that also does that without active player input, there's just a bit more to it.

**Comment by lAimBotl** [comment]
1. A mob farm would be easier (didn't know liquid xp can be converted to chroma)
but does crc have its own way? (well one way I could think of is dropping mobs into a tiny space with a collector under them, hmm? does it also convert xp orbs? )

2. Is it that dis enchanter thing? (enchantment decomp)

3. Is that a part of crc?

**Comment by Rewyn** [comment]
1. Yea, you can just pump liquid xp into it. I don't think CrC has its own way of collecting xp. Rotarycraft however does, as well as OpenBlocks Vacuum Hopper which is mostly present. Not sure what other options are there, as I've pretty much always had one of those available.
2. Not what I meant, but that'd work as well, if you have a somewhat steady supply of enchanted gear.
What I meant was the 
<details>
  <summary>Spoiler!</summary>
  Crystal Furnace. When you supply an additional type of lumen, it speeds up and also produces chroma as a side-product. At least if I recall it correctly.
</details>
3. Yes. Like I said not sure about the entire setup, but it sounded like you could (only?) do it with CrC stuffs.

**Comment by EyeDeck** [comment]
ChC does have a lot of ways of generating exp/chroma, though it's certainly true that a lot of them aren't immediately obvious. I don't think there's any reason to be clandestine about them, though, since they aren't spoilers.
- Early(ish) game has the enchantment decomposer—which, as a small side note, was specifically designed to chew up all of the crappy enchanted items produced by some other mods' fish trap to passively produce a little bit of liquid chroma with minimal setup.
- Most mods' liquid exp can be piped into a chroma collector—the most practical way to do this is probably to plop an EnderIO experience obelisk on top of a collector, then configure the obelisk to auto-output on the appropriate side.
- An extension of the above, the chroma collector can draw exp from the player _while_ liquid exp is piped in—a simple, practical example is to place an OpenBlocks XP Drain on top of the chroma collector, which roughly doubles the production rate
- You can stand on a 1x2 or 2x2 of chroma collectors, which can (as above) be further sped up by adding XP Drains.
- The chroma collector can be tile accelerated, which accelerates both drain from the player and conversion of liquid exp.
- Crystal Furnace—combined with an auto-miner and a well-designed RoC [bedrock] Extractor setup, this can produce tens of thousands of buckets after a few days of running

There are a ton of ways that ChC produces raw exp too, some more obvious than others, e.g.
- Piles of cave crystals
- Piles of potion crystals
- Potion crystals _with_ the player interaction (Argia) adjacency core
- Zambarau bees, which are absolutely ridiculous

**Comment by lAimBotl** [comment]
I just noticed a "player imitation core" maybe that is what i am looking for? hmmm
