### ISSUE TITLE
[CC] GregTech ingots dupe with Crystal Furnace

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2141]
1. Every parts of GregTech made of metal can be smelted into its nugget form. (like Steel ingots -> 9 steel nuggets)
2. Crystal Furnace can make the recipe output twice much as before.
![image](https://user-images.githubusercontent.com/24620047/61850972-349f1f80-aee8-11e9-91d9-7abaf5d1116a.png)
![image](https://user-images.githubusercontent.com/24620047/61850992-3ec11e00-aee8-11e9-9ceb-5839a4e3989b.png)
![image](https://user-images.githubusercontent.com/24620047/61851005-497bb300-aee8-11e9-8115-733b23799677.png)

This could be used to quickly duplicate most of the metal ingots in GregTech, causing the line completely broken.

**Comment by ReikaKalseki** [comment]
> Every parts of GregTech made of metal can be smelted into its nugget form. 


....why?

**Comment by OvermindDL1** [comment]
Conceptually it is remelting the metal into dropped nuggets of liquid metal that form the solid nugget 'drops'.

And they meant "All Metals of GregTech...".

For note, GT6 has a *lot* of circular recipes, for example you can essentially 'uncraft' machines back into constituent parts (a little more ground up, but same 'mass' and types of stuff).

EDIT:  And no, I don't know why you don't have to remelt the nuggets to get the ingots, I may suggest that...  ^.^;

**Comment by Prunoideae** [comment]
> ....why?

Similar to why HSLA scrap was added into the RC, maybe?
The smeltable ones are more than only ingots, other parts like gears or plates can be smelted into equivalent metal resources too.

**Comment by GregoriusT** [comment]
This Ingot to Nugget Recipe looks much like a GT5 Recipe I added back in the days, not a GT6 one. But regardless, I would recommend fixing that little Issue. ;)

And GT6 pretty much kills EVERY Furnace Recipe that outputs Ingots or Nuggets made out of known Materials (aka Materials GT6 can handle), and later adds them back for certain earlygame or low meltingpoint Metals, such as Copper for example. Doing the overkill first and then adding the proper ones afterwards is way more performant than checking every single Recipe individually. ^^

**Comment by ReikaKalseki** [comment]
I do not see a clean fix for this; the only way that will catch every circular recipe *and* not catch tons of extra items in other mods is to simply make all GT items in the crystal furnace not have any multiplication, but that surely catches many GT things that *should*...

**Comment by GregoriusT** [comment]
You know you could just check for things such as crushed Ores which start with the OreDict Prefix "crushed", because those are literally the only things that should ever have output duplication for balance reasons. Well and the Prefix "ore". Examples would be "oreCopper" and "crushedCopper" or "crushedPurifiedCopper" or "crushedCentrifugedCopper". The OreDictionary has an ItemStack->Strings Lookup that you can easily use for checking this efficiently.

Everything else in GT6 is definitely not duplicateable and has a very fixed amount of output.

And I have added Compat to lots of Mods, and I haven't seen all that many that actually have anything where it makes sense to duplicate Smelting Output except for Ores and Ore Processing Steps, since the only non-reversible operation is Ore->Outputs.

**Comment by Prunoideae** [comment]
It should be possible if there's a wildcard for metadata and only exclude some 'base' item in the mod, as GregTech mainly differentiate things and their materials with damage values, the items actually registered by the mod is a fairly small amount.

**Comment by GregoriusT** [comment]
Sorry this has absolutely nothing to do with MetaData or Wildcard, this is OreDict we talk about. For all intents an purposes Wildcard and MetaData don't really matter in a lot of cases.

OreDictionary is the String to ItemStack Mapping to find out if two Items from different can be used for the same purpose.

**Comment by Prunoideae** [comment]
From ore prefixes, well what if there's an another mod add things like boltMetalRaw or something like that?

**Comment by GregoriusT** [comment]
In that specific case it is very likely that duplication is also not a good idea, because you simply dont know much about said Bolt, maybe its only "raw" because you did not "sharpen" it or "polish" it, so the smelting might just be a recycling Recipe.

Always assume that something cannot be duplicated if it's not an Ore or an Ore Processing Step, otherwise you will inevitably create exploits.

**Comment by Prunoideae** [comment]
Err... This comes even worse when there are materials in other mods, but registered in GregTech, like this:
![image](https://user-images.githubusercontent.com/24620047/61990801-becabd80-b079-11e9-95d5-bea766f9f149.png)

**Comment by GregoriusT** [comment]
Yep, Mod Ownership doesn't matter either in this case, it's PURE OreDict that needs to be checked, no other way around it.

**Comment by ReikaKalseki** [comment]
A lot of non-ore items reasonably have duplication. Things like ProjectRed stone plates and OpenComputers circuit boards.

**Comment by GregoriusT** [comment]
Yeah and for things like those, you should maaaaybe do it manually, because if you do it automatically you will get exploits, and your particular examples, while not exploity, do not "feel" right for duplication, Food would be a good example for duplication, and you can even check if an Item is Food too!

It took me years to be manually compatible with most Mods I know of without causing exploits in the process, why do you think am I still on 1.7.10?, apart from future MC versions being plain old garbage and me trying to mostly finish GT6 before i move onto my own Game.

**Comment by OvermindDL1** [comment]
> Things like ProjectRed stone plates and OpenComputers circuit boards.

I'm not really sure how duplication makes sense here.  Unlike getting a 'little bit more' of metal out of a block of ore (combination stone and metal), getting more stone out of stone to make plates is odd, and circuit boards are *way* detailed things to build, not something you can get many of for free...

> Food would be a good example for duplication, and you can even check if an Item is Food too!

Eh, not sure how that makes sense either...  ^.^;

**Comment by Prunoideae** [comment]
Looks like I will need to remove CC from this modpack, the good side is that I don't need to worry about the modification now.
:-P

**Comment by ReikaKalseki** [comment]
> Looks like I will need to remove CC from this modpack

It is not exactly reasonable to have expected me to have already released a fix for this when you only reported it a bit over a week ago...

**Comment by ReikaKalseki** [comment]
Fixed.

		else if (ModList.GREGTECH.isLoaded() && ReikaItemHelper.getRegistrantMod(in).toLowerCase(Locale.ENGLISH).contains("gregtech")) {
			if (in.getItem() instanceof ItemFood)
				return MULTIPLY;
			int[] ids = OreDictionary.getOreIDs(in);
			for (int i = 0; i < ids.length; i++) {
				String name = OreDictionary.getOreName(ids[i]);
				if (name.startsWith("crushed") || name.startsWith("ore"))
					return MULTIPLY;
			}
			return 1;
		}

**Comment by GregoriusT** [comment]
Well wrong, very much wrong. You are aware I am also registering Recipes involving Ingots and Stuff that are owned by other Mods? And even GT5U does that, so checking what Mod owns the Item is not going to help you at all what so ever. Especially because you check for "gregtech" and not things like "gregapi" which does all the registering.

**Comment by ReikaKalseki** [comment]
Are you saying you register recipes which have other mods' items both as an input *and* and output, and which *also* need to not have duplication? I do not see how such a thing would exist, as other mods are not going to have the items to use as said outputs.

**Comment by GregoriusT** [comment]
You are aware that some Mods try to avoid having multiple Copper Ingots or multiple Copper Nuggets registered at the same time, by making only one Type from one chosen Mod work?
Or about the fact that a lot of Mods screw up registering OreDict Entries properly so I have to do it for them to make things actually work smoothly?
I'm trying to make everything work together nicely, so ofcourse I have to register a bunch of Items from other Mods to the OreDictionary just to make them work, and then I use the OreDictionary to make Recipes work regardless of what Mod they come from, while also trying to make sure I dont lag the Startup time of Minecraft.
There is a lot of effort going into preventing exploits using that System, but checking for the Mod that does it is not possible in this case, so you would have to be doing it in a way that isn't discriminating against one specific Mod, since you just cannot detect what Mod added the Furnace Recipe.

**Comment by ReikaKalseki** [comment]
My point is that other mods add ingots and the like, where the smelting recipes being doubled is not a problem.

The exploits arise due to more advanced products with recipe circularity; this is not going to be a thing from plain ingot smelting or something.

**Comment by GregoriusT** [comment]
Yes and GregTech causes said Circularity in a LOT of places within other Mods and Items registered by other Mods. That's why one has to be very careful with Recipes that multiply Outputs from Recipes that are simply not known about.
Just blindly multiplying the Outputs without having any base Concept as to what is multiplied and what isn't will ALWAYS lead to exploits, and that is exactly what you are doing right now.
