### ISSUE TITLE
RotaryCraft - Blocks such as the Reservior and Liquid Pipes cause very odd behavior in cold biomes.

### ISSUE THREAD

**Issue by waterlubber** [ReikaKalseki/Reika_Mods_Issues#2186]
In very cold biomes, (temperature in the -30s, like Taiga or whatever) RotaryCraft liquid pipes and reserviors spawn game-breaking amounts (in the sense that they **overwrite other blocks, including RoC machines**) of ice near them. 

This ice spawns randomly in the near vicinity, and appears to be like some sort of "freezing" effect. However, it rapidly spreads when disturbed and overwrites other blocks, meaning that this bug is extremely disruptive if you accidentally place a liquid pipe near your expensive RoC machinery. 

You can reproduce this issue by placing a liquid pipe in a cold biome. It appears to be intermittent, but having water nearby and using empty reservoirs and liquid pipes seem to make it happen more often. I'm not sure if you need water in the pipes, but that seems to prevent it assuming the water is warm enough.

Screenshot:
![image](https://user-images.githubusercontent.com/7517025/65095709-4b19a280-d990-11e9-8794-fe7dd2e0fe4a.png)

**Comment by reik019** [comment]
This is because the internal pressure of the liquid pipes its null/zero, pumping some liquids on it might help you to stop this from happening, as the pressure makes the pipes to get certain temperature.
On cold biomes its easier to see this effect if you are pumping water on some pipes, once certain internal level of liquid reaches, it will start melting nearby ice/snow (and if you keep going, you can start fires when there are bedrock pipe-level pressures in the pipe system).
I hope that this will help you to workaround this, while Reika Kalseki gives you a proper workaround/fix to this issue.
Note that I'm NOT the developer of this mod.

**Comment by ReikaKalseki** [comment]
Fixed.
