### ISSUE TITLE
clouds appear as 2D with DragonAPI v23a

### ISSUE THREAD

**Issue by Rotzo** [ReikaKalseki/Reika_Mods_Issues#2207]
Hi. My clouds render as 2D instead of 3D with the newest version of DragonAPI. Furthermore the y-layers above the cloud height are invisible when i look at them from under the clouds and only appear again when i go up above cloud height myself. I included 2 short clips to demonstrate it.

I used Forge version 10.13.4.1614, in the first clip DragonAPI v23a is the only mod installed, in the second clip it's DragonAPI v23a plus the Highlands mod.

first clip:
https://streamable.com/k8zcm

second clip:
https://streamable.com/yihwv

Thanks for your work :) I'm late but i recently started to get into RotaryCraft + Addons and i'm enjoying it a lot.

**Comment by Duckfan77** [comment]
Both of those links are dead, vimeo says that the page can't be found.

**Comment by Rotzo** [comment]
Sorry, my bad. I edited my post adding new links. I hope they work now :)

**Comment by ReikaKalseki** [comment]
Some testing implies this to be some sort of alpha/depth clipping behavior, and not the clouds actually rendering in 2D.

**Comment by ReikaKalseki** [comment]
In fact it was. Turns out the cloud texture is *not* transparent in the "No cloud" areas, but has an alpha of 1 out of 255.

The new alpha clip reset in DragonAPI as of v23 was causing that to be treated as opaque, and thus causing the clouds to cause the classic "transparency over object causing it to disappear" (nether portal over water) behavior.

Fixed.
![https://i.imgur.com/xWIZFQR.png](https://i.imgur.com/xWIZFQR.png)

**Comment by Rotzo** [comment]
Well, you're fast ^^ Many thanks, it works now.
