### ISSUE TITLE
Reduce CPU Utilization of DragonAPI

### ISSUE THREAD

**Issue by koiNoCirculation** [ReikaKalseki/Reika_Mods_Issues#2218]
top - 11:45:13 up 15 days, 12:19,  5 users,  load average: 6.51, 6.33, 6.43
Threads: 114 total,   5 running, 109 sleeping,   0 stopped,   0 zombie
%Cpu(s): 49.3 us,  2.1 sy,  0.0 ni, 48.4 id,  0.1 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 65909828 total,   437416 free, 31325208 used, 34147204 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 33419704 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                             
24434 lyt       20   0 25.143g 0.011t  56384 R 98.7 18.5   1008:46 ReactorCraft -                                                                                                                                      
23669 lyt       20   0 25.143g 0.011t  56384 R 98.3 18.5   1010:27 DragonAPI - Cus                                                                                                                                     
23851 lyt       20   0 25.143g 0.011t  56384 R 98.0 18.5   1009:39 ChromatiCraft -                                                                                                                                     
23969 lyt       20   0 25.143g 0.011t  56384 R 98.0 18.5   1009:11 RotaryCraft - C                                                                                                                                     
24175 lyt       20   0 25.143g 0.011t  56384 R 98.0 18.5   1009:03 ElectriCraft -                                                                                                                                      
23244 lyt       20   0 25.143g 0.011t  56384 S 28.3 18.5 451:39.98 Server thread                                                                                                                                       
28115 lyt       20   0 25.143g 0.011t  56384 S  1.7 18.5  52:33.12 File IO Thread 

The Logging System in DragonAPI cost too much of CPU, one core one mod.
With the Thread dump:
"ElectriCraft - Custom I/O Logger" #76 daemon prio=5 os_prio=0 tid=0x00007f902028c000 nid=0x5e6f runnable [0x00007f904c903000]
   java.lang.Thread.State: RUNNABLE
        at java.util.concurrent.ConcurrentLinkedQueue$Itr.<init>(ConcurrentLinkedQueue.java:692)
        at java.util.concurrent.ConcurrentLinkedQueue.iterator(ConcurrentLinkedQueue.java:669)
        at java.util.AbstractCollection.removeAll(AbstractCollection.java:373)
        at Reika.DragonAPI.Instantiable.IO.ModLogger$LoggerOut.run(ModLogger.java:278)
        at java.lang.Thread.run(Thread.java:748)

Thouugh the inspection of ModLogger.java in Dragon API, I found you should not use while loop to print logs, using while cost almost all cpu time, which is a fucking waste. The cpu time should be handed over when there's no logs.Please Use wait/notify mechanism to implement asynchronous logging.

**Comment by ReikaKalseki** [comment]
Thread.sleep is supposed to "release" the CPU for other tasks.

**Comment by OvermindDL1** [comment]
> Thread.sleep is supposed to "release" the CPU for other tasks.

Eeehh, `Thread.sleep/1` is more complicated then that.  It's true it "Gives up it's timeslice on the kernel", but that also means that it will take at minimum 12-16ms before it returns if not 0 (bad for accurate timing), and if it is 0 then it just gives up the current remaining timeslice, which causes a lot of context switching.  It's always better to wait 'on' something rather than waiting for a certain time period.

However, I don't think that's what the OP's issue was about.  I think he's talking about this function: https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/IO/ModLogger.java#L262-L287
```java
		@Override
		public void run() {
			while (!terminated || !messages.isEmpty()) { //killed by MC if closes (deamon thread)
				Collection<LogLine> printed = new ArrayList();
				for (LogLine l : messages) {
					try {
						outputFile.write(l.toString());
						outputFile.flush();
						printed.add(l);
					}
					catch (IOException e) {
						ReikaJavaLibrary.pConsole("ERROR: Could not output logger line to its IO destination '"+destination+"'!");
						ReikaJavaLibrary.pConsole(l.level, l.message);
						e.printStackTrace();
					}
				}
				messages.removeAll(printed);
			}
			try {
				outputFile.close();
			}
			catch (IOException e) {
				e.printStackTrace();
				ReikaJavaLibrary.pConsole("ERROR: Could not close logger stream!");
			}
		}
```
This has no `Thread.sleep/1` calls at all, rather it's just dumping the collection of `LogLine`'s to a file, repeatedly, with no delay at all, so this is busy looping, never sleeping.  In addition it's flushing every single line, which is pretty costly as well (forcing a filesystem sync), and it's all pulling from a concurrent container, which is forcing a lock and unlock in extremely rapid succession due to the busy-wait, blowing the cpu cache for that access.

Looking over the rest of this file reveals a significant amount of other issues.  Logging is a complicated topic, it's not just pushing out some data to a file and saving/flushing it, you will kill performance that way.

A list of issues that I immediately see in no specific order and missing others I didn't see on a quick cursory check:

* The hotpath calls in this class, like all of them, are not `final`, so there is an excessive amount of virtual calls (optimized out in some cases but not all...).
* Any call of this logger to log a message is performing at minimum four conditionals right off the bat, on a hot path, however the JIT 'should' optimize this well, maybe, it would reliably do so if things like `logNone` and `printDebug` and all the similar ones were `final`, but since it supports config reloading this makes it ambiguous, so the JIT might not optimize this.
* Any call of this logger to log a message, if it's not going to a file, is calling `ReikaJavaLibrary.pConsole`, which is accessing reflection information in an entirely non-cacheable way, then performing a *LOT* of full string rebuilds, before finally passing it to the FML logger.
* Any call of this logger to log a message, if it *is* going to a file, is first wrapping the string into a new allocation (why?!? it could go into level-based queues, no-op'ing if disabled or so!), then being stuffed into a concurrentlinkedqueue (yay major lock contention with the excessively polling thread I'm getting to next!)
* This concurrentlinkedqueue is being polled in another dedicated thread at the above shown code, the things wrong with this thread are pretty substantial:
  * No sleeping, ever, like *ever*!
  * A few minor ordering issues.
  * Allocating a new arraylist every-single-iteration (instead of allocating it one outside of the loop then just clearing it, which will almost never touch memory short of a couple of times in full).
  * That arraylist of `printed` isn't needed at all, just pop the front of the queue and log that, saves *multiple* locks on each call, significantly faster, and keeps `messages` in a good state.
  * It's setting up an exception handler, not just every loop of the function but *also* every loop of each message being processed, unthrown exceptions may be 'free' in java when at the top function level, but embedded try handlers are not!
  * The output file is flushing on every single call, forcing a filesystem sync on every single call.
  * A few other things but I'm getting busy at work, so...

Basically everything about this is built pretty wrong.  The OP's issue could be fixed by having the inner run loop just wait on a [Condition Variable](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/Condition.html), and that variable gets set whenever a log message get's logged (thus instantly waking up the thread, having it sleep all the rest of the time).  An easy extra useful change is getting rid of that `printed` variable and instead just pop the queue (if null then don't write and wait on the conditional variable, if not null then write and loop).

However, this class has a whole lot of performance issues, and considering how slow logging is anyway this just compounds it to quite an amazing degree I've not seen in a long time.  All of it should be tossed, just use the normal log4j logger as it does about everything right (including it can write to a file quite *efficiently*, far more so than this class)..

And yes, remember that using `Thread.sleep` is almost always wrong, don't do that here, it definitely is wrong.

**Comment by ReikaKalseki** [comment]
Cleaned up.
