### ISSUE TITLE
Crash when viewing secret burrow light with Thaumometer

### ISSUE THREAD

**Issue by Alrena** [ReikaKalseki/Reika_Mods_Issues#2225]
https://pastebin.com/VrkEppyv

Scanning all the other parts of the secret burrow were fine, it immediately crashed when I pulled it out when looking at the light on the lower level. I scanned a pylon light previously without issue but never attempted that with any other burrow of any kind.

Currently I can't even start the world back up, I even tried deleting character data, so I'm wondering if there's a possible fix besides making a new world?

**Comment by OvermindDL1** [comment]
It seems https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Base/BlockChromaTile.java#L577 of:
```java
ItemStack core = m.getCraftedProduct();
```
`core` is being `null` and there is no `null` check and Java isn't encouraging any of it due to lack of annotations.

**Comment by Not-February** [comment]
https://gist.github.com/Febilian/bbe55d694ddd7bda0dc2e11411767ae5

I'm getting what appears to be the same crash on a friend's dedicated server - it's only my client that crashes and not the server itself.

Subsequent attempts at rejoining my friend's server have ended in my client crashing as soon as I connect, with pretty much identical crash logs between the different attempts.

The server itself never went offline throughout those various attempts, though since I was the only one who was playing on it at the time I couldn't say with _certainty_ whether it would cause anyone to crash upon connecting or just me(I am _guessing_ it would be just me, since I am the one holding the thaumometer and looking at the ball of light and therefore experiencing the rendering issue related to that niche situation).

For me, it happened within one of those underground structures where the entrance is a 1x2 hole from a cave wall leading into a little room with shielding cloaks and crystals. I can't recall if this is the same structure as the 'burrow' mentioned by Alrena or if 'burrow' is the name assigned to the 'just-below-the-surface' structure type in the mod instead; I've always mixed up the names of the two...

If I just redundantly described the same thing, I apologize - but if these _are_ two different structures, then I would assume that this issue could happen in _any_ structure which contains that sphere of light at its core.

EDIT: An update for the sake of "how I bypassed the issue" since that was originally asked:

If you know how to edit the player.dat file, what my friend with access to the server files did is change the direction my player was facing so that when I logged in again, I would not be facing the glowy light ball, and thus was able to put the thaumometer off my hotbar and continue as normal. Whenever I know I'm going to be in one of ChromatiCraft's structures now, I make sure the thaumometer is not on my hotbar to avoid accidentally scrolling onto it at an inopportune time.

**Comment by ReikaKalseki** [comment]
So it turns out the core cause of this was a very poorly-planned change I made some weeks ago, which inadvertently marked all CC tiles as "has NBT on the item".

https://github.com/ReikaKalseki/ChromatiCraft/commit/352e75902570d731b787165653578819b991bf5f#diff-e54d63172d058a9641ef3e4ea5c9f04c

**Comment by ReikaKalseki** [comment]
That mess has finally been cleaned up.
