### ISSUE TITLE
[TreeClimbing v24a] Сompatibility

### ISSUE THREAD

**Issue by ORANG4** [ReikaKalseki/Reika_Mods_Issues#2301]
I can't climb on trees from those mods:

- Erebus 0.4.7
- TheBetweenlands 1.0.6
- Tropicraft 6.0.5
- Witchery 0.24.1
- Aether II 1.6
- Pam's harvest the nether 1.7.10a
- Growthcraft Community Edition [apples] 2.7.2
- BiomesOPlenty 2.1.0 (Yellow autumn, Orange autumn, Maple, Dying, Apple, Origin and Persimmon trees)

Is it possible to add support for the trees through the config file?

**Comment by ReikaKalseki** [comment]
Not configs, because TreeClimbing is ASM-based and ASM runs far too early to check configs.

The GC tree and the BoP trees you mention are not recognized because they mix a vanilla log with modded leaves; this breaks the DAPI "is a tree" check and thus TreeClimbing thinks it to be a random pile of logs.

As for the others, in order to add handling I would need to know A) the class representing each of those log and leaf blocks, and where there is a centralized registry within the mod of such blocks.

**Comment by ORANG4** [comment]
**Erebus:**
- erebus/block/BlockLogErebus.class
- erebus/block/BlockErebusLeaves.class
- erebus/ModBlocks.class

**TheBetweenlands:**
- thebetweenlands/blocks/tree/BlockBLLog.class
- thebetweenlands/blocks/tree/BlockBLLeaves.class
- thebetweenlands/blocks/BLBlockRegistry.class

**Tropicraft:**
- net/tropicraft/block/BlockTropicraftLog.class
- net/tropicraft/block/BlockPalmLeaves.class
- net/tropicraft/block/BlockRainforestLeaves.class
- net/tropicraft/registry/TCBlockRegistry.class

**Witchery:**
- com/emoniph/witchery/blocks/BlockWitchLog.class
- com/emoniph/witchery/blocks/BlockWitchLeaves.class
- com/emoniph/witchery/WitcheryBlocks.class

**Aether II:**
- net/aetherteam/aether/blocks/natural/BlockAetherLog.class
- net/aetherteam/aether/blocks/natural/BlockAetherLeaves.class
- net/aetherteam/aether/blocks/AetherBlocks.class

**Pam's harvest the nether:**
- com/pam/harvestthenether/BlockNetherLog.class
- com/pam/harvestthenether/BlockNetherLeaves.class
- com/pam/harvestthenether/BlockRegistry.class

**Comment by ORANG4** [comment]
Any info?

**Comment by ReikaKalseki** [comment]
There have been several dozen far more serious issues.

**Comment by ReikaKalseki** [comment]
Ok, finally done. I added all the ones of these that I could - not all are compatible with the system, since some again do share log or leaf types (notably skyroot).

This also adds all the other ModWoodList compatibility, such as the bedrock axe and the RC woodcutter, as well as things like the CC item fab.
