### ISSUE TITLE
Heavy performance issue with certain Item Rendering

### ISSUE THREAD

**Issue by Skyler-Altol** [ReikaKalseki/Reika_Mods_Issues#2307]
[@OvermindDL1 reformatted unreadable Discord copy of text, see link for the original.  ^.^]

See https://discordapp.com/channels/466852131895508992/466852735635947530/671601325787709460 for further info.

There is a tremendous cost while rendering the `CASTTUNING` Info Fragment.

See:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Registry/ChromaResearch.java#L683-L691

Specifically it is allocating a `TileEntitySkull` every frame via the code `TileEntitySkull te = new TileEntitySkull();`, this in itself though not efficient is not the cost.

At the end of this block it finally renders the skull via the code `TileEntityRendererDispatcher.instance.renderTileEntityAt(te, 0, 0, 0, ReikaRenderHelper.getPartialTickTime());`, this itself is not the cost either.

In between there is this code:
```java
				GameProfile p = ReikaPlayerAPI.getClientProfile();
				if (p != null && MinecraftServer.getServer() != null)
					te.func_152106_a(p);
```
Calling `te.func_152106_a(p);` causes a lookup in Yggdrasil the first time it's called on a new skull instance, however after that the result is cached and it doesn't need to be called again, the render will render the correct head.  However, since the skull is being recreated each frame it's having to do that lookup each time.

Tested via simply commenting out `te.func_152106_a(p);` and replacing it with the empty block of `{}` recovered over 70% of the frame time (I.E. rendering this one single item is costing almost 75% of the entire frame time, the main cause of <1FPS when it's in view).  The Skull without that line then rendered the normal skeleton head.

Either the Skull needs to be cached (which should be evicted on world change or server join) so it's only created once and `te.func_152106_a(p);` is only called once, or can choose a head that is not a player so no Yggdrasil call is made each frame.

---

Continued in next post...

**Comment by OvermindDL1** [comment]
The next most costly Item render in that NEI page is not an info fragment but rather the `Reika.DragonAPI.Auxiliary.ReikaSpriteSheets.renderItem()` call.  Specifically this is changing the GL state so much and so rapidly that it is dropping FPS on my system down to <5FPS when that NEI page in view.  Roughly 40% of the rendering time is taken up by this single call, and within this call the time is taken up due to the inefficient pushing and popping of GL attributes.

After the above the next most costly thing is `Reika.ChromatiCraft.Render.TESR.AdjacencyUpgradeRenderer.renderTileEntityAt()`, which by itself is using up about 15% of the overall frame time with the above.  Profiling this shows that about 40% of its own time is taken by inefficiently done GL attribute push/pop again.  About 50% of the overall rendering time is taken up by the multiple `this.drawInner(te);` calls.  Both the main function and the `drawInner` are inefficiently drawing the animated model when they should be drawn in a single batch.  As this is called for in-world rendering as well then the cost will be there too.

**Comment by ReikaKalseki** [comment]
I fixed the head rendering.

**Comment by OvermindDL1** [comment]
I saw, haven't tested it but the code looks good on just a quick look, including the cache eviction.  :-)
