### ISSUE TITLE
v24c DragonAPI black in-game screen

### ISSUE THREAD

**Issue by Arcaneless** [ReikaKalseki/Reika_Mods_Issues#2315]
Tested with clean install minecraft forge 1614 and DragonAPI v24c only
Experienced: black in-game screen once created or joined a world

It pops out a GL error @ Post render: 1282: Invalid operation
Last exception thrown before this happen i guess...
java.lang.ArrayIndexOutOfBoundsException: 1
 	at Reika.DragonAPI.Auxiliary.Trackers.ModLockController.readSync(ModLockController.java:94)
 	at Reika.DragonAPI.APIPacketHandler.clientHandle(APIPacketHandler.java:461)
	at Reika.DragonAPI.APIPacketHandler.handleData(APIPacketHandler.java:386)
 	at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper$PacketObj.handleClient(ReikaPacketHelper.java:1703)
 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:157)
 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:147)

Full log: https://pastebin.com/CaVCcxDQ

**Comment by Prunoideae** [comment]
This can be resolved if you resize your screen to maximized or other scale, though it is absolutely a bug.

**Comment by Arcaneless** [comment]
> 
> 
> This can be resolved if you resize your screen to maximized or other scale, though it is absolutely a bug.

yeah there's something wrong with the window size...
the black screen can be reproduced by going full-screen or nearly max window size before entering the game.
Launching the game with a smaller window, enter the game, then go back to full-screen or other scale could solve the problem, huge thanks bud!

**Comment by OvermindDL1** [comment]
Sounds like the framebuffer that reika creates is being evicted before the game finishes loading and it gets used, which means the resize message is missed and thus is never recreated.

**Comment by ReikaKalseki** [comment]
I reuse the same buffer every frame, and every frame its size is compared with the game window size. That should be impossible.

**Comment by OvermindDL1** [comment]
@ReikaKalseki Oh sorry, not what I meant.

In essence the OS gives your program (MC in this case) a framebuffer to be the final output that will be displayed.  This framebuffer gets wiped from the GPU memory whenever a variety of effects happen, such as resizing, fullscreening, minimizing, etc... (OS and driver dependent of course)  Applications are supposed to either test it every frame or listen to the appropriate events from the OS to re-request the main FB from the OS.  MC does this correctly.

However, when the main framebuffer is dropped the operating GL context is also often dropped in many cases, however that's re-requested when a new framebuffer is requested as well, which MC also does right (including resending the texture information and so forth back to the GPU).

When the context is dropped, then everything else that has a handle to the system is also dropped, including any other framebuffers manually created (which MC also does correctly for it's own framebuffers.

Thus what I 'think' is happening (I've not tested it yet to verify) is that when the context is reset during game loading, a message is missed and not everything is recreated, specifically MC still recreates its GPU handles, but not all mods are.

And when the window is finally resized it causes the message to finally be sent again and MC finishes recreating all the GPU handles in the system, and since DAPI is now fully loaded it gets its framebuffer recreated as well.

Honestly what I think is actually happening is that the framebuffer and all are created properly, but the links between them are not (like a texture handle or shader argument or so), and recreating again will relink them, but again I've not looked at the code enough or attempted to replicate this issue to verify.

**Comment by ReikaKalseki** [comment]
Linking to #2260


Overmind: I have no idea what you are trying to say.

**Comment by OvermindDL1** [comment]
In short:  I 'think' just on a very cursory look that your framebuffer is being deleted by the OS due to the window shape changing and it's not being recreated because not listening for a proper lwjgl update message (at least until someone resizes it or maximizes/minimizes it to cause the message again for MC to propagate it back to you).

**Comment by ReikaKalseki** [comment]
I have never heard of a "lwjgl update message".

**Comment by OvermindDL1** [comment]
Its a message 'returned' via error messages in some calls, meaning that the context has been invalidated and must be recreated.  MC does this itself (via glfw I think or what windowing system did it use again?) internally for its own things.

**Comment by ReikaKalseki** [comment]
I have no idea what you are talking about, and "glfw" appears nowhere.

**Comment by AbsoluteOmega** [comment]
I'm having the same problem but changing the size of the game doesn't work. if i start it in window mode, it shows the toolbar and the moded minimap but when i put it in full screen, everything goes black, even the Esc menu.

**Comment by OvermindDL1** [comment]
GLFW is included inside of LWJGL, that's the windowing library it uses...

**Comment by FavoritoHJS** [comment]
Can replicate this issue [SetGameDifficultyReika, 2.2], workaround is to resize the screen on world load if on Windowed, or going in and out of Full-Screen.

**Comment by ReikaKalseki** [comment]
Having done my own OGL programming since this issue was first posted, @OvermindDL1 GLFW is not in the lwjgl version MC uses - it uses the old "Display" class.

**Comment by ReikaKalseki** [comment]
This is fixed in v27.
