### ISSUE TITLE
Location Warp crashes client

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2335]
https://paste.ee/p/bJYC7 when clicking on one of the bottom arrow buttons with no waypoints in the list

**Comment by ReikaKalseki** [comment]
I have seen this before, but have never been able to reproduce it.

**Comment by BlueAgent** [comment]
Same crash with the Location Warp GUI.
[crash-2020-03-16_22.46.06-client.txt (deobfuscated the crash log)](https://gist.github.com/BlueAgent/8e800d1c16126eddb3429007b8f5b0ae)

To reproduce, open the GUI, press the `+` button, then press the `>` button.

Issue seems to be caused by `listOffset` being negative.
It can become negative [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/42842ad41ea3f8b2663f9dc19cb0b8983f64545e/GUI/GuiTeleportAbility.java#L183) since `maxListOffset` [can be negative](https://github.com/ReikaKalseki/ChromatiCraft/blob/42842ad41ea3f8b2663f9dc19cb0b8983f64545e/GUI/GuiTeleportAbility.java#L243-L245).
Seems like `private int maxListOffset()` should really be:
```java
Math.max(0, points.size() - MAX_LINES)
````

Might need to review where `listOffset` is used [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/42842ad41ea3f8b2663f9dc19cb0b8983f64545e/GUI/GuiTeleportAbility.java#L217-L226).
Potentially you might want to change:
```java
int sz = Math.min(MAX_LINES, points.size());
```
To what I think you intended it to be:
```java
int sz = Math.min(MAX_LINES, points.size() - listOffset);
```
Which with the first suggested change `listOffset` will always be non-negative and lower than size.

When you do `points.clear();` [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/42842ad41ea3f8b2663f9dc19cb0b8983f64545e/GUI/GuiTeleportAbility.java#L101) you should probably also reset `listOffset` back to 0.

**Comment by ReikaKalseki** [comment]
Fixed.
