### ISSUE TITLE
Damage booster (Ruzova core)

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2353]
- [ ] Fix tooltip (currently "Does nothing...yet.")
- [ ] Add support for more constructs beyond Meteor core:

Chromaticraft:
- Lumen Fence Emitter
- Lumen Turret
- Aura locus?
- **Avolite Defense Beam** (seriously)

Rotarycraft:
- All turrets
- Mob Harvester
- Arrow Gun
- Sonic Weapon
- Van de Graaff?

Botania:
- Bellethorne
- Dreadthorne
- Hyacidus
- Livingwood Avatar (when holding damage-dealing rods)

EnderIO:
- Killer Joe

**Comment by ReikaKalseki** [comment]
I do not have enough control over Botania or EiO code to make that kind of interaction possible.

**Comment by ReikaKalseki** [comment]
I implemented the tooltips and support on multiple machines. However:

I will not be adding it to the Aura Locus or Lumen Turret; I find those inappropriate balancewise and/or thematically and/or visually.

For RC, the turrets are a headache due to the fact they all use projectiles; it is not the turret itself dealing damage. Additionally, several turrets do not even deal damage directly, instead leaving it to ancillary effects (most notably the flame turret).

It was also not implemented on the Sonic Weapon as that does not do scaled damage.

The VDG damage is similar, plus the fact that an adjacency core tends to attract the bolts.

I looked at the Botania source; the bellethorne (which the dreadthorne extends) is hardcoded and would require ASM; the hyacidus does not even do damage, instead adding potion effects.
