### ISSUE TITLE
[Chromaticraft] Crash while rendering Block Entity

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2407]
Crash report: https://pastebin.com/jFDSLYuy
I was afking at my mob farm for a few hours then came back to see a crash report.

**Comment by ReikaKalseki** [comment]
I have never seen this before, nor does it make any sense, as it says `Index: 9, Size: 10`, ie that index 9 was out of bounds for a list size 10, *and* this was in vanilla code managing the TileEntity list.

**Comment by OvermindDL1** [comment]
I don't think this is a vanilla bug, this bug can happen, though rare it can be, but it absolutely can happen, when another thread is calling `world.getTileEntity(x, y, z)` at the same instance that a tile entity was added.  So this happened because another thread called `world.getTileEntity`, which is not safe to call from another thread.

However you have such a huge variety of mods that it's not easy to tell that any of Reika's mods caused it, though possible.  This is an extremely rare and unlikely to happen bug that happens because some mod (or mods) are calling non-threadsafe world functions from other threads.

Because it's so unlikely to happen though then you likely won't encounter it again.  The fact I've seen it *3* times in MC now since modding was a thing probably puts me as the only person to see it that often.

But no, it's not a vanilla bug so that's not an appropriate tag for it, vanilla won't hit this bug since it doesn't call a world function from another thread than the thread that owns it, only mods do that, just hard to figure out which mod without looking at every mod that uses threads and see which accesses the world from another thread.

**Comment by tiny-maple** [comment]
My personal modpack do not have a large number of mods installed, and in my world I only have enderIO, AE2, rotarycraft and chromaticraft machines. AE2 and enderio machines majority of the time stay idle since I barely use them. I can try to narrow down which mod throws this bug, because I have 10+ crash report on the same issue, each time having a different number.
Example: index: 8, size: 9
index 45, size 46
A pattern I observed is that the size is always 1 more than the index.

**Comment by OvermindDL1** [comment]
> I can try to narrow down which mod throws this bug, because I have 10+ crash report on the same issue, each time having a different number.

Wait you can replicate this issue?!?!  That's crazy if so, this bug can only pop up via the most crazy mix of conditions!

> A pattern I observed is that the size is always 1 more than the index.

Yep it will always be because a single tileentity got added or removed.

**Comment by ReikaKalseki** [comment]
I have no other threads after the game is done loading, and none of those touch the world or TEs.

**Comment by tiny-maple** [comment]
>Wait you can replicate this issue?!?! That's crazy if so, this bug can only pop up via the most crazy mix of conditions!

I did not really discuss this issue since I am not proficient in Java, as I do python, C# and C. Recently I only just started learning Java on my own. What conditions should I consider since I do not really know how I throw this error, it usually happens when I go away and leave the game running. I only play for 30 minutes each day and the rest of the time I just leave the game running.

**Comment by OvermindDL1** [comment]
@ReikaKalseki Yeah so it shouldn't be your mods then, has to be one of the others they use if you don't access the world from another thread ever...

> I did not really discuss this issue since I am not proficient in Java, as I do python, C# and C. Recently I only just started learning Java on my own. What conditions should I consider since I do not really know how I throw this error, it usually happens when I go away and leave the game running. I only play for 30 minutes each day and the rest of the time I just leave the game running.

This issue is a Data Race, the worst form of Multithreading bugs in any language (short of languages like Rust that don't have these issues due to stronger ownership patterns) and can absolutely happen in languages like python/C#/C (this is some of the worst form of bugs possible, heisenbugs!), this is why locking things is so important in multi-threaded contexts.  As for the game this only happens when both the TE list is being accessed, and just happens to hit the end of the TE list, *while* another thread is adding or removing a TE *and* the ordering of the memory synchronization just lined up in the wrong way, hence why it should be way crazy rare (it can actually cause corrupt data, I.E. corrupt world without this crash, that would be more common than this crash).  So if you really can replicate this issue then I'd say try testing different mods with it.  ^.^

**Comment by tiny-maple** [comment]
>it can actually cause corrupt data, I.E. corrupt world without this crash, that would be more common than this crash

Interesting, I actually lost my world several times, I recovered them by loading backup as I make world backup often. 

>So if you really can replicate this issue then I'd say try testing different mods with it. ^.^

I will try doing so when I have more time, currently I am rushing my final year project so I can make it for university graduation.

**Comment by GregoriusT** [comment]
Well this Issue could happen if you use the Serverside World for Clientside Rendering, since there is two World instances in Singleplayer, and why do i expect this to even be messed up that badly, clearly no one would cache the Serverside World to do Clientside Rendering in Singleplayer, right?

**Comment by OvermindDL1** [comment]
Hmm, yeah that would make it more reliable in how often it breaks, let me look through the callstack posted above's code...

So the world's are accessed via the `TargetData` constructor accessing a WorldLocation helper of Reika's, which is done by not passing in the client world but using it's internal world to the WorldLocation...  That WorldLocation comes from a container of WorldLocation's passed through the stack... multiple levels... and that comes from a `getTargets` call on the `CrystalTransmitterBase` TE, but that TE is accessed via the client thread so that parts fine, however where does that TE populate that container of WorldLocation's...

So it looks like it's populated from two places, one of those places is the `CrystalTarget.readFromNBT`, which leaves the world `null`, which `TargetData`'s init handles by thinking there is no TE at that world location, so that's fine (but sounds like a bug waiting to happen...), and the other is `CrystalTarget.addTarget`, which has this code:
```java
  44   │     public final void addTarget(WorldLocation loc, CrystalElement e, double dx, double dy, double dz, double w) {
  45   │         CrystalTarget tg = new CrystalTarget(this, loc, e, dx, dy, dz, w);
  46   │         if (!worldObj.isRemote) {
  47   │             if (!targets.contains(tg))
  48   │                 targets.add(tg);
  49   │             this.onTargetChanged();
  50   │         }
  51   │     }
```
So first of all it doesn't even populate this as a valid target unless the `worldObj` for this TE is not remote, I.E. it is the server...

However, this code's callstack was called from the renderer thread, not the server thread, meaning this data holds a server world object.

So it seem @ReikaKalseki made the perfect condition to make a heisenbug more reliably happen it seems.  This is absolutely a bug in ChromatiCraft accessing the server world from the client thread (I.E. across threads), which will make this normally-heisenbug happen very reliably on certain system types, which I'm guessing OP has (what CPU do you have @tiny-maple out of curiosity?).

So yes @ReikaKalseki, this is a ChC bug.  Don't hold the server world in that WorldLocation since it needs to be accessed from multiple threads.  Instead pass in the world that is being used in the callstack instead in `TargetData`'s constructor, I.E. make it take in a `World` in the constructor too and change the `TileEntity te = tg.location.getTileEntity();` line to be `TileEntity te = tg.location.getTileEntity(world);` instead.  There might be other issues with this as well (this structure terrifies me for stability a bit...) but this right here is absolutely a bug and is very likely the cause of OP's bug if it really is reliable for him.

You might want to check other areas to make sure you aren't accessing the server world from the client thread and vice-versa as well.  Since you always test in multiplayer you won't see these issues, but this is an absolutely massive bug for single-player (you *don't* access the server world from the client thread or vice-versa).

**Comment by tiny-maple** [comment]
Do you need my full PC spec?

**Comment by OvermindDL1** [comment]
@tiny-maple Nah, just your CPU I'm curious about, the rest won't effect this bug in any real meaningful way.

**Comment by OvermindDL1** [comment]
For note, you can work around the bug for now until it is fixed it by hosting your game in a dedicated server on your computer then connecting your client to it instead (and it will run slightly faster too, but use more memory).

**Comment by tiny-maple** [comment]
I own a i5-4670k 4core
I did a count of the number of duplicate crash report on this, and it total to 41.

>For note, you can work around the bug for now until it is fixed it by hosting your game in a dedicated server on your computer then connecting your client to it instead (and it will run slightly faster too, but use more memory).

thanks for the temporary work around. I will try this tomorrow.

**Comment by OvermindDL1** [comment]
@tiny-maple Wow 41!  Well congrats, you've hit that specific multithreading bug more than I've ever heard anyone hitting it *combined*, lol. And yeah, I5-3670k is a native quad core it looks like, with a dual memory bus, so yep you have a great hardware setup for this bug to happen too (your setup is usually 'very good', but with programming bugs they can definitely hit such cases more on such good hardware).  So yep, I'd say run a dedicated server for now and connect your client to it until reika makes a patched version.  :-)

**Comment by tiny-maple** [comment]
>And yeah, I5-3670k is a native quad core it looks like, with a dual memory bus, so yep you have a great hardware setup for this bug to happen too

Why does this hardware allow the bug to trigger so often? I cannot seem to grasp it.

**Comment by OvermindDL1** [comment]
Because it's dual channel memory there are 2 cores each for direct memory access.  Synchonizing them (like the `size` field on the arraylist) will happen to the 'other' core hundreds to thousands to hundreds of thousands of *cycles* later or before (it's very random...) from when the data storage in the arraylist itself actually updates to the other core.  If your world and client threads are running on different memory buses (very likely as they are both very busy threads and the OS will try to balance them across for speed reasons) then you get the desynchronization happening far more often.  Java `synchronize` calls and locks like mutex's cause memory barriers to happen (this is also why they can be slow and you don't want to run locks or even add memory barriers when at all possible), which means the threads must force sync their memory cache's before the code in the lock is run, but without a lock they will sync randomly (whenever the CPU feels like it, which can be never actually).

I.E. this bug will not happen on single-core CPU's, and will likely not happen (still possible but excessively less likely to happen as each L2 cache on a core is barely like a meg or so on average) on dual-core's with a single memory bus (very rare nowadays), but is very likely to happen on 2-core or more with dual (or more) memory lanes if the code patterns happen to line up in just the right/wrong way, like they do with your world.

**Comment by tiny-maple** [comment]
Wow holy, thanks for teaching me. I should check on my project code(written in python), as I used multi threading for data processing and I believe I did not do a proper synchronize in there.

**Comment by OvermindDL1** [comment]
@tiny-maple The main Python distribution actually has a Global Interpreter Lock, meaning that python code is only ever executed on one thread at a time, so it won't experience that issue unless you start using native libraries (which absolutely could then cause that issue).  Other Python distributions (like pypy or so) you can hit those bugs more easily without good usage of locks and so forth as they don't have a GIL (and run a lot faster because of it).  Languages like C# and C can absolutely hit major massive data race heisenbugs without proper use of locks in multithreading contexts.

@ReikaKalseki I also just noticed, you aren't clearing the `world` from the `WorldLocation` when the TE has its world cleared out, which can cause a world to stick around much longer than it should when a game is exited back to a main menu.  Do you have any bugs related to loading a world multiple times without closing the whole game down, because issues like that would cause bugs like that.

**Comment by OvermindDL1** [comment]
@tiny-maple You might be interested in languages like Rust as well, which bakes ownership violation detection into the language design itself, things like Data Race's just outright cannot happen in safe Rust code (and Rust uses the same compiler backend as C and C++ so it's as fast, though in some cases faster due to better aliasing handling, than the same C/C++ code while being significantly safer as 'most' bugs are ownership violation bugs that it prevents).  :-)

**Comment by tiny-maple** [comment]
> Do you have any bugs related to loading a world multiple times without closing the whole game down, because issues like that would cause bugs like that.

I have experienced this, whenever I try to load other world than the world which this bug was discovered, my client VM would close, but on task manager shows minecraft is still running.

**Comment by tiny-maple** [comment]
> Do you have any bugs related to loading a world multiple times without closing the whole game down

I have experienced this, whenever I try to load other world than the world which this bug was discovered, my client VM would close immediately, but on task manager shows minecraft is still running.

>You might be interested in languages like Rust as well, which bakes ownership violation detection into the language design itself.

I do not know if AMESIM support that, as I am doing HIL using AMESIM with an arduino microprocessor, and AMESIM has terrible documentation(maybe i suck at using it). We can take this conversation to discord or elsewhere that is convenient for you, since this is not related to reika mod.

**Comment by OvermindDL1** [comment]
> I have experienced this, whenever I try to load other world than the world which this bug was discovered, my client VM would close immediately, but on task manager shows minecraft is still running.

Yep, holding on to the `world` (client or server) past being within a single tick will cause issues like this, unfortunately a few mods do that, like these mods.

> I do not know if AMESIM support that, as I am doing HIL using AMESIM with an arduino microprocessor, and AMESIM has terrible documentation(maybe i suck at using it).

Never heard of AMESIM, but Rust does work on the arduino, however it's not the easiest thing to set up (though only need to set it up once).  Other embedded things that use ARM chips are almost trivial to use with rust though if you have like rpi's handy or so.  ^.^

> We can take this conversation to discord or elsewhere that is convenient for you, since this is not related to reika mod.

I'm on both Discord and IRC.  On Discord I'm OvermindDL1#3629 and on IRC on both espernet and freenode servers I'm `OvermindDL1`.  Feel free to message anytime, I get back when I can.  :-)

**Comment by ReikaKalseki** [comment]
I fixed a related bug which should help with this.
