### ISSUE TITLE
DragonAPI causing crash on world load when removing or updating mods

### ISSUE THREAD

**Issue by FaceNommer** [ReikaKalseki/Reika_Mods_Issues#2437]
Title says most of the problem. Upon removing or updating a mod from an existing world, forge will bring you to a screen asking you if you want to continue since mods and items are missing. Pressing "yes" will crash Minecraft entirely. 
Here's the problem: I tried reproducing this on a totally fresh install of both forge and minecraft, and it doesn't do it. However, on an existing modpack that I modified, I removed EVERY mod other than DragonAPI and it still occurs? I've spent a few hours trying to fix this with no luck. I'm no coder but the header of the crash logs say it's somehow related to DragonAPI looking for an update.

Log: https://pastebin.com/gNhWfNP2
Log with ONLY DragonAPI active: https://pastebin.com/Ere9xZsf
(also I searched the tracker for a while and couldn't find any similar, if there is just close this lol)

**Comment by Joker72rus** [comment]
same problem

**Comment by Matachusets** [comment]
The very same here, my last private server world, cant be load afther update from v24 to v25c, i yust created another new world, works fine at first, then a cras whit "Ticking entity" and when i restart the server "Exception in server tick loop" even afther NBT deleted the ticking entity, cannot load. dont want to create a new onee, since i going to have the same result, and the big prize, is...
this problem persist even if i downdate from V25c to V24.


log: "Exception"
[crash-2020-04-20_12.46.28-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4503065/crash-2020-04-20_12.46.28-server.txt)

**Comment by ReikaKalseki** [comment]
#2397 #2413 #2420 #2435
