### ISSUE TITLE
[Chromaticraft] Every villager trades lumen pods

### ISSUE THREAD

**Issue by LighttronPrime** [ReikaKalseki/Reika_Mods_Issues#2449]
I was exploring a village, and found that every single villager trades 25 emeralds for a lumen pod, with no limit on how many times this trade may be done (I grabbed 64 lumen pods from NEI, and a single villager gave me 25 emeralds each for all of them, filling my inventory). This seems very excessive; I don't know how you get lumen pods, but seemingly you would only need one villager to have this trade, not all of them. If this is an intended feature, it would be great if there was a config option to decrease the frequency of this trade. If this is a bug, you should note that I am using several mods that additional villager types, including Witchery, RFTools, Tinkers Construct, Immersive Engineering, Railcraft, Traincraft, and Flaxbeard's Steampower, which may be part of the issue.

**Comment by LighttronPrime** [comment]
Actually, I did find a blacksmith and a butcher who didn't have this trade, but it's still way to common.

**Comment by ReikaKalseki** [comment]
Not every villager; there is a 1/4 chance for each of the CC trades to be added. I did this because I do not want to add a CC villager type, as finding a specific one is a huge pain in the ass - if you have ever needed the Forestry one, you know what I mean - and given the level of villagers' competency in CC, it would not make sense for there to be an 'expert'.

25% was picked because it was common enough to guarantee it was present in nearly every village, even those - often the majority - with only a few villagers, without being so common as to be present on every or even most villagers.

Because this is required for progression, I am not willing to make it rarer, as I am not willing to introduce the risk of needing to scour half a dozen villages to find the trade.

And there is no way to only add it to a couple villagers per village; the calculation for which trades a villager gets is done on entity creation, and with zero knowledge of any other villagers in the vicinity, or any sort of village data.

**Comment by LighttronPrime** [comment]
It's worth considering that witchery generates absolutely enormous villages with 30+ villagers. Maybe if witchery is installed, it should be a 10% or 15% chance instead. This is a very minor problem, but it is moderately annoying

**Comment by ReikaKalseki** [comment]
And is there any guarantee that those villages *stay* with that many villagers? Or do they, like in vanilla, have 90% die in the first night and all but two more in the next few nights?

**Comment by OvermindDL1** [comment]
Witchery big villages are surrounded by walls and protected.  They last a very long time in my experience.
