### ISSUE TITLE
Crash "java.lang.IllegalArgumentException: Duplicate id: RCdynamo" in intialization of game with latest RotaryCraft when language is set to german

### ISSUE THREAD

**Issue by Kanaye** [ReikaKalseki/Reika_Mods_Issues#248]
If I startup the game it crashes with a "java.lang.IllegalArgumentException: Duplicate id: RCdynamo".
To recrate the crash get a Minecraft with latest RotaryCraft installed and set the Language to German (either start the game and change it in the menu or set the "lang" property in the options.txt in your minecraft root directory to "de_DE").
Took a while to figure that out :).

Thank you for your attention.
Have a nice day!

**Comment by ReikaKalseki** [comment]
This is because of the v8g registry fixes, and is because "dynamo" is unchanged between English and German. Though it is not going to be an issue in v9, the only way to fix it before then, short of undoing the bigger fix - which I am not going to do - is to change your German .lang file and change "dynamo" into something else.
