### ISSUE TITLE
[Reactorcraft] Using Angular Transducer on new steam lines display incorrect information

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2543]
![2020-05-31_20 12 22](https://user-images.githubusercontent.com/62176592/83352021-37c23200-a37b-11ea-8925-f43f7f0c260c.png)
Placed down new steam lines in my sodium solar farm, then tried to check for the amount of steam in the line. I do not have fission reactor built in the age. Will this affect my turbine power output? They are fluctuating between 1GW and 900MW.
DAPI 26b
Reactorcraft 26b

**Comment by ReikaKalseki** [comment]
The default type of boilers is 'FISSION', and for some reason steam was added to them before they were converted to SOLAR by the exchanger.

**Comment by voidsong-dragonfly** [comment]
To add on to this, I have seen >60% amounts of `fission` steam with straight steam lines off of a solar tower, and I have seen >3% `null` steam in some cases, and increasing.

**Comment by ReikaKalseki** [comment]
@BlueAgent has claimed that this is due to the reactor type proportionality not being saved to NBT.

**Comment by ReikaKalseki** [comment]
Which it now should be.

**Comment by Thorinair** [comment]
Here is the steam I am getting from my Fusion reactor, I have manually freshly placed all the boilers and steam lines.
![image](https://user-images.githubusercontent.com/7534126/84070226-15a85f80-a9cc-11ea-9427-3f2a9d7c8d14.png)

**Comment by BlueAgent** [comment]
> @BlueAgent has claimed that this is due to the reactor type proportionality not being saved to NBT.

@ReikaKalseki That wasn't the only issue I mentioned. Just making it save to NBT will not fix it completely since the way it mixes is also an issue. Proportionality isn't mixed, it is copied by reference from any higher to lower steam amount and also when using a pump from the input to output. Really what you also need to do is make a copy of the proportionality with an updated mix instead of just overriding the current reference, so merging with the existing proportionality based on how much steam was transfered and how much steam was contained in the steam line.

Essentially when steam is transfered by flow or pump, you need to do something like:

new steam = delta + current steam

new proportionality = (delta * source proportionality + current steam * current proportionality) / new steam

The latter is operating over each Reactor Type.

**Comment by MachiavelliSeraphim** [comment]
Ive noticed the new feature showing steam sources.  
Does it affect turbine output or consumption rates?
Ive just started up with Reactorcraft again and had a hell of a time getting a HP turbine to start.
It said I had some % breeder steam, I think it was, with a straight fuel core reactor.
Thought maybe the mechanics changed, but I didnt see anything in the handbook and Google found nothing useful.
Change logs had very little info either.

Sorry to bother, Thanks.

**Comment by ReikaKalseki** [comment]
It always did.

**Comment by ReikaKalseki** [comment]
Fixed.
