### ISSUE TITLE
[Chromaticraft]Allow mouse wheel scroll for browsing through abilities in ritual table.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2549]
Currently there are so many abilities in ritual table, and one must go manually click left or right button to go through the catalog of abilities. A mouse wheel scroll to quickly move to select the abilities to cast would improve user experience.

**Comment by ReikaKalseki** [comment]
The wheel code in the existing "main" ability GUI is glitchy and unpopular, and was a massive headache to implement. Just use the normal "large jump" keys other CC GUIs use, like PgDn/End/etc.

**Comment by tiny-maple** [comment]
>The wheel code in the existing "main" ability GUI is glitchy and unpopular, and was a massive headache to implement.

Never heard of it being unpopular nor seen it glitching out as it works perfectly fine for me.

**Comment by ReikaKalseki** [comment]
All mousewheel-based behavior is heavily tied to the FPS, and is very unstable in terms of the relationship between input timing and duration and "game input signal detection".

**Comment by OvermindDL1** [comment]
> All mousewheel-based behavior is heavily tied to the FPS

Wait what why?!?  Certainly it is not done by reading the 'state' in a given frame, it's done by listening to the events right?  Reading the input state in a frame is a debugging aide while programming something up, it is not and should absolutely never ever be used in something released...  o.O

**Comment by ReikaKalseki** [comment]
That is just how LWJGL works; all mousewheel handling is done by comparing the results between polls, and each frame has one poll.

**Comment by OvermindDL1** [comment]
No, that API is for a quick setup, it's not intended for final gameplay as it *will* miss states.  And I *know* lwjgl has an event buffer API so nothing is skipped as I've used it before.  I'd probably bet money you are using the immediate API like `Mouse.getDWheel()` or whatever the function name was, which is for quick setup and debugging as calling it clears its state every single time, it is *not* for gameplay.  The correct way to iterate events is the eventbuffer, which is iterated through via `Mouse.next()` (similar for keyboard as well), but this should be getting done by Minecraft itself so you need to hook into that system.

If you are indeed using `Mouse.getDWheel()` then remember that every time it is called then it is cleared, so if you call it once it might return the delta value, but call it again on the next line and it will return 0.  If *any* other mod (or if MC itself) or if 'your' mods are calling `Mouse.getDWheel()` multiple times in a frame then you will get *extremely* spastic inputs like I've always experienced with this (and what OP and others experience).

You *should* be hooking into MC's eventbuffer handling and listen to the events there.

**Comment by OvermindDL1** [comment]
I'm SSH'ing home to look at the code for a sec...
```zsh
➜ rg 'Mouse\.getDWheel'  
ChromatiCraft/GUI/GuiAbilitySelect.java
152:            int move = Mouse.getDWheel();
```
And just to make sure...
```zsh
➜ rg 'Mouse\.next'
```
No results, so you aren't wiping the event buffer thankfully.

So it looks like you call it only once among *all* of your code, so that's good there, let me check what Minecraft itself is doing...

```zsh
➜ rg 'Mouse\.getDWheel'
net/minecraft/client/gui/achievement/GuiAchievements.java
171:            k = Mouse.getDWheel();
```
So MC calls the DWheel in it's achievements screen...
```zsh
➜ rg 'Mouse\.next' 
net/minecraft/client/Minecraft.java
1776:            while (Mouse.next())

cpw/mods/fml/client/GuiScrollingList.java
243:            while (Mouse.next())

net/minecraft/client/gui/GuiScreen.java
311:            while (Mouse.next())

net/minecraft/client/gui/GuiSlot.java
312:                for (; !this.mc.gameSettings.touchscreen && Mouse.next(); this.mc.currentScreen.handleMouseInput())
```
(EDIT: Fixed)

So Minecraft can call it under a few occasions...  And in the main game in `Minecraft.java` it is always calling it at base, so you need to hook in to that, which would be minecraft's input dispatcher system instead of calling mouse calls directly.

What you 'should' do is use MC Input Bindings, that way mouse/keyboard input is centralized in Minecraft's core and so there is no race condition.  The way it stands right now calling `Mouse.getDWheel` is absolutely broken and setting up for race conditions.

**Comment by GregoriusT** [comment]
> What you 'should' do is use MC Input Bindings

You mean the ones that are null and void once there is an identical binding somewhere else, because you cant bind the same thing to two different things?

**Comment by OvermindDL1** [comment]
> You mean the ones that are null and void once there is an identical binding somewhere else, because you cant bind the same thing to two different things?

Didn't forge fix that?  I could have sworn it was one of its applied patched since like 1.5...

**Comment by OvermindDL1** [comment]
But yeah, as it stands MC is reading the event buffer, so you will only get a non-0 response from `Mouse.getDWheel` 'if' someone happened to scroll in the couple of milliseconds between when MC iterates `Mouse.next()` and your call, so that is why it was crazy glitchy.  Don't use the immediate Mouse calls, use MC's input handling.

**Comment by OvermindDL1** [comment]
Ah hah!  Forge didn't fix the input mapping system 'directly' but in a roundabout way!

@ReikaKalseki To listen to mouse events directly from the event buffer Forge added a hook, the `MouseEvent` hook!  The `MouseEvent` constructor queries the eventbuffer mouse state, so that way it is always correct and you don't miss anything!  **That** is what you want to use.  :-)

**Comment by Speiger** [comment]
@ReikaKalseki Here is a example of using scrolwheel that is really relyable (in IC2Classics reactor planner)
Context: onGuiTick is called every frame before rendering happens.
```java
@Override
@SideOnly(Side.CLIENT)
public void onGuiTick(GuiIC2 gui)
{
	Slot hoverSlot = gui.getSlotUnderMouse();
	if(hoverSlot instanceof SlotComponent)
	{
		int amount = Mouse.getDWheel(); //Output is either 0 or a multiplier of 120 (negative or positive) depending on how many steps the wheel did
		if(amount != 0)
		{
			ByteShifter shifter = new ByteShifter();
			shifter.writeInteger(0, 2);
			shifter.writeInteger(0, 3);
			planner.getNetwork().initiateClientTileEntityEvent(planner, shifter.getEncodedData(), -(amount /= 120));
		}
	}
}
```
Context: getDWheel consumes the MouseWheel effect after it returns the value.

**Comment by OvermindDL1** [comment]
> Context: onGuiTick is called every frame before rendering happens.

Doing it this way means it will work more often then not for 'you', but you are breaking other mods that also use `Mouse.getDWheel` (like ChC) later in the tick cycle.  ;-)

You also need to use the `MouseEvent` Forge event instead.

The cardinal rule of input with lwjgl, never ever use the immediate input functions in an actually released game.

**Comment by tiny-maple** [comment]
>Context: onGuiTick is called every frame before rendering happens.

This _never_ worked for me, I'm actually surprised it worked for you. o_O

**Comment by OvermindDL1** [comment]
> This never worked for me, I'm actually surprised it worked for you. o_O

It's because he happens to get called early enough.  That's the thing with immediate mode calls, they are race conditions waiting to happen.  And because his is called early enough then any other call on the same tick will be broken.

**Comment by GregoriusT** [comment]
> This never worked for me, I'm actually surprised it worked for you. o_O

Turns out that in IRC Speiger did mention this was 1.14 and not 1.7.10, so I guess that is the issue.

**Comment by OvermindDL1** [comment]
It would work in 1.7.10 as well, but it is still a call race issue, which is why it didn't work for tiny-maple I'd imagine.  Don't perform immediate mode input calls in lwjgl for anything beyond some testing because of that.

**Comment by Speiger** [comment]
@GregoriusT false statement. The code is 1.12.2 code that is the same as 1.7.10 code.
What 1.14.4 code is is this:
```java
default boolean mouseScrolled(double p_mouseScrolled_1_, double p_mouseScrolled_3_, double p_mouseScrolled_5_) {
  return false;
}
```
All guis get scrollevents.

**Comment by GregoriusT** [comment]
> @GregoriusT false statement. The code is 1.12.2 code that is the same as 1.7.10 code.

Then you should not make the statement its 1.14, while talking to us. Don't complain I am repeating what you said here, when someone else seems to want an answer. ;)

But after some more talking we found better ways to implement it anyways, which I bet @OvermindDL1 will post here soon. XD

**Comment by OvermindDL1** [comment]
Just the way I already spoke of, MouseEvent.  That's the only way to get mouse events (and optionally cancel them too before the hotbar processes them, which it will skip that if a GUI is open in any case, but if you didn't have a gui...) from the event buffer in MC.

**Comment by OvermindDL1** [comment]
Ah I did find more, ChC's ability select GUI inherits from GUIScreen, which it's own `Mouse.next` event loop doesn't call the hooks, but rather calls the `handleMouseInput` within the GUIScreen subclasses (be sure to call the parent).

ChC's `GuiAbilitySelect` screen doesn't override `handleMouseInput`, which it needs to, then within it call `Mouse.getEventDWheel()` to get the DWheel state from within the eventbuffer.  So that's the way to do it, no hooks needed!
