### ISSUE TITLE
[RotaryCraft] Canola seeds can't be placed on BoP farmland

### ISSUE THREAD

**Issue by pablode** [ReikaKalseki/Reika_Mods_Issues#2566]
Biomes O' Plenty adds farmland blocks, but canola seeds can't be placed on them.

This issue can be fixed by replacing the `id == Blocks.farmland` check [at this line](https://github.com/ReikaKalseki/RotaryCraft/blob/c97ee05079e17f85a11e14af3a5c76916b66a2a7/Blocks/BlockCanola.java#L356) with `id instanceof BlockFarmland`, since [BoP farmland extends the vanilla farmland class](https://github.com/Glitchfiend/BiomesOPlenty/blob/fc7f1f6392a16224d19538900acedd152ff4f350/src/main/java/biomesoplenty/common/blocks/BlockBOPNewFarmland.java#L29). This will solve compatibility issues with other mods, too.

Although this issue it might not be RC's fault, I think this workaround solves the problem without introducing new ones. Since farmland checks occur at multiple places in the RC code (sprinkler, hoe, hydrator), I suggest a DragonAPI `isFarmland` helper method.

**Comment by ReikaKalseki** [comment]
An "isFarmland" method would also automatically handle CC luminous cliffs grass, which is also desirable.

**Comment by OvermindDL1** [comment]
Doesn't Forge have an API specifically for plantibility on Block.class specifically because people are not supposed to be testing blocks directly nor even instance-of.  Like testing to Block.farmland or even an instanceof check to BlockFarmland will fail with a lot of mods, like planter blocks.  Using the Forge-official plantable api on the Block.java class (near the bottom, up a dozen pages or so as I recall) is what should always be used.  It should be what vanilla is using as well so even if you copied vanilla it would be using that, only way you wouldn't is if it was done manually without looking at the vanilla classes.

**Comment by OvermindDL1** [comment]
A combination of `canBlockStay`, `canSustainPlant`, and `isFertile` is what farmland/pots/etc should implement, and the plants should call canSustainPlant, passing in an appropriate `IPlantable` (usually just `this`) and fulfilling that contract like vanilla does.  And don't forget to call `onPlantGrow` when it grows stages or some things like fertilized pots that are supposed to be 'used up' will become magically infinite, though vanilla only calls it for saplings so farmland can turn into dirt when a fullblock appears above.

**Comment by ReikaKalseki** [comment]
That API usage is already in place, and has been for years.

**Comment by ReikaKalseki** [comment]
I added some tweaks, but this is mostly already in place.
