### ISSUE TITLE
[DragonAPI] OpenGL Error:1282 @ Postrender

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2606]
The error message also appears in a fresh Minecraft installation using Forge 10.13.4.1614.It causes minecraft to display nothing (execept for GUI). Link to full log: https://pastebin.com/ywhhUDkr

**Comment by Jonius7** [comment]
The "fix" seems to be disabling the Forge Splash Loading screen: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2516#issuecomment-633653490
Or resizing the window upon world load.

This would indicate that the OpenGL shaders in Forge, conflicts with the shaders in DragonAPI since at least v24, I don't know much beyond that.

**Comment by ghost** [comment]
Ok that fixed it, forgot to search the closed issues. My bad and thank you.

**Comment by Jonius7** [comment]
I don't blame you on not finding the "fix". There have been multiple issues on this problem; this was one of the earlier ones with no solution linked in the issue: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2260. This also seemed to be a problem exacerbated by having Optifine back then. Now, no Optifine, I tried v26a/b with a couple other mods and same problem.

Also, resizing the window does seem to fix this. Could a patch be to just use `Display.setDisplayMode(new DisplayMode(width, height));` for the sake of just refreshing the window dimensions? Would save having to do it manually.

This problem was the reason I stayed on v23 mods for a while and eventually stopped playing.  Granted I went to other games and 1.12.2 modpacks since the problem popped up months ago, but I am back on 1.7.10 and checking in

**Comment by gatoborrachon** [comment]
i have the same issue, but disabling the Forge Splash Loading screen makes minecraft somewhat unstable, after testing some machines the game closes

**Comment by Jonius7** [comment]
I would just go with resizing the window upon world load, as a temporary fix

**Comment by George5610** [comment]
> Or resizing the window upon world load.

Thank you, trying to fix this for ages. Cant believe changing the window size was the fix.

**Comment by ReikaKalseki** [comment]
Nowadays that is no longer necessary - DAPI does it automatically.

**Comment by George5610** [comment]
Must be coincidental then. Not sure what is causing it but resizing the window works.
