### ISSUE TITLE
Dimension Structure Issue Collection

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#269]
Preliminary Information:
- Config: Set "Dimension Structure Difficulty"=1 after first music dungeon, just in case this affects anything below.
- feel free to ignore any of these if they seem to minor ;)

General:
G1: The extreme distances between structures imho dillute the experience. Walking for (cumulative) hours in a straight line just isn't fun.
G2: Dimensional Cores are destroyed when mined with hand/diamond pick. Bedrock pickaxe drops Tahara Core for all cores. (But i still got the relevant progression regardless)
G3: Worldgen infrequenty produces unaligned chunks (straight walls, half trees),
G4: Resetting puzzles on disconnect seems unfair especially with the longer puzzles. (music!)
G5: Dimension ambient music does not respect turning minecraft music volume to "off".

Locks Structure:
L1: No fancy message on entering.
L2: Door graphics flicker like aluminium foil in sunlight when moving the camera. (The color overlay and the base white texture intersect).
L3: All "shielding cloak" blocks can be broken.

Non Euklid:
E1: Block seams flicker with white dots.
E2: The warp glass room has no indication of what side you're on. The original AC room had different colors afair.
E3: The warp glass can be interacted with with the elemental manipulator (shift+rmb) or broken.

3D Maze:
D1: Torches can not be put on walls :(.

**Comment by ReikaKalseki** [comment]
G1: You are not supposed to be walking.
G2: I will investigate.
G3: Please elaborate.
G4 is unfixable without turning off dimension resetting, which is unacceptable for multiplayer.
G5: I set up the system so that turning the volume very low functionally disables it - since you are never going it hear it at 1% - but zero is ignored. This is because 90% of people have music turned off anyways, and I did not want it such that 90% of users would never even notice the feature in the first place because of pre-existing settings. Much like how the cloud setting is ignored in the dimension.

L1 is a known bug and related to chunkloading issues.
L2: Is Optifine installed?
L3 is already fixed.

E1: Same cause as L2.
E2: Though the AC room _did_ have colors outside the room, the structure as a whole does not support that. And I did specifically design it to be the same on both sides. Again, experimentation.
E3: ....That is a bug.

D1: Not a bug, inherited from overworld structures.

**Comment by ReikaKalseki** [comment]
Also, record for most tags per issue... :P

**Comment by lossycrypt** [comment]
G1: If you're suggesting the mobility wand: You still can't move faster than worldgen, and the furthest away structure i've had to travel to was over 9000 blocks away from the origin. I do not think that travelling+stopping to use sonar+finding the entrance to the structure taking close to half an hour per structure adds much to the experience. Also keeping in mind that most players will only solve a few puzzles and then leave and come back later to do the rest, meaning they have to do the initial travel to the structure area again. In conclusion i do think that cutting distances in about half would help the ejoyment of the searching experience.

G3: Tried zipping around for 10 mins put can't find a good example right now, have a very minor example (notice the exposed stone on the right):
![disalign](https://cloud.githubusercontent.com/assets/14168854/9934077/61867e4c-5d4f-11e5-97c7-90eda5588396.jpg)
What i mean is that sometimes - more often than i'm used with other dimension generations - on the seam of two chunks the landscape does not fit. Chunk 1 might have a tree trunk with 50% of the leaves, and Chunk 2, which was supposed to have the rest of the leaves, has a beach instead.

G5: I totally agree that the music made the "first entrance" experience a very pleasant one, helped by the whole "no landscape" thing. Maybe you could add a "music has played" check somewhere and disable it afterwards.

L2+E1: Yes Optifine is installed. Is there any solution without uninstalling it?

Addendum:
Still didn't get the "@&#%?!" tag i was aiming for. But having "Bug" and "Not a Bug" in the same issue isn't too bad i guess. ;)

**Comment by ReikaKalseki** [comment]
There are some hacks for terrain height that are the cause of that ground level issue, but it should not affect things like trees or other structures...

L2/E1: On my end. But I think I already fixed L2 (but not E1) for v9.

> Maybe you could add a "music has played" check somewhere and disable it afterwards.

As it happens, the sound thread (temporarily) crashes on the end of the music (no idea why) and so the music never does repeat like it was intended to. I may end up reworking the music and adding more tracks.

G1: Yes, that is what I had in mind. But 9000 blocks? The origin of the structures is at most 5000 blocks away. Also, there is no good way to cap the distance, because the structures need to be quite far from one another to ensure non-interference.

**Comment by lossycrypt** [comment]
Except when it's 9000 blocks away. Meaning the puzzle structures are even further.

![o9k](https://cloud.githubusercontent.com/assets/14168854/9935083/102ce364-5d55-11e5-9922-39252c211259.jpg)

**Comment by ReikaKalseki** [comment]
OK, I need to revisit this.

**Comment by TomeWyrm** [comment]
Reika, I understand why you want to do this, but a check and alert for "hey your music is off, could you please not do that?" is MUCH better than ignoring settings. It's not your fault that the MC music annoys most of the playerbase, but it IS your fault that you're making player-set settings inaccurate. When I turn music off I damn well want music OFF.

I cannot STAND background music while I play, because it always makes it impossible to hear quiet sound effects, and I either don't listen to it, or that's ALL I'm doing.

If I had gotten to the Chroma dimension, I would have manually muted MC in the OS sound control rather than put up with forced-play background music. Yes it really does bug me that much to have settings ignored.

Some people have sound setups that can error, so if they turn off music because certain frequencies bug out their system (one guy I know had an odd bug when his speakers played anything around 8k hertz, it would linger for about 2 seconds.), you're forcing them to experience a bug.

Then again, I'm a power user, so having ANY programmer assume that I don't know what my settings do and "fix it" for me by ignoring a global setting; especially when the settings are intuitively simple it tends to tick me off a bit.

Same kind of thing goes for clouds. I cannot stand MC clouds, it's disabled because they're ugly, get in the way, and obstruct things. Please don't assume you know better than the user that they do or do not want a setting flipped. They have their reasons, and those might be important reasons. For instance, the sound engine lag has forced me to disable all sounds before (mob farm using water, the splashes were causing massive lag spikes when I moved in and out of range)

**Comment by lossycrypt** [comment]
@TomeWyrm

> I cannot STAND background music while I play, because it always makes it impossible to hear quiet sound effects, and I either don't listen to it, or that's ALL I'm doing.

To be fair without spoiling too much, on first entry that _is_ very much _all_ you're going to do. It's on subsequent visists where it started to bug me. And compensating for broken hardware is not anyones job. Your friend should get a refund.

The clouds are force disabled, not enabled i presume, because i've never seen any. And that is very much an atmosphere thing.

**Comment by ReikaKalseki** [comment]
> The clouds are force disabled, not enabled i presume, because i've never seen any. And that is very much an atmosphere thing.
> 
> I cannot stand MC clouds, it's disabled because they're ugly, get in the way, and obstruct things.

Force enabled, actually. I use a custom cloud renderer (the colored fog effect). But your reasoning as to why is entirely correct. And @TomeWyrm, why complain about something that does not even exist?

> Reika, I understand why you want to do this, but a check and alert for "hey your music is off, could you please not do that?" is MUCH better than ignoring settings.

That is far, **far** worse both in terms of annoyance and in terms of immersion breaking.

**Comment by lossycrypt** [comment]
Unless "colored fog" is some crypting description i haven't seen any of that either.

**Comment by ReikaKalseki** [comment]
![](http://i.imgur.com/G890YZl.png)

**Comment by lossycrypt** [comment]
Nope. Not on my screen.
![nofog](https://cloud.githubusercontent.com/assets/14168854/9942903/1e2be22a-5d7e-11e5-9a56-fa605b0bb074.jpg)

**Comment by ReikaKalseki** [comment]
...Then Optifine is overriding my changes (which in hindsight is not too surprising). Try without Optifine. Also, check for "Successfully applied CloudRender ASM handler".

**Comment by ReikaKalseki** [comment]
OK, everything that was a bug, except for the no-clouds and the as-yet-undocumented "sliced worldgen" bugs, have been fixed. Also fixed, even though technically not a bug, was needing silk touch to harvest dimensional cores.

**Comment by lossycrypt** [comment]
Tested without Optifine, and after that with Optifine. Conclusion:
If clouds are turned off in _vanilla_ options (options.txt) then the clouds will not show, but that setting is not available in the gui anymore once Optifine is installed. If clouds are enabled in vanilla, then Optifine options work as expected by the user - aka turning clouds off with optifine _works just fine_.

Also i noticed that some of the clouds are heavily pixelated.
![clouds](https://cloud.githubusercontent.com/assets/14168854/9952587/e0e30c90-5dd7-11e5-890e-d1e382fecb27.jpg)

And as things always happen when they're least expected i found some pretty good evidence for world slicing:
![sample1_00](https://cloud.githubusercontent.com/assets/14168854/9952598/02577d3e-5dd8-11e5-88f3-168064458a88.jpg)
![sample1_01](https://cloud.githubusercontent.com/assets/14168854/9952600/0281049c-5dd8-11e5-9b20-f317467a03b7.jpg)
![sample1_02](https://cloud.githubusercontent.com/assets/14168854/9952601/0283eefa-5dd8-11e5-9364-c32060e1de6c.jpg)
![sample1_03](https://cloud.githubusercontent.com/assets/14168854/9952602/02870540-5dd8-11e5-870b-40f74c599d91.jpg)
![sample1_04](https://cloud.githubusercontent.com/assets/14168854/9952603/028b93c6-5dd8-11e5-83ff-ebe7c9275ba7.jpg)
![sample1_05](https://cloud.githubusercontent.com/assets/14168854/9952604/028bec68-5dd8-11e5-9499-cda0f1fe98ba.jpg)
![sample2_00](https://cloud.githubusercontent.com/assets/14168854/9952599/0272dbb0-5dd8-11e5-9f69-5e7b04a21ed6.jpg)
![sample2_01](https://cloud.githubusercontent.com/assets/14168854/9952605/028fc1da-5dd8-11e5-9ef0-644913ff77f4.jpg)
![sample2_02](https://cloud.githubusercontent.com/assets/14168854/9952606/02986902-5dd8-11e5-8cc6-5e402ecc51f0.jpg)

Looking at the coordinates (Entry Point == 0/0), i noticed that the upper right corner on the first map is exactly region r.0.0.mca. So my speculation would be that this is not actually a worldgen bug, but an uncomplete map reset problem. Adding to this is the fact that i have sometimes been able to return to the monument during testing, even after leaving the dimension.

**Comment by ReikaKalseki** [comment]
I...have never seen anything this bad. It looks like total seed change, not a simple chunk variability issue (which I know about and cannot fix). Are you sure that it was not caused by a crash or something?

EDIT: It appears you saw the same.

> So my speculation would be that this is not actually a worldgen bug, but an uncomplete map reset problem. Adding to this is the fact that i have sometimes been able to return to the monument during testing, even after leaving the dimension.

**Comment by lossycrypt** [comment]
The server rarely crashes. And i saw this a lot before. But i found the error in the console:

```
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.IOException: Unable to delete file: E:\minecraft\bergwerk2.0\servers\bergwerk2\bergwerk
2-world-2015-08-05\DIM60\region\r.8.15.mca
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.IO.ReikaFileReader.deleteFolderWithContents(ReikaFileReader.java:385)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager.resetDimension(ChromaDimensionManager.java:
84)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.ChromaticEventManager.resetDimension(ChromaticEventManager.java:445)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_309_ChromaticEventManager_resetDimension_Unload.invok
e(.dynamic)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:334)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[07:14:28] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[07:14:29] [Server thread/INFO] [FML]: Unloading dimension 60
```

```
[07:29:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.IOException: Unable to delete file: E:\minecraft\bergwerk2.0\servers\bergwerk2\bergwerk
2-world-2015-08-05\DIM60\region\r.0.0.mca
```

Looks like it's trying to delete the region files before unloading the dimension.

**Comment by ReikaKalseki** [comment]
Yes, it does that. That is how the dimension auto-resets.

**Comment by lossycrypt** [comment]
Any idea why it would fail?
(Also lacking any knowledge of mc internals i assumed that it might be better to delete the regions _after_ unloading.)

**Comment by ReikaKalseki** [comment]
> (Also lacking any knowledge of mc internals i assumed that it might be better to delete the regions after unloading.)

It does (WorldUnloadEvent), which is _supposed_ to happen after the Save event.

I dug through the dimension unloading and saving code, and did some little hacks like forcing an I/O flush and a Garbage Collector run, but unless you know of a Java way to "delete this file, I don't care about permissions, if another program has it open, et cetera", like those file shredding tools do, I do not know how to fix it.

**Comment by lossycrypt** [comment]
Sadly i don't know any java.
How about if you deleted the files on entering the dimension instead? Logically they shouldn't be writelocked at that moment if the dim was unloaded before. Basically:
Catch dim entering attempt > clear files > start worldgen. If that is possible.

**Comment by TomeWyrm** [comment]
Or a once-every-5-seconds query; if the Chroma has been unloaded for two consecutive queries, delete it.

And Reika, you want immersion breaking? Try playing Minecraft with music disabled in the main menu anytime it gets heard for multiple years (so you never EVER hear it in game) and then having music play. It drops me so far out of the experience having to go into the options menu and disable the music normally, if I then found out that the music was in fact already disabled but still playing anyway, I'd probably mute ALL SOUNDS. I don't care if it's immersion breaking, ignoring settings a a giant no-no. It's the PLAYER'S machine, not yours. Respect the settings that the player has set. There are in-game ways to indicate that you're going to want music enabled in the Chroma. Heck make opening the portal require playing Simon with a 16-color Crystal Orchestra if that can be made to play via the music setting instead of block sounds or what-have you. Brainstorm, don't just say "players don't matter". There are truly valid reasons people want their music disabled, which is why that setting is in-game in the first place. Maybe I play at night in earshot to a sleeping baby, with my music disabled, but normally I like my music at 100. Force-ignoring the setting means you could very easily wake that baby up. I can come up with so many more scenarios you couldn't have anticipated during planning, programming, and limited beta testing. That's why options are a good thing: your software WILL encounter a situation you could not have planned for.

Honestly I wish you could disable individual sounds like you can in... wait we have resource packs now, so I can but jeez that's a lot of effort. Wonder how hard it would be to make a mod to query all the sound locations so you could make a "blank" template easily. I'll probably listen to the music once and then have it disabled via resource pack much like the base music from C418 except I can do that with a setting. It was neat the first time, and I'm glad I heard it. But I am also glad I can turn it off. I play the music in nearly none of the games I play, and that's the way I play my games, because I do NOT like BGM. It doesn't matter how epic you think it is, I don't and I bet the whatever % of players that have music turned off would probably agree with me. Once might be neat (make it play as a normal sound upon first dimension enter or something, it can't be that hard to trip a flag in the player's nbt), but ignoring any setting is a giant "DO NOT DO THIS". You get yelled at already for having nonexistant DRM because of sneaky things and people assuming you're doing sneaky things. Don't give them actual ammo by ignoring settings at any point!

**Comment by ReikaKalseki** [comment]
...Twice now you have either missed or ignored the fact that you can still functionally disable the music, just not the default way.

**Comment by TomeWyrm** [comment]
Discarded as unintuitive, difficult to set, and insufficient. I don't know if it is unique to my system, but I can still clearly – if quietly – hear the music even at 1% on the Minecraft volume slider. Obviously so long as no other sounds are drowning it out, but even at 100% for basically everything – except the weather which I also disabled because rain is annoying; there isn't something making sound ALL the time and hence I can still hear the music very often, well enough that it bothers me.

Can't you check/set a "has visited" flag? If you absolutely, positively, must have the music play once, would you at least respect to the setting for all subsequent visits? I still don't think you have sufficient reason to ignore the setting the first time, but you seem to; so I'm providing ideas to minimize the annoyance

**Comment by ReikaKalseki** [comment]
> but I can still clearly – if quietly – hear the music even at 1% on the Minecraft volume slider.

There was a bug (setting the min volume to 35%) and I just fixed it. Try again in v9.

Also, for the hasVisited. There are going to be at least 2 new tracks in v9, and so the annoyance factor drops dramatically.

**Comment by TomeWyrm** [comment]
I mean the vanilla music. I could test the CrC music as well in v9, but unless it's an order of magnitude less volume as compared to the base tracks? I'm betting I still hear it :-/

I, personally, will probably disable them with a resource pack after I listen to them once. But it still might be nice for other people to have a config option maybe? Have an "only play BGM tracks once" option? Per track would be funny, who knows, maybe someone REALLY like one of the tracks and only want to hear that one for background.

**Comment by lossycrypt** [comment]
As a compromise, would you be willing to have a config volume option like for RoC sounds effects? It would be on by default but still easily adjustable/disableable for people who really want to.

**Comment by ReikaKalseki** [comment]
Everything that can be fixed has.

**Comment by TomeWyrm** [comment]
Thank you for adding the dedicated music slider!
