### ISSUE TITLE
[Suggestion] Music Structure Difficulty Reevaluation

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#270]
Music Structure:
M1: The notes are too fast.
M2: Some of the rooms have far too long sequences. The longest i solved(!) was a 29 note sequence (have video evidence :p), with every dungeon having at least one room with 11+ notes.

This puzzle is imho far too difficult for anyone without at least relative pitch (https://en.wikipedia.org/wiki/Relative_pitch). This sort of music puzzle is not the kind of "intellectual challenge" that your usual mechanics rely on. And the longer sequences can not be solved by pure patience/logic deduction without using external recording tools. You have to have some basic musical skill or it will simply be unsolvable. The only thing that can be logically deduced is how to play the notes reliable at all, and what all those floating runes mean. (I think there's still some decoy runes floating up tho, that don't follow the usual pattern, but not sure about that.). YMMV.

If i may suggest some rebalancing (easy/normal/hard == 1/2/3):
M3: Fixed number of notes per room scaled by difficulty (i.e 4/5/6).
M4: Fixed number of rooms scaled by difficulty (i.e 2/3/4). Keeping in mind the player will have to solve several of these dungeons and after the first one it's pure repetition.
M5: Have a small (optional) "tutorial/getting-used-to" room with only 2 or 3 slow notes and only 4 crystals at the entrance.

**Comment by ReikaKalseki** [comment]
There _is_ a structure difficulty config, which in this structure currently controls the number of rooms. I will also make it control max length. However, the 29-long sequence is one of the "prefabs" - i.e. melodies not randomly generated, usually either from public domain or music I wrote - specifically the same piece as in the [Crystal Orchestra demo](http://www.youtube.com/watch?v=K8atGKfijdo&t=1m47s). (Fun fact: I made the Crystal Orchestra because of the structure). I can make lower difficulties reject long prefabs, but that one in particular is more than double the length of all the others, and I have been uncomfortable about that from the start; it was only included because of the fact  the Crystal Orchestra uses it. It _is_ melodically far more simple than most.

Also, the floating runes are the main hint. I knew that doing it based on pitch alone would be impossible for most - myself included - and so I made it display the colors capable of generating that pitch (as there is often overlap). It then falls to the user to know _which_ of the four notes can do that, which some basic trial and error can reveal. This then turns it into a memory puzzle, holding a sequence of indexes in mind.

Yes, even that will be impossible to someone who is tone-deaf, but tone-deafness is rare, and I cannot be dumping functionality for it, much the same way color-blindness and deafness are currently highly disadvantageous for CC.

> Keeping in mind the player will have to solve several of these dungeons and after the first one it's pure repetition.

This is only temporary. The original plan was to have 16 structure types. That proved a massive undertaking, so in v8 I rewrote it to reuse structure types as necessary, meaning that as I implement more and more structure types, the reuse will lessen and eventually stop.

> Have a small (optional) "tutorial/getting-used-to" room with only 2 or 3 slow notes and only 4 crystals at the entrance.

The system does not support speed - though I suppose it _could_ - but giving only four crystals would probably be misleading. I do like the idea of a tutorial room, though.

**Comment by lossycrypt** [comment]
I know there's difficulty config - as i mentioned in the other issue - i turned mine down from 3 to 1 after solving a 10 room crystal music dungeon in about 5-7 hours. The fact that there is note-overlap and that that is what the runes indicate is something i only noticed at the end of the third dungeon i solved (meaning after at least 16 solved rooms). The rest i solved via recording a video and listening to the tones, because i happen to have above average pitch hearing. But trying to do that from memory would still be impossible for me because the memory of e.g. the third tone in a sequence would be "overwritten" in my memory by the time the demo play of an 8-note sequence finished.

The main difficulty for me at the start was to figure out at all that there is four notes per crystal because usually in mc "one block" does not behave differently depending on how you click it. This is a nice idea but might need some stronger visual clues. I was just totally confused why clicking the block sometimes registers as the right note, sometimes gives an error sound, and half of the time doesn't do anything at all (clicking the middle). This probably took me between 30-40 minutes to realize.

Even comparing notes based on which runes float up still requires you to run around the room and playing all tones on several different blocks, trying to figure out which ones overlap. And even then this means that you first have to memorize all the floating symbols, when it is imho even on video, difficult to distinguish which symbol belonges to note 1 and which to note 2 because they just play so _fast_ after each other. At one time i even thought that the number of runes above a crystal indicated which "number" of tone on that crystal you need to play.

Also i wasn't suggesting you dump functionality for the tone-deaf. I was merly saying that this type of dungeon requires a radically different skill set than your mods usually do, and thus are accordingly more difficult to your target audience. Imho.

Number of structures:
16 different dungeons does indeed sound more enjoyable, and much more difficult to implement. I originally thought of suggesting to make the current puzzles slightly longer and then have two cores per puzzle instead, with one in the middle and one at the end.

Tutorial:
"4 crystals" is ofc not a fixed number, it was just meant to indicate that the tutorial room should be less complex than the actual riddles because otherwise it wouldn't be much of a tutorial. In a tutorial room you could also possibly have stronger clues about which notes are played possibly by having the actual buttons on the triggers flash accordingly.

**Comment by ReikaKalseki** [comment]
> The main difficulty for me at the start was to figure out at all that there is four notes per crystal because usually in mc "one block" does not behave differently depending on how you click it. This is a nice idea but might need some stronger visual clues. I was just totally confused why clicking the block sometimes registers as the right note, sometimes gives an error sound, and half of the time doesn't do anything at all (clicking the middle). This probably took me between 30-40 minutes to realize.

You are not the first, but after already having made the "buttons" animated and pulsing color, I do not see a way to make it more obvious. The trigger blocks are not TESRs and cannot render anything really "real-time".

**Comment by lossycrypt** [comment]
If you implement a tutorial room then inside that room you could have a 4 blocks "large trigger" which is basically a scaled up version of the normal trigger, so that each block gets one button. That would ofc remove all speculation about those buttons, if you wanted to keep those. Also the pulsing looks more like a rotating animation. Maybe if all four buttons had different colors it would be easier.

**Comment by ReikaKalseki** [comment]
> If you implement a tutorial room then inside that room you could have a 4 blocks "large trigger" which is basically a scaled up version of the normal trigger, so that each block gets one button.

That would be a major headache to implement.

**Comment by lossycrypt** [comment]
Well, that one headache on your side would prevent one headache for each player to figure those out the hard way. Having a more obviously colored normal-size trigger might work too (in the tutorial room). "Obviously colored" meaning something like red/green/blue/yellow, and not four shades of blue. Or actual 3D buttons. I don't know how difficult any of those would be to implement.

**Comment by ReikaKalseki** [comment]
In order, trivial, trivial, and headache.

**Comment by ReikaKalseki** [comment]
I tried changing the colors of the buttons on the trigger. Anything too different looks downright _awful_, and most color combos give me headaches.

EDIT:
I had an idea.
