### ISSUE TITLE
Exception Getting Block Type In World (ChromatiCraft)

### ISSUE THREAD

**Issue by jadenquinn** [ReikaKalseki/Reika_Mods_Issues#2716]
Once again, a crash on my custom pack:
(No full log, it would not work)
https://pastebin.com/S9XAupv2

I don't remember if I got this one before, but I moved the pack to my PC so it should start faster, AKA better times for testing.

**Comment by ReikaKalseki** [comment]
world.setBlock(x-5, y-8, z-2, ChromaTiles.STRUCTCONTROL.getBlock(), ChromaTiles.STRUCTCONTROL.getBlockMetadata(), 3);
						TileEntityStructControl te = (TileEntityStructControl)world.getTileEntity(x-5, y-8, z-2);
						te.generate(s, e);
`te` should never be null right after placing a block of that type in the world. Either something went horribly wrong, or it tried to place the block below y=0, but since y is determined by `world.getTopSolidOrLiquidBlock(x, z)`, that still counts as something being horribly wrong.

Are you trying to generate these in a void world or something?

**Comment by jadenquinn** [comment]
Nope, just generating entering an already-created world a few hours prior, just resuming playing. Not sure what happened, just knew to post it here. The pack is strange but it kinda works, for example, sometimes the screen will become very pixelated, 30secs apart from such events, and also 30secs apart, meteors will continuously make the "uproar" sound that they make, which I've run into in the past. The pack is just.... abnormal. What I think I did was just generate a few new chunks in the world.

**Comment by ReikaKalseki** [comment]
The pixelation sounds like the CC progress shader (example [1](https://i.imgur.com/xHi97gt.png), [2](https://i.imgur.com/TILlmid.png)) and the meteor sounds can happen if they continuously unload and reload.

**Comment by ReikaKalseki** [comment]
Tell me if this happens again.
