### ISSUE TITLE
java.lang.NoClassDefFoundError - Please fix this.

### ISSUE THREAD

**Issue by jadenquinn** [ReikaKalseki/Reika_Mods_Issues#2736]
I created a new issue about this about a month ago, and there is no way TeamCoFH is going to fix a version they haven't developed for in 3 years. To be fair, you did break it, it's been fine for 3 years before this. I can think of 5 friends who would be using this mod in their pack right now, but they can't, because ChromatiCraft is incompatible with CoFH mods because the only developer that CAN fix it, won't. It can't be that hard to fix.

Please consider fixing your mod or making a workaround other than removing ChromatiCraft altogether, just to have RF machines, which is basic.

https://pastebin.com/k6pgwYPd

**Comment by ReikaKalseki** [comment]
There is no "fix" other than removing the Manipulator focus completely, for everyone. As long as that class exists along side the old TC API, you crash. Period.

This is what happens when mods package old copies of APIs.

And no, your options are not only "removing CC to have RF machines". You have been told in the other issues what you can do on your end. That you apparently ignored it is not my concern.
