### ISSUE TITLE
[ChromatiCraft v28a] Custom recipe handler configs do not work on a dedicated server

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#2750]
Going to reference this issue, where I went into more detail initially:

https://www.curseforge.com/minecraft/modpacks/a-polychromatic-world/issues/3

The custom recipes in question work perfectly fine clientside, when tested in single player and doing the same thing. And playing on a server, it acts as though it _should_ be crafting the custom recipe's output on the client's end, but actually trying to craft it results in failure/error.

This leads me to believe that it's _not_ an error on the modpack creator's end, but a syncing issue in the recipe handler itself. I apologize in advance if this is not the case.

This is the folder containing the custom recipes from the modpack, used to test this.

[Chromaticraft_CustomRecipes.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6022874/Chromaticraft_CustomRecipes.zip)

**Comment by ReikaKalseki** [comment]
This is a modpack error.

**Comment by LordPINE** [comment]
https://www.curseforge.com/minecraft/modpacks/a-polychromatic-world/issues/3 for context, the issue came from a missing capital letter in the configuration file directory, which is handled differently on Windows and Linux. It seemed to be a server issue since most people run their servers on Linux, but have their client on Windows
