### ISSUE TITLE
[ArchiSections] Crash when starting on the server with Pistronics 2

### ISSUE THREAD

**Issue by erplsf** [ReikaKalseki/Reika_Mods_Issues#2833]
Single player client works fine, configs are the same between the server and client.

If i remove Pistronics 2 from the mod list on the server, it starts fine.

Here's the crash log from the server:
https://pastebin.com/UK6UJDnm

**Comment by ReikaKalseki** [comment]
His block is throwing an NPE on `getRenderType()`, presumably making the assumption that since it sounds rendering-related, it need not be safe to call on the server side. However, even vanilla checks the render type from serverside code in some cases, to say nothing of mods.

In the meantime, you can add an override for that specific block type, using other functions.
