### ISSUE TITLE
Forestry chrashes Dragon Api

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#2882]
As soon as i try to load Dragon api with forestry it chrashes and the error: "Dragon api is not installed correctly" shows up but when i delete Forestry it works just fine. Tried in 3 different profiles on the new Curseforge. To recreate just install Dragon api and Forestry.

**Comment by ghost** [comment]
Which versions of DragonAPI, Forge, and Forestry?
Also, could you please post the crash log? That will have more information on the crash - just knowing the error really doesn't tell people much.

**Comment by MalTeeez** [comment]
I've tried both manual install and via the curseforge app, since both worked some logs would be helpful

**Comment by ThomasDennisSp** [comment]
with forestry
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7042776/latest.log)

without forestry
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7042790/latest.log)

Forge 10.13.4.1614
Dragon api, Rotarycraft, Chromaticraft 29g ,elecrticraft 29a

**Comment by ghost** [comment]
First, I thought you said it crashed just with DragonAPI and Forestry? Because the only logs I'm seeing are for what is a larger modpack.
I tried it with just the version for Forge, Forestry, DragonAPI, and Chromaticraft that were listed in your logs, and I'm not having any problems. Fully loads, and I was able to create a new world without problems.
I would look at this section below the crash log, and try the suggestions there:
`	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.429_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.`
Especially the stuff about Optifine. There's a reason a lot of mods say they don't support it.

**Comment by ThomasDennisSp** [comment]
without forestry it works even with the enderr io warning

ok for backstory
 
So as i was creating the modpack in the logs i tried it with with all mods and who would have guessed it didnt load. So i tried with fewer mods till it loaded at some point because i knew in a 5 month old profile with got lost it worked with forestry. I tried it all the time with it and then i was at only the 2 mods as stated in the 1st post so i deleted forestry and it worked then i tried it in 2 new profiles in them it didnt work with forestry and dragon api but i  drag and dropt the mods from the other profile were the logs are from. I tried it again after i saw your response in a completly fresh profile with new mod downloads and it works. But in this instance (where the logs are from) it will not work when i install forestry even with a new forestry install it buggs dragon api out and it wont launch.

**Comment by ThomasDennisSp** [comment]
ok i tested all 200+ mods now and found out that when dragon api, chromaticraft, Hardcore ender expansion (dont know where it comes from or i was just blind and didnt saw it the other time) and forestry are installed it gives the error 
![Screenshot 2021-08-25 041558](https://user-images.githubusercontent.com/61876687/130719199-22dcac13-29d0-4154-b75f-3d17ecacbe7d.png)
when i take either forestry or Hardcore ender expansion out it works properly but not when both are installed together
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7043301/latest.log)

**Comment by ghost** [comment]
In the crash log:
`Reika.DragonAPI.Exception.InstallationException: DragonAPI was not installed correctly:
Could not add sound category CHROMA_MUSIC! Use the Sound HashMap config!
Try consulting http://www.minecraftforum.net/topic/1969694-for information.
This is not a DragonAPI bug. Do not post it to http://www.minecraftforum.net/topic/1969694- unless you are really stuck.`
There's an option in the DragonAPI config.

**Comment by MalTeeez** [comment]
Did you change the Sound Hashmap config in the ChromaticCraft config, as stated in the crash log?

**Comment by ThomasDennisSp** [comment]
no i didnt know there was a option

**Comment by ghost** [comment]
@MalTeeez 
> Did you change the Sound Hashmap config in the ChromaticCraft config, as stated in the crash log?

It's in the DragonAPI config, not the Chromaticraft one. Which could maybe be made explicitly clear in the crash log text.

**Comment by ThomasDennisSp** [comment]
ok thx now it works but i would like to know why it doesnt work if both are installed but not if only one is instelled thats weird

**Comment by ghost** [comment]
I'm not a modder, _so don't quote me on this:_
Looking at the code, it seems like Forestry/HEE tend to conflict in terms of their sound settings, internally - there's old code that would have enabled the HashMap if both were in the modpack.
Reika probably made it a config option in case there were other mods that also caused such issues. Or in the event that forestry/HEE somehow fixed the issue themselves.
Either way, this issue was resolved by changing a config setting, so I think you should close the issue.
Edit: I probably should have left closing it up to Reika.

**Comment by ThomasDennisSp** [comment]
ok
