### ISSUE TITLE
Chromaticraft v9a: Graphical problem with fused crystals

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#297]
http://i.imgur.com/eL3FSaG.png

Not sure what happened here, as I can't replicated this by just placing fused crystals as a test. 

The area was pitch black and I had just placed a torch and gotten into range of the night vision crystal. The black non-see squares are particle smoke from the torch at my feet. The see through bits are the stone texture of the top two fused crystals.

**Comment by ReikaKalseki** [comment]
I have noticed this as well. Its almost nonexistant manual reproducibility, as well as the fact I have never seen it in the dev environment, has severely hampered fixing it.

Something is clearly wrong with [the ISBRH](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Render/ISBRH/TieredOreRenderer.java), but [the stone part](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Render/ISBRH/TieredOreRenderer.java#L277) is simple and nonvariable, so I have no idea what.

Have you noticed any patterns at all? I have seen it at all light levels, with all surroundings, in multiple dimensions, so I have not.

**Comment by 1skandar** [comment]
INo. That said I have video documentation as I was recording my LP. Let me upload the relevant bit and maybe that will help you?

**Comment by 1skandar** [comment]
https://www.youtube.com/watch?v=tL_C3rnrw3k&feature=youtu.be

Also, maybe it is video card related? I have a NVIDIA GTX 970

**Comment by ReikaKalseki** [comment]
> Also, maybe it is video card related? I have a NVIDIA GTX 970

And I have an AMD Radeon 6850, meaning it clearly is not card related. On top of that, I do not see how it could be; MC uses OpenGL immediate mode, which is far more involved with the processor rather than the GPU.

Also your video is private and thus inaccessible.

**Comment by 1skandar** [comment]
True, that said I have seen people have graphical issues that are GPU dependent.

Oh, not sure it matters but I am not using Optifine.

Hmm,

**Comment by 1skandar** [comment]
And fixed the video. Meant to have it unlisted and derped because I was tired. Worth noting that the first block only showed the bug on the first face to render right after it came into view and the second only on the face that was hidden by the first. Maybe some sort of intermittent failure to update what should be rendered? 

Edit/ Hm, it also the first block, or the closest block in a particular direction. That holds true for both blocks.

**Comment by 1skandar** [comment]
Did some further testing: The problem is persistent. Where it occurs, it ALWAYS occurs. Reloading the chunks, exiting and re-entering the world, quitting Minecraft entirely, the bug is still there. If you mine out the bugged blocks, and then replace them, the new blocks are bugged. If you place new blocks in line with the bugged blocks those blocks will be bugged. Up to a point, although at what point that stops seems to be arbitrary. I've seen lines as high as 8 and as little as 5 in my testing. And the direction doesn't matter, running the line east/west, north/south, up/down or even a mixture of those and the blocks will be bugged with seemingly no rhyme or reason. Even which sides are bugged can vary in an area of bugged blocks, although the top and bottom sides appear to be immune, but even that I can't state with 100% certainty. 

If you want a copy of my world, let me know. I've found two sections of bugged out blocks, and a few sections without. If you want to see a video of the above in action, let me know.

**Comment by ReikaKalseki** [comment]
What are the coordinates?

**Comment by 1skandar** [comment]
x-680  to x -689 z 410 to 413, more or less. This is my survival world and this one is buried into a rock very well. The y 
THe other one is massive x -754 to -731 z 498 to 512

Huh. And there is something odd. I can toggle the effect on and off for some of them. I put a block on top of them, they are fine. I over hang that top block, and whichever side is under the underhang becomes bugged. And this extends all the way down. As in I can build a tower from bedrock to, at a guess, build height and overhang at the top causes all of them to bug. Hold on, I'll make a video. This is....very odd.

**Comment by 1skandar** [comment]
Ok, those coordinates are WORTHLESS. Sigh. There are section of the world that are bugged regardless, that overhang trick will ALWAYS cause the bug. Ok, video incoming

**Comment by 1skandar** [comment]
The coordinates are worthless. I have found something interesting. While some parts of the world seem to bug out regardless, I can now trigger the bug at will.

Put a fused block down. Put a block on top of it. Then put a block beside that one. Whatever side that block is on, that side of fused blocks becomes bugged. This is 100% repeatable regardless of coordinates.

Oh, and you can stack the fused blocks arbitrarily high. You only need to overhang the top block and ALL the fused blocks on that side will bug.

I'll get a video so you can see this.

**Comment by 1skandar** [comment]
https://www.youtube.com/watch?v=ctpHKF21j0w

This is just weird.

Edit: and it gets weirder. That overhang does NOT need to be directly on top of the block. You can, in fact, put the overhang at world ceiling and the fused block on the bedrock and it will trigger the bug.

However, there is something that prevents this from happening, and I'm not sure what. A bugged block should have all 4 sides naked, but some don't. And some blocks are fine, despite overhang. I think it is some combination of blocks near them or something. Ah well, you at least have a way to trigger at least part of the bug.

**Comment by ReikaKalseki** [comment]
wtf....

**Comment by Modbder** [comment]
I've done some testing. The problem is in the stupidest possible place... The lighting value. To be more precise, the Tessellator.instance.setBrightness((int)(b.getMixedBrightnessForBlock(world, x, y-1, z)*n)) lines. The thing is - if there is a block above the block on the offset you are getting the light value of the lighting value returns something different than full light value. Now, your *n transforms that value into something weird that tessellator is unable to understand and renders the block as an invisible one.  The full 100% light value(I will say in mc's light levels from now) or 15 is 15728640 in dec or 0xF00000 in hex. The 14 is 0xE00000, 13 is 0xD00000 and so on. See the point? The first number of the hex is our light value. Now, let's take, for example our light level of 13, which is 0xD00000, or 13631488 in dec. Now \* that by 0.8 as you do. That would be 10905190 dec or 0xA66666 in hex. Somehow those 66666 screw everything up completely when it gets to rendering. Sadly I have no clues to what happens - I am not good with OpenGL and Minecraft rendering in particular. I can just point the line out that causes the error to happen... My fix would be simply removing those *n from the rendering - I've tested that and it works without affecting the look of the block in the world much.

With *n:
http://postimg.org/image/s4jkbk67v/

Without *n:
http://postimg.org/image/rgapsm7i3/

**Comment by 1skandar** [comment]
I'd have to see it in game to be absolutely sure, but I kind of like the without better. It is like the crystals are buried in the rock a bit more. which isn't a bad thing.

**Comment by ReikaKalseki** [comment]
The *n is to account for side brightness.

Also, MC Tessellator brightness is not a normal ARGB color. It is a simple variable form 0-255 that controls where on the lightmap the texture falls (0-239 are block light, 240 is full bright, and 240-255 are night light).

I do not want to remove the sided brightness, as it would make the block look very odd with a "flat" light model and make its bottom side very much brighter than the surroundings.

Also, I use this code everywhere, including in all of the [pipe-type renderers](https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/BaseBlockRenderer.java#L121) ([RC pipes](https://github.com/ReikaKalseki/RotaryCraft/blob/master/PipeBodyRenderer.java#L1361), [ReC steam lines](https://github.com/ReikaKalseki/ReactorCraft/blob/master/SteamLineRenderer.java#L44), [ElC wires](https://github.com/ReikaKalseki/ElectriCraft/blob/master/WireRenderer.java#L66)...) as well as many of my other ISBRHs. This has never caused issues before.

I will investigate to see if something is odd with this version of it, but its removal is not the proper fix.

**Comment by Modbder** [comment]
And, as you have pointed out in your PipeRenderers(https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/BaseBlockRenderer.java#L155) you are not multiplying the light value, you are instead multiplying the color. The setBrightness functions look like this:

int l = b.getMixedBrightnessForBlock(world, x, y, z);
v5.setBrightness(!b.isOpaqueCube() ? l : b.getMixedBrightnessForBlock(world, x, y+1, z));
And the multiplication is for the color:

float f7 = f4_multiplier;
float f8 = f4_multiplier;
float f9 = f4*multiplier;
v5.setColorOpaque_F(f7, f8, f9);

For chromaticraft you are multiplying directly the brightness value, not the color - this causes issues.

You could also use >> and << to multiply light, I suppose(I made a quick and derpy example):

Tessellator.instance.setBrightness(((int)((double)(b.getMixedBrightnessForBlock(world, x-1, y, z) >> 20) \* 0.8) << 20));

instead of 

Tessellator.instance.setBrightness((int)(b.getMixedBrightnessForBlock(world, x-1, y, z)*0.8));

That works just fine without render glitches and it indeed makes the stone part darker. The only problem would be that a light level of 1 will get darkened to 0, but you can use MathHelper to round the numbers better... Anyway, I am not good with rendering, so your solution would anyway be better than mine :P

**Comment by ReikaKalseki** [comment]
Oh....

_tail between legs_

**Comment by ReikaKalseki** [comment]
Fixed.
