### ISSUE TITLE
GTNH AE Incompatibility

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2977]
This happened on placing a fluix cable onto an already existing on, and when placing a charger onto the cable. [gist](https://gist.github.com/MalTeeez/e8e393d59e5774bab6373f600130546f)

**Comment by MalTeeez** [comment]
After a bit more testing, it appears this happens whenever I place something onto a fluix cable while looking at it.

**Comment by MalTeeez** [comment]
This has become quite troublesome, since I can now also not open my Crafting Terminal

**Comment by MalTeeez** [comment]
This seems to only be affecting a newer fork of ae2 [ GTNewHorizons /
Applied-Energistics-2-Unofficial ](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial), but since this version fixed a few annoying bugs, it would be helpful to add support for it. 
Here are the few mentioned classes in the disconnect:
[AEBasePart](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/parts/AEBasePart.java)
[PartPlacement](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/parts/PartPlacement.java)
[ApiPart](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/core/api/ApiPart.java)
[ItemMultiPart](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/items/parts/ItemMultiPart.java)

**Comment by ReikaKalseki** [comment]
I need more information before I can act on this.

**Comment by MalTeeez** [comment]
Can I provide anything for that, or will that just be on your side?

**Comment by Shibva** [comment]
I am having this issue as well; can you elaborate on what type of info you need, please?

**Comment by Shibva** [comment]
idk what you mean, but for the sake of convenience ill give you a few things
1. the crash that I got from the interaction
[crash-2022-07-10_02.11.06-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/9078568/crash-2022-07-10_02.11.06-server.txt)
2. I asked the folks since im in the GTNH server and they provided me with a link to their public respiratory on their GTNH version of AE2
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial

if you need any more information that is specific; please feel free to let me know ^w^ 
hope this helps

**Comment by Shibva** [comment]
I can also confirm with @MalTeeez that this is only happening when your trying to place it on the cable itself, even if it's not connected to a ME network; it behaves fine if you put it on a non-cable block, and then for a few use a wrench to rotate the few that can be turned.

the crashlog I posted also seems to be caused by it erroring at this line (this is at the top of the stacktrace)
``at Reika.ChromatiCraft.ChromaticEventManager.registerPatternHandler(ChromaticEventManager.java:335)``

**Comment by Shibva** [comment]
ok, the guys maintaining it on their end made a remark on it, for convenience sake ill post it here what they said to me

"Thanks for the callstack, the reason of the crash doesn't seem to be at our side (although probably caused by our changes). I try to keep the API unchanged but Reika is probably using some implementation details, judging by the call stack. Should be easy to fix on his side I think."

I also have an update; it seems like its not happening to just AE2 blocks being placed on the cables. its in fact all blocks that you place on the cables directly

again, it seems that this is not happening if your not putting a block on the cable itself, so it seems to be some sort of interaction when placing stuff when.

(this is a crude diagram I made, the areas checked are areas where you can place blocks without the game crashing, the red X represents spaces where you will crash the game if you place them on it)
<img width="605" alt="image" src="https://user-images.githubusercontent.com/38770780/178166993-ed6fde9b-3dfa-4052-8150-f37e4261015e.png">

Update: OK I just found something interesting. IT IS when your looking at a network cable. You are able to place stuff on the pre-existing cables if your placing it on a paced faccadel; furthermore it seems that the faccade is the only block that you can place directly on a cable without it crasihg

**Comment by DarianLStephens** [comment]
Any news of this? Me and my friends just encountered it in our server, and it's caused quite some annoyance to people who've been bee-lining towards an AE2 system.

**Comment by MalTeeez** [comment]
Nope, I'd say either downgrade your AE version to non GTNH or try to fix it yourself in AE Code, but doesn't like GTNH wants to fix it either.

**Comment by DarianLStephens** [comment]
Yeah, we did that a few days ago (Downgrade to non-GTNH). Sad to miss out on the fixes and all, but we're still determined to give Reika's mods a fair try, so we do what we must.

**Comment by Shibva** [comment]
The interaction seems to only happen when you place a network block on another network block; if you put a network block on a normal block without placing it while facing the network block it won't crash as far as I have tested

**Comment by Shibva** [comment]
Such as placing it on the facing side of where the network block is

Ie: you build off of it

**Comment by Shibva** [comment]
Ironically enough it seems that this interaction is negated if you have a facade on it and then place it

**Comment by Shibva** [comment]
Also based on the erroring line, It seems to be a bad interaction with the pattern handler for some reason

"Thanks for the callstack, the reason of the crash doesn't seem to be at our side (although probably caused by our changes). I try to keep the API unchanged but Reika is probably using some implementation details, judging by the call stack. Should be easy to fix on his side I think."

**Comment by Shibva** [comment]
This may be relevant or not but I made an interesting discovery

for a while I thought that when you change a mod with this mod present your game will need to crash once for it to work the second time… But I've learned that this is not the case and is in fact issue. I've discovered that the reason why this happens is because of AE2. Apparently this issue only exists if you're using the latest alpha and not the latest RELEASE

Also where in the Stacktrace is disconnection issue occurring? Maybe being able to locate where it's trying to use it in the GTNH version and then comparing it with a regular version could yield a probable solution

**Comment by Shibva** [comment]
Maintainers of the GTNH version did say that they would try to keep the API has similar as possible; so I'm guessing what rake it was using was probably broken because of a slight optimization that either was removed due to lack of relevancy or was replace with something new that it's not recognizing


I guess it depends

**Comment by MalTeeez** [comment]
After testing with the newest version of all the mods involved in this, I can confirm this no longer happens.
