### ISSUE TITLE
Mob Harvester doesn't run/function when you are in a different dimension

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#299]
So as the title states I've noticed that the mob harvester won't run when you are not in the same dimension as it (At least in my SSP). Note everything is chunk loaded and mobs will spawn when not in an alternate dimension, they just won't die which can lead to large TPS issues. 

Here is an imgur album to help demonstrate what happens, as visuals are probably better than my rambling from the forum post. 
http://imgur.com/a/0ldxi

If this is an intended effect, potentially add a note to the rotarycraft book, if not. I'm glad to help find the issue if possible.

**Comment by ReikaKalseki** [comment]
If everything was chunkloaded, then there should be no difference to you being there...

**Comment by Reignofmagic** [comment]
Yeah it is odd... I'm beginning to think your mods don't like Java 8. Since a few others have posted odd things with Java 8 that are similar to mine.

I'll see if I can install Java 7 and see if that changes anything. 

Edit--

No, java 7 did not fix anything which is unfortunate.

**Comment by Modbder** [comment]
Each dimension has it's own World instance. Players are stored in the world's instance playerEntities(ArrayList). If the player leaves the dimension - he will be removed from the list.

https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Farming/TileEntityMobHarvester.java#L49
https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Farming/TileEntityMobHarvester.java#L51

You are trying to get the player from the world instance for the dimension the harvester is in. If the player is in another dimension both of those methods will return null, since they both iterate the playerEntities to find the player, and the player is in another world's instance for another dimension. 

https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Farming/TileEntityMobHarvester.java#L61

And the harvester will only damage mobs if there is any player at all.
You could use MinecraftServer.getServer().getConfigurationManager().func_152612_a("%PLAYERNAME%"); to get the owner of the device throughout all dimensions and there is an ArrayList too which contains all players to get the player from if the owner simply does not exists(MinecraftServer.getServer().getConfigurationManager().playerEntityList)

Those are only server-side methods though, so a !world.isRemote check would be required and could mess up some things... I guess it can be done via a sided proxy too...

**Comment by ljfa-ag** [comment]
Well getting the player from the list won't help either when they are logged out from the server

**Comment by Modbder** [comment]
Yes - that's why there are 2 ways of getting the player !already! - the harvester first tries to find it's owner, and of can't - it will pick a random(1st in the list) player.

**Comment by ReikaKalseki** [comment]
OK, so this is a result of the Mob Harvester having legacy code. Easily fixable.

**Comment by Reignofmagic** [comment]
Additionally, since there will be times when no players on on the server there should be a method that just does normal damage (could do something like lava/fire/falling) instead of player/fake player damage. This way there will not be an excess of mobs if a spawner is left on while using the mob harvester as the primary means of killing them. 

I'm not sure how you would go about that, but if using player damage isn't possible while the player is either not online or in an alternative dimension the above suggestions might work instead. 

https://github.com/powercrystals/MineFactoryReloaded/blob/68c87a84c0bacb1da2e00bbbe339964a3d451971/src/powercrystals/minefactoryreloaded/tile/machine/TileEntityGrinder.java

Might be of some service to you as the MFR Grinder drops player only items such as blaze rods as well.

**Comment by ReikaKalseki** [comment]
Fake player damage will work fine.

**Comment by ReikaKalseki** [comment]
Fixed.
