### ISSUE TITLE
Very Small Amounts of Torque/Speed Become 0 when Geared

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#30]
![untitled](https://cloud.githubusercontent.com/assets/10469156/7267049/975c86ac-e882-11e4-8c58-290225c651f3.png)
![untitled](https://cloud.githubusercontent.com/assets/10469156/7267053/a1d7ccc2-e882-11e4-8c54-bcc0d990ddf6.png)
![untitled](https://cloud.githubusercontent.com/assets/10469156/7267054/af7bf9d4-e882-11e4-809b-27c8b45f69e6.png)

CVT can be set to anything larger than a value and it will return 0. In this case it's set to 32 speed, but it can be set to 2 and still have the same effect, as long as Math.floor(1/speed) = 0.

**Comment by zemerick** [comment]
Not sure Reika wants the power to be non-integer. We'll have to get his attention and see what he thinks there. ( That was a part of his reasoning a long time ago about not including English measurements as an option. They would be non-integer. )

Obviously, we can't just round back up to 1 either due to power exploits.

**Comment by ljfa-ag** [comment]
This is probably intentional. Else you would be able to gear small power amounts up to ridiculous speeds.

**Comment by madolinn** [comment]
```
tor = (tor / gear > 0) ? Math.floor(tor/gear) : tor/gear;
```

Although this will suck later on. (Coils).

**Comment by ReikaKalseki** [comment]
This is intentional. Power is an integer for both gameplay and computational simplicity.
