### ISSUE TITLE
Nether Ores Exploding with Bedrock Pick 

### ISSUE THREAD

**Issue by Rivaryn** [ReikaKalseki/Reika_Mods_Issues#3118]
Digging Nether Ores with a normal pick with Silk Touch prevents them from exploding (when the config option for explosions is on).  However, the Bedrock Pickaxe does not prevent these explosions.  Tested with latest version of RotaryCraft (v31b) and Nether Ores 2.3.2B1-25.  Also note the "higher chance when mined with fortune" config was also enabled.

**Comment by ReikaKalseki** [comment]
Either their code is set to trigger when fortune is present (maybe they assumed that since normally Fortune and Silk are mutually exclusive, an if-else would be valid), or they hardcoded something. Bedrock pickaxe silk touch is entirely vanilla - there is nothing special about its implementation.

I added a little code that *might* bypass this, but if it does not work there is nothing I can do.
