### ISSUE TITLE
ChromatiCraft V9B Issue Collection

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#312]
As before just ignore things that sound too minor.
Chromaticraft:
~~CC1: Lexicon tooltip shows max number of pages one too big. "Has 154 of 155 pages." is maximum.~~
~~CC2: 3D Structure Help block textures render in wrong order. I.e. Portal Structure "Portal" blocks always render on top regardless of rotation. (This makes it mostly useless.)~~
CC3: All structure entrances are generated at wrong height. (mostly too heigh, see screenshots)
~~CC4: No ingame indication that entering the dimension requires Desert, Burrow and Hollow progression.~~
~~CC5: I suggest adding some Information about the volatile nature of the Dimension. Possibly a fragment obtainable after first entering it. Something like: "This Dimension seems to be even more flexibile/unstable/$fitting_adjective than some of the more obscure ones you've read about in some books. It's as if you enter a new place every time you return here. It seems to be in a constant flux, changing when not observed."~~
~~CC6: Vacuum gun can move Crystal Lamps in Crystal Music Structure.~~
~~CC7: Lighted logs "break progress"-overlay is not rendered on age-rings side (i.e. top+bottom on natural trees)~~
~~CC8: Lighted logs "light-dots"-overlay is replaced by "break-progress"-overlay if a texture-resource pack is used. (Tested with soartex-fanever).~~
CC9: Structure Types should be hard-linked to Core-Colors so none of the dungeon types are too common or too rare. This will be needed if you want 16 different dungeon types later on anyway.
CC10: The sonar always shows two structures right at 0,0 which do not exist. This is probably some error with the GOL structure which doesn't seem to generate.
~~CC11: RF Radiator particles fly through supplied blocks instead of vanishing. (Tested with Immersive Engineering Capacitor)~~

Shift-Maze:
SM1: Keys are indistringuisable (from each other and) from player made keys. Maybe some tooltip text with player name could be used?

3DMaze:
~~DM1: Crystalline stone column/beam/corner on structure entrance can be broken to get some nice free blocks.~~

Locks Structure:
~~L1: Vacuum gun can move lock blocks, possibly getting the player stuck. Not sure if that shold be fixed or left :D.~~

![2015-09-30_20 48 13](https://cloud.githubusercontent.com/assets/14168854/10299485/f3564e0c-6bea-11e5-9f78-a78fb8d8a341.jpg)
![2015-10-02_23 52 25](https://cloud.githubusercontent.com/assets/14168854/10299487/fb24dfc2-6bea-11e5-85dd-95d6a223a6d4.jpg)
![2015-10-06_01 49 44](https://cloud.githubusercontent.com/assets/14168854/10299488/fb52bafa-6bea-11e5-8aea-e56e378c8180.jpg)
![2015-10-06_02 48 38](https://cloud.githubusercontent.com/assets/14168854/10299489/fb54651c-6bea-11e5-9013-465defebbe5b.jpg)
![2015-10-06_03 04 34](https://cloud.githubusercontent.com/assets/14168854/10299490/fb5888cc-6bea-11e5-97cb-6b76331d35eb.jpg)

**Comment by ReikaKalseki** [comment]
CC6 is already fixed.

**Comment by ReikaKalseki** [comment]
- CC1 is fixed
- CC2 is extremely difficult to fix
- CC4: Ideas?
- CC7 may not be fixable, as most custom-render blocks do not render cracks properly
- CC8: ?!?!?!
- CC11 is fixed
- DM1 is unfixable; crystalline stone has no unbreakable variants
- L1 was fixed with CC6

**Comment by lossycrypt** [comment]
CC8:
![cc8](https://cloud.githubusercontent.com/assets/14168854/10345052/275dc8dc-6d27-11e5-90ec-46f66de52b69.png)

CC4:
The simplest solution would be to have the lexicon render lines from the structures to the dimensional core progression (Rendering lines to off-screen progressions is currently broken).

Another possibility would be to require structure specific drops to actually build the portal. (This seems to already be the case for Buried Hollows entrance's breakable "Shielding Cloak" blocks.) But that would mean altering the portal structure every time a new overworld structure is added.

How do you explain the nessecity of having to discover them lore-wise? Currently it seems arbitrary to me.

CC2:
As i said the wrong order rendering makes 3D almost useless in some cases, regrettably. The worst example for that is the ReactorCraft Hydrogen Preheater (assuming that's the same code) as it is a solid cube and thus has lots and lots of overlapping. I guess having an actual 3D model (even a non-dynamic one) is not feasable?
![cc2_heater](https://cloud.githubusercontent.com/assets/14168854/10345571/f9e6b20c-6d2a-11e5-84c7-c00becac76b5.png)
(Just for reference how other mods do similar things, here's a picture of Immersive Engineering's manual, which uses buttons to manually switch through layers of the structure in an isometric view:)
![cc2](https://cloud.githubusercontent.com/assets/14168854/10345209/5365274e-6d28-11e5-9457-8a09743dd0e3.png)

**Comment by ReikaKalseki** [comment]
CC2: It attempts to sort blocks back-to-front, but it appears to not have very much visual effect. Also, rotating the blocks with the model is nearly impossible to implement.

**Comment by lossycrypt** [comment]
CC2:

> It attempts to sort blocks back-to-front, but it appears to not have very much visual effect

From a laymans perspective it looks rather like the order of rendering is simply incorrect.

> Also, rotating the blocks with the model is nearly impossible to implement.

If it's difficult to implement rotating a dynamic block-by-block model then how about a complete premade model that contains all blocks? Basically just rendering one standard 3D object made in Blender or whatever software you use for 3D modelling.
If that isn't feasible either then a layer-by-layer view like in the IE manual might convey more useful information than what you currently get when rotating.

**Comment by ReikaKalseki** [comment]
> If it's difficult to implement rotating a dynamic block-by-block model then how about a complete premade model that contains all blocks? Basically just rendering one standard 3D object made in Blender or whatever software you use for 3D modelling.

I use Techne for the ingame models. It is not even remotely viable for actual 3D rendering.

**Comment by ljfa-ag** [comment]
Looks like right now, it's just that the positions of the blocks on the screen are calculated with a matrix and the blocks are rendered like vanilla renders items in the inventory.

Would it not be feasible to render the blocks in 3D, like blocks are rendered in the world? Then they would not overlap and the whole structure could easily be rotated. I think Ars Magica is doing it this way.

**Comment by ReikaKalseki** [comment]
> Would it not be feasible to render the blocks in 3D, like blocks are rendered in the world?

Not remotely. Cubes are one thing, but what about much more complicated things like TESRs and ISBRHs?

**Comment by ljfa-ag** [comment]
Well TESRs are easy, just need to call renderTileEntityAt with some dummy tile entity (the same way you already do it with rendering them as items).
And ISBRH will be handled for you if you use a custom RenderBlocks instance.

It would be more complicated to implement than now surely, but it might be worth it if it can display multiblocks properly.

**Comment by ljfa-ag** [comment]
I was curious as to how difficult it would really be to implement this, so I quickly cobbled together a proof of concept: https://gist.github.com/ljfa-ag/0088a1f14014985581ac
Feel free to use this code if you want.

http://imgur.com/3pThQf3
Edit: a small video on @lossycrypt's request: http://gfycat.com/LivelyUnimportantBullfrog

**Comment by ReikaKalseki** [comment]
This code does not actually rotate the renderers.

**Comment by ljfa-ag** [comment]
Well, the whole stucture is being rotated with glRotatef, depending on the mouse position. The individual renderers won't need to be rotated.

**Comment by ReikaKalseki** [comment]
Well, it works...mostly. Some render errors are present (for example repeaters render twice, and the TileEntity block is missing from pylons, as well as some rotation origin issues), but it works.

EDIT:
I fixed the 2x-rendering - it was the same fix as the null-world issue you had - and it turns out the rotation origin is the origin of the structure, which is usually the main TileEntity. This is normally not an issue, but if it is far off-center (eg the new lumen broadcaster), it does look odd.

**Comment by ReikaKalseki** [comment]
It is also hitting some render pass issues, because the GUI render pass is -1 and since the worldObj on the TileEntities is not null, it only renders models on pass 0 and transparency on pass 1.

EDIT:
Also fixed, as are the origin issues.

Now all that is left is the entity rendering for the portal structure...

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=24391

**Comment by ljfa-ag** [comment]
Nice, that definitely looks much neater than before!

Also, by using display lists the FPS can be much increased for large structures

**Comment by ReikaKalseki** [comment]
In a GUI, FPS is generally insignificant unless it drops below 10 or so.

**Comment by lossycrypt** [comment]
Yeah! That looks infinetly better than before.
Also FPS problems usually also cause input lag, which is annoying in any situation. So if it's particularly slow then any improvements would be good. (And not everybody has a high end rig)

**Comment by ReikaKalseki** [comment]
Done.
![](http://i.imgur.com/fZ5Yl0S.png)

It also works for ReactorCraft:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=24397

**Comment by ReikaKalseki** [comment]
CC5 is done. CC4 is supposed to already render the connected lines.

**Comment by ReikaKalseki** [comment]
I fixed it.

**Comment by 1skandar** [comment]
Thank you, thank you, thank you for fixing that lexicon. I'm old, my eyes are bad and parsing the structures was beginning to give me a headache. 

On the bad eyes subject, and as I mentioned on Twitter, could you improve the Elemental Manipulator dial? To my eyes the difference the difference between filled and unfilled for some of the darker colors is hard to discern and Kuro is pretty much impossible. Instead of going from a dimmer version of the color to the actual color may I suggest leaving the rune colored but have the bar be empty until filled. much the way Thaumcraft does with vis in the various wands?

**Comment by ReikaKalseki** [comment]
I do not like the way the TC style looks, and it would get especially bad for this renderer, which is 3 times denser with values and has more render layers.

A better idea would be some sort of indicator at the "outer edge" of the filled area.

Also, you might want to look into the color response on your monitor, because the difference between "empty Kuro" and "filled Kuro" is 0x30 on all three channels. This is a very substantial difference (20% of the "max" of 0xFF=255), especially given that, generally speaking, the human eye is logarithmically sensitive, i.e. much better at noticing brightness differences at low brightnesses than high ones (so it is easier to tell black and dark gray apart than it is white and light gray). However, some monitors, or some configurations, "floor out" at something like 0x20, and maybe that is the cause.

Additionally, the runes within remain "filled color", so you _should_ be able to see the contrast fairly easily.

**Comment by 1skandar** [comment]
It isn't the contrast. Yeah, maybe if I left it half filled I could see the difference, but once it is filled there is nothing to contrast with. Here: http://i.imgur.com/m2AUkuk.png

The Kuro is filled, all well and good. But when you consider it next to the bright red it certainly doesn't look it. Worse, it is actually darker than the unfilled color on the other side of it. 

Several colors are like that. Once filled you have no contrast against what they looked like unfilled, and the only reference you have is the lighter filled colors that are very vibrant and against that you are kinda scratching your head and wondering if you actually filled them.

**Comment by lossycrypt** [comment]
I have to agree that Kuro can be very very difficult to tell at times, this gets gradually worse on smaller HUD elements but is quite noticable on the large personal charge wheel too.That said aside i took the liberty to open a seperate issue for this discussion. (But apparently i was too slow >_>)
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/340

**Comment by ReikaKalseki** [comment]
> It isn't the contrast. Yeah, maybe if I left it half filled I could see the difference, but once it is filled there is nothing to contrast with. Here: http://i.imgur.com/m2AUkuk.png

I look at it and it really is clear to me. For one, the color inside the rune is the same as outside, a good indicator of being filled. Two, it is very clearly not "jet black"...

> Worse, it is actually darker than the unfilled color on the other side of it. 

That is what happens when you darken white...

> Several colors are like that.

Aside from Kuro, I really do not see which are hard to see.

**Comment by 1skandar** [comment]
It is hard to describe. The biggest thing is immediacy.  If you tell me what to look for I can see it, but it takes me a few seconds to put together. At a glance it isn't the runes I see, it is all the colors contrasting off each other. Again, Kuro is the worst offender, it is grouped with white on one side and red on the other. From that grouping you have a very, very sharp contrast from empty to full on each side and then Kuro's much subtler contrast in the middle. And being in the middle of two bright colors makes it look darker by comparison which really doesn't help matters. The dark grey paired between pink and light grey has the same problem to a lesser degree, and the dark green and brown surrounded by the brighter blue and red also suffer.

That is one of the reasons why I pointed out the Thaumcraft interface. When a certain vis is empty the contrast isn't between two different colors, that particular section is just absent. This is immediate and easy to grasp even with a quick glance. I'm not saying you should copy that verbatim, but including something with the same quick, clear difference would be a very good help. 

Hmm, if I would suggest something, instead of having the runes be the same hue as the rest of the bar when full, have them always contrast. When empty the runes should be bright, when full they should be dark. This would provide a better contrast to judge each individual color to help separate them from the surrounding colors.

**Comment by ReikaKalseki** [comment]
> Hmm, if I would suggest something, instead of having the runes be the same hue as the rest of the bar when full, have them always contrast. When empty the runes should be bright, when full they should be dark. This would provide a better contrast to judge each individual color to help separate them from the surrounding colors. 

This is...interesting. Can you create a mockup of the kind of thing you mean?

**Comment by lossycrypt** [comment]
I think what he means is something like this:
![contrasted_charge](https://cloud.githubusercontent.com/assets/14168854/10523965/6e3eb804-737d-11e5-93d8-cc1a0099fa0d.png)
So if the gauge is empty the rune is darker than the background, and if the gauge is full the rune is brighter than the background.

**Comment by 1skandar** [comment]
Yup, that would be exactly it.

**Comment by ReikaKalseki** [comment]
Cutting the rune itself is not possible like that because of the way the wheels render; they are drawn as "triangle fan" mode where (after one at the origin) all the render vertices are along the outer arc. You cannot cut an quad (cartesian)-coordinate image such that it can be rendered in radial (polar) coordinates.

I could try some sort of blend effect, but that would probably fail.

**Comment by 1skandar** [comment]
Ah. Um, it looks like there are two ongoing discussions about this. I'm going to stop commenting here and move it there for clarity sake and stop cluttering this issue up.

**Comment by ReikaKalseki** [comment]
Fixed SM1, and investigating C10. Log lines are consistent with your guess, @lossycrypt:

[16:05:20] [ChromatiCraft Structure Gen/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Generated a YELLOW Reika.ChromatiCraft.World.Dimension.Structure.GOLGenerator@733a9833 at 0, 0
[16:05:20] [Client thread/INFO] [FML/Forge]:   Unknown recipe class! Reika.DragonAPI.Instantiable.Recipe.ShapelessNBTRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
[16:05:20] [ChromatiCraft Structure Gen/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Generated a BLACK Reika.ChromatiCraft.World.Dimension.Structure.GOLGenerator@bde775f at 0, 0

**Comment by ReikaKalseki** [comment]
As it turns out, the issue was the generation coordinates never being set for the structure. That meant it still generated, but its location was always reported as 0,0. This is fixed for v10, finally closing this massive thread.

**Comment by lossycrypt** [comment]
Looking forward to finally being able to find them then ;).

What about CC3, CC9 and SM1 btw?

**Comment by ReikaKalseki** [comment]
Already on fix list, rejected, and above respectively.
