### ISSUE TITLE
problem with reactorcraft, or my world

### ISSUE THREAD

**Issue by TheMgfeedthebeast** [ReikaKalseki/Reika_Mods_Issues#3120]
hello where playing on my own server and the game just crashed and now i can't get back in crash report from client: 
https://pastebin.com/7VgDczwg
info from server:
https://pastebin.com/Lc4K1Ac9

my friend does not have this issue

**Comment by Maxwell-lt** [comment]
This doesn't look like an issue caused by Reactorcraft. The logs suggest that you tried to look at a Reactorcraft block with a wand from Better Builder's Wands. If this is what you did right before the crash, have your friend (or yourself from the server console) TP you somewhere safe in the few seconds between logging in and crashing, and in the future avoid looking at Reactorcraft blocks while holding a builder's wand from that mod.

**Comment by FavoritoHJS** [comment]
surpricingly, this doesn't seem to be caused by mw for once! this seems to be a combined issue between:
- Rotarycraft not failing safely in case of problems getting surrounding blocks
- BetterBuilderWands expecting getting a collision box to not throw an exception

despite most devs having long abandoned 1.7.10, some madlads are still working with it, including a more updated fork of bbw: https://github.com/GTNewHorizons/BetterBuildersWands
alas, the affected bug doesn't appear to be fixed, at least not from a quick glance at the code, but it's worth checking just in case the fix was somewhere else.
if it still breaks, scream in their discrod or smth as issues aren't open there.

PS: Make sure your reactors aren't leaking radiation everywhere, that generates tons of entities and thus lag.
PPS: your mod list is delightfully cursed, and I mean that in the best way. Not content with one highly dangerous reactor, you have mods providing around _4_ of those, and if another issue of yours says anything you're using all of those!

**Comment by TheMgfeedthebeast** [comment]
hey maxwell-it can i ever get back to that part of the world, or is that part gone as its in my base

**Comment by FavoritoHJS** [comment]
you can, you just need to find a way to stop looking at a pipe and not hold a builders wand from then on.

**Comment by TheMgfeedthebeast** [comment]
favoritohjs lol i like my mods list do you not? its perfect for multiplayer! now comes with reactor craft and hbms nuclear tech mod perfect!

**Comment by TheMgfeedthebeast** [comment]
so that means the world is not complitly destroid for ever favoritohjs

**Comment by ReikaKalseki** [comment]
You have corrupted blocks but I fixed the crash.
