### ISSUE TITLE
Use DragonAPI in Eclipse

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#3133]
Hey there I've tried to use the RotaryCraft API in my mod but unfortunately I cannot use it, because DragonAPI is a dependency and don't work in eclipse. So my question is if there is a way to use DragonAPI and the RotaryCraft API in Eclipse.

**Comment by FavoritoHJS** [comment]
from what i know, it's kinda hard, since the repo only includes the code, not the assets folder, and IIRC Reika uses custom mappings that aren't publically available, so you are missing dependencies.

If you are trying to make an addon, I wonder if you can get away with making a "fake" API that only contains definitions, compile against that (but not including it in the finished jar), and have that work with the game after obfuscation.

**Comment by ReikaKalseki** [comment]
You can replicate those couple of classes - stripping them down as needed by removing all methods/fields referencing other DAPI classes. As long as you do not build those into your JAR, it should work.
