### ISSUE TITLE
Chromaticraft's Thaumcraft Tab crashes with shaders using Optifine.

### ISSUE THREAD

**Issue by Azzezima** [ReikaKalseki/Reika_Mods_Issues#3142]
Game crashes when selecting the Chromaticraft tab in the Thaumonomicon.
I managed to make it not crash by turning shaders off and on, though it does show missing textures in that case (Screenshot included)
Shaders: ComplementaryShaders v4.7.1
Optifine: HD E7 Ultra

![Chromati Crash Report](https://user-images.githubusercontent.com/42901705/224187028-7ee1f11e-7106-4ae9-aa11-10fefe17c620.png)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10937196/latest.log)
[crash-2023-03-10_00.22.22-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10937197/crash-2023-03-10_00.22.22-client.txt)

**Comment by ianlavr** [comment]
Well... You have OptiFine. Its kinda expected that it would break things, especially ChromatiCraft

**Comment by ReikaKalseki** [comment]
There are a few OF versions that work. DR has one. In general, this is not my doing.

**Comment by Fantazer3z** [comment]
I'm writing through a translator, because I don't know English well, so don't swear. it also crashes when I select the chromaticraft tab in the thaumonomicon if I go in with shaders. if I go in without shaders, click on the tab and turn on shaders, minecraft will not crash, but the tab will be something like in the screenshot above. I didn't really understand your answer, @ReikaKalseki. /

**Comment by Azzezima** [comment]
Reika is saying that the problem is not from chromaticraft.

Angelica is close to shader support and will most likely not have all the
problems that optifine has, I suggest you look into Angelica (developed by
the GTNH team) for 1.7.10 instead.
