### ISSUE TITLE
[DragonRealm] No way to get Charged Certus Quartz

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#3185]
I know that the guide says that to get charged Certus Quartz you need to set up a mining node in Satisforestry, but there's no information on how to make the multiblock structure and the power hub block is invisible and reverts to the RF version whenever it's broken. At the moment I've just re-enabled the charger and gave myself one to get started, but I'm wondering if I'm just missing something.

**Comment by EyeDeck** [comment]
Yeah, there's no documentation for the Satisforestry multiblock, outside of some vague screenshots Reika posted on his Discord server once.
I'll copy/paste what I wrote a few months ago:

---
Here's a BuildCraft blueprint: [Satisforestry_Drill_Multiblock-f80f4a8f77e6e1bf9d9055e8a0441b5741d78e64479fac0f8ed185b685f67769.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11360133/Satisforestry_Drill_Multiblock-f80f4a8f77e6e1bf9d9055e8a0441b5741d78e64479fac0f8ed185b685f67769.zip)

Exact item requirements (excluding the TE) are:
>79 (64+15) Housing   
78 (64+14) Framework Metal
55 Scaffold
31 Connecting Rod
10 Drill Bit
3 Redstone Lamp
2 Electrical Connection
2 Conveyor Belt
1 Power Hub

Which if I did the math right, the housing+framework+scaffold+connecting rod+drill bits cost:
>1190 Iron Ingots
442 Iron Bars (~166 Iron Ingots)
158 Bronze
453 HSLA
20 Tungsten Alloy Ingot
20 Diamond
10 Obsidian

The lamp+electrical connection+conveyor belt+power hubs are relatively negligible.

Blueprint places like this relative to the node:
![2022-10-12_01 52 49](https://user-images.githubusercontent.com/2722970/235325482-1f30e30e-95b5-421e-9a9e-c5d0c75f598a.png)

The (currently invisible) `Resource Node Extractor` goes directly on top of the Satisforestry `Resource Node`; shaft power goes into the `Power Hub` on the top of the multiblock, or presumably RF/EU into the `Electrical Connection` depending on which version you've built.
Output ejects out of the back `Conveyor Belt`, possibly into an inventory if there is one.

In all configurations it needs _exactly_ 2048 Nm torque, geared from 262kW by default—the GUI accepts power slugs to overclock it:
- 1 `Green Power Slug` increases power to 524 kW
- 2 `Green Power Slug`s, _or_ 1 `Yellow Power Slug` goes to 1MW
- 3 `Green Power Slug`s, _or_ 1  `Green Power Slug` and 1 `Yellow Power Slug`, _or_ 1 `Purple Power Slug` goes to 2MW

Resource generation rate is comically fast even at 262 kW, I'm sure this thing would make tens or hundreds of thousands of charged certus (with current pack config) if you left it running overnight.

If for some reason you need to dismantle it, break anything except the TileEntity first or it bugs out slightly (render breaks until you break some other block, and the redstone lamps completely vanish), and also the TE isn't saving its damage value when broken so EU/shaft ones will transmute into RF ones when the item drops

**Comment by Mettymagic** [comment]
@EyeDeck is there a way to get into this discord server? It seems like a lot of mod information is inaccessible otherwise. The link on his website doesn't work.

**Comment by EyeDeck** [comment]
@TrueThaumaturge
I guess you'd have to poke Reika directly (Reika#3161 on Discord) and ask.
It's invite only, and even as a mod in his server I can't generate invitations.

**Comment by ReikaKalseki** [comment]
This is now documented in v32.

**Comment by tprussak** [comment]
The documentation seems rather lacking. The only thing I found for it was the structure blueprints, which I have no idea how to obtain other than cheating one in. Even with that, the blueprints do not say what the blocks are in a tooltip or something, so I could not figure out that the first block was supposed to be a redstone lamp, admittedly largely due to the texture pack.

**Comment by ReikaKalseki** [comment]
Those blueprints are obtainable, and just spawning things in when you cannot think of how to get it does not give me confidence that you have actually tried very much.

**Comment by tprussak** [comment]
Looking through the code, it appears there should be a recipe for it, but NEI does not show any recipes for any of the blueprint items on v32c with Dragon Realm's hard configs. The listed recipe in the code also does not appear to work (3 paper and an orange pressurizer/miner housing block). I suspect this might be an issue with a bad build from Dragon Realm, as I have noticed several bugs that were apparently fixed in v32c, but my files do say they are v32c.

**Comment by ReikaKalseki** [comment]
DR disables the recipe SF adds for it, in favor of another approach.

**Comment by tprussak** [comment]
I did try several things, quite thoroughly. I did find the solution by using JD-GUI to look inside DragonRealmCore, and the answer is that it was, in fact, unobtainable for me due to #3245.

**Comment by Waisse** [comment]
> DR disables the recipe SF adds for it, in favor of another approach.

And what is this approach?? I've been battling with your Satisforestry mod for weeks trying to understand how everything works between the server-ending biome worldgen, finding the resource node, building the extract- can't do it because you made connecting rods uncraftable, assembling the damn thing because no recipe for the blueprint (there's a legit way of getting it, how?! Do you want people to play your pack or not?!).

And after all that, after all this time bashing my head again and again with a non-functionning drill receiving the required shaft power... IT NEEDS EXACTLY 2048 TORQUE?! How, literally how are you supposed to find out when there's NOTHING telling you there's a torque requirement? Reika for the love of god please fix, I want ae².

**Comment by tprussak** [comment]
The blueprint drops from bookshelves in strongholds. 
If you have not set up TerritoryZones, strongholds will not generate (https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3245) and they will be unobtainable.

**Comment by Waisse** [comment]
That only leaves the connecting rod to have a working recipe then, thanks.

**Comment by tprussak** [comment]
That one does not have a workaround, you will have to cheat items in or add a recipe.
