### ISSUE TITLE
[Chromaticraft] Nothing Draws From Lumen Tree

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#3188]
I have a Lumen Tree in my world and it's full of a few million of each type of energy, but none of my constructs will pull from it even if the pylons of that color are exhausted.

**Comment by EyeDeck** [comment]
There's a small secondary structure that has to be built around the lumen tree (4 2-block pillars) to allow it to discharge. It's in the lexicon somewhere.
It exists so you can let the tree charge up before attempting to draw from it, because otherwise actively used colors tend to charge up to 1k or 5k, then drain back out immediately and break the leaves, which creates a very restrictive throughput bottleneck

**Comment by DFliyerz** [comment]
I have that built, but it's still not drawing anything from the tree.

**Comment by DFliyerz** [comment]
It seems I just positioned the pillars wrong, I wasn't sure if it was meant to be 1 block away from the tree or two.
