### ISSUE TITLE
Need advice

### ISSUE THREAD

**Issue by Pyromanc3r** [ReikaKalseki/Reika_Mods_Issues#3208]
I don't know where to ask. If there is a topic, please send me there.
I have never played with this mod (and other Reika's mods), only heard about it. But it seems like it's time to give it a try. Can you recommend additional mods for ChromatiCraft? My goal is magic, exploration/battle, and automatization.

Its page says that it supports a lot of different mods, but it doesn't say which ones. I will have to rely on screenshots.
What mods do you think must have? I want to get good synergy between them.
I love magic mods and Thaumcraft will definitely be added. Botania, Ars Magica, Blood Magic - I can do without them if ChromatiCraft has similar functionality.
I'd also like to add something on biomes diversity and exploration, but I noticed that Biomes O' Plenty isn't supported =( And vanilla MC have boring biomes. What about something like ExtrabiomesXL and Natura?

From what I can see, the mod supports:
Applied Energistics 2
Ender Storage
Forestry
Open Blocks
Thaumcraft
Tinkers Construct
Twilight Forest
VoxelMap

Since ChromatiCraft supports Applied Energistics 2, which energy generation option would you recommend? Railcraft, Industrial Craft 2, Thermal Expansion?
One last thing. Since the player becomes very strong because of the provided modification possibilities, it would be nice to apply them somewhere. There should be some kind of challenge. A dungeon or dimension where you can apply all your power and get some kind of reward. Something like Roguelike Dungeons. Thanks!

**Comment by Milii20** [comment]
Hello!, i have the following sugestions: 

-   If you are using Applied Energistics 2, remember to use the official version, NOT the GTNH's one since there is currently a bug (i think) which will prevent you from right clicking any AE2's thing.
- ExtraBiomesXL is amazing and it's the main biome mod for me in 1.7.10, natura works as well.
- If you are looking for intresting mods for 1.7.10 Witchery is really cool (remember to add witcheryextras mod and witcheryPatch mod, two must have addons), ElectricalAge (in case you want to try anything really cool and new), Magneticraft (immersive engineering like multiblocks, really cool), and may others i can't recall right now (in case you are curios, this is my modlist: https://pastebin.com/16cCvMFS , everything there works pretty good (Ignore endlessids, swap it for notenoughids if you want to avoid some weird crashes))
- If you want a Challenge: i use SpecialMobs, InfernalMobs (as a suggestion, disable Sticky modifier), Grimoire of Gaia, Hardcore Wither, Hardcore Ender Expansion, Void Monster, and Draconic Evolution (For setting the Chaos dragon as a intresting enemy to defeat), and for dungeons, ChocolateQuest (Check the extra dungeons you can get from their wiki, some are pretty intresting) and Roguelike Dungeons (With SpecialMobs, it's pretty challenging, just remember to disable witch spider and witch cave spider since it may or may not crash).
- If you want an intresting way to power AE2 use buildcraft or IC2, as a backup, you can always go to Railcraft or thermal expansion power, or even better, Rotarycraft and Reactorcraft as main power


That's all, have fun!

**Comment by Goddfrey** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1285

A better place to discuss things like this.

**Comment by Pyromanc3r** [comment]
Milii20, Thank you so much for such a comprehensive answer! I think that will be enough for me. Thanks for the heads up about AE2, as I just downloaded the GTNH fork. Some mods I haven't even heard of (although I've been playing 1.7.10 for a long time and love it). Special thanks for the list of mods, I will read and get acquainted.
Goddfrey, thx for the link :)

Well, it looks like I have to spend some more time to create a modpack for myself and will be adjust the config files :D
I will soon close this thread if there is nothing to add.
