### ISSUE TITLE
[Satisforestry] Feature request: configurable Pink Forest biome frequency 

### ISSUE THREAD

**Issue by bakaawful** [ReikaKalseki/Reika_Mods_Issues#3221]
Feature request: please make the frequency of the Pink Forest biome from Satisforestry configurable (in the direction of less frequent spawning, with a range of perhaps even 1% of current spawn rates).

Rationale: mainly aesthetic. I enjoy the biome, but I find it's too large a departure from my usual Minecraft biomes, and it clashes. Secondarily, it does take a long time to generate (~20 seconds on a Ryzen 3800x CPU), and it does interrupt exploration runs and glider flights. I could solve both these issues by making it ~50 times less frequent.

I did look in Satisforestry's and DragonAPI's config files , but haven't found a setting pertaining to my request.
Thank you.

**Comment by ReikaKalseki** [comment]
Barring the use of other mods, like ClimateControl, the biome does not use the usual spawning rules where there even *are* weights. It instead gets one "climate slot", ie when the vanilla code decides to try and place a whole-climate-zone biome (in vanilla this means mesa, mega taiga, jungle, etc) instead of subdividing into the more common biomes, it can instead roll pink forest.

This system picks a random value out of 16 and each mod gets some number of those "slots"; SF already only gets one.
