### ISSUE TITLE
DSU label from SimpleLabels mods does not display the icon

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3234]
When you attach a label to a DSU it's supposed to automatically display icon based on what's inside. Does not work with any items that I've tried from Rotarycraft, Chromaticraft, Electricraft and Reactorcraft, _except_ ores - pitchblende ore and whatever Electricraft ores seem to be displayed fine.

DSU in the screenshot is storing RC's compost.

![2023-07-08_20 44 25](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/5149ba6f-98e8-4a4f-991b-c270c2c70463)

**Comment by ReikaKalseki** [comment]
This is the same root cause as the botania "crafter" (petal apothecary, runic altar, etc), agricraft book, and a few other things not rendering the item properly. My items use a custom Forge `IItemRenderer` and a mod that naively assumes the item has no special rendering and just and blindly fetches the `IIcon` and draws that will not work properly. They need to render the item properly.
