### ISSUE TITLE
Pylons are unreliable in whether they connect to repeaters or not

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#345]
hi,
Using cc v9b I noticed it seems to be pretty random whether a pylon connects to a repeater or not. Usually reloading the world, as in going back to the main menu and loading it again fix the issue.
One example:
http://imgur.com/mMa9IIh
After reloading it worked just fine.

**Comment by lossycrypt** [comment]
I talked to some guy on irc who mentioned he had a similar issue (having to leave+rejoin a world) with pylon connectivity. He also mentioned he uses Java8 like Turmfalke does.

**Comment by globsb** [comment]
I have the same issue. Repeaters was randomly disconnecting even in the middle of longer crafting (multiple power crystals) when i was standing in front of the table. After few crafts when casting table was making sound of finished crafting and trying to draw power for next one it was crashing because of  broken connection at some point of repeaters line. Even though i saw multiple comments that chunkloading doesnt help i tried and it worked. Loading all the chunks which beams are crossing from pylon to table solved this issue. However its still disconnecting entire network after teleporting through dimensions which cant be reconnected in any way but relogging. Version of java doesnt matter its the same on 7 and 8.

**Comment by ReikaKalseki** [comment]
I have never had any issues like this, where the connectivity fails _during_ the game and where there was not an obvious cause (tree growth in the beam, pylon empty, etc).

**Comment by globsb** [comment]
Ok i have no idea whats the problem. I tried with only few mods installed and couldnt replicate the issue with disconnect after teleport through dimensions. After i tried on new world with all mods installed and they still didnt disconnect. Logged to my normal world tped to the nether and back... bam error sound. Its not even mod interaction which i thought would be the case.

**Comment by globsb** [comment]
Finally got it. Pylons are disconnecting only when chunkloaded. Teleporting with chunkloader which is loading both pylon and repeater brakes the connection. Braking chunkloader and going to dimension and back reconnects them again. Tested with forge 1448, 1387 and 1291 and both immibis dimensional anchors and chicken chunks.

**Comment by ReikaKalseki** [comment]
Dimensionwide network clearing only happens if the dimension is unloaded. That event is not fired if forced - chunkloaded - chunks remain:

```
 if(loadedChunks.size() == 0 && ForgeChunkManager.getPersistentChunksFor(this.worldObj).size() == 0 && !DimensionManager.shouldLoadSpawn(this.worldObj.provider.dimensionId)){
     DimensionManager.unloadWorld(this.worldObj.provider.dimensionId);
     return currentChunkProvider.unloadQueuedChunks();
 }
```

That is Forge code, not mine. Try Forge 1558 and see if the issue still occurs.

**Comment by Saereth** [comment]
We had this issue about 4 months ago, worse for us though at it would corrupt the crystal network making the server unbootable after the next restart.

**Comment by globsb** [comment]
Problem is still there. With newest version of CC and recommended forge pylons are still disconnecting and minecraft is still crashing during longer crafts like i described previously. The question is why its not happening to you for example as i tested it on vanilla + your mods and chunkloader only so its not mod interaction problem. This mod is one of my favourites and this issue is bugging me to much as it is impossible to build reliable system without checking every now and then if its still connected or not.

**Comment by TomeWyrm** [comment]
Because it flat-out doesn't happen for us. It shouldn't happen according to code. It appears to be a bug that is in some way tied to your particular setup.
