### ISSUE TITLE
Chromaticraft 9b GUI enhancement

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#349]
Any chance I could get a setting to allow things like the Manipulator color wheel to be rendered twice as big as it is now?

 I watched Reika's base tour and noticed how much larger the color wheel was in his video versus mine and I figured out why. My monitor is 27" and 1440p, which means I run with my GUI scale set to Large.  Changing the GUI over to AUTO rendered the color wheel big enough to be clear, but makes everything else huge and a distracting annoyance. Having some sort of scale setting to make at least the color wheel larger would be a huge help.

**Comment by lossycrypt** [comment]
Are you talking about the "personal charge" indicator in the upper ~~right~~ left or the smaller one without runes that shows the charge of machines you point at? The latter one will have a "sneak to x2 zoom" option in v10.

Edit: Yes. Left. Meh.

**Comment by 1skandar** [comment]
Upper left for me, the one you get when you're h9olding the elemental manipulator.

**Comment by ReikaKalseki** [comment]
I am very hesitant to add configs for things that are entirely dependent on graphics settings, as they are essentially fixed by the pack maker (you likely realize as well as I do that most users are unaware configs are even a thing, much less how to change them or what they do) and as such are just as likely to be detrimental as beneficial. Something checking monitor resolution and/or GUI scale (the latter of which I know I can access) would be better.

**Comment by 1skandar** [comment]
Ah, true enough. and yes, GUI scale would be fine, I think. Doubling resolution at all GUI scales except auto would probably do it just fine.

**Comment by lossycrypt** [comment]
I certainly do not want to have the already huge wheel doubled in size. I playing on "Large" gui on a 24"@WUXGA display specifically because "auto" is too big for my taste (and presumably for yours too, or else you woulnd't have asked.) Doubling the "large" size would make it bigger than auto. 
The real problem here is that minecraft bases the "small/normal/large" size on a fixed scaling value whereas auto is based off current resolution. So the larger the resolution of your game window the smaller "large" becomes. (This is basically the same 4K issue that's happening to all software right now that does pixel-count based instead of dpi-based rendering,)
As a workaround or to see for yourself you can use Optifine to play in a fullscreen with less than maximum resolution and get bigger guis again.
Here's how the 4 scales look on my screen with thaumcraft's gui layed over for reference:
Small|Normal
Large|Large(x2 scaled)
![plxno](https://cloud.githubusercontent.com/assets/14168854/10621754/f8f14f6c-7782-11e5-8385-35705e5280d5.jpg)

**Comment by 1skandar** [comment]
Yeah, see, that is my problem, on my screen what you call small is just slightly smaller than my large, which is pretty much a general problem with the GUI settings. Auto is obnoxiously large, but even large ends up being a bit too small.
![2015-10-15_08 21 01](https://cloud.githubusercontent.com/assets/4127779/10622231/0c202312-7754-11e5-8bea-f1e6a24e7254.png)

**Comment by 1skandar** [comment]
By comparison, this is my auto, which is roughly analogous to your large setting. This would be fine if the rest of the gui wasn't quite so obnoxious (not my inventory bar versus yours)
![2015-10-20_18 04 56](https://cloud.githubusercontent.com/assets/4127779/10622480/e7dd29da-7755-11e5-9392-7d05b6a73ce4.png)

**Comment by ReikaKalseki** [comment]
I do not see a good way to implement this. Though I can get both GUI scale and screen resolution, I doubt there is any value usable as a cutoff that will not trigger complaints.

**Comment by 1skandar** [comment]
Maybe an in game key that would switch it?

**Comment by ReikaKalseki** [comment]
That I can certainly do. Since LSHIFT does the same to the mouseover wheel, that key is a natural choice.

Done.
