### ISSUE TITLE
Can't produce Aluminum Alloy Ingots

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#357]
My NEI recipe says 900 degrees, 1-9 Aluminum Ingots, Silicon Powder. Does not work. I am adding two screenshots, one for recipe and one for actual Blast Furnace. Is it possible the recipe has changed but NEI was not updated? 

I am using RotaryCraft 1.7.10 V9b, DragonAPI 1.7.10 V9b 

http://postimg.org/gallery/2h708271s/1ecdaeb3/

Edit: Ingots in the screenshot are actual RotaryCraft Aluminum ingots, not some other kind of Aluminum from other mods.

Edit 2: I did try to look for it in the ingame manual book, wasn't able to find anything about aluminum.

**Comment by ljfa-ag** [comment]
Well it's a bit confusing since Rotarycraft actually has two different kinds of aluminum ingots: The ones that come from aluminum ore, and the ones as byproduct from redstone ore.
Make sure that the ingots you use are of the latter kind, i.e. ones you get from smelting aluminum dust. I think those have a slightly darker outline.

To make the matters even worse, the latter kind of aluminum is oredicted and can be used in other recipes, e.g. to make aluminum blocks. However if you do this there seems to be no way to get the latter kind of ingots back.

Maybe this should be changed so as to avoid this confusion.

**Comment by notchriss** [comment]
Thanks Ijfa-ag, that was the problem. I've tried with ingots from byproduct aluminum, and it worked fine.  It is confusing indeed, to put it mildly :)

**Comment by ReikaKalseki** [comment]
I made the other kind of aluminum usable as well. I kind of liked the Extractor gating, but requiring Silk Touch is a bit much.
