### ISSUE TITLE
Crash after clicking fluid compression champer with angular transducer

### ISSUE THREAD

**Issue by valveo** [ReikaKalseki/Reika_Mods_Issues#39]
Clicking chamber with angular transducer crashed game few times. Then I gave up to trying it.
Same crash every time.
Using latest version of dragonapi and rotarycraft (v6f)
Crash log and fml log: https://gist.github.com/valveo/a3c4667b8bc778e942ab

**Comment by zemerick** [comment]
I have reproduced this on my current test build. It isn't minimized yet, so I won't bother with the log until I verify on just RoC.

I did notice it only happened when there was fluid in it, and it did not need to be powered or even connected to anything else. ( Simply placing the empty block from creative on dirt, then clicking with AT did nothing, but repeating the same with a tritium filled chamber caused immediate crash as above. )

**Comment by zemerick** [comment]
Confirmed on minimal build ( DragonAPI and RoC ), Forge 1291 and 1373.

http://pastebin.com/AVfd9rbc

**Comment by zemerick** [comment]
I think I found it:

Line 153 of the Angular Transducer:
```
ReikaChatHelper.writeString(String.format("%s contains %.3fB of %s of a capacity of %.3fB.", m.getName(), clicked.getLevel()/1000D, clicked.getFluid().getLocalizedName(), clicked.getCapacity()));
```

Line 42 of the fluid compressor:

```
public int getCapacity(Fluid f) {
```

It's expecting some fluid to be passed in. If it's empty, it returns before the fluid is used, but if it makes it to line 47:

```
int factor = f.isGaseous() ? 8 : 1;
```

It doesn't have a fluid passed to f, so it just looks at it as a character, which is not an int and crashes.

**Comment by ljfa-ag** [comment]
https://github.com/ReikaKalseki/RotaryCraft/blob/master/Items/Tools/ItemMeter.java#L153 :
I think it's just that the return value of "clicked.getCapacity()" is an integer and not a float as expected by the %f format.
I suspect the value is supposed to be divided by 1000D to display it in buckets rather than millibuckets.

**Comment by zemerick** [comment]
It appears to be the converter from Integer to Float that is failing.

Not sure about Java, but you can usually put an integer into the place of a float, as that conversion is quite trivial.

A bit earlier in the error, you see it's dealing with a string, and the actual error is "f != java.lang.Integer" hence my thinking that it is seeing the f and expecting an int, but instead using the actual string character f instead of the variable f ( which was not set due to not passing the fluid as an argument. )

I could still absolutely be wrong though. There's a reason I'm not a programmer:) That's just how I see it so far.

**Comment by valveo** [comment]
My setup is get oxygen from extractor and put in fluid compression champer with enderio fluid pipe.
I don't know if this is important or not, but still better tell.

**Comment by ReikaKalseki** [comment]
Fixed. It was indeed a float/int string formatting error.
