### ISSUE TITLE
Request: "Technical" means of shaft power transfer between dimensions

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#392]
I'm trying to find a "technical" way to allow shaft power to be transported between RFTools dimensions.  Because it needs to be technical, Mystcraft is out, and Chromaticraft is out, partially because it's also magic, and partially because I can't afford heavy worldgen for the modpack, as the custom ore generation mod takes the lion's share of worldgen time.   Neither RFTools nor Enhanced Portals seem to support transfer of shaft power between dimensions.

I'm wondering if you could add a technical variation on the world rift, or perhaps making some form of shaft power compatibility with RFTools or Enhanced portals.

**Comment by ReikaKalseki** [comment]
I can add handling for the other two portal types, but I will need to know exactly how they work.

**Comment by ghost** [comment]
Well, here are the Githubs for [RFTools](https://github.com/McJty/RFTools) and [Enhanced Portals](https://github.com/enhancedportals/enhancedportals).  Enhanced portals actually provides a portal; if I'm not mistaken, RFTools provides a teleporter, so I don't know if you can provide the support for that mod.  The point for RFTools is that it, like Mystcraft, can create custom dimensions (which need to be powered to remain stable).

I hope this helps.

**Comment by redelman** [comment]
The only feasible way I see of transfering power to an RFTools dimension is to convert it to RF and send it through a tesseract, then convert back. Or (still converting it to RF and then back), use the RFTools Energy Extractor inside the RFTools dimension. That has some severe limits on how much energy you can extract at once though. You may very well need multiple energy extractors.

**Comment by ghost** [comment]
All the same, I'd like to avoid the massive power loss that conversion to and from RF would cause.

**Comment by ReikaKalseki** [comment]
There is not normally a loss when converting to RF, and with v10(?) the efficiency upgrades for the magnetostatic will reduce the loss substantially.

**Comment by ghost** [comment]
Okay, so it can work as a workaround (especially at ReactorCraft levels, which was what the original issue was regarding), but I'm still hoping that a non-conversion-based solution is in the cards.

The point to Survival Industry is to treat shaft power like other packs treat RF: the central mechanic, not just something on the side.

**Comment by TomeWyrm** [comment]
You could have RFTools detection/integration that makes a Dimensional Shaft which you can uniquely link and use Dimensional Shards in the crafting of. I would suggest creating the shafts in linked pairs with linkage specified in NBT and stacking disallowed with mismatched NBT (assuming that's not vanilla behavior). That way you don't get the possibility of odd bugs with unlinked/mislinked/triple-linked shafts.

The Enhanced Portals integration I have no ideas on. I've never been able to tolerate the mod.

**Comment by redelman** [comment]
I personally like the idea of a 'dimensional shaft' that's somehow in a linked pair. However, I think it should follow the RFTools design and need a dialer of some type to make the connection, and take RF to keep it open. Perhaps higher amounts of RF depending on the amount of power being transferred between shafts?

Shaft recipes could be 4 (or 8?) dimension shards around a bedrock shaft to get the 'dimensional shaft', and then put that in a mount of some kind. Standard mounts wouldn't necessarily work, would they? Maybe a mount surrounded by dimesional shards or ender pearls, or both? 

The nice thing about using the dialer concept is that you could make new connections to transfer shaft power around, however that could possibly be abused when combined with flywheels.

Perhaps @McJty has some ideas here.

**Comment by TomeWyrm** [comment]
Hence the unique-link-at-craft pair. It prevents nearly all exploits and bugs. If you need to move the power somewhere else, you need another pair of shafts, or to move one of the current ones. Which is pretty much how it works right now. It also makes a lot of sense. The angular transducer could even tell you the dimID and coordinates of the "mate".

**Comment by redelman** [comment]
Okay, but it should still take RF to keep the connection between the pairs
open and somehow transmitting the shaft power. It's RFTools after all, not
quantum entanglement. ;)

**Comment by ghost** [comment]
Actually, I like the idea of a dimension-agnostic "quantum-entangled shaft" that can be used with any mod... That way, they can be used in the Nether, End, Aether, Twilight Forest, RFTools Dimensions, Mystcraft Ages, bedrock dimension, Dark Millennium, etc, bypassing the need for explicit mod compatibility... thereby returning to the original request I made... a RoC-specific equivalent to the CC "world rift" for RotaryCraft shaft power transport.

As a side note, I would not recommend making the shaft chunkloaded; if we want to chunkload its endpoints, we'll just have to build two RoC chunkloaders and see to it that they're running on both sides. ;)

On another side note: yes, I know quantum entanglement doesn't work that way. :P

**Comment by TomeWyrm** [comment]
Solves basically all the problems with dimensional transport in one fell swoop, which is neat. You could even add alternate/disableable recipes involving core dimensional components. Like Dimensional Shards from RFTools, linking panels from Mystcraft, whatever EP3 uses, chromaticraft stuff, and finally a "just RoC" option (aka "vanilla"). Much like MachineMuses' Modular Powersuits or Minefactory Reloaded have "difficulty" levels for their recipes

**Comment by redelman** [comment]
Now Reika just needs to implement it. ;)

**Comment by ghost** [comment]
Which means that the ball is in Reika's court. ;)

**Comment by ReikaKalseki** [comment]
I have no desire to implement a special machine type exclusively for this purpose, but the idea of a "linked shaft" would have to in-universe look like it was on RFTools' end, not mine. A quantum-entagled shaft is antithetical to the "real-world engineering" design of RotaryCraft.

**Comment by TomeWyrm** [comment]
Hmm, is there a way to implement a "workaround" block for something like the tesseract/dimensional anchor? Functionally in code it would be the same "linked block" idea, but to the player it functions as an addon to the dimensional transport of (currently limited, but easily expandable) choice? Make it a "trans-dimensional shaft interface", as long as you simply assume the magic is a black-box component, real-world engineering still works fine. Nearly all magic systems in video games follow Clarke's Third Law and the "Magic A is Magic A" trope, which means while you may not understand some of the "W" interrogatives (like who, why, or how); the only one you properly need to understand when engineering is the "what", and I guess when/where. So long as consistent input gives consistent output, you can engineer around your lack of understanding (at the obvious risk of potential failure from unknown factors).

Is that idea a bit more of a palatable balance between mod design, player capability/choice, and reasonable realism?

**Comment by ReikaKalseki** [comment]
No. As far as RC is concerned, magic does not exist in any form.

**Comment by TomeWyrm** [comment]
Then how does the current portal mechanic work? I mean it's rather explicitly a magic portal to another realm. Might give us some thematic ideas to work a more mod-agnostic transdimensional shaft idea into being.

**Comment by ghost** [comment]
Hmmm... I doubt that a quantum-entangled shaft (or perhaps an Einstein-Rosen Bridge) is any less plausible than a freeze ray or a general-purpose containment/repulsor field (or a chunkloader, which has no real-world functional equivalent), but it's your mod.

And TomeWyrm, I think what Reika's getting at is that he intends his interacting mechanic to be "blamed" on the physics distortions provided by the other mod's rules, rather than incorporating those rules into RotaryCraft.

**Comment by ReikaKalseki** [comment]
> Then how does the current portal mechanic work? I mean it's rather explicitly a magic portal to another realm.

Because in-universe, RC is not addressing the magical side, merely sticking a shaft into what is to it an empty space.

**Comment by TomeWyrm** [comment]
Yeah, I got that impression Reteo.

That's why I'm trying to think of a good method for transdimensionalism that fits appropriately into RoC's design philosophy. I can tell you right now that we don't have the power generation for an Einstein-Rosen bridge (fancy name for wormhole, in case anyone reading this is lost), not even by a few orders of magnitude. You're talking "lifetime output of star" ranges more than "planetary" levels. The tokamak is capable of running, what, a US state or two by itself? I am not an electrical engineer, most of those scale ideas were blind guesses; this is the internet if I'm wrong, it'll be corrected :-)

Hmm. Why not use an ignitor surrounded by obsidian and ender pearls (or eyes of ender) to make shafts with built-in portals, or "sub block" portals that you can run shafts into? You're not doing much more than vanilla already does, except miniturizing and that process having the side-effect of also dimensionally unlocking the portal pair could easily be implied by the materials you decide to use (end stone and obsidian maybe?)

From RoC's perspective it's still plugging into an empty hole. You're just providing a more capable extension of existing vanilla "tech".

We could also poke @McJty and @enhancedportals and see if they'd be willing to help implement RoC shaft transmission devices/methods from their mods perspectives.

**Comment by ghost** [comment]
Let's wait and see what Reika intends to actually do first.  He said he wasn't going to make an independent method of cross-dimension power transfer, he did not say he wouldn't provide compatibility for the mods originally mentioned above.

And since this ticket is still open, I'm pretty sure he's working on something.

**Comment by TomeWyrm** [comment]
I didn't say "implement", I said "help implement".

Integration doesn't always have to be one-sided :-)

**Comment by McJty** [comment]
I'm a bit busy and I haven't been 100% following this discussion here but what would be needed for this to work exactly?

**Comment by ReikaKalseki** [comment]
> I'm a bit busy and I haven't been 100% following this discussion here but what would be needed for this to work exactly?

Well, for one, I would need to know how RFTools works, particularly regarding dimensional linking and connectivity. This is from both an ingame ("universe") and basic-code standpoint.

Depending on the desired means of connectivity, I might also need an API of sorts to call "What dimension/location does this connect to" logic.

> Hmm. Why not use an ignitor surrounded by obsidian and ender pearls (or eyes of ender) to make shafts with built-in portals,

This idea is viable thematically, but not all mods have portals, much less ones with frames.

**Comment by TomeWyrm** [comment]
I meant for a base mechanic to "enhance" the current capability. Then it would be mod-agnostic. Tesseracts and world rifts don't care if it's a mystcraft or RFTools dimension, after all :-)

**Comment by ReikaKalseki** [comment]
Those methods also explicitly supply the magic interdimensionality.

**Comment by ghost** [comment]
I see, so you piggyback off the dimensional logic of the mod providing the portal/teleporter/what-have-you?

**Comment by McJty** [comment]
Linking different dimensions in RFTools works with a teleportation system that is actually an independent part inside RFTools (you can just as well use that teleportation system to go to the nether or inside the same dimension). Basically it is a system where you have matter receivers and transmitters. To have a working two-directional portal you need two receivers and transmitters. You also need a dialing device to dial both transmitters to each receiver. The portals do _not_ have frames. Instead you get a vertical beam that the player has to step in. Here is a screenshot of a dialer and a transmitter that has been dialed:

https://pbs.twimg.com/media/CEPkPIZWAAAMznp.png

Perhaps it makes more sense to try to connect directly to the matter transmitter block (the block below the beam) and the receiver block instead of interacting with the beam. Just a suggestion. There is currently no API to get the location that a transmitter is dialed too but that would not be hard to add.

Whether or not this makes sense in the context of RotaryCraft I cannot decide. One problem may be that the RFTools teleportation system also works inside the same dimension so it could essentially be a cheap way to circumvent shafts and similar. To work around that one could also allow this only when the dialer and receiver are set to different dimensions. Or you could introduce some kind of loss in power

**Comment by ReikaKalseki** [comment]
> I see, so you piggyback off the dimensional logic of the mod providing the portal/teleporter/what-have-you?

At least outwardly, yes.

@McJty 
If these work as one-way links, like world rifts, you might be able to piggyback onto the World Rift handling. CC's API has a "WorldRift" interface; if you make that TileEntity implement it and return the same thing as world rifts do (ie other end of the link, opposite ForgeDirection side), it might be handled automatically.

**Comment by ghost** [comment]
As an update to this question: Does RotaryCraft interact with the EnderIO Dimensional Transciever?

**Comment by ReikaKalseki** [comment]
No.
