### ISSUE TITLE
Void Cell can not be preformatted.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#398]
Void Cells can not be formated for a specific item type using the Cell Workbench. Also if they are in an me chest (not tested with me drive), you put something in them, and then take all items out again, then they will not accept any items at all until taken out of the chest and put in again.

**Comment by ReikaKalseki** [comment]
Formatability is handled by AE, not me. All cell behavior is automatic and on AE's end, aside from raw storage amount.

**Comment by lossycrypt** [comment]
[Yueh sais your implementation is wrong.](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2005#issuecomment-156869038)
"Complain to Reika for not implementing the cell correctly and persisting its partition."

**Comment by Builderb0y** [comment]
Methods related to preformatting: (copy-pasted from [extra cells's block-placing cell](https://github.com/ExtraCells/ExtraCells2/blob/rv2/src/main/scala/extracells/item/ItemStoragePhysical.java), because it also stores only one item type.)

``` java
@Override
public FuzzyMode getFuzzyMode(ItemStack is) {
    if (!is.hasTagCompound())
        is.setTagCompound(new NBTTagCompound());
    return FuzzyMode.values()[is.getTagCompound().getInteger("fuzzyMode")];
}

@Override
public void setFuzzyMode(ItemStack is, FuzzyMode fzMode) {
    if (!is.hasTagCompound())
        is.setTagCompound(new NBTTagCompound());
    is.getTagCompound().setInteger("fuzzyMode", fzMode.ordinal());
}

@Override
public IInventory getUpgradesInventory(ItemStack is) {
    return new ECCellInventory(is, "upgrades", 2, 1);
}

@Override
public IInventory getConfigInventory(ItemStack is) {
    return new ECCellInventory(is, "config", 63, 1);
}
```

getFuzzyMode() is the readFromNBT method that fetches the specific-ness of metadatas configured to the cell (the button in the GUI that cycles between "match all" and "split at X percent").
setFuzzyMode() is the writeToNBT method that writes that mode to NBT.
getUpgradesInventory() is the readFromNBT method that returns all cards inserted in the cell, invert and fuzzy are the only 2 cards that I know of that can be inserted into cells.
getConfigInventory() is the readFromNBT method that returns all the items configured to the cell via the cell workbench.

Additionally, setUpgradesInventory() and setConfigInventory() do not exist on the item class, they are hard-coded by the cell workbench.
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/tile/misc/TileCellWorkbench.java#L106

**Comment by ReikaKalseki** [comment]
Done. I still nulled out the upgrades and fuzzy mode, but now it can be preformatted.
