### ISSUE TITLE
Crystal Tank size behaves wrongly.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#416]
1) Crystal Tank GUI, Waila tooltips and In-World-Render cap at 2 Million while the content caps at 1 Million. So a Tank of "2M" capacity never looks more than half full.
2) The tank capacity formula given as "4*(n^2)" is not how the tank behaves. 1M capacity is reached at 262 blocks and "2M" at 320 blocks. [Though i have to admit that i find the current tank size scaling a lot more favourable than the intended one.]

```
4*(262^2) = 274,576
4*(320^2) = 409,600
4*(500^2) = 1,000,000
```

![2015-11-22_10 37 19](https://cloud.githubusercontent.com/assets/14168854/11323030/0c8054d2-9106-11e5-855a-945a1340aa19.jpg)

**Comment by TomeWyrm** [comment]
The formula is being parsed logically, just not following the order of operations.
262*4=1048
1048^2=1,098,304

The display thing is totally odd though

**Comment by ReikaKalseki** [comment]
The hard limits you are seeing are due to Int.MAX (2.147 billion). Remember that one bucket is 1000 millibuckets - the actual stored value - and I cut that in half again to "be safe".

I am a bit concerned that fixing this may void large (>100000 buckets) quantities of fluid for many players, myself included.

Also, there are other terms in the actual formula omitted from the GUI for space and complexity reasons:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/TileEntityCrystalTank.java#L186

**Comment by lossycrypt** [comment]
@Tome: I beg to differ that "not following the order of operations"  is certainly not "parsing logically". I actually tried that order thought, but it "felt" too inaccurate. Further testing suggests it's actually only about 10% off. On that point maybe Reika could change the description to "(4n)^2"? 

@Reika: Well, the easiest "fix" seems to just increase the maxium tank volume to 2M. That way both the GUI and rendering should be (mostly) fixed, nobody gets their fluids voided and honestly i don't think doubling is much of an issue at this scale.

**Comment by TomeWyrm** [comment]
It's logical. It has clear reasoning, it's consistent. It's just wrong. Microsoft's inbuilt calculator parses much the same way (it's what made me think of how to get the much closer number).

Instead of following PEMDAS (which is actually misleading anyway, but a subject for another time and place, with a mathematician to explain the underlying concepts behind the shortcuts you think of as operations) it most likely evaluated left-to-right. Which is honestly how computers do math unless you're careful telling 'em not to.

I would fix the formula display to (4n)^2.

Could you not also store large chunks of fluid, programmatically, as a smaller absolute value which represents larger divisions that can be converted to the smaller ones? Sorry, that was a very convoluted sentence – I meant, basically, storing something in a higher unit. Kilograms instead of grams, buckets instead of milibuckets, or even kilobuckets instead of milibuckets.

But yeah, the best fix would probably be doubling the current limit.

**Comment by ReikaKalseki** [comment]
> Could you not also store large chunks of fluid, programmatically, as a smaller absolute value which represents larger divisions that can be converted to the smaller ones? Sorry, that was a very convoluted sentence – I meant, basically, storing something in a higher unit. Kilograms instead of grams, buckets instead of milibuckets, or even kilobuckets instead of milibuckets.

No, because it needs mB-level precision. Requests often are made for amounts less than 50 mB, and 200 of those still need to subtract 10 buckets.

**Comment by TomeWyrm** [comment]
I don't think I explained myself fully.

I meant a secondary (non-exposed) tank. So let's say the USER sees a 2 million bucket tank. You've got a small-ish tank of say 100,000 mb which is what is exposed to the game, and an "internal" tank which takes 1000mb chunks out of the small-ish exposed tank when it hits a threshold, and returns them when it hits another threshold.

This secondary tank ONLY deals in full-unit buckets, which means it can store capacities 1000 times as high as the mb-precision tank. BUT the tank exposed to the game world, the one that pipes and such draw from? Still deals in mB.

You don't even need to have a "tank". You could store it as whatever value type you wanted, you could store it as items, or energy, or another type of liquid, in a hidden tank, or as a non-standard variable that the rest of MC won't be able to inappropriately access. But it "compresses" the fluid into chunks that you can convert INSIDE the tank so as to store more without hitting the INTMax limit.

**Comment by ReikaKalseki** [comment]
At that point you might as well just use a custom tank implementation that could handle longs.

**Comment by ReikaKalseki** [comment]
Fixed...I hope.
