### ISSUE TITLE
ReactorCraft fission Fuel Cores don't cool down when empty

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#42]
I made a small (four core) reactor to produce tritium today, and despite having two sides open to the air one of the cores decided to heat up to over 1000 degrees, even though the other cores were hovering around 300 degrees. I took out the fuel pellets until I fixed the issue, but the core temperature stopped updating and stayed static at 1027 degrees. Is this intentional? Since I assume it's possible to cool empty cores through heat exchangers, I can't see any reason why it would be unbalanced to not allow cores to air cool, as the heat isn't being converted to power.

**Comment by zemerick** [comment]
Could use some more details, and a pic would be great.

I did a quick test just now with 4 cores, using plutonium, surrounded by reflectors. At around 250 C, I pulled the fuel and they started cooling down fine. They've all stabilized at ambient temp.

BTW: It's common for 1 core to temporarily spike in temperature due to the random nature of the fission and neutrons. Cooling demands need to take large spikes into account.

**Comment by umbralOptimatum** [comment]
I restarted the client and it started cooling down properly, so it clearly isn't a constant issue. My setup is below.
![2015-04-23_22 28 38](https://cloud.githubusercontent.com/assets/12092270/7311277/2fc607f2-ea08-11e4-83fd-4c7d7c781b93.png)

**Comment by zemerick** [comment]
Well...FYI...that design, if you use Uranium...not stable:) In fact, I think even Thorium might not be.

I tried to see if it was related to going over 1000 C...and my test world now has a new radioactive crater, lol

I also count 12 cores, not 4 there, and you are letting neutrons out of the cores that have the piping on top as there are no reflectors or steel blocks. ( BTW: Bedrock Ingot blocks are better than steel. Recent addition, with 97.5% absorption instead of 90% which the steel has. )

Anyways, needless to say I'm still having trouble replicating this at all.

What fuel did you use?
Were you on a multiplayer server, or single player?

If there's anything else you can think of, or if you manage to replicate it as well, please let us know.

**Comment by umbralOptimatum** [comment]
Eight of what you're counting as cores are actually the neutron irradiation chambers, hence the fluiducts. (Also, would it still be unstable even with only four cores?) I'm on SSP and was using uranium.

**Comment by zemerick** [comment]
Ok, that makes a lot more sense. I was wondering where the NICs you mentioned were:)

I think the big reason your design wasn't stable was the reflectors. I did not use them, so they would increase the output. Without reflectors, the cores mostly sit under 100C, and with spikes only go to like 150C.

I recommend going ahead and doing 2 NICs btw, as 1 will let I think 25% of the neutrons through it still, and 2 would make the reflectors have a far lower effect on the cores as long as you have D in the NICs. ( This could be a big part of your problem. If they ran out of D after you stopped watching, they let more neutrons hit the cores. This heats things up a lot. )

Perhaps it's related to the NICs working, so I'll try to get that up and running in my test and see what happens.

**Comment by umbralOptimatum** [comment]
Alright, I'll try with two NICs per side. I should also mention though that this reactor is right above bedrock so the default temperature for the cores is 87 degrees - I imagine this would work much better in a colder location.

**Comment by ReikaKalseki** [comment]
They should cool when empty, and this is my experience as well. The thermal code is independent of the nuclear reactions.

**Comment by zemerick** [comment]
Unfortunately I have been completely un-able to replicate this.

Please let us know if you think of anything else, but for the time being I have nothing I can think to try.

**Comment by umbralOptimatum** [comment]
Yeah, since it fixed itself when I restarted the client I'm guessing it was a one-time-only thing. Ah well, thanks for all the help anyways!
