### ISSUE TITLE
Crash in RotaryCraft when looking up recipe for Storage Drawers in NEI

### ISSUE THREAD

**Issue by duckblaster** [ReikaKalseki/Reika_Mods_Issues#429]
Single player client crash every time I try to look up the recipe for the 2x2 oak drawer.
https://gist.github.com/duckblaster/317ea45c42657213fb5a

**Comment by TomeWyrm** [comment]
Dollars to donuts your issue is Forge 10.13.4.1566. The crash references the fluid registry. Try downgrading your forge version. You're using newer then the current recommended, and more importantly you're using newer than the recommended when the mod versions you have access to were last worked on. I can't recall which forge version the v9 series was built on, but I'm betting it's somewhere in the 1400's.

I've added v9 of RoC, CrC, ReC, DAPI, EC, and ER to Regrowth using Forge 10.13.4.1448. I'll see if the bug is present there.

**Comment by TomeWyrm** [comment]
No crash here.

**Comment by ReikaKalseki** [comment]
Repeated duplicate.
