### ISSUE TITLE
[ReactorCraft] HazMat Suit Bug

### ISSUE THREAD

**Issue by darqen27** [ReikaKalseki/Reika_Mods_Issues#432]
The ReactorCraft HazMat Suit doesn't prevent radiation poisoning from its own mod

I tested the IC2 hazmat suit as well with no effect other then the radiation destroys it

TPPI2 ModPack

V9b

**Comment by TomeWyrm** [comment]
The ReC suit, or the IC2 suit? Also ReC radiation or IC2 radiation?

**Comment by ReikaKalseki** [comment]
Also, the ReC suit does not protect against meltdown-level radiation.

**Comment by darqen27** [comment]
This was not meltdown level radiation. It was just around the reactors(which are extremely shielded)

**Comment by TomeWyrm** [comment]
Neutron collisions don't cause radiation poisoning, from what I can remember. But I know the hazmat suit will protect from radiation poisoning caused by holding radioactive items (from ReactorCraft obviously).

Which means, to me, that your reactor has irradiated the area. I don't know the specifics, but I'm betting it's still not a bug

**Comment by darqen27** [comment]
everything is shielded, thier should not be pockets of radiation, but they pop up in random spots that inline should be overshielded(6+ blocks thick concrete and lead)

**Comment by TomeWyrm** [comment]
Yeah, that's just a side effect of how the radiation is coded. There's no way to not kill your computer and do radiation realistically. So the reactor cores occasionally irradiate things in a small radius. Someone more familiar with the code and myself would have to explain it better

**Comment by darqen27** [comment]
The permanant radiation poisoning is pretty dumb at this point, can it be disabled.

The mod is not even usable in most of its state on a public server with how radiation just blasts everything unrealistically

**Comment by TomeWyrm** [comment]
Actually it is quite usable on a public server. It's just not a hand-holding kind of mod. If you do something wrong, the mod will punish you for it.

There are methods to get rid of radiation entities in the world, to reclaim areas you accidentally irradiate. I wouldn't try them on a reactor meltdown, but for "oops, my reactor irradiated the area" it should be fine, if a bit tedious or time-consuming.

Also the radiation is neither permanent, nor does it "blast everything". You can die to remove the radiation poisoning, or drink milk. Just don't have any radioactive materials in your inventory, and don't hang out in irradiated areas.

**Comment by darqen27** [comment]
Drinking milk does not work in TPPI2 modpack, nothing cures it

Nothing works to mitigate it, I stop the neutrons from coming out everywhere but still get random radiation

There is NO reason for the radiation to be effecting these areas, Still consider this a bug as it causes major slowdowns in server ticks when the radiation effects mobs in the area plus all the entitys it adds

**Comment by darqen27** [comment]
My apoliges, I was misinformed, I thought reika was included with tppi2

I will see if we can solve this ourselves with some tweaking

**Comment by TomeWyrm** [comment]
Honestly, I build my reactors in void worlds. You can fix basically every single problem with "it's in another dimension which is also a void"

**Comment by ReikaKalseki** [comment]
@darqen27 
I am getting very tired of your spam tactics, opening multiple issues, renaming issues to get more attention (including putting "Not closed" to try to trick me) or generally aggressive tone ("doesn't prevent radiation poisoning from its own mod", "The permanant radiation poisoning is pretty dumb", "The mod is not even usable in most of its state on a public server", etc).

Again, your issue is either spurious - you are seeing something that is not there, or are misunderstanding the cause - or intentional behavior you have mistaken for a bug.

Neutrons leak from all but the most well-shielded reactors. As of v9, these can spawn radiation. Solution? Better shielding. And no, 6 layers of concrete is not very good.

_That said_, the minor radiation from neutron leakage, though it currently is classified as meltdown-type - and thus unshieldable - probably _should_ be shielded against. But do not go saying "See, it was a bug!" No, it is intentional behavior that I have decided to revise.

However, this is a substantial codebase change; radiation entities, such as those from meltdown, waste being left on the ground, and neutron leakage, are not currently shieldable. Other "pulse" effects, or some auxiliaries like holding Plutonium, are. Now I have to change the radiation system to handle the entities in both directions as well.

**Comment by TomeWyrm** [comment]
Even the bedrock alloy block at 99.6 would let a neutron through on average once every 250 events. Now with 6 layers that chance reduces to 1 in 244,140,625,000,000.

On the other hand? Concrete is 75% I think? So 1 in 4096 at 6 layers… waaaaay more common

**Comment by ReikaKalseki** [comment]
Done. Ambient radiation now has an "intensity" parameter. This controls, among other things, whether it can be shielded, its effects on the world, and the damage it does to players. Moderate-level (plutonium, irradiated creepers) no longer does as much world damage nor bypasses the suit; high-level (waste) no longer bypasses the suit. However, "lethal" levels (corium, meltdowns, spent waste containment failure) will do all of that and more, as I increased the danger level.

The dragon gives, and the dragon takes away. :P

**Comment by TomeWyrm** [comment]
Here's hoping I never have to find out the effects of "lethal".

**Comment by ljfa-ag** [comment]
Hey, even at Chernobyl firemen were able to get close to the reactor shortly after it blew...well they died soon after in the hospital, but they were not instantly killed :p

**Comment by ReikaKalseki** [comment]
Barring ridiculous - like inside active reactor - doses, you tend not to die immediately. Radiation triggers cell death on a grand scale (due to blowing apart DNA molecules far faster than [polymerase](https://en.wikipedia.org/wiki/DNA_polymerase) can repair it), and the toxic byproducts of that, as well as the simple loss of massive amounts of tissue, eventually leads to systemic organ failure, shock, and death. The cell death takes hours to days (since it is ultimately an inability to synthesize appropriate proteins, particularly enzymes, that causes the death), and then the death from organ failure some hours or days more.
