### ISSUE TITLE
Chromaticraft Ley Lines Not Connecting [Resolved]

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#446]
So for some reason I'm having an issue where a mutli-aura repeater is failing to connect to a repeater. It does do that ding sound once every 50 left-clicks (this is just an estimate).
Here's a video of what is happening: 

https://www.youtube.com/watch?v=_EjvC2X3CWw

**Comment by metnavman** [comment]
Multi-aura repeaters only "ding" when they've cycled to a color they're connected to. In your case, you're looking at an Asveste Repeater. You right-clicked just as the Asveste cycled away and a Galazio/Kitrino rune popped up in your video, which you're not connected to. Thus, the error sound. Watch the Multi-aura cycle until it hits the Asveste rune, then click.

Edit: I've also got to ask, because it looks like you're trying to move the Ley Line to an underground repeater setup, why are you using a Multi-aura? They cause a much larger loss-per-connection than just using a single repeater does, and have no benefit over regular repeaters besides multi-color connection. With no other colors connected in your video, (unless your goal is to eventually connect a bunch of colors to that spot. If so, disregard) that multi-aura is a waste.

**Comment by ghost** [comment]
Ohh that explains it. Thanks. Also, I am connecting more repeaters it's just a slow process.
