### ISSUE TITLE
Chromaticraft charges/abilities lost after returning from the end

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#45]
I lose all my charges on the wand + abilities in chromaticraft as soon as i exit the end via the portal.
I do have Hardcore Ender Expansion installed. Maybe this could be the issue. 

Chromaticraft V6f
HEE 1.8

**Comment by 1Matthias** [comment]
Reproduced successfully, without HEE.

**Comment by ReikaKalseki** [comment]
This is because the end portal counts as a death. This is technically a Forge or vanilla bug.

**Comment by 1Matthias** [comment]
> This is because the end portal counts as a death. This is a Forge or vanilla bug.

Who...whaa...why? Just why?

**Comment by zemerick** [comment]
Yea...that's always been a weird one. It's caused Reika problems before too. ( IIRC it previously caused a chromaticraft progress wipe. )

**Comment by ljfa-ag** [comment]
It's not a bug, it's just a weird vanilla thing. When you return from the end, your player gets cloned as if he was dead.
Maybe the PlayerClone event will help you.

**Comment by ReikaKalseki** [comment]
Player Clone event?

**Comment by chylex** [comment]
Does that actually trigger the death event? If so, you can check the achievement event that triggers after returning from the End, which happens before the entity is removed.

I could potentially fix it in HEE as I'm rewriting the way the portals work, will have to do some testing because currently I can't see what would trigger the death event.

**Comment by ReikaKalseki** [comment]
This was fixed in v7.
