### ISSUE TITLE
Suggestion: add config options to make reactorcraft deuterium extractor works in non-ocean biomes

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#459]
Like river biomes
Because on certains maps it's hard or even impossible to find a oceam
And with ted80's RWG there is no ocean at all

**Comment by ReikaKalseki** [comment]
Deuterium is exceedingly rare, and only obtainable "directly" at all because it sinks to the bottom of oceans and _slightly_ increases the concentration above what is essentially zero.

Also, this would make it possible for people to make large vats of water that magically generate deuterium.

And if RWG has no ocean-type biomes, that is a design issue on its end. More mods than ReC rely on the existence of oceans, including ChromatiCraft.
