### ISSUE TITLE
2 HTTP Requests caused by DragonAPI in primary Minecraft thread

### ISSUE THREAD

**Issue by rallias** [ReikaKalseki/Reika_Mods_Issues#473]
There are two HTTP requests triggered by Reika.DragonAPI.Auxiliary.Trackers.CommandableUpdateChecker.getLatestVersion(), them being done down in Reika.DragonAPI.IO.ReikaFileReader.isInternetAccessible() and Reika.DragonAPI.Auxiliary.Trackers.CommandableUpdateChecker$UpdateChecker.fetchData() (2,772 ms and 1,279 ms respectively, according to Sampler's startup.nbs file). Realistically, these contribute to the time it takes for Minecraft to load to title screen, and should be offloaded to an external thread.

**Comment by ReikaKalseki** [comment]
3 seconds of load time is nothing to care about, and on top of that, even those numbers are highly atypical.

On the bright side, you got a new tag made for you. :P

**Comment by TomeWyrm** [comment]
Are you using satellite or something? That's 4 seconds of latency for two HTTP requests!

**Comment by diesieben07** [comment]
This is a joke, right? You are not seriously considering this as "not a bug"?
Things like this are why people bitch about modded minecraft taking so long to start.

**Comment by TomeWyrm** [comment]
It's NOT a bug. It's a crappy connection on his end. if BOTH of them took 500ms each, I'd wonder if the player can play on a server, or watch youtube, or basically utilize the internet.

**Comment by diesieben07** [comment]
So you are not allowed to play Minecraft without an internet connection?
I would say "that's racist!" but my humor is pretty much dead in this thread.
Even _if_ it's a crappy connection. Even if it is a good connection and they are currently downloading a game so it is acting crappy. That is not an excuse to not do this properly.

**Comment by diesieben07** [comment]
Oh. And what if the version check server is currently down? Then you block the whole loading until the connection times out. And "is google reachable" is not an adequate way to check if you have a working internet connection.

**Comment by Duckfan77** [comment]
That issue has occurred before, I believe the workaround was remove all network connectivity for the duration of launching minecraft. It skips the remote connection in that case.

**Comment by TomeWyrm** [comment]
Modded minecraft takes forever to load. A few seconds longer will be unnoticable. Something like Gretech increasing by 15 minutes, or the Project E handler issue from a long time ago that boosted times by nearly an hour? That's a bug/issue.

This? Not.

**Comment by rallias** [comment]
> It's NOT a bug. It's a crappy connection on his end. if BOTH of them took 500ms each, I'd wonder if the player can play on a server, or watch youtube, or basically utilize the internet.

You're right. Strictly speaking, it is not unexpected behavior. What it is is an opportunity to remove a significant portion of the time it takes to load modded Minecraft.

**Comment by diesieben07** [comment]
> Modded minecraft takes forever to load. A few seconds longer will be unnoticable. Something like Gretech increasing by 15 minutes, or the Project E handler issue from a long time ago that boosted times by nearly an hour? That's a bug/issue.

Ok, so where is the line? Gregtech can say "15 minutes is noting that project E thing took an hour, not an issue". Other people doing stupid shit is not a reason to be stupid yourself.

**Comment by keybounce** [comment]
I have seen 30 second delays when a TCP connection fails to open; I think the standard allows (or was it requires?) a 70 second timeout (nobody seems to actually use the full 70 seconds, and I have not checked the standards in over 10 years if they were altered).

Forcing two connections may be reasonable in the normal case, but not in all cases.

**Comment by gigaherz** [comment]
Sorry to butt in, but I can't just stand aside and watch.

@TomeWyrm Modded minecraft takes forever to load **BECASUE** modders think it's OK to stall the loading process for things such as doing a version check.  "Oh your DNS is acting funny and it's not responding to this request? well sucks to be you." is NOT the way to go. Specially when the solution takes just a few minutes to implement.

**Comment by TomeWyrm** [comment]
> Other people doing stupid shit is not a reason to be stupid yourself.

The PE issue was Reika. It was also immediately fixed.

> What it is is an opportunity to remove a significant portion of the time it loads Minecraft.
> "significant"

FTB Infinity takes 186 seconds for me to load. 3 seconds of load time is an increase of 1.6%... That is insignificant.

> @TomeWyrm Modded minecraft takes forever to load BECASUE modders think it's OK to stall the loading process for things such as doing a version check. "Oh your DNS is acting funny and it's not responding to this request? well sucks to be you." is NOT the way to go. Specially when the solution takes just a few minutes to implement.

No, it takes that long because modders make mods that do a lot of things during load.

**Comment by ReikaKalseki** [comment]
So many people here - some who really should know better, given their apparently undeservedly high position in the community - are making blatantly fallacious claims or unfounded arguments or getting so hostile that this discussion has no validity and thus no need to be permitted to continue.

The facts are as follows:
- The version checker normally takes less than half a second to perform its checks. Anything else is either a transient issue on someone's end or is the result of very subpar connection speeds that I have no ability, much less obligation, to work around.
- There is no "need" for an internet to be able to play the game. Contrary to claims being made, the game does **not** fail to function without an internet connection or if the version server is  inaccessible (though the latter will log a warning telling the user to notify me). At worst, the connection hits its max timeout of five seconds.
- The only way to fix this would be to remove the version checker entirely, as well as anything else that uses the internet. I wonder what the largest users on that are...oh wait. Forge and MC itself.
- What I am doing is hardly unusual or complained about, and I cannot shake the suspicion that a large amount of the vitriol is because this is regarding my mods. Many other mods have version checkers or other downloaders, and I have yet to see a single complaint about them that was not also shrugged off, much less expanded into an entire wall of text about how evil/incompetent the mod dev is for not accommodating a literally bottomless standard of hardware. This is further strengthened by [the fiasco a few months ago regarding my Remote Asset downloader](https://www.reddit.com/r/feedthebeast/comments/3m0bqk/this_seems_like_a_terrible_terrible_idea_remote/).
- Three, or even the maximum of five to ten seconds really is nothing to care about. Yes, if you had 150 mods and each one did the same thing, then that would add up to a few minutes, but on hardware like that, you can barely play to begin with, and loading times as it is are likely approaching ten minutes or more. On top of that, as was repeatedly stated, there is a simple workaround that not only prevents the issue from occurring but also likely speeds loading elsewhere. On top of that, to harp on _this_ of all things as the source of loading times rings as opportunistic rather than logical, as this is _hardly_ the most expensive operation commonly done by my or other mods during the loading time.
- Moving something to another thread is _not_ a simple "few minute" fix. Not even close. I did that with remote asset loader, and not only was that an enormous amount of effort, _even that_ has not totally solved the issue as there are users who, much as here, have connections so slow that even the entire loading duration of Minecraft is not long enough for everything to complete, and complain that I am "ignoring them" and that I have a duty to accommodate them and that anything else constitutes outright discrimination.
