### ISSUE TITLE
Crash with Rotarycraft v10a and Harder Ores 11.18.0b

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#479]
http://pastebin.com/pLcqR06B

Any ideas?

**Comment by ReikaKalseki** [comment]
Gregtech?

**Comment by Haggle1996** [comment]
Oh god no, your stuff is plenty difficult. :D

**Comment by Haggle1996** [comment]
I've completely removed all mods that I updated alongside v10 (Forestry v4, Applied Energistics rev3); still receiving the error with what was a functional v9 installation; I'm continuing to work towards a minimal modset in which this occurs, but it must be related to an API or integration you updated in v10.

**Comment by Haggle1996** [comment]
I've narrowed this down to just an issue with Harder Ores, from Reasonable Realism. I've also logged an issue on the author's site. To be clear, this was functional in v9f, so something has changed in RotaryCraft v10a that renders it no longer compatible.

**Comment by Draco18s** [comment]
Looks like Reika is trying to examine ore colors?

`at Reika.RotaryCraft.Auxiliary.BlockColorMapper.addOrSetColorMapping(BlockColorMapper.java:376)`

What does this class/method do with an ore block?

**Comment by Haggle1996** [comment]
I would guess it's because Harder Ores uses the metadata to indicate how much ore is left in a block, whereas every other mod I know of uses metadata to indicate a different type of ore. Reika is probably looping through all possible variations of the ore's metadata and just exhausting the ID list.

**Comment by Draco18s** [comment]
That is probable.  It should be easy to detect and code for, in which case, Reika should only be interested in the ore at meta:15, but I don't know what the goal is.

**Comment by ReikaKalseki** [comment]
The BlockColorMapper - used for the [Ground Penetrating Radar](http://i.imgur.com/VII0RqT.png) and Spy Camera - maps Block-Metadata pairs to colors for display. I natively handle every ore in [my ore list](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModOreList.java#L40) and pull everything out of the OreDict and register it to the mapper.

That hits an issue where metadatas >= 16 are registered, as the array declared for metadata colors is size-16, not expecting there to be any blocks with metadata larger. Clearly that expectation was wrong, as both GT and HarderOres use such blocks.

I will rewrite the system to use the (newer) BlockKey system, so that this issue should be fixed.
