### ISSUE TITLE
Server Crash on startup with chromaticraft

### ISSUE THREAD

**Issue by Ethryan** [ReikaKalseki/Reika_Mods_Issues#491]
every time i try to start my server i receive this crash report.
Seems to be some trouble with dye compatability.
Here is the log: http://pastebin.com/jhs6rxJ5

**Comment by thepete89** [comment]
@digger5 The Problem is on ChromatiCraft's end, for RotaryCraft alone it's fixed.

I can also confirm that this crash still happens for ChromatiCraft, ExpandedRedstone, GeoStrata and ReactorCraft - see appended crashlogs.

Crashlog ChromatiCraft: http://pastebin.com/UTx7uGG6
Crashlog ExpandedRedstone: http://pastebin.com/BkJDjSdP
Crashlog GeoStrata: http://pastebin.com/xBgbAWTc
Crashlog ReactorCraft: http://pastebin.com/cmSgqqC2

**Comment by ReikaKalseki** [comment]
Redownload RotaryCraft.

**Comment by thepete89** [comment]
Regarding the other mods: Is there a fix on the way or is it already fixed and Curse just didn't update the files in time?

**Comment by zemerick** [comment]
The problem was in the RoC API, so updating should fix them all. You might want to download them all again just to make sure you have the latest of each.
