### ISSUE TITLE
Chromaticraft Download missing 

### ISSUE THREAD

**Issue by Towsty** [ReikaKalseki/Reika_Mods_Issues#492]
Not sure if there was a mixup in the upload or if this is curse being stupid but there are no files to download for chromaticraft. 

http://minecraft.curseforge.com/projects/chromaticraft/files

**Comment by zemerick** [comment]
As of last night it was curse. Will have Reika double check that nothing else is going on.

**Comment by Towsty** [comment]
Ya it was for a bit. I was able to download V10b. Around 11 CST I saw that Reika seemed to have fixed #489 so I went to redownload it, have not been able to since then. Not sure if its just me, probably something weird on my end. Did clicking that link actually bring up a file for you @zemerick

**Comment by zemerick** [comment]
No it's not. That's why I said it's probably a curse problem. It was uploaded last night, but I will double check with Reika asap that nothing has changed. Maybe a failed upload, it got rejected for some reason, etc.

2 hours for the previous version to get accepted was a bit crazy, but this one was uploaded around 12 hours ago.

**Comment by ReikaKalseki** [comment]
The file was apparently rejected (as it is no longer there). Reuploading.

**Comment by zemerick** [comment]
It's available now.
