### ISSUE TITLE
[Modded FTB Infinity] Startup Crash Forestry

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#504]
I have added DragonAPI, RotaryCraft and ReactorCraft to FTB Infinity 2.2.2 (newest version). Everything worked just fine until version 10 of your mods: My server (private, don't worry ;) as well as my client are crashing during startup, therefore I had to use the old version 9 of your mods. I tried this with every new version (see crashlog)  As you can see in the crash log, an old version of Forestry (see crashlog) is included into FTB Infinity by default, that may cause the issue.
I saw in your DragonAPI code that you canged sth in the RecipeHandlers.ForestryRecipeHelper class, but I can't see the error.

Crash-Log: http://pastebin.com/S4jtRXvm

**Comment by zemerick** [comment]
You guessed right, you need forestry 4 with v10.

**Comment by TomeWyrm** [comment]
Well, first Private as in just you (or people in your house), or semi-private (i.e. whitelisted, other people can access)? Because the pack rules do distinguish between the two.

This is a known issue see #229 for more details.

This means that in order to use v10, you will have to upgrade to Forestry 4.
Which means you will need to update Gendustry and Magic bees at the least, and stop using Binnie's Mods (Extra Trees, Extra Bees, Genetics, and Botany), because they have no version that supports v4

**Comment by amesgen** [comment]
Thank you for your quick reply. It is a personal server (only for me) (so I can run minecraft 24/7). Sorry for the duplicate post.
Merry Christmas!

**Comment by zemerick** [comment]
NP, it's hard for any of us to keep track of what all is up or not as well. It's also a trivial matter to close an issue. As long as you're civil, we're happy:)

Merry Christmas to you too.
