### ISSUE TITLE
Reactorcraft HP turbine splits water on the ground even with turbine generator installed?

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#508]
Like this,
there is no water or steam output from the turbine gen's steam bypass
![image](https://cloud.githubusercontent.com/assets/2989009/12006037/1df05808-abcc-11e5-834a-36f0ffb262b4.png)

**Comment by ljfa-ag** [comment]
Not sure what your point is. Afaik water falling down from the end of the turbine is the intended way of reusing the water, and I don't think a turbine generator is meant to change this.

**Comment by wormzjl** [comment]
In the documentation the steam is meant to be outputed from the turbine gen's steam bypass

**Comment by ghost** [comment]
If I recall, HPTs do not output steam from the turbine generators steam bypass. The LPT does this however, the HPT requires steam to be piped in instead of using a steam grate.
That's why you're getting water at the bottom of the turbine for use in a fission, fusion reactor or anything that requires water. But you can ignore the water too and just let it disappear.

**Comment by zemerick** [comment]
Hyperion is correct. The steam bypass is for actual steam blocks that need to rise into the air, specifically from the standard low pressure turbine. The HPT outputs water, not steam, and so its output remains unchanged.

Also, I'm looking at the ReC handbook entry for the turbine generator, and it does not mention the steam bypass or turbines at all.
