### ISSUE TITLE
Chroma Dimension shrine Chests Crash

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#530]
Hey Reika, 
I found another weird bug for you. I saw it in the v9 of chromaticraft, and brought it up on the forums and I don't remember the result of that. Regardless I never made a issue on here because it is an easy thing to avoid. Don't loot shrine chests, at least for me.

Here is the crash report 
http://pastebin.com/cdzSCZDn
Note lines 45 to 50. It is trying to render an item at the maximum NBT data. Which makes absolutely no sense since it is a slab of wood.

**Comment by ReikaKalseki** [comment]
The log contains only Forestry and vanilla code, probably because he registered something null to the OreDict.

**Comment by Reignofmagic** [comment]
Alright, thanks Reika I'll post this to the forestry github as well

**Comment by mezz** [comment]
@ReikaKalseki I registered a slab with wildcard metadata to the ore dictionary. It's meant to be compared against, not spawned into the world. Where did this slab come from?

**Comment by mezz** [comment]
Yep, ore dict entries for "slabWood" are grabbed

https://github.com/ReikaKalseki/ChromatiCraft/blob/adc391d5188a3460afbb2c098cb95537ba160b70/Registry/ItemMagicRegistry.java#L43

``` java
this.addElement("slabWood", CrystalElement.GREEN, 1);

private void addElement(String s, CrystalElement e, int amt) {
    Collection<ItemStack> li = OreDictionary.getOres(s);
    for (ItemStack is : li) {
        this.addElement(is, e, amt);
    }
}

private void addElement(ItemStack is, CrystalElement e, int amt) {
    KeyedItemStack ks = new KeyedItemStack(is).setSimpleHash(true).lock();//.setSized(true);
    ElementTagCompound tag = data.get(ks);
    if (tag == null) {
        tag = new ElementTagCompound();
        data.put(ks, tag);
    }
    tag.addTag(e, amt);
}
```

It's added without checking for wildcard meta.

and then it gets put into the chest:

https://github.com/ReikaKalseki/ChromatiCraft/blob/63b8e8272273450d3fe5da89de86859e81e6f6fa/World/Dimension/Generators/WorldGenMiniAltar.java#L106-L126

**Comment by Reignofmagic** [comment]
@ReikaKalseki @mezz 
It drops from the shrines that occasionally spawn in the chroma dimension. It seems to spawn any "magical" plants, forestry stuff is seen relatively commonly, as well as other seemingly random items and any chromaticraft base material (shards, berries, leaves, etc) 

I think this is the structure in question, if it is lines 106 to 124 would be where it gets the code to spawn the items. 
https://github.com/ReikaKalseki/ChromatiCraft/blob/63b8e8272273450d3fe5da89de86859e81e6f6fa/World/Dimension/Generators/WorldGenMiniAltar.java

**Edit**
Should have read your second post first mezz, haha

**Comment by ReikaKalseki** [comment]
An item that crashes when being rendered or otherwise used should _never_ be added to the OreDictionary. Spawned or not, this will also crash all sorts of recipe display code including NEI and my RC/CC handlers, as well as anything like randomized fetches and recipe comparison code.

At the very least, ensure that it does not crash; it need not actually function.

I have seen the same happen with Natura logs (OOB) and with various ingots and gems (OOB, NPE, ClassCast(!)) from a few mods. Mods are not expected to have to sanitize lists coming in from things like the Ore Dictionary, meaning that anything added to them has to be safely interactable.

**Comment by mezz** [comment]
From OreDictionary.java:

``` java
registerOre("slabWood",    new ItemStack(Blocks.wooden_slab, 1, WILDCARD_VALUE));
```

Yes I should handle the case where other mods mess it up, and I will. 
Can you reopen this issue? There is no use for a wildcard meta slab, it's not a valid item to give players.
I took the time to debug the issue for you in good faith, why are you being terrible to work with? 
What is with the insulting issue tags?

**Comment by ljfa-ag** [comment]
Well an itemstack with any metadata and NBT can be created ingame with the /give command, so I think a mod should expect anything there.

But yeah, the wildcard value does not say which values are actually valid to insert, so it's not really guaranteed that you can get a meaningful itemstack from a wildcard entry. The only value that will probably work in most cases is 0.

**Comment by TomeWyrm** [comment]
The "Stupid Code" label isn't meant to be insulting. It's meant (from my understanding) for basically "code that reacts in unexpected ways that we cannot fix". It tends to get used a lot on Forge bugs, for obvious reasons.

As for wildcard slabs, what he's doing is calling for slabWood (among many other items) from the ore dictionary to populate his chests in the endgame of ChromatiCraft (from what I remember). This is much easier to do than to have explicit handling for mod items which should be equivalent (_cough_ Natura _cough_). Unfortunately this means he calls a random value for the allowable metas. Which can pretty obviously give an exception when the wildcard "allows" entries up to say 16, and there's only 4 slab types; the code asks for slab 14, and boom.

**Comment by mezz** [comment]
The code is not randomly choosing from 0  to 15, it is keeping 32767. From the crash report:
`Entity Name: item.tile.for.slabsFireproof.32767`

**Comment by TomeWyrm** [comment]
Well, apparently wildcards in the ore dictionary register at least up to 65535. The illustration still stands despite being specifically inaccurate for this case. I was also illustrating for those that can't follow along, not experienced programmers who should be able to deduce this information from nothing but the stack trace and previous discussion.

In any case, having to try/catch, or otherwise sanitize/validate entries in the ore dictionary seems like a lot of work for potentially everyone else… whereas not registering a wildcard in the first place seems, to my admittedly inexperienced eye, to be a much simpler option for everyone involved.

I am wondering: what is gained by registering  nonexistent items to the Ore Dictionary?

**Comment by mezz** [comment]
Wildcard is a specific value, `public static final int WILDCARD_VALUE = Short.MAX_VALUE;` which is 32767.

Registering wildcard items in the OreDictionary is standard practice, it is even done by Forge in `OreDictionary.java` as I quoted before.

The reason it works this way is because the OreDictionary was created for recipe comparison. The wildcard metadata is so that you can register one item instead of many. When I register my wooden slab with wildcard metadata, I can use "slabWood" in one of my recipes and it will match any one of my wooden slabs. If instead I registered every slab, plank, stair, wood, leaf, etc, individually, the OreDictionary would get much more bloated with entries and it would not work any better for recipe comparisons.

If you want to safely get the variants of an ItemStack from the OreDictionary, petition Forge to remove `@SideOnly(Side.CLIENT)` from `Item.getSubItems` and `Item.getCreativeTab()`. Then you can ask the wildcard item what its variations are.

**Comment by ReikaKalseki** [comment]
> If you want to safely get the variants of an ItemStack from the OreDictionary, petition Forge to remove @SideOnly(Side.CLIENT) from Item.getSubItems and Item.getCreativeTab(). Then you can ask the wildcard item what its variations are.

That has been suggested by me and several others, always being shot down for "useless", "too much work" or "encourages bad practice".

**Comment by TomeWyrm** [comment]
Also it would almost certainly not be backported into 1.7.10... and so is useless to most anyone for a long time (I might not ever move forward to 1.8+ for instance)
