### ISSUE TITLE
current V10s

### ISSUE THREAD

**Issue by Remanscimitar** [ReikaKalseki/Reika_Mods_Issues#551]
Upgraded my minecraft forge to 10.13.4.1558 (Recommended) and upgraded from the V9s Rotary/Reactor crafts and Dragon API to current settings and seems to error after construction, curious if there is another needed modification for them or a patch, plus Chromaticraft seems to error at start of loading of game vs the others. Can reconstruct the report if needed.

**Comment by ljfa-ag** [comment]
Do you have the crash reports?

**Comment by Remanscimitar** [comment]
Report without Chromaticraft
http://pastebin.com/BBWm049U

**Comment by Remanscimitar** [comment]
And here is with Chromaticraft:
http://pastebin.com/aTqdYWxD

**Comment by ljfa-ag** [comment]
The first crash is due to v10 not bering compatible with Forestry 3.
And the second crash: Read the beginning yourself and do what it says. You have to add a certain Java argument in order to avoid a very strange crash that might otherwise happen, see #208 and #475.

And please do not paste crash reports directly, use Pastebin or Gist or something like that.
