### ISSUE TITLE
Improper Matter Overdrive API Usage

### ISSUE THREAD

**Issue by shadowfacts** [ReikaKalseki/Reika_Mods_Issues#553]
Currently in [`MatterOverdriveHandler`](https://github.com/ReikaKalseki/DragonAPI/blob/d15835463b045ce03c09594ee94cabb69fd1b808/ModInteract/DeepInteract/MatterOverdriveHandler.java) you are using reflection to access Matter Overdrive functions. FML IMC messages have since been added ([usage](https://github.com/simeonradivoev/MatterOverdrive/blob/master/src/main/java/matteroverdrive/api/IMC.java#L21-L45)) and are now the preferred method of interacting with MO.

**Comment by ReikaKalseki** [comment]
How does this handle wildcarding of metadatas and NBT? I do not want a repeat of the Project E "you have to register every metadata separately" incident that resulted in tens of thousands of IMCs.

**Comment by TomeWyrm** [comment]
That was because you thought you had to register every metadata. When PE had automatic handling for that due to the construction of it's EMC system. :-p

**Comment by ReikaKalseki** [comment]
They explicitly told me I had to register every metadata.

**Comment by simeonradivoev** [comment]
You can blacklist items through the simple IMC calles we have https://github.com/simeonradivoev/MatterOverdrive/blob/master/src/main/java/matteroverdrive/imc/MOIMCHandler.java. We handle only item metadata through the matter registry. There only one way to handle custom matter values on items, by using our API. You can use the https://github.com/simeonradivoev/MatterOverdrive/blob/master/src/main/java/matteroverdrive/api/matter/IMatterItem.java for items to return custom matter without even having to register the item in the matter registry.

**Comment by ReikaKalseki** [comment]
My point is that the "Item" variant is in fact _ItemStack_, which has a metadata. If I blacklist a stack of some item, with some damage value, will it auto-blacklist other metadatas?

The problem is that I have metadata-specific items that I would blacklist that share an item ID with other nonblacklisted items, and other items for which I would blacklist _all_ possible metadatas.

**Comment by simeonradivoev** [comment]
Ah yes, I didn't even think about that. Well shadowfacts did add the IMC calls. I should add the option to specify if you want the metadata to be used. In my API I have this option. If you register an Itemstack the metadata will be taken into consideration. You can skip the metadata if you register the item itself without using the itemstack. I really should redo my matter registry to be more advanced. I haven't changed it a lot since I first created it.

**Comment by ReikaKalseki** [comment]
I will admit I would prefer a method other than making the item classes implement an interface, as that is not easily expandable and requires I add the interface to dozens of classes. On top of that, I am afraid of running into classloading issues like I did with the AE, OpenComputers, and Minechem APIs.

**Comment by simeonradivoev** [comment]
I will expand the IMC calls to allow for that, but in the meantime should should remove the old calls to MO so the players don't crash.

**Comment by ReikaKalseki** [comment]
Depending on your schedule, your expansion may well come before v11.

**Comment by enterprise12nx** [comment]
Hoping this is fixed soon..downgraded matter overdrive now reikas mods are crashing me constantly, cant remove it because the forge fix dont work since it was compiled before forges fluid registry change...
If i remove reikas mods my world is destroyed.
Rumor has it your fixing the forge fix for V11 Reika
Really hope you are...cause tons of people are screwed rn

**Comment by TomeWyrm** [comment]
"tons"
Matter Overdrive is not _that_ popular. Jeez the hyperbole in these mod-version-conflict issues. It's not the end of the world, and you should ALL learn to fix this kind of crap, it'll continue to happen for the forseeable future because Forge/Minecraft suck like that.

**Comment by enterprise12nx** [comment]
Well for my whole modpack player base, id consider that tons, because i have over 100 players who play on my dedicated server for my modpack, theres plenty of others who use single player, and im sure there are others who use these mods combined as well.

**Comment by TomeWyrm** [comment]
Forestry would like a word with you about a matter called "scale"

**Comment by enterprise12nx** [comment]
not sure what your talking about, but i removed reikas mods, my player base preferred matter overdrive

**Comment by ReikaKalseki** [comment]
Given the nature of your posts, and the kind of audience I cater to being those who are more reasonable and amenable to logic, that does not surprise me.

**Comment by TomeWyrm** [comment]
> not sure what your talking about

Effectively? Matter Overdrive is small potatoes, and this kind of error is something any competent pack developer/maintainer should learn to handle with grace. Because I would bet (and win) a million dollars that this will happen again between plenty of other mods that do API changes between versions (changes, as in removals or renames; not additions). When that intersects with a mod that doesn't have a rolling release schedule... which is a surprising number of them. You get this kind of stuff.

I've been playing this game for coming up on 5.5 years now. I've been playing mods for ~5 years. This thing is beyond a horse that was beaten to death, zombified, beaten back to death, resurrected, and is still being beaten; it is something you _really_ need to learn to deal with.

Additionally? "the forge fix dont work since it was compiled before forges fluid registry change" is demonstrably false. It doesn't touch fluid code, so it doesn't matter half a whit.

As for downgrading Matter Overdrive crashing, I'm betting it's user error. If you tried with a fresh pack, I would be shocked if it didn't work. You probably got invalid data from somewhere when you downgraded a mod. Downgrading versions generally is a bad idea without a backup. Something I learned back in the days where EVERYTHING was a jarmod. As in open up the MINECRAFT jar and edit the files MANUALLY.

So sorry your drama-llama self decided to take your ball and go home. We're going to keep on going the only way we have as an option... which is waiting for a fix when it's damn well ready and not bitching at the mod author even in a passive-aggressive way that carries no weight because we don't know you and your overblown sense of your own importance due to your frankly minuscule user-base.

**Comment by enterprise12nx** [comment]
It doesnt matter if its small..my users prefer it over all of Reikas mods, it was their decision not mine.  Whether a mod is small or big, somebody is putting effort, and time into their mod, allowing others to use it and enjoy it, there is no "better mod" its each to their own opinion. 
I have been playing minecraft since its release in 2009 when it was only creative on their website, and have been modding since minecraft beta right when beds came out.

There are reasons Reikas mods are in few modpacks, one Strict rules and two the problems it causes between other mods because of how it hooks to anvil.

I handle bugs just fine, and usually manage to fix them myself through googling and research, and talk to all the mod authors involved, and have helped aiden c brady (author of mekanism) fix conflicts between enderIO and his mod, and helped sort out issues with other mod authors, they have come to know my pack quite well.
I have been maintaining my modpack for 3 years now, and running servers for 5 years, my player base respects my work, and generally we have very few problems.

Yes i know how old minecraft worked with the minecraft.jar really wasnt that long ago, we have backups, that hasnt been the issue.

The problem is, i cant let my dedicated server sit dead while we wait for an update, which usually for Reika takes a good month at least, 
I dont recall "bitching" at Reika, i simply stated we were hoping for a fix and that many people are having this problem. 

I know how to read code, and attempt to fix errors..im in a programming course in college, am i the best? no.
So dont put yourself on a pedestal, there are plenty of users who have been modding for as long, and longer than you have
My player base is of my importance, and your mod is of your importance, your maintaining it, were giving feedback, pretty sure any mod author should expect bitching and problems, thats part of every day life lol.

**Comment by TomeWyrm** [comment]
Yeah, I honestly don't believe you. You have misquoted and misnamed nearly every term you've used and are making newbie-level mistakes and assumptions.

Also the passive agressive "tons of people are screwed", "reikas mods are crashing me constantly", "Hoping this is fixed soon", "If i remove reikas mods my world is destroyed."... That's still complaining. A complaint that has been heard thousands of times, and will not change the release schedule or style.

You ACT as though you started playing less than a year ago, and started maintaining your pack less than 5 months ago. Show your age, act like a civilized being instead of an entitled teenager. Because frankly "pics or it didn't happen". I've seen a lot of boast and nothing to verify.

It's trivially easy to notice that I'm not the mod author, that there's a difference between playing mods and modding, and finally? Bad behavior being common is no excuse for continuation of such behavior between civilized people.

**Comment by ljfa-ag** [comment]
This place is not for discussing who is better or has a larger userbase or whatever. Take this elsewhere please.

**Comment by ReikaKalseki** [comment]
I would have already locked it, but I want simeonradivoev and shadowfacts to be able to reply if necessary.

**Comment by enterprise12nx** [comment]
Lol, its the internet i dont come here to spell every word to its exact letter and capitalization,  "pics or it didn't happen" to you too.
Pretty sure i havent put up any act, if you want proof your welcome to goto nucleartekkit.enjin.com to see my work, or just goto http://www.technicpack.net/modpack/a-new-age-enterprise.55905 and you can clearly see im the author and its creation date.
You can just about goto any mod author and ask them about my modpack and i guarantee they will know me.
Ya its a complaint, it ruined my servers save world, gonna be a tad pissed.

![2011-08-18_20 33 30](https://cloud.githubusercontent.com/assets/3360014/12506023/bfc66314-c0b9-11e5-9320-b1a1409293ee.png)

Theres your photo lol, but i will stop responding as asked.

**Comment by shadowfacts** [comment]
@ReikaKalseki, I am closing this issue, please lock it. I will make a new one for _relevant_ discussion.

@enterprise12nx and @TomeWyrm: Drop it. It seriously doesn't matter, nobody except you cares at this point.

**Comment by TomeWyrm** [comment]
@shadowfacts Thank you for closing the issue and requesting it be locked, but this is not your issue tracker:  please don't be rude to Collaborators in the future. Even if we are being overly bitchy, as I was.
