### ISSUE TITLE
Mod crash when installing new Mods

### ISSUE THREAD

**Issue by Luysita** [ReikaKalseki/Reika_Mods_Issues#585]
##

**Comment by ReikaKalseki** [comment]
This makes absolutely no sense. Try removing mods.

**Comment by zemerick** [comment]
Are you doing anything unusual? Scripts, tweaks, etc. Did you download Reikas mods, especially Chromaticraft, from a non-legit source? ( Anywhere that isn't either a verified legit modpack or sites.google.com/site/reikasminecraft/home )

**Comment by Luysita** [comment]
##

**Comment by MachiavelliSeraphim** [comment]
He said to remove the mods because there are other mods listed at the end of the crash file.  

Install all the Reika mods, start it up.
Wipe the configs and then add one mod, start it up.
Repeat as necessary until the one you add causes a problem.

Ive done this MANY times over the years and it usually resolves the problems, because as good as forge is at configuring things, sometimes it has problems too.

also per your crash log:
"    EnderIO: Found the following problem(s) with your installation:
                  \* Optifine is installed. This is NOT supported.
                  \* The RF API that is being used (1.7.10R1.0.13 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from buildcraft-7.1.14.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it."

**Comment by zemerick** [comment]
Reika means to remove the other mods you have installed, not his. The vast majority of crashes come from a conflict between mods, so this helps to narrow down which one is the source.

No one has been rude to you. When Reika says "This makes no sense.", it's because the error itself doesn't make sense. The error is saying it can not find a part of Chromaticraft. A part we all know is there.

Hence why I was asking if there is anything unusual. I did not call you stupid, and I definitely read the report. Same with Reika. Lots of people make plenty of tweaks ( Reikas own dev server has quite a few, designed to force people into using all of the mods to properly test things. ) Downloading from unofficial sources happens a lot. There is no need to be defensive, we just have to be thorough.

**Comment by Luysita** [comment]
##

**Comment by ReikaKalseki** [comment]
And this is why when I give instructions in the search of more information, the correct response is to try and be constructive by following them, not to get belligerent and make claims that are demonstrably false and belie an unwillingness to actually help.
