### ISSUE TITLE
Plasma Injectors failing to form multiblock in the dimension "The Last Millenium"

### ISSUE THREAD

**Issue by Meller127** [ReikaKalseki/Reika_Mods_Issues#631]
So i will try to describe this problem so good i can

Im building my fusion reactor in The last millenium from ExtraUtilities, i hade my injectors form the multiblock then i accidently picked the solenoid when it was spinning BOOM.

After that i cant get the injectors to form the multiblock, if i build them in another dimension or the Overworld they will form correctly..

Solenoid will form correctly
Turbine Generator will form correctly
Injectors will not form

ReactorCraft V10d

**Comment by Meller127** [comment]
So i fund the bug

If you have ARC lamps from GalactiCraft directed on your Injector it cant form the multi block. As soon i removed the lamp the injector forms correctly

**Comment by ljfa-ag** [comment]
Seems like these lamps are placing invisible blocks...although these blocks should be replaceable and behave like regular air

**Comment by TomeWyrm** [comment]
Heh "should". Something about air-but-not-air blocks just breaks so much code in MC. Even Reika's invisible light blocks break a lot of the same sorts of things that the heat block from Railcraft will.

**Comment by Aivech** [comment]
Why is there not a way to decrease the falloff (the distance it takes for the light from a light source to decrease 1 level)?

**Comment by zemerick** [comment]
It's a vanilla MC thing, and has been a royal PITA for modders ever since.

Normally, this wouldn't be a problem with Reikas multiblocks. His don't care about other blocks touching them, or being within their bounds. However: The injector is a bit special: It has the 2 holes on the sides which need to be air.

One solution I can think of, would be to add a new block that is needed there. Something like an "Injector Field Coil". However, you can probably guess a problem with this: It immediately breaks all current builds and tutorials on how to build it.

**Comment by TomeWyrm** [comment]
@DaMachinator. Because Mojang.

That is the honest answer to a lot of "why" questions about Minecraft. Especially the annoying ones
