### ISSUE TITLE
Developers argue among

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#658]
I use KCauldron and update Reika's Mods to V10, then server crashed any time, **I can't start server again, I lost a lot of players.** And if I delete all Reika's Mods, my ALL WORLDS will completely destroyed. And I can not give up Reika's Mods because I like it.

But, next thing is funny:

`Reika said: Server crashed is not my fault.`
And then V11d version is released, still does not work properly.

```
Prototik(KCauldron's Developer) said: 
YOU don't want to support YOUR mods on other platforms.
It is still possible to understand.
But when YOU forbid SOMEONE else to support YOUR mods you looks like ass-fucked piggy.
So FUCK YOU Reika! Arrive in Russia and force me to follow you idiotic rules, asshole.
I WILL release patched mods or patches singly for any mods as I want, and no one can forbid to do it. INCLUDING YOU!

Look at this: https://gitlab.prok.pw/KCauldron/KCauldron/issues/272
```

And then KCauldron no any update.

Just till me, what do you want to do? You and KCauldron, are the most important thing and we can not give up any one of them. My god, what should we do? Close our server and our players? Just because you and him refuse to make concessions?

**Comment by ReikaKalseki** [comment]
I fixed that issue in v11. If the fix does not work, the information Prototik gave me was false, or Cauldron has been built in such a way that the Cauldron check is either broken by updates or never worked in the first place.

**Comment by ghost** [comment]
I try a min ago, crashed any more...............

**Comment by TomeWyrm** [comment]
Check out #541

Also
#657 #621 #538 #523 #493 #375 #139

KCauldron is NOT supported, nor will it ever be supported. If Prototik breaks things, that's HIS fault. Reika designs his mods on FORGE. You are not using Forge. This is in NO WAY Reika's problem, at all.

Much like running minecraft on your toaster might literally fry your toaster (assuming you've got a smart toaster running java). That isn't Mojang's fault. You're running minecraft on a TOASTER. At best it's the toaster's fault, but honestly? It's yours for running incompatible software together.

This can probably be made to work if Prototik gives Reika accurate information, but any and all issues running Reika's stuff on Bukkit/Cauldron/MCPC/KCauldron/Thermos/IllegalSoftwareYouReallyAllOughtToQuitUsing are on THEIR side, because they're messing with Forge. If you had a patched Java version and your java programs suddenly started throwing up errors... that's not Java's problem, nor is it the problem of your software. That's the problem of the PATCH. Which in this case is KCauldron.

**Comment by Aivech** [comment]
Why is the KCauldron dev being rude?

**Comment by TomeWyrm** [comment]
Pretty much the reason why anyone is rude. He doesn't like being told what to do, most likely because he thinks he's better than other people. Note: entirely personal speculation.

**Comment by ReikaKalseki** [comment]
That particular outburst came after I instituted my sixth modpack rule (the one stating you have to use official builds of my mods).

**Comment by Aivech** [comment]
> stating you have to use official builds of my mods

ummm.....

I thought that was a rule since like the beginning of time (don't redistribute the mod - what every modder who doesnt have an opensource license says, including yourself)

**Comment by TomeWyrm** [comment]
Nearly every one of those rules is "duh" and should NEVER have needed to be stated... except people are people, and are thoughtless or entitled. Experience neccesitated their inclusion so Reika could point at the rules and say "You agreed", and hence get the community more on his side to stop people from being complete idiotic assholes. It helps... some.

**Comment by ljfa-ag** [comment]
In the end Prototik was just trying to help players and server owners. He felt like the new rule was especially made to prevent him from trying to accommodate users, or having compatibility at all.
Although he should be watching his language

**Comment by TomeWyrm** [comment]
Unfortunately, his patched redistribution was illegal many times over, and caused more pernicious problems than it fixed. A much better solution would have been either some change on his end, or a working solution for Reika to work around the issue.

Which is what we thought had happened. Apparently we were wrong.

Also I think you're being generous: Prototik was an abrasive condescending ass throughout the process, it only became more prevalent the more time passed.

**Comment by Aivech** [comment]
To be fair, he probably _is_ better than most of the people he works with IRL - or his job is tech support.

**Comment by ReikaKalseki** [comment]
Better coder? Possible. Better in general......? If so, he really needs to find somewhere else to work.

**Comment by Aivech** [comment]
I meant better at whatever his job is.

**Comment by TomeWyrm** [comment]
Being better never excuses poor attitude. It in fact worsens the backlash and negative consequences of being a thoughtless jerk. You SHOULD be using that superiority to improve the situation for others, else you're not only a jerk, but you don't have an accurate grasp of the reasons why humanity managed to do the impressive things it has over the millennia (here's a hint: It involved cooperation and support structure).

**Comment by InitHello** [comment]
It's funny, because I hear rumors of Reika being an ivory-tower elitist mod author, and yet he's always come across as sane and reasonable. Projection much?

And yeah, as a software developer myself, I've had to deal with the fallacy of thinking I'm superior just because I have a fair amount of domain-specific ability. Spoiler alert: It makes me a lot less special than my ego wants me to believe.

**Comment by ReikaKalseki** [comment]
> I hear rumors of Reika being an ivory-tower elitist mod author, and yet he's always come across as sane and reasonable.

Such rumors usually arise from people who very much either have ulterior motives - personal or otherwise - or those who share the "no matter what someone does, they never should be treated with anything other than deference and politeness" mindset, and take issue with my (lack of) tolerance for dishonesty, laziness, or unwarranted hostility.

**Comment by InitHello** [comment]
You mean if I treat you with courtesy you'll respond in kind? _What a novel idea_!

**Comment by Paralaxus** [comment]
Um i know this is dead, but i am having issues with Kcauldron (latest) and DragonAPI (latest) anything that can be done about this anytime soon?

**Comment by TomeWyrm** [comment]
Nope. It's all KCauldron's end. Talk to them, good luck.

**Comment by TomeWyrm** [comment]
Also, locking this discussion. If anyone has this issue in the future? The answer is "Go talk to the dev of whatever MCPC+/Cauldron/KCauldron is called now". Reika can't support it, and really doesn't want to now that the developer has been such a jerk. I wish you luck.
