### ISSUE TITLE
Crashing When opening the game

### ISSUE THREAD

**Issue by DweiaCaelum** [ReikaKalseki/Reika_Mods_Issues#669]
I'm playing the Atonement: Sins of the past modpack from the curse launcher and I'm getting a crash when I try to open the game. Crash report:
http://pastebin.com/Gd25b4Zc

When I removed dragon API, the game opened without issues. I asked the modpack creator for help, but he said I should post this here. 

Also, since I had issues with this before, my system langueage is Turkish, could that have anything to do with the crash?
Thanks.

**Comment by ReikaKalseki** [comment]
[EDIT: This is incorrect, see below]

Your modpack author needs to learn how to read a crashlog and/or how to not shove off his responsibility on the mod developers. In all likelihood, the download is corrupt.

> Caused by: Reika.DragonAPI.Exception.InstallationException: DragonAPI was not installed correctly:
> The version file was either damaged, overwritten, or is missing!
> Try consulting http://www.minecraftforum.net/topic/1969694-for information.
> This is not a DragonAPI bug. Do not post it to http://www.minecraftforum.net/topic/1969694- unless you are really stuck.

Can you link me to where you reported this to them? I want to speak with them.

**Comment by 1skandar** [comment]
That would be me. And you'd be better served not to jump to conclusions, k? Sometimes, believe it or not, us pack devs know what we're doing.

First thing I suggested was a reinstall, as that crashlog did, indeed, look like a corrupt download. However, when he said that a redownload did NOT fix the problem and he mentioned he was using a language other than english I thought it best to have him post it here. I've heard of some other languages, like Turkish here, that could cause problems at least somewhat like this and I figured if this is what it was this is something you'd need to know.

(please see here: http://support.feed-the-beast.com/t/os-language-bug/10596 for something a bit like this related to the Turkish language)

Now I think you owe him, and me, an apology. Sheesh.

**Comment by ReikaKalseki** [comment]
The report here at no point mentioned a redownload not fixing it. Had that been mentioned, I would not have assumed user error as is the case 99% of the time.

Now, I, after some looking into it, have determined that yes, it is an OS language issue. Apparently, capitalization works differently in Turkish, and the string parsing fails. This is a very easy fix on my end for v12, but there is nothing, short of setting the OS language to English, you can do to fix it.

> Sometimes, believe it or not, us pack devs know what we're doing.

You do, yes. However, you are top few percentile; most pack devs are happy to slough off all errors onto the mod developers, and the original wording of "I asked the modpack creator for help, but he said I should post this here" is vague and does not contradict what is normally a fairly accurate interpretation.

Also, had I heard of the pack before, I would have known it was you and also not assumed installation error, since I know you would not make such a mistake.

**Comment by 1skandar** [comment]
Sorry to come off harsh, but this is _exactly_ why some people have problems with you. Instead of using the language you did and just dismissing the bug (and bad mouthing the pack creator in the process), you should have asked for some clarity first. 

I understand you take a lot of abuse, but basic politeness, eh?

**Comment by ReikaKalseki** [comment]
The thing is that this is a very commonly reported error, and the past 70-odd times it has been reported in the last 30 days, it has always been an installation error. Barring the knowledge that this pack is made by someone who does know what they are doing, as opposed to xX_SuperPackDev_1337Haxors_Xx, it is not unreasonable to reach the same conclusion as the previous times.

> I understand you take a lot of abuse, but basic politeness, eh?

I did not see myself being impolite. Blunt, sure, but not rude.

Also, I am currently not exactly on the receiving end of much politeness myself, with everyone from end users to pack devs to mod devs to server admins currently wanting to beat me with a rubber dick, and with developers of mods from MagnetiCraft to ProjectE to DartCraft to half a dozen smaller mods doing things ranging from telling their users to report all crashes to me to outright threatening to do TiC-GT style crash-on-load, or just publicly calling me all sorts of names and acting like I am trying to dominate everyone else.

**Comment by 1skandar** [comment]
Yeah, I get it. That said, the amount of impoliteness you are currently receiving is no excuse for impoliteness yourself. It's a vicious cycle, with insults feeding on insults. Taking the high road and sticking to strict professionalism is the best way to nip that kind of thing in the bud. And, if nothing else, there is the feeling of self satisfaction that you've reduced your detractors to petty insults and name calling without getting right into the mud with them.

And i'm sorry, your bug tracker is not the place for this discussion. I think I've made my point here, you just managed to catch me at a bad time. Carry on, and good luck.

**Comment by ReikaKalseki** [comment]
> And, if nothing else, there is the feeling of self satisfaction that you've reduced your detractors to petty insults and name calling without getting right into the mud with them.

Whatever this says about me, I rather get a better feeling from tearing someone a new orifice after they make ridiculous demands or stoops to petty insults - especially if my reply is not in that form, but instead a (hopefully witty) judgement of their reasoning skills or similar - than I do from "taking the high road", which to me has never really offered much satisfaction at all, nor has it done much to make people any less hostile.

> And i'm sorry, your bug tracker is not the place for this discussion.

I am perfectly fine with this happening here.

**Comment by ReikaKalseki** [comment]
Fixed, and hopefully in hundreds of other locations as well.
