### ISSUE TITLE
GeoStrata crashes with potions

### ISSUE THREAD

**Issue by uhsting** [ReikaKalseki/Reika_Mods_Issues#67]
Hi I got a strange crash with this mod. When I threw a potion to myself or I was given a potion effect, it crashes and gives the following crash log:

http://pastebin.com/AbbP0Kga and http://pastebin.com/7TbercP2 

I've tried adding the following mods in my modpack and it crashes when I add GeoStrata and DragonAPI into my modpack (all potions have no conflicting ids), without it the modpack works fine:

Status Effect HUD (Even if I remove this mod, another crash is introduced)
EnviroMine
Extended Potions
Galacticraft Core, Planets and Micdoodlecore
Thaumcraft (inc. Mod Aspects, NEI Plugin, Exploration and Tinkerer)
Witchery

I hope I could get a reply soon.

**Comment by ReikaKalseki** [comment]
Try Forge 1291.

**Comment by uhsting** [comment]
It's still crashing and the error log is more or less the same.

http://pastebin.com/AXQ6kDJV and http://pastebin.com/ujBXyRRd

I'm currently finding which mod is the culprit with the crash.

UPDATE: Gotcha, Extended Potions crashes with GeoStrata.

**Comment by ReikaKalseki** [comment]
Try removing GeoStrata, but keeping DragonAPI. Does it still crash?

**Comment by uhsting** [comment]
Still crashing:

http://pastebin.com/Qi3DF0rh

Note that only DragonAPI and Extended Potions are included

**Comment by ReikaKalseki** [comment]
Then what that means is the two are incompatible. I know I have some potion-related ASM, as well as expand the potion array; ask him to join here to help.

**Comment by lumien231** [comment]
Okay so the "problem" lies in the transformation of the S1DPacketEntityEffect Constructor, DragonAPI removes the bytecast to allow potion ids up to 255, ExtendedPotions also removes the & 255 to allow potion ids above that.

ExtendedPotions just removes the 3 instructions after the getPotionID() call, however since DragonAPI removes one of them (The Byte Cast) ExtendedPotions removes the PUTFIELD instruction that is supposed to actually set the potion id packet field so the potion id stays at 0 which causes the client to crash because there is no potion with the id 0. I'll just fix this on my side by checking whether the 3 instructions i'm removing are actually the correct ones.

**Comment by ljfa-ag** [comment]
Maybe it's better to skip the instructions using GOTO rather than removing them?

**Comment by lumien231** [comment]
Really i should probably not even remove any instructions, i think i'll just add code that simply sets the field again at the end of the constructor, should work better with other asm transforming.

**Comment by ReikaKalseki** [comment]
Personally I would keep removing instructions but verify their opcodes beforehand.

Also, I am not sure potion IDs above 255 will work elsewhere.
