### ISSUE TITLE
[Feature Request] [Cosmetic] ChromatiCraft 

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#682]
Is there any chance you could nerf the particle effect on Aura ivy a bit? Or add a config for it os something?

[This is a bit silly](http://i.imgur.com/zJ73bYG.png)

It spreads really rapidly, including through cave systems, and the sheer amount of particles that gets put off is overwhelming.if you have to be close to it (like, for instance, wandering through a cave).

A minor niggle, I know and I'm not asking for a complete removal, just like 1.2 or 3/5 or something so the effect isn't quite as distracting.

**Comment by ReikaKalseki** [comment]
I am thinking about making it only emit particles if it has air on one of the four sides.

**Comment by 1skandar** [comment]
Yeah. I like the effect, don't get me wrong, just it is just a tad overkill. Not by a lot, but it is enough to make navigating a cave choked with it irritating.

**Comment by TomeWyrm** [comment]
You should have seen the... actually I still have that screenshot.

http://puu.sh/mLbWU/7eaabe116c.png

That is what happened when Reika derped a bit and skipped a full growth check when the ivy grew upwards. The floating ivy are invisible because of the way the renderer works, so all you get is a column of particles.

That was fixed shortly thereafter, you really should have seen it in person :-)

**Comment by ReikaKalseki** [comment]
Done.

**Comment by TomeWyrm** [comment]
Has that fix been pushed to git?

If not, could a short description of the conditions for particles be placed here?

**Comment by ReikaKalseki** [comment]
At least one side that is not the "mount side" or its opposite not being Aura Ivy.

**Comment by TomeWyrm** [comment]
Awesome, so basically the "edges" of the "carpet" will become particle emitters. That will help a lot with caves!
