### ISSUE TITLE
Elemental Manipulator Crash Issue in ChromatiCraft

### ISSUE THREAD

**Issue by Lenzeru** [ReikaKalseki/Reika_Mods_Issues#692]
So recently I have Installed and started playing the Revolution2 mod Pack on ATLauncher which includes Chromaticraft. I got all excited to when I discovered the recipe for the Elemental Manipulator and created it but for some reason whenever I right click with it in my hand it crashes my client.

I play on a MP server with 2 others.. It seems that the other players are able to take the manipulator and use it fine, It only crashes when i use it. I tried reinstalling the entire mod pack (and ATLauncher and it still crashes my client..

I read through the crash report but I dont really understand what its telling me.

[http://pastebin.com/vyVwdp2b](url)

Any assistance in this matter would be much appreciated. :)

**Comment by Aivech** [comment]
Your URL is broken...

[Crash Report](http://pastebin.com/vyVwdp2b)

**Comment by DracoScythem** [comment]
Are you by any chance using MutantCreatures Skeleton Armor?
Because for some reason it (and Galacticraft) are heavily interfering (the latter one doesn't seem to have to do with the crash itself though). It seems like the Skeleton armor is trying to accelerate the bow-like 'charging' (don't really know how to call it) of the Elemental Manipulator thus causing the crash. (As CCs only reference to Vanilla Bow code is the ItemUse enum value I suspect Mutant Creatures to try to influence all items having that value...)

That's what I can read out of that report... if I'm assuming the right thing regarding the armor retry without it active on you player - if it does fix everything Mutant Creatures is the culprit if it doesn't we should at least get a cleaner crash-report (though I doubt that'll be nessescary) :)

**Comment by Aivech** [comment]
> the Skeleton armor is trying to accelerate the bow-like 'charging'

Mutant Creatures has 3 or 4 boss monsters that are "mutant" versions of regular monsters. The skeleton, when killed, supplies the materials required to make a set of armor. I assume this armor does something to allow you to draw a bow faster, and is trying to do it to the elemental manipulator. In this instance, it should also affect most of the botania rods as well.

**Comment by ReikaKalseki** [comment]
Mutant Creatures may well have an error here, but the crash is being generated by "DynSurround" .
