### ISSUE TITLE
ChromatiCraft Mod sorting data

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#719]
I found a strange crash on the client. HardcoreEnderExpansion and Forestry and  ChromatiCraft
if so:
UCH     mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
 UCH     FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar)
 UCH     Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar)
 UCH     <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar)
 UCH     IC2{2.2.817-experimental} [IndustrialCraft 2](2_1_industrialcraft-2-2.2.817-experimental.jar)
 UCH     HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion](7_HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar)
 UCH     Forestry{4.2.11.59} [Forestry for Minecraft](4_1_forestry_1.7.10-4.2.11.59.jar)
 UCH     DragonAPI{1.0} [DragonAPI](0EXT_LIB_RM_DragonAPI 1.7.10 V11b.jar)
 UCE     ChromatiCraft{1.0} [ChromatiCraft](3_RM_ChromatiCraft 1.7.10 V11b.jar)
1 load HardcoreEnderExpansion 
2 load Forestry 
3 load ChromatiCraft

crash:
https://gist.github.com/17d3250a83adf1b2164a8b31b3469d44
if so delete example. HardcoreEnderExpansion or Forestry:
all OK

problem seems is that HardcoreEnderExpansion loaded before ChromatiCraft
when installed Forestry.
since the working version without Forestry. HardcoreEnderExpansion after ChromatiCraft

I will try to fix through "inject Dependencies.json" 
,

```
    {
        "modId": "HardcoreEnderExpansion",
        "deps": [
            {
                "type":"after",
                "target":"ChromatiCraft"
            },
            {
                "type":"before",
                "target":"Forestry"
            }
        ]
    }
```

but it is impossible log:  https://gist.github.com/75a301b6e6fed8d6a7a039816de18e56
tell me how to do?
without Forestry
crash when I did HardcoreEnderExpansion before ChromatiCraft  

```
        "modId": "HardcoreEnderExpansion",
        "deps": [
            {
                "type":"before",
                "target":"ChromatiCraft"
            }
```

https://gist.github.com/8b5163e2e8ec5f16425323ad7aac62c4

**Comment by ReikaKalseki** [comment]
You have a mod sorting exception. And CC is hardcoded to load after DragonAPI, which is hardcoded to load after Forestry.

**Comment by SvEgiiVEteR** [comment]
@ReikaKalseki please tell me how to fix it using inject Dependencies.json?
or it is not a possibly?

**Comment by ReikaKalseki** [comment]
....What?

**Comment by TomeWyrm** [comment]
he's wondering where he needs to load the mod to fix the error. He apparently has a mod that will change load orders.

**Comment by ReikaKalseki** [comment]
That sounds like a very bad idea. Load orders exist for a reason.

**Comment by TomeWyrm** [comment]
@SvEgiiVEteR Just change the new config (update Reika's mods first) and the crash will stop... quit changing the mod load order arbitrarily, and the crash should stop. If there's another mod that is causing you to use this dependency injector, talk to that mod author about fixing the problem, or quit using that mod. Because using that dependency injector will CERTAINLY cause you problems.

**Comment by SvEgiiVEteR** [comment]
@TomeWyrm Thanks looked adjoining theme. and understand what kind of config you.
in 11a no such option. 12 still does not work PlayerAPI

**Comment by TomeWyrm** [comment]
Then you will have to stop using Reika's mods, Hardcore Ender Expansion, Forestry, or PlayerAPI until this is resolved. Because arbitrarily changing load order is an extremely bad idea. Those "before" and "after" entries are there for good reason 99.99999% of the time. As in "this will crash if I don't load before/after this other mod" type of good reason.

You are now seeing something I learned a very long time ago: Not all mods are compatible all the time, and you will need to choose which mods you prefer when problems arise.

**Comment by SvEgiiVEteR** [comment]
@TomeWyrm Ah ... the old days everything was simpler.
I will not give up his mods. I will remove just ChromatiCraft.
his other modes is that they work well)

**Comment by ReikaKalseki** [comment]
v12e has been confirmed to work with PlayerAPI.

**Comment by TomeWyrm** [comment]
He means PlayerAPI
