### ISSUE TITLE
Strange 'a mod tried to access an invalid slot' message when right clicking on steam engine.

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#72]
One of the users on my development server, running [Revolution Pack](https://www.atlauncher.com/pack/revolution), is encountering an odd behavior when right-clicking on RotaryCraft steam engines. He's made a short youtube video of the problem here: https://youtu.be/gEz-vFKVG30

I run the same pack, on the same server and I don't experience the message when clicking on his or any other steam engine. Any ideas?

Haggle1996/RevolutionPack#23

**Comment by ReikaKalseki** [comment]
This is a mod interaction that has happened since 1.5.2. Some mod (possibly multiple mods) have inventory manipulation functionality (eg InvTweaks, Forestry backpacks, etc) and assume a TileEntity has an inventory when opening the GUI. They do not, so attempting to access its "inventory" crashes the game...or would, were it not for the fact I intercept the invalid slot lookup and print that message instead. Because the request comes over a packet, I have no way of determining what mod made the request.

**Comment by ReikaKalseki** [comment]
You know, with my modern knowledge of ASM I might actually be able to add detection for who is actually doing this, and solve this very old mystery. That said, I have doubts it is worth it - it is not like any other mod is going to be making 1.7.10 bugfixes, and they may well have already fixed it in newer versions.
