### ISSUE TITLE
Not Responding crash on powering a flywheel

### ISSUE THREAD

**Issue by ArchAngel075** [ReikaKalseki/Reika_Mods_Issues#734]
Version V12e (Rotary craft / DragonAPI)
Reproduce :
Place a steel shaft, 
Attach a wood flywheel such that the shaft inputs into it,
Place a steel shaft such that it is connected to flywheels output,
Place a DCEngine such that it will power the input shaft.
Use a lever on the DCEngine to power it.
the moment I flip the lever to power the engine my game completely freezes,  ZERO error is produced in the console to provide from the time stamp of me placing and powering the flywheel.

This has been an issue for me since 11b (i first experienced this around 11b, updated to make sure it wasnt fixed)

any material of fly wheel, any input causes this regardless.

[fml-client-latest.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/208248/fml-client-latest.txt)

**Comment by Aivech** [comment]
Try https://gist.github.com for large logs.

EDIT: Wow, 5k+ lines: https://gist.github.com/DaMachinator/26aa5cadde7d6473215a7613b167a021

**Comment by ArchAngel075** [comment]
I decided to rerun my client with only reika mods used to isolate if its not mod interaction related. error still persists (and reduced log from 9mil lines to the 5k+ lines....)

**Comment by TheGuyRunningSouth** [comment]
@ReikaKalseki I'm experiencing the same issue and this can be reproduced on the x64 versions of both Java 7 and Java 8.

**Comment by jakbruce2012** [comment]
Woops, I didn't see this one and made a duplicate.

**Comment by ReikaKalseki** [comment]
I am not sure I can fix this. Flywheels reference some very old code, and the error is coming from something I did not write.

**Comment by redelman** [comment]
Fix it by removing flywheels! I've never used them actually.

**Comment by ghoulsblade** [comment]
this one bit me too and now i cant start my world, can you maybe detect it happening and destroy the flywheel after the server was rebootet ? that would at least save future victims having to worldedit or restore backup

**Comment by ReikaKalseki** [comment]
> can you maybe detect it happening

How am I supposed to detect anything when no code is running?

**Comment by ghoulsblade** [comment]
assuming the endless-loop is inside the flywheel tick code: 

e.g.   set watchdog at start of flyweel-related tick, clear watchdog next tick.
if watchdog isnt cleared after 1 minute, write a statusfile or other persistent state that will destroy the flywheel on next serverstart/chunkload

The server did react to ctrl-C signal and terminated sort of clean after that, so if you can hook up code on that shutdown the watchdog can be a simple global variable with pointing to the suspicous 
flyweel.

If you cant hook into that shutdown code without much hassle, consider starting a global watchdog thread that can continue running when main thread hangs so it can check the watchdog variable.

if the endless loop is in another part of rotary craft tick code, and you know roughly where, set the watchdog there.

Otherwise set it in all mayor rotary related tick and update code starting points and clear it at the end of the current tick, or at the start of every tick.

**Comment by ghoulsblade** [comment]
on server start after watchdog fail:
if you dont know which flywheel caused it, stop (destroy,rotate,empty fuel / charge) the machine that caused it (set the watchdog), if that fails too, list all flyweels currently in loaded chunks and destroy a random one, or the one in the last chunk that was loaded (endless loop when specific chunk is loaded).
Print info accordingly so server admins know what was done and what triggered the watchdog with details if possible.
That server admins could at least keep their world by restarting the server (a few times if needed).

**Comment by Builderb0y** [comment]
Restarting a server multiple times is an unacceptable solution because the player who did it can simply place another one. Anyway, I've looked at some sampling data and I suspect the error is an infinite loop in [TorqueUsage:51](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/TorqueUsage.java#L51):

``` java
while (TEMap.containsValue(false)) {
    //Multimap <Boolean, WorldLocation> invert = ArrayListMultimap.create();
    //Multimaps.invertFrom(Multimaps.forMap(TEMap), invert);
    //recursiveFind(te.worldObj, (TileEntity)invert.get(false).toArray()[0], te);

    List<WorldLocation> c = (List<WorldLocation>)TEMap.invert().get(false);
    if (c != null && !c.isEmpty())
        recursiveFind(te.worldObj, c.get(0).getTileEntity(), te);
}
```

False never gets removed from TEMap from anywhere. I don't know much about how your TileEntityCaches/NestedMaps work, but the only places where TEMap is referenced from in that loop are in the declaration of the loop, and TEMap.invert(), and neither of those set the value of TEMap, nor do they modify it via cross-referencing.

**Comment by ghoulsblade** [comment]
You could ban a griefer doing it repeatedly if the log contains the coords of the destroyed flywheel.
If a fix is impossible, at least a form of self-repair after server restart would be preferrable to world-editing or backup recovery.

**Comment by Builderb0y** [comment]
The log doesn't mention any locations, and neither forcing a crash/killing minecraft nor VisualVM can determine its location. The only thing that _might_ work is a plugin that logs block placement (or territory zones). However, this assumes it logs the location/player who placed it to a file BEFORE the flywheel is allowed to tick, which is not guaranteed if they're not forcibly flushing the data to a file for every line logged. And this is assuming your idea succeeds at clearing them on startup. If it doesn't, you'd have to use MCEdit to remove it every single time.

True, if someone's constantly placing one in an attempt to crash the server repeatedly then they deserve to be banned. However: what if someone doesn't know they're broken, what if they don't figure that out when the server freezes, and what happens if they try to place it again immediately after logging on without waiting to be told that they're broken because "the server froze in the middle of this project, so I'm going to continue where I left off"? And lastly, what if multiple people all don't know it's broken and try to power them?

At that point, you might as well ban flywheels all together, and that has 2 problems as well. 1: I expect some server admins might forget (or choose not to) unban them even after this bug is fixed, and 2: that will probably spread rumors that flywheels are broken forever and should never be used even a year later.

**Comment by ghoulsblade** [comment]
If flywheel can be fixed, that'd be great, but atm it was said that it is unclear if it can be fixed.
So atm just leaving a world corrupting bug without self-repair in that is easy to reproduce by accident would be bad for rotarycraft usage as a whole.
Someone who doesnt intentionally break it will only do it max twice and then tell the admins.

The server still wrote "stopping server" or so when i interrupted it by ctrl-c, so the actual log was intact, no need to flush every line.

The main thread gets stuck in endless loop but a watchdog thread could still write a flyweel-bad.dat file cleanly, and that file could be detected on next server start.
The coords could be written to log on next start as well if they can be determined by the watchdog.
One global watchdog thread for all of rotarycraft is enough, it could check for the 1-minute timeout of the last flywheel for which the tick was started.

**Comment by TheGuyRunningSouth** [comment]
@ghoulsblade The only efficient way to "destroy" a flywheel like that would be to have it automatically break upon being placed.

The best way to handle this situation is for server owners to warn their users about the problem and deal with users who insist on placing flywheels themselves.

And having code that auto-bans a user in a mod file is a bad idea. Poor Reika gets enough crap from the community as it is.

**Comment by TomeWyrm** [comment]
I'm also in the "remove" camp. If there are power sources that don't cause issues, limit the flywheel usage to those sources?

**Comment by Builderb0y** [comment]
The only power sources that don't cause this are the ones with insufficient torque to power them.

**Comment by TomeWyrm** [comment]
Yep, firmly in the "get rid of these" camp

**Comment by ReikaKalseki** [comment]
:D

![](http://i.imgur.com/u6O2oqA.png)
![](http://i.imgur.com/hHIcAzS.png)

**Comment by ArchAngel075** [comment]
Oh i didn't realize this was fixed now, thank you reika, I all ways liked the idea of using flywheels early for various needs (which i forgot but am bound to realize/remember)
