### ISSUE TITLE
Woodcutter won't replant Chromaticraft dye saplings without Infinity enchant

### ISSUE THREAD

**Issue by mystise** [ReikaKalseki/Reika_Mods_Issues#761]
Steps to reproduce:
New world, super flat, redstone ready preset
/chromaprog ADudney maximize all
Build basic woodcutter setup with creative coil (mine is set to 64 Nm at 1024 rad/s)
Place down any of the 16 dye saplings and apply bonemeal
When finished, saplings appear in the output chest but aren't replanted.

I managed to get it to replant a Kuro sapling once, but any further tries on that world or a newly created world failed.

Applying infinity does allow the woodcutter to properly replant.

Mod list:
ChromatiCraft V12e
CodeChickenCore 1.0.7.47
CritterPet V12a
DragonAPI V12e
ElectriCraft V12c
ExpandedRedstone V12a
GeoStrata V12a
NotEnoughItems 1.0.5.118
ReactorCraft V12d
RotaryCraft V12e
UsefulTNT V12a
VoidMonster V12a
Waila 1.5.10
Forge 10.13.4.1614
Launched using MultiMC

Screenshots:
![2016-04-24_16 03 10](https://cloud.githubusercontent.com/assets/246232/14770742/1b24a48a-0a36-11e6-988d-eacba9c83697.png)
![2016-04-24_16 03 13](https://cloud.githubusercontent.com/assets/246232/14770746/1b32b048-0a36-11e6-81c9-0e0fb2f5bf64.png)
![2016-04-24_16 03 21](https://cloud.githubusercontent.com/assets/246232/14770745/1b3295e0-0a36-11e6-8004-24c95afb9cc3.png)
![2016-04-24_16 03 23](https://cloud.githubusercontent.com/assets/246232/14770743/1b320f26-0a36-11e6-9912-14775ccc14ed.png)
![2016-04-24_16 03 25](https://cloud.githubusercontent.com/assets/246232/14770744/1b32530a-0a36-11e6-8cb3-b5f7e1dc6a0a.png)

**Comment by ReikaKalseki** [comment]
Are you sure the tree even dropped a sapling? Did the woodcutter drop any when broken?

Also, this has always worked for me.

**Comment by mystise** [comment]
As shown in the chest (which was empty before running the woodcutter), the tree definitely dropped at least 2 saplings. And no, the woodcutter doesn't drop any saplings when broken in survival mode or creative mode.

I tested with all the vanilla sapling types and they work as expected, and it does drop saplings when broken.

However, I just got it to work in the same world shown above. If the woodcutter you want to use is already placed in world when the world is loaded it works perfectly, but if it is newly placed it only works on vanilla trees for some reason. Any ones placed after loading the world, even if there are ones that work already existing, will have the problem. Reload the world and suddenly they work.

**Comment by ReikaKalseki** [comment]
WTF?

**Comment by DragGon7601** [comment]
Woodcutter definitely has some issues. I came here to see if someone had reported it planting the the wrong sapling. I'm in using an old version (RotaryCraft 1.7.10 V14d/ChromatiCraft 1.7.10 V14d/DragonAPI 1.7.10 V14d) as thats what haggles dev server is using, so Im unsure if I should open an issue. This might have the same root cause, So Ill put the info here.  

I had a set up for nila trees. It had Infinity. And sat over a draw controller with a bank of draws. Should have been enough to hold all the different wood outputs and they had void upgrades to stop them from overflowing. I think I remember it planted a non-nila sapling one time and I broke and replace it, forget what tree though. The other day I came online to find a Natura Redwood had grown where it should have been... The cutter is gone. So are 3 fertility blooms (Had 2 on the nila sapling to speed up its growth) with enrichment vines. Lost 4 of the 8 Ender-lillys I had around one of those blooms. All of the Draws with there Void upgrades that I had used the last of my obsidian on are also missing. And I think it also got half the chest for the dark wood tree, Lest I think that was a double chest.

The woodcutter for the natura dark wood has been there longer and has always planted the right tree... But there have been some fuse wood (I think) saplings in its chest. Figured they sometimes drop other trees

Don't think it matters; but both were/are powered by 4 Wind Turbines, used Wooden shafts & had a wooden gears with cooling fins to get the right torque/Speed.

I remember others in the IRC channel had similar issues... but with sacred oaks and such. Im sure they put it down to going through there nether portal but I cant find a quote for that. But searching my logs I have fond these quotes:

...
Apr 29 02:45:20 [Romantic_Jo]   huh, my tree farm managed to grow a sacred oak.
Apr 29 02:45:27 [Toksyuryel]    fancy
Apr 29 02:45:28 [Romantic_Jo]   and _wrecked_ the machinery
Apr 29 02:47:29 [Toksyuryel]    ah Minecraft tree growth mechanics
Apr 29 02:48:00 [Romantic_Jo]   I woudn't even know how to grow a sacred oak in the first place.
Apr 29 02:48:42 [Toksyuryel]    well if you weren't actually trying to grow one, perhaps it's just a whole bunch of oak saplings in a square?
Apr 29 02:52:26 [nlorence]  how do you get pollen from a tree ?
Apr 29 02:52:52 [Toksyuryel]    oh is it a forestry tree farm?
Apr 29 02:53:03 [nlorence]  apple oak pollen i need
Apr 29 02:53:04 [Toksyuryel]    that would be it then, the trees mutated
Apr 29 02:53:18 [RomanticJo]    I could keep it, it's not _bad_ http://puu.sh/oyTJI/234e2ab432.png
...
Apr 29 06:37:36 [Romantic_Jo]   funny thing about the sacred oak busting my setup:
Apr 29 06:37:56 [Romantic_Jo]   the jabba barrles it busted out created 100s of mk1 and mk2 upgrades.
Apr 29 06:38:05 [Romantic_Jo]   and about 40 hopper facades.
...
Apr 29 08:47:42 [Romantic_Jo]   After the server restart, the tahara sapling that was being planted by the treecutter
Apr 29 08:47:50 [Romantic_Jo]   became a fir sapling.
Apr 29 08:48:05 [Romantic_Jo]   I'm wondering if that's how a sacred oak tree appeared out of nowhere
...

Sorry to always be adding to these "@&#%?!" issues. I do like your mods when they work (that's 99.99% of the time). Thanks for all the fun you give us.

**Comment by ReikaKalseki** [comment]
You can thank @Builderb0y for pestering me to rewrite TreeReader, and @HellFirePVP for the new implementation...which magically fixed this issue.

**Comment by TomeWyrm** [comment]
Thanks @Builderb0y and @HellFirePVP!

**Comment by Savallator** [comment]
Should this fix be in V18b? If so, it is not working. I have other trees in my farm reproducable after every Server restart. One time i got a twilight forest Sortingwood and timewood tree which destroyed the entire farm. If needed, i can provide further info or conduct more tests to pin it down.

**Comment by ReikaKalseki** [comment]
Only if the dye leaves were broken would it do that.

**Comment by Savallator** [comment]
Wait, what? So when the Leaves are gone, and the stump is standing, and then the server restarts, it cannot know which sapling to plant and plants a sapling of the type of the wood?

**Comment by TomeWyrm** [comment]
Correct, and unless the dye trees had their own unique wood type, it's AFAIK unfixable.

**Comment by ReikaKalseki** [comment]
^

**Comment by Savallator** [comment]
Maybe make it possible to lock the Woodcutter to one Type of Sapling? Because as it is right now, it is nearly unusable with the dye-Trees when every Server restart totally wrecks your base by spawning a Twilight Forest tree with massive roots destroying everything. Maybe The Woodcutter could have a GUI slot where you could place a Sapling as a filter. Or, alternaticely, you could set the Sapling by right-clicking, as you would set the infinity enchant. Or, as workaround, add a mode where the Woodcutter does not replant at all and only cuts, then one could replant the correct Sapling by other means.

**Comment by Aivech** [comment]
You could have the woodcutter determine sapling type by whatever is in the chest placed below it.

**Comment by OvermindDL1** [comment]
> Correct, and unless the dye trees had their own unique wood type, it's AFAIK unfixable.

Could always use a special metadata id to specify 'extra data', so that when a tree grows from a saplings then there are associated non-ticking TE's that specify extra information about it (like what kind it was) so you know what to get back, but if placed via any other means then no TE so the information is purposefully lost (to prevent player placing trees exploits).  Forestry does this for example (though on its leaves).

**Comment by ReikaKalseki** [comment]
> Could always use a special metadata id to specify 'extra data', so that when a tree grows from a saplings then there are associated non-ticking TE's that specify extra information about it (like what kind it was) so you know what to get back, but if placed via any other means then no TE so the information is purposefully lost (to prevent player placing trees exploits). Forestry does this for example (though on its leaves).

And how well will that work with tens of thousands generated per Rainbow Forest?

**Comment by Savallator** [comment]
They are not growing from a sapling, but generated in world. The special information would only be necessary when a sapling is GROWN. Of course this is still exploitable. You can get saplings this way you would not get otherwise: find tree with logs, remove leaves, plant woodcutter with infinity, take the sapling.

Edit: Maybe just give the cutter ia single GUI slot for a stack of Saplings, and when infinity is applied, this becomes a template.

**Comment by OvermindDL1** [comment]
> And how well will that work with tens of thousands generated per Rainbow Forest?

As long as the TE ticking is 'false', quite fine.  GT6 spawns tens of thousands of ores every few chunks that have non-ticking TE's on them.  They only eat memory (not much if you batch them up well too) and no processing at all (they are not even on the ticking list so they do not even need to be skipped or anything).  If you are worried about it though you could always, say, put it on the base-most block (the one where the sapling turns into a log) or so?

@Savallator edit sounds quite good.

**Comment by ReikaKalseki** [comment]
> As long as the TE ticking is 'false', quite fine. GT6 spawns tens of thousands of ores every few chunks that have non-ticking TE's on them.

I did this with GeoStrata ores. Between massive inflation of the chunk TE list, a huge amount of NBT data that caused sending the chunk data to clients to choke the connection, and serious problems with data persistence, there are reasons they are disabled.

> put it on the base-most block (the one where the sapling turns into a log) or so?

And if the woodcutter is placed higher up?

These solutions have a multitude of holes and side effects. It is not happening.

**Comment by OvermindDL1** [comment]
> I did this with GeoStrata ores. Between massive inflation of the chunk TE list, a huge amount of NBT data that caused sending the chunk data to clients to choke the connection, and serious problems with data persistence, there are reasons they are disabled.

That is why you need to batch them.  For example, GT6 ores look like solid stone at first, only when a player gets 'near enough' to a chunk then a bulk load of the TE data is sent to the client packed together minimally (since most ores in an area are of the same 3/4/5 types, it makes the packet quite small).  It is highly efficient.  But yes, if you use the normal MC communication channels it really hurts, but that is why Forge added Mod Channel's for network communication efficiently.

> And if the woodcutter is placed higher up?

Ignore it and don't drop as it is now, or have it search 'down' until it either finds it or finds a block that is not of the same log type.

> These solutions have a multitude of holes and side effects. It is not happening.

Indeed, hence why they are being worked out, all are better than the current state though.

**Comment by TomeWyrm** [comment]
A minimalistic GUI sounds like a good idea. One ghost slot with a "lock" button. If you want to farm one tree type exclusively and have restart protection? Specify the sapling type and lock the Woodcutter. If you want to be Frey and farm all 16 with a single Woodcutter? Leave the slot blank, or lock it blank if it turns out that an actual inventory slot is a significantly easier solution.

**Comment by ReikaKalseki** [comment]
The woodcutter already *has* an actual inventory slot, though it is hidden.
