### ISSUE TITLE
[All Mods] Items don't render in the proper direction in Storage Drawers

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#792]
Items render perpendicular to the face of the drawer. Vanilla and other-mod items work just fine.

![2016-05-06_20 05 06](https://cloud.githubusercontent.com/assets/6917535/15089947/2d67688c-13c6-11e6-84bb-90233aea019d.png)
![2016-05-06_20 05 19](https://cloud.githubusercontent.com/assets/6917535/15089948/2d67ad56-13c6-11e6-87ca-a29687e8770e.png)

**Comment by Barhandar** [comment]
Only certain items, presumably ones with different rendering like crystals (and I also presume everything that renders outside of the view when held in hand, like CC working-plants). RoC Metal Flakes and CC chromasaplings/chromaberries work fine.

**Comment by Shahelion** [comment]
Berries have the same issue.

**Comment by ReikaKalseki** [comment]
Literally every one of my items uses a custom renderer (TESR-type items also have their own renderer, which often looks...odd...in hand, but that is irrelevant here) so that I can still use spritesheets.

However, they all have _exactly_ the same renderer, from DragonAPI, and the textures are designed identically (unboosted shards and berries are even on the same texture sheet!):

Berries: https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Textures/Items/items_color.png

Flakes: https://github.com/ReikaKalseki/RotaryCraft/blob/master/Textures/Items/modextracts.png

Shards: https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Textures/Items/shardglow.png

At any rate, like with the TiC casting table or anything else, I cannot fix this without scrapping the renderer.

**Comment by Shahelion** [comment]
Would there be any way to implement a fix for this on SD's end? Like, detect if it's from this mod, and rotate it to fit?

**Comment by ReikaKalseki** [comment]
In theory, yes. Good luck convincing them to do so.

**Comment by Barhandar** [comment]
> Literally every one of my items uses a custom renderer

Then your item renderer fails to account for orientation, that is, renders items on the east-west plane and OP tried to place them on the north-south plane on the drawer, while my drawer face is aligned with E-W plane so I've not had issue. 

Alternately! I'm using a less stupidly fancy looks for SD so the items render as actual icons on texture for me and don't try and pretend to have volume, so they _cannot_ render sideways (without major derping in code). Can't really tell without knowing versions I and OP have installed.

> so that I can still use spritesheets

Is it the _only_ reason for the custom renderer?

> In theory, yes. Good luck convincing them to do so.

@jaquadro, what do you say about this?

**Comment by jaquadro** [comment]
So, knowing nothing about the custom renderer, why is this behavior unfixable in the renderer?  Did you also do anything special to get them to render correctly in vanilla GUIs?

**Comment by ReikaKalseki** [comment]
> Is it the only reason for the custom renderer?

Mostly, though some take advantages of other features (eg Void cells and shift-render capability).

> So, knowing nothing about the custom renderer, why is this behavior unfixable in the renderer?

Because to fix it would break its "normal" behavior.

> Did you also do anything special to get them to render correctly in vanilla GUIs?

That depends on what you mean by "special". I have to apply specific GL transformations - for example, two rotations for inventory mode - to get them to render properly. Other ItemRenderTypes require other operations.

Also, I have no idea what render modes are being used by other mods' renderers; some use Entity, some use Inventory, some use custom.

**Comment by jaquadro** [comment]
> Alternately! I'm using a less stupidly fancy looks for SD so the items render as actual icons on texture for me and don't try and pretend to have volume, so they cannot render sideways (without major derping in code). Can't really tell without knowing versions I and OP have installed.

It's not clear to me what this means.  Are you saying that everything works okay in "fast" render mode, or are you saying that the reported issue is extra severe in "fast" mode because it renders an icon to a plane?

> Also, I have no idea what render modes are being used by other mods' renderers; some use Entity, some use Inventory, some use custom.

For non-block/3D items, SD reimlpements RenderItem's renderItemIntoGUI but is essentially equivalent to the Vanilla implementation.  Unless you've registered the renderInventoryItem hook, in which case that is called instead.

**Comment by ReikaKalseki** [comment]
> renderItemIntoGUI

So ItemRenderType.INVENTORY. In that case, two rotations are applied (from the initial state supplied by Forge). One is 45 degrees left or right, and one is 30 degrees up around the X axis. This is to go from the supplied isometric mode (which has my texture render as if it was the right side of a held block) to "face-on" mode.

https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/ReikaSpriteSheets.java#L236

**Comment by Barhandar** [comment]
> It's not clear to me what this means. 

In pack I'm using items in SDs don't have displayed volume (visible on OP's screenshot), i.e. don't protrude from the flat plane of the drawer. I'm using an older version of Storage Drawers (1.5.15), though.  
~~I'm now going to try to install SD 1.9.7 and check.~~  
Aaaand Reika invalidated the check by releasing v13. But with latest OD and v12 CC I see exactly 0 issues, items render flat on the drawers regardless of the way drawers face, including on framed drawers.

OP, provide modlist. Issue cannot be replicated with Reika's mods and Storage Drawers alone.

> Are you saying that everything works okay in "fast" render mode

Nope, no relation to Minecraft's badly named render modes.

**Comment by jaquadro** [comment]
> Nope, no relation to Minecraft's badly named render modes.

I meant the item render mode in SD itself.  The terminology is borrowed from Vanilla mostly for worse.  "fast" renders icons flat, "fancy" renders them like an item frame.

**Comment by Barhandar** [comment]
> I meant the item render mode in SD itself. The terminology is borrowed from Vanilla mostly for worse. "fast" renders icons flat, "fancy" renders them like an item frame.

Um. I wasn't aware it even _had_ unique config for this. Both the old version's config, and the default freshly generated one, neither of which have issues, are on "fast".  
Let me load on "fancy", then.

Sure enough, all items tested except for saplings (wut? Reika, are you using vanilla renderer for CC saplings?) have rendered sideways on latest SD with "fancy" item rendering, regardless of drawer facing. Checked on vanilla Item Frames, don't have this error.

**Comment by ReikaKalseki** [comment]
> Reika, are you using vanilla renderer for CC saplings?

Any item that is an ItemBlock will, yes.
