### ISSUE TITLE
Game never finishes launching with Reika mods

### ISSUE THREAD

**Issue by pixelas83732** [ReikaKalseki/Reika_Mods_Issues#795]
My game never finishes booting if I have any of reika's mods installed. It works fine without it. I left it for like 2 hours and it never finished.

http://pastebin.com/MdijUL7P

**Comment by ReikaKalseki** [comment]
Did you run out of memory?

**Comment by ReikaKalseki** [comment]
Did you run out of memory? Your log just stops, which is usually triggered by running out of RAM.

**Comment by pixelas83732** [comment]
Thanks for the feedback but that's not the problem; I tried giving it like 8 gigs, and nothing changed.

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by pixelas83732** [comment]
Aside from your mods, removing BigMobs makes it go away. But then I can't log into our server.

**Comment by TomeWyrm** [comment]
What happens if you just have BigMobs and Reika's mods?

**Comment by ReikaKalseki** [comment]
Also, I have never heard of BigMobs before. What _is_ it?

**Comment by pixelas83732** [comment]
It's a mod for our server. And if I have just both of them the problem comes back.

**Comment by ReikaKalseki** [comment]
Then it is the problem. Does it have source available? If not, send me the jar.

**Comment by TomeWyrm** [comment]
Then it's an incompatibility between those two mods. The log stops after "Sending event FMLPostInitializationEvent to mod BigMobs" which is unsurprising.

**Comment by pixelas83732** [comment]
I can't share it, because the guy who makes it say's its copyrighted and I'll be in deep trouble (banned from server, he says maybe even sued) if I give it to anyone. He says the problem is something called asm, but I don't know what that is.

**Comment by TomeWyrm** [comment]
Basically it's someone's fault and nobody will let someone have both halves of the problem to fix it. They're incompatible and probably will be forever, or until Reika and the other mod author can get together directly.

Edit: Apparently I don't know enough about asm. Disregard the following paragraph.

At a guess? BigMobs ASM is modifying something that Reika did as well. This never does good things. In this case it appears to hang the process.

**Comment by Barhandar** [comment]
> I can't share it, because the guy who makes it say's its copyrighted and I'll be in deep trouble (banned from server, he says maybe even sued) 

Can we see his license? Maybe the legal documents about him registering his mod as his intellectual property?  
Either way, the problem is on his side, and most likely ONLY his side. If he threatens to sue you, he's full of hot air, prideful and short-sighted and will not admit fault. So you'll be unable to play with both mods installed. 

I personally would drop BigMobs. In art, there's general trend of obtrusively-watermarked art being low quality and not worth taking in the first place, except to get cheap laughs at artist's expense. I won't be surprised if it holds true for MC mods as well.

**Comment by ReikaKalseki** [comment]
> He says the problem is something called asm, but I don't know what that is.

Then he is either an idiot or a liar. Because though ASM conflicts are a real thing, and they can cause all sorts of issues, the odds of it doing _this_ are so low as to be negligible. ASM conflicts present as NoClassDefFound errors or actual ASM errors (either mine, like NoSuchASMMethodException, or things like ClassFormat "bad type on operand stack"), not a freeze.

> I personally would drop BigMobs.

Unfortunately, that would mean ditching his server, which I presume has both his friends and his time investment.

> I can't share it, because the guy who makes it say's its copyrighted and I'll be in deep trouble (banned from server, he says maybe even sued) if I give it to anyone.

He is very likely making empty threats, especially knowing the rules regarding mods and sharing them. Another thing he is making is me - suspicious. That said, I imagine you are unwilling to send the jar anyways - since they _could_ still ban you - but I have an alternative: Are you familiar with a program called JD-GUI?

**Comment by pixelas83732** [comment]
OK, I downloaded it. What do I do now? Sorry, I'm not used to it.

**Comment by Builderb0y** [comment]
JD-GUI is a program to decompile mods' source code. What reika was asking for was for you to look through big mobs' source to find the problem, but if you're not familiar with it (or coding in general), then it's going to be more effort than it's worth to teach you where to find the relevant information.

Alternatively, do you know how to use VisualVM? It's a program that can "inspect" java applications to see what they're doing, which could also help find the problem.

**Comment by pixelas83732** [comment]
No, I've never heard of VisualVM, and it looks like its really complicated. Can we do something easier?

**Comment by CrystalMageX** [comment]
> Can we do something easier?

(You will need to setup the JDK before you do this)
1. Run Minecraft until it seems to freeze, and do not close the game
2. Note the pid of the java process.
3. Open command prompt
4. Run the command `jstack pid`, replacing pid with the id you noted earlier
5. What is the output of that command?

**Comment by ReikaKalseki** [comment]
Something tells me he will not find that easier....

**Comment by TomeWyrm** [comment]
Oh well, we apparently have people that are willing to walk him through this. Might as well see how far this goes, maybe we can find out why and if there's something that can be done about compatibility (as unlikely as that is).

**Comment by pixelas83732** [comment]
I got the command. http://pastebin.com/Q9LQqqwY

**Comment by TomeWyrm** [comment]
BigMobs was the only mod mentioned. I'm not surprised. Does this give you any useful information Reika, or should we try a different investigative tool?

**Comment by ReikaKalseki** [comment]
java.lang.Thread.State: RUNNABLE
        at mod.bigmobs.BigMobs.postinit(BigMobs.java:29)

His code is stuck in an infinite loop, probably having messed up some check. Go rub his ignorance in his face. And open the bigmobs jar with JDGUI and go to mod/bigmobs/BigMobs, and take a screenshot of line 29.

**Comment by TomeWyrm** [comment]
So... why does it only do this with your mods installed?

**Comment by pixelas83732** [comment]
Is this what you want?

http://i.imgur.com/f6JqtNu.png

**Comment by Barhandar** [comment]
Yes. He is purposefully freezing the game if DragonAPI is detected. This means first, that he's a petty and immature asshole, and second, that he's got something against Reika.

Your options are to drop BigMobs _and_ said friend (and persuade server admin to do the same) because actions must have consequences, somehow manage to persuade him to not be as petty and immature, or wait for Reika to do fun things.
P.S. I suspect the only thing his mod is doing, is upscaling some mobs. I won't be surprised if [MobProperties](http://mods.curse.com/mc-mods/minecraft/224298-mob-properties) can do this (and more) instead, without malicious code.

Temporarily, you also could use a HEX editor to mess up his detection in BigMobs.class (find "DragonAPI" in there and change it to, say "PettyJERK" - keep the amount of symbols the same) and replace said file in the mod's jar.

**Comment by ljfa-ag** [comment]
Then I wonder why he uses Reika's mods on his server. Or not?

**Comment by Barhandar** [comment]
Server'd not start if there were any. He's probably trying to add them to the same client profile to test them out in singleplayer.

> ReikaKalseki: Unfortunately, that would mean ditching his server, which I presume has both his friends and his time investment.

A _friend_ who, when questioned about "game doesn't load when I add X and your mod together", answers "the problem is asm", instead of true "I hate X and have made my mod prevent game from loading if X is detected", is probably not worth said time. While sunk cost fallacy is overrated in general. :V

**Comment by TomeWyrm** [comment]
But community isn't. People value companions and the familiar. Plus it's actually pretty hard for people to find a match between the type of game they like and the people they like. It's why I always yell at people saying "find another server". It often isn't that easy

**Comment by Barhandar** [comment]
Community isn't overrated, but there's a high chance said community will be, or is already being, poisoned by that person. Since they're petty enough to include hostile code _and_ lie about it when asked (also quite likely said person doesn't understand ASM and reflection and just used it as bogeyman, thinking no one will be wise enough to actually check).  
And then it comes up to "are all the other people worth tolerating the toxic person?". And if they aren't (on either side), well, time for another community or social skills for kicking said toxic person out. It's not worth suffering hostilities and possibly being alienated once they start perceiving you as the enemy (which will happen as soon as their pettiness is discovered).

**Comment by ReikaKalseki** [comment]
I see that I was wrong in assuming the freeze was because he did something stupid.....actually, no, that still applies. @pixelas83732, you have two options. Uninstall DragonAPI (and everything else of mine) or uninstall BigMobs (and likely face retribution from the rest of your toxic community). Barhandar linked another mod that can likely suffice for the purpose of BigMobs - field_111264_e is attackDamage and field_111267_a is maxHealth, and these are very simple properties; hell, if I had a mod for which it was relevant, I would add configs for it.

If you do decide to ditch the cluster of idiots who have deceived you into thinking of them as friends, I want to know names, so that they can regret their decisions.

**Comment by Barhandar** [comment]
MobProperties claims to work on NBT-editable properties. attackDamage and maxHealth are NBT Attributes, so it can replace BigMobs fully. Or at least should be able to.

**Comment by TomeWyrm** [comment]
My recommendation if the author of BigMobs isn't the server admin (or close friends with that admin)? Suggest MobProperties as an alternative to BigMobs.

**Comment by pixelas83732** [comment]
There's no way that's gonna happen, sorry. I guess I'll just have to go without reika mods :/

**Comment by ReikaKalseki** [comment]
`>_<`

**Comment by TomeWyrm** [comment]
@pixelas83732 Were you trying to get Reika mods on the server, or in a personal pack? Because if it's a personal pack, reproducing BigMobs would be easy with MobProperties and there would be plenty of people willing to help you (either here or in the MCF thread for MobProperties) replicate the other mod.

If it's a server, I would really strongly suggest ditching BigMobs and the author even if it means finding another server. It won't be easy, but it will almost certainly be worth it. EnderIO, Extra Utilities, Mystcraft, Railcraft, RotaryCraft, ReactorCraft, Thaumcraft, and Mob Properties is a tiny pack, and with the Curse Launcher it's nearly trivial to make that into a pack a server (and most especially its community) could use. Reika's rules are quite easy to follow (blame dishonest jerks for compelling Reika to create them).

Though at this point we're getting off-topic for the issue at hand. Would you like to open a thread on FTB Forums or the Minecraft forums and discuss options at more length? Because I'd LOVE for you to try Reika's mods, and the BigMobs author doesn't sound like good/wholesome people.
