### ISSUE TITLE
ReactorCraft: Control Rods can not be individually raised or lowered

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#811]
1.7.10-V13b

It used to be the case that each control rods can be raised or lowered.  Why is this no longer the case?

**Comment by ReikaKalseki** [comment]
I never changed it.

**Comment by Fatmice** [comment]
Then why does it do nothing when I click on the green squares in the CPU interface?

**Comment by ReikaKalseki** [comment]
Is this a dedicated server?

**Comment by Fatmice** [comment]
Local, so server and client is on the same machine.
Saves+Mods
http://www.mediafire.com/download/wnmzfy0994f9dkd/1.7.10-Thorium_Experiments.7z

Load the thorium savegame, go to nether if I'm not already there.  There should be a portal nearby.  Once there, try to manipulate each rod from the CPU interface of the unfinished reactor test bed.

**Comment by Barhandar** [comment]
> Local, so server and client is on the same machine.

If you're launching 2 things, client + server (joining through multiplayer menu), then it's dedicated server (because you're dedicating different process _with only the server_ to it), local or not. If you're just launching client and going into singleplayer, then it's non-dedicated. If you have a separate _client_ running with LAN server, on which you can play, it's still non-dedicated because you're running a client+server, not server alone.

Loaded up singleplayer, clicking on control rod squares, red or green, makes clicking sound and [generates error in the log](http://pastebin.com/Us4UL7vX) without switching anything.

**Comment by Fatmice** [comment]
Local for me meant single player.  Minecraft is always server+client even in single player, where the server is running on the same machine as the client.

**Comment by Barhandar** [comment]
> Minecraft is always server+client even in single player, where the server is running on the same machine as the client.

Not on same machine, as same process.

**Comment by Fatmice** [comment]
Sigh, how is this pertinent?  Of course it's the same process...it has multiple threads since you are splitting hairs.  It's one launch of Minecraft.  The server should not be dropping any packets.  Very likely this issue is inter-related with the rods all lowered upon reload.  I made two reports since there is also that off chance this is a separate issue.

**Comment by redelman** [comment]
And this is why I always say "singleplayer" or "multiplayer." Then everyone knows what you mean and there is no confusion.

**Comment by ReikaKalseki** [comment]
```
REACTORCRAFT ERROR: Machine/item was deleted before its packet could be received!
[15:07:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: Reika.ReactorCraft.TileEntities.Fission.TileEntityCPU cannot be cast to Reika.ReactorCraft.TileEntities.Fission.TileEntityControlRod
```

...wtf?

**Comment by ReikaKalseki** [comment]
I found it. It was a stupid mistake introduced in a packet system change.
