### ISSUE TITLE
[Assistance] Kcauldron Compatibility.

### ISSUE THREAD

**Issue by Paralaxus** [ReikaKalseki/Reika_Mods_Issues#823]
Hello,

Starting off i really enjoy the works of Reika, such as rotarycraft, reactorcraft, and electricraft.
However the issue is that DragonAPI does not work with Kcauldron, as said in other issues.
I have the latest Kcauldron build as of 2 hours ago, with the latest forge and latest Reika Mods.
I'm not sure what to do now, and i do not want to consider patches as they are against rules.

Is there any permanent fix offered, or maybe something i am doing wrong at this point?

Many thanks in advance.

**Comment by coolsquid** [comment]
KCauldron neither is, nor will be, supported. Reika's mods are intended to work with Forge, not a Bukkit version modified to work somewhat similarly to Forge.

Besides, the KCauldron dev has been extremely uncooperative. Reika has tried to fix KCauldron issues before, but the dev has been actively providing misinformation, illegally redistributed modified copies of DragonAPI, and generally been very hostile.

**Comment by Paralaxus** [comment]
I understand,

But every modded server utilizes them in order to use plugins to filter the modpack to work in the desired themes, thus without the support it cannot be used on 95% of modded servers (citation needed)

**Comment by Paralaxus** [comment]
I saw the hostilities but there needs to be some collaboration in hopes of a better experience in multiplayer, i mean there are other options to fix said issue but i am looking for a legal way.

**Comment by TomeWyrm** [comment]
No, there really doesn't. As I've explained NUMEROUS times, what needs to happen is people need to quit using illegal software, developing for illegal software, and supporting illegal software.

Bukkit was useful, except that it fractured the community; forge is now capable of doing everything that bukkit did... people are just too entrenched in their ways to migrate their plugins to forge.

There are alternatives for nearly every Bukkit plugin amongst the forge ecosystem. Go look. If you need a capability that you can't find? Ask. If it doesn't exist, see if someone with similar functionality would be willing to add that.

Also, what CoolSquid said. The dev is being actively uncooperative, and the problems are because of what HE IS DOING. Reika develops for forge, and the devs working on latest-attempt-of-DMCA-loophole-used-to-be-called-cauldron-after-it-was-MCPC+ whatever it is, was, or will be called? They are responsible for providing an imperfect melding of Bukkit and Forge. It's their responsibility to fix bugs arising from code they did.

**Comment by ReikaKalseki** [comment]
> It's their responsibility to fix bugs arising from code they did.

And by _actually fixing them_, not just copying a given mod, gutting it of anything that might conflict - breaking a dozen other things in the process - and telling people to use that copy instead.

Oh, and @Andrew2070, by "rude", we do not just mean saying, "No, go fix it yourself". We mean this gem of a diatribe:

```
YOU don't want to support YOUR mods on other platforms.
It is still possible to understand.
But when YOU forbid SOMEONE else to support YOUR mods you looks like ass-fucked piggy.
So FUCK YOU Reika! Arrive in Russia and force me to follow you idiotic rules, asshole.
I WILL release patched mods or patches singly for any mods as I want, and no one can forbid to do it. INCLUDING YOU!
```

**Comment by ReikaKalseki** [comment]
https://www.reddit.com/r/feedthebeast/comments/4k2ure/kcauldron_and_conflicts_note_contains_quoted/
