### ISSUE TITLE
auto-inserting iron in blast furnace for hsla steel

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#825]
Trying to automate hsla steel in the blast furnace in a ME system, I noticed the following: Exporting coal, sand and gunpowder via an export bus works just fine, but the tricky thing is the iron: As of effiiency/speed reasons, I want the blast furnace to process always 9 iron ingots. Obviously, this does not work with export buses, so I tried the OpenC Transposer, an adapter with inventory controller upgrade and the OpenP method (pushStackInSlot). Sadly, this does not work either: In an empty blast furnace, the first ingot is exported as expected (in an arbitrary slot), but every other ingot goes in this slot, preventing an efficient exporting method.
For now, I just export into one slot (does not really matter with 100M+ iron), but this is not really satisfying, espc. if you are early game.
If you have the time, could you fix this? Thanks!

**Comment by ReikaKalseki** [comment]
The Blast Furnace, without a pattern, only allows insertion into slots already containing a given item.  This is not a bug. Simply input faster than it is processing.

**Comment by amesgen** [comment]
Thanks for the quick reply. What do you mean with "without a pattern"?

**Comment by ReikaKalseki** [comment]
The recipe pattern can be used to override the normal behavior and allow automated insertion into empty slots. This does not help your use case, but is for things like TRISO and bedrock parts.

**Comment by amesgen** [comment]
Thank you! I will check out the recipe pattern.

**Comment by TomeWyrm** [comment]
It won't allow you to do what you want with Iron > HSLA, which Reika did say. Literally the only method to be always processing HSLA efficiently is to cut off the "fuel" periodically if you can't output the 9 ingots faster than it can operate on them.

**Comment by torqk999** [comment]
found a solution. its a bit pricey at first but will guarantee even distribution. instead of having an import bus on the blast furnace, use a storage bus. this will use the output inventory of the furnace itself as the buffer, and so withdrawing from it will allow the furnace to continue smelting. this does however imply that all 9 slots will be filled with 9 stacks of iron all the time, but if ur at the point where u can afford automation anyway, and still looking for efficiency, its one step closer right? plus it saves from having to even build a separate storage bus. Now just need to solve the problem of automating coke coal production, tempted just to use the rail craft one instead for full automation.

**Comment by torqk999** [comment]
ER MAH GERD! The same setup works for coke coal! wtf! my night has been made! X-D
