### ISSUE TITLE
RC Blast Furnace doesn't get heat from IE External Heater

### ISSUE THREAD

**Issue by RaineAndrews** [ReikaKalseki/Reika_Mods_Issues#843]
I posted an issue on IE's github.  I'm not sure who handles mod interactions (if they handle them at all).

BluSunrize/ImmersiveEngineering#1147

**Comment by ReikaKalseki** [comment]
Because of the progression problems this could cause - heating a blast furnace is gating in multiple places - I will not add mod compatibility on this, unless the system is incapable of generating temperatures in excess of 650 degrees centigrade.

And, as BlueSunrize said, no two mods implement heat the same way. I have never used IE, but unless it uses explicit temperatures, "heat units", like what IC2 uses, are conceptually irreconcilable. Even if it uses temperatures, if it uses F or K (or worse, R), it will not work without deliberate conversion.

---

Actually, there is a way to tell RC your block is "hot like lava", and that would work, but I doubt making a machine use that would make much sense. You could possibly bootstrap it to "is the machine on and heated", so a heated whatever would be equivalent to a lava block.

**Comment by RaineAndrews** [comment]
I didn't mean to subvert your vision.  I just thought it would be more visually appealing the a glob of lava!  Sorry for the trouble.
