### ISSUE TITLE
Dragonapi, remote asset download is stuck

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#846]
hi,
Launched a new modpack and now dragonapi's remote asset download seems to be permanently stuck at 7.93%. The time is still counting up, currently at 1645000 ms.
DragonAPI 1.7.10 V13b.jar

E: After 4h of repeatedly restarting minecraft in the hope that it would manage to download the files and constantly getting stuck and with that having wrong checksums I did a:
wget https://cache.techjargaming.com/reika/ccmusic/explorer.ogg
wget https://cache.techjargaming.com/reika/ccmusic/ethereal\ contact_c.ogg
wget https://cache.techjargaming.com/reika/ccmusic/luminescence.ogg
wget https://cache.techjargaming.com/reika/ccmusic/polychromacy_c.ogg
wget https://cache.techjargaming.com/reika/ccmusic/nightfall.ogg
wget https://cache.techjargaming.com/reika/ccmusic/glowing\ horizons.ogg
wget https://cache.techjargaming.com/reika/ccmusic/singularity.ogg

which finished in about 50 seconds, seriously is there any reason why these files can't be part of the mod jar?

**Comment by ReikaKalseki** [comment]
Did your internet go out midway through? Is your connection speed pitifully low?

> seriously is there any reason why these files can't be part of the mod jar?

Do you want a 200 MB download every time I update? Even if so, I am not about to have to keep uploading that.

**Comment by Turmfalke2** [comment]
No, my connection has been stable for the whole day and using wget I was able to download the files within 50seconds so I don't think it is an issue with my download speed.

**Comment by ReikaKalseki** [comment]
Then maybe it was a hiccup on Techjar's end, though the lack of other reports makes me doubt it.

**Comment by Veronimish** [comment]
For speed up, I get the file path (on cache.techjargaming.com) with a downloader app (free download manager) and place the files in \mods\Reika\ChromatiCraft\Music

Its because im in africa and yes, our internet is not on the top 10 most speedy of the world :p...
I download music during the night and if possible it's finished tomorrow morning...maybe..

actually, the download speed is........ TADAAAAMMMM... 422 o/s :'(
I have a 4M/s internet speed...

In anyway, thanks for your mods and... You don't have plan to made your proper mod pack ?

Best regards
