### ISSUE TITLE
[ChromatiCraft] Random crash, maybe relate to lumen network

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#871]
Since yesterday I have been suffering series of weird crash, and most of them mentioned lumen network and `ConcurrentModificationException`. I have no clue about why those crashes happened, and the only thing I can recall is that, if I am doing something related to lumen network (e.g. starting a new casting, place/remove repeater, or even just using ritual table), then crash will more likely happen.

The following are several examples:
[A crash-report, with file name "crash-2016-05-25_14.49.25-server.txt"](http://paste.ee/p/Mk88V)
[Another crash, with file name "crash-2016-05-25_15.26.49-client.txt"](http://paste.ee/p/Za0Pu)
[Yet another crash, with file name "crash-2016-05-25_20.05.07-client.txt"](http://paste.ee/p/O615L)

[And also a crash happened today, with file name "crash-2016-05-26_19.37.59-server.txt"](http://paste.ee/p/Nya39)
[And another crash happened today as well, with file name "crash-2016-05-26_19.38.06-client.txt"](http://paste.ee/p/ij51R)
[If necessary, the fml log for the last two crash is also here.](http://paste.ee/p/56fXd)

**Comment by ReikaKalseki** [comment]
There is basically nothing I can do to fix CMEs, but they are usually very rare.

**Comment by Zedrimar** [comment]
this is somewhat unrelated but Just out of curiosity.... did you happen to have voxelmap by chance on the client? I saw a new release that was just uploaded yesterday that made the chance of getting a CME much much much rarer. 

If you don't have that mod then I don't know what to say XD

**Comment by 3TUSK** [comment]
Unfortunately I use Mapwriter rather than voexlmap.

**Comment by 3TUSK** [comment]
I notice something interesting:
By some reason I cannot recall immediately, I had the following flags in my jvm arguments:

```
-XX:+UseConcMarkSweepGC -XX:ParallelCMSThreads=3
```

After I removed them everything seems fine now.

**Comment by Zedrimar** [comment]
CMS is deprecated, G1GC works better and is the newer GC

**Comment by 3TUSK** [comment]
So I would like to close this issue right now...

**Comment by ReikaKalseki** [comment]
> CMS is deprecated, G1GC works better and is the newer GC

This is entirely backwards. 'G1' stands for Generation One!

**Comment by redelman** [comment]
G1GC IS the newer GC. The 'G1' stands for Garbage First.

**Comment by ReikaKalseki** [comment]
...And I stand corrected. If G1GC is newer, why was @keybounce referring to it as the older, "legacy" one, which performs worse in nearly all cases?

**Comment by keybounce** [comment]
There have been ... 4? GC's for Java.

The first was a simple "stop the world, and GC on a single thread". That's still the best for small programs because it has the least overhead. It does both the new and tenured collections on a single thread.

There's a parallel new collector, that requires a solo tenured collector (not sure if this one is maintained or not), and a parallel tenured collector that requires a single-threaded new collector. That's the throughput collector, and is still considered the best for batch processing. I don't know why you can't mix both parallel new _and_ parallel old, but last time I checked, you could not.

(Side note: When I was doing large amounts of chunk pre-gen in either 164 or 1710 (I don't remember which), that throughput collector outperformed CMS significantly. At the time, the chunks being pregened did not get released, so it was start up, pregen as much as there was memory for, and then stop. That was using Custom Ore Generation for the pregen.)

CMS was designed for low-pause collection; it does not stop the world in most configurations (I was able to abuse it -- throw enough memory at it, and it's small pauses become big enough to be noticeable). For multi-threaded programs, it has the highest overhead; for Minecraft, with large amounts of unused cores (two single-threaded threads, for the most part) it has the lowest overhead.

G1GC is the newest, and it's designed for low-pause, but it is stop the world, low-pause. Oddly, with no customization arguments, it works wonderfully. I say oddly for two reasons:
1. It's designed for a minimum of 6 GB of heap.
2. Trying to specify a maximum pause time small enough to ensure it won't run into trouble with minecraft's tick rate -- 20 ms -- resulted in horrible performance and massive memory consumption back in J7, enough that I gave up on it (nothing else that I specified did anything to fix that). In J8, with no max pause specified, it "just works".

The older, legacy GC would probably have been the single-threaded, small memory garbage collector -- at least, I can't think of anything else that would fit that. In which post did I refer to the legacy GC?

(NB: Remember, despite being the oldest, it is still the fastest for small memory heaps because it has the least overhead.)

**Comment by ReikaKalseki** [comment]
> In which post did I refer to the legacy GC?

Verbally.

**Comment by TomeWyrm** [comment]
I remember a textual discussion of the garbage collector... probably on one of the "CHC requires GC flag" issues.
