### ISSUE TITLE
[ChromatiCraft]Crash regarding lexicon and death event

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#884]
MC crashes when players do the flow of actions below.
Player opens and saves somewhere in the Lexicon pages, and die.
After respawning, player picks up the Lexicon, press X button.

Crash log
http://pastebin.com/Uubc5vfn

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by Builderb0y** [comment]
So we need to make it reset on death as well. Lovely.

The reason for this is because saving a page directly saves the current GUI object to a static variable, which includes information about the player entity that opened it. When you die and respawn, you get a new player entity, with the same name as the old one. So clicking the X now searches your old (dead) player's hand for a lexicon, and fails.

**Comment by Turmfalke2** [comment]
Or how about storing the information in the book instead of the player?

**Comment by ReikaKalseki** [comment]
Because the GUI object is more complex than that, and is all clientside.

**Comment by TomeWyrm** [comment]
In other words... blame Mojang because their code does derpy things.

**Comment by ReikaKalseki** [comment]
Fixed.
