### ISSUE TITLE
[ChromatiCraft]Ability “Passive Draw” affect only 44 blocks away

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#888]
There seems wrong behavior comparing to source code.
When the ability, “Passive Draw” is activated, the source code says that the effect can be used 1024 blocks away. However, it affect only 44 blocks away in an actual game play.

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by Builderb0y** [comment]
Not sure where you got 1024 from, but the [code](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Storage/TileEntityPowerTree.java#L272) is checking for 2048. You'll also notice that it's checking for distance squared instead of actual distance; this is because it's more performant, and the square root of 2048 is approximately 45.

**Comment by Mr-kk** [comment]
I'm sorry. It seems Finding of I did not have enough. Thank you for teaching me.
