### ISSUE TITLE
GeoStrata: Please add an option to disable Stem Vents from spawning

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#894]
Even with the config set to 0, stem vents still spawn.  I love the additional rock types but the vents are annoying (and sometimes startling!)  Thanks.

**Comment by freyskol** [comment]
Sorry, Reika says it's not gonna happen.

**Comment by TomeWyrm** [comment]
There is a way to work around this issue by using other mods to replace generation. One such mod is in basically every modpack ever. Warning: these will cause more processing while generating terrain. This can get expensive, be careful.

**Comment by ghost** [comment]
I don't understand the flat-out rejection to this request.  I can't be the only one that's annoyed by these loud vents erupting on an irregular schedule...
Anyway, I'm not familiar with the mode TomeWyrm mentioned.  I use BOP terrain generation, and wish to continue using it.  I suppose another option would be to use a tool to replace the vents with air (or water) blocks... Seems like a silly and time consuming workaround though...

**Comment by ReikaKalseki** [comment]
> I don't understand the flat-out rejection to this request. 

The same reason I do not add options to disable Basalt, or Opal (or even all the rocks simultaneously).

**Comment by TomeWyrm** [comment]
I'm feeling generous today. Biomes too many is not a terrain generator, it's a biome mod. It has a terrain generator in it because it mucks with the world type, but I was speaking of ORE generation. Hence Custom Ore Generation, or COFH oregen.

_shrug_ the vents are loud and annoying Reika. The stones are why people install Geostrata or don't (in my case). It used to be the CrC stuff OR the rocks. But not everyone likes making caving more dangerous and obnoxious with a decorative mod :-p

**Comment by ghost** [comment]
> The same reason I do not add options to disable Basalt, or Opal (or even all the rocks simultaneously).

And that reason is...?

I really liked GeoStrata in that it added more stone to the world, which made caving a bit more interesting.  Same with Metallurgy.  I don't have any other reason for using either mod except for decoration - just for fun.  Steam vents are the opposite of fun - they are simply annoying.
I don't even know if a 1.7.10 version existed before vents were put in place - the project page only lists the latest build.

**Comment by ReikaKalseki** [comment]
> And that reason is...?

Because it is part of the mod. GeoStrata is not just about the rocks.

> don't even know if a 1.7.10 version existed before vents were put in place

No, the vents were added in the 1.7.10 update.

**Comment by ghost** [comment]
> Because it is part of the mod. GeoStrata is not just about the rocks.

It used to be...  That's why I liked it.

Well, thanks for replying anyway.  Unless you decide to add an option to disable them I guess I won't be using the mod, which is really a shame.  The rock generation and textures are good.

**Comment by ReikaKalseki** [comment]
Look into TomeWyrm's method.

**Comment by TomeWyrm** [comment]
> GeoStrata is a small mod to diversify underground world generation, making mining and caves more interesting, while simultaneously adding many aesthetic and functional building materials.
> 
> Its basic premise is that it adds a bunch of real-world rock types which overwrite 10-20% of vanilla stone. These rocks generate at realistic depths, and in realistic biomes (for example, shale and limestone, being silt/mud rocks, spawn more often in oceans, and cannot spawn in deserts). These stones cannot overwrite ores, nor do they block ores from spawning.

That's what Geostrata was. You rightfully removed the effect-giving cave crystals because they didn't belong in the mod. What jdrox is trying to tell you is that the vents don't suit the theme of the mod either. I certainly agree with him, the vents are a major reason I don't include geostrata in my instances, and would remove it from any pack that had it if possible. Getting poisoned or being set on fire while mining is not atmospheric to me, it's obnoxious. If I wanted to do something like that, I'd install Glenn's gases
