### ISSUE TITLE
DragonAPI + Gregtech (optionally + HarvestCraft) = insane MC loading time

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#898]
Force Gregtech Ore Compatibility config in D.Api set to false, console loading info set to false (not sure that this matters): game loads about 7 minutes.
Set them to true: HarvestCraft and Greg spammed console. The game didn't load for me for 1 hour (stuck at post-init load GT MetaItems, 7-10 minutes per 1 stage out of 150). HarvestCraft was pre-initing 673 seconds, and 1161 "[FML/harvestcraft]: DRAGONAPI: Logged OreDict registration of" strings were written to log during the pre-init of HC.

**Comment by ReikaKalseki** [comment]
...Are you surprised? GT iterates over all the registries the first time and is well-known for long load times. DragonAPI, especially paired with large mods, can also add substantial (~1-2 minutes) time.

**Comment by MineWitherMC** [comment]
@ReikaKalseki but that's _not_ 1st GT loading. 1st GT loading was much faster than loading with Force GT Compat set to true (about same 7-10 minutes).

**Comment by TomeWyrm** [comment]
It's GREGTECH. He registers all the things, cross-registers all the things, and then registers more things because he feels like it!

You added three of the biggest "register a billion things" mods in minecraft. The interaction is GOING to cause problems. I'd be surprised if GT doesn't register HarvestCraft plants on top of Pam's registrations to the ore dict. Then DragonAPI sanity checks the whole thing because some modders are less than thoughful when coding causing obnoxious errors.

Try to do this without HarvestCraft, with logging turned on, without force compat, and with GT+DragonAPI.

Then try without HarvestCraft, with both options turned on, and GT+DragonAPI

Then finally try with HarvestCraft, with logging on, force compat off, and GT+DragonAPI.

Also, please provide your mod list (It'll be in your client loading log, you can install http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289490-all-versions-mod-lister-lists-the-mods-you-are?comment=37 or you can do a directory list piped into a file from the command line (hold shift, right click, command prompt here, dir > mods.txt, obviously in your mods directory))

**Comment by MineWitherMC** [comment]
Oops. Seems not to be D.Api issue because this doesn't happen on pure D.Api + GT + IC2 + HC. Sorry for bothering...
