### ISSUE TITLE
Electricraft v14b crash on trying to place a block

### ISSUE THREAD

**Issue by BakermanLP** [ReikaKalseki/Reika_Mods_Issues#920]
Hello,
I wanted to place a Immersive Engineering Capacitor to a RF Network Cable out of ElectriCraft. Before placing (no mouse click, only mouse over) the game crashed:
https://paste.ee/p/nd65K

List of used mods and configs: https://github.com/BakermanLP/ProjectRETv8/

**Comment by 1Matthias** [comment]
Ok, after a cursory read through the error log...have you turned off the hidden "heat" block in railcraft? It seems that you moused over one of those and the connection logic thew a hissy fit from what I can tell.

**Comment by ReikaKalseki** [comment]
It is the hidden block:

Caused by: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to cofh.api.energy.IEnergyHandler

**Comment by 1Matthias** [comment]
That thing is a nightmare. It seems that every time I see/hear about it, it is in the context of a crash.

**Comment by TomeWyrm** [comment]
Yep, there's a reason nobody likes "airlike" tile entities. The prime example is the RC heat "Tracking" block. It has screwed up things since its inception. It NEEDS to be removed and the ability tracked in some other manner because nobody uses it in packs SPECIFICALLY because it is probably the second issue on the list of things to try. Number one, incidentally, was "remove optifine" though I guess fastcraft might've supplanted that now and shoved Optifine to 2 and RC heat to 3.

**Comment by ReikaKalseki** [comment]
Airlike tiles are fine, but ones trailed all over the ground everywhere you walk, and which are supposed to not even be known about, are a real issue.

**Comment by TomeWyrm** [comment]
I dunno, TC4 arcane lamp, your floodlight, I could probably pull up other examples if I really thought about it. I try to avoid stuff like that around anything sensitive like plants or multiblocks.
