### ISSUE TITLE
ChromatiCraft crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#934]
Please see the Log file. I don't know what happend.
Log is deleted.

**Comment by coolsquid** [comment]
> Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
> CONFLICT: Biome IDs: biomesoplenty.common.biome.overworld.BiomeGenChaparral @ 653c96b1 @ ID 48 (BiomeGenChaparral & BiomeRainbowForest)
> Check your IDs and change them if possible.
> This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..

**Comment by ghost** [comment]
@coolsquid Not a mod bug? So can you tell me what is "IDs"? And how to "change" it?
And, for users, we are not developers, there is something we do not understand, so we are lazy or extremely foolish? I think this is not a developer should to say.

**Comment by TomeWyrm** [comment]
You are being both right now as well as rude. Instead of asking politely to be taught, you are complaining about something that should be basic knowledge for anyone who is being a pack developer. Which is what you ARE being by adding/removing mods.

However, your inexperience is the cause of this, not a bad attitude.

ID's are the numbers/names Minecraft assigns to things so it knows what they are. This saves space and makes Minecraft run faster. A side effect of it saying that biome ID 1 is Plains, potion ID 12 is Fire Resistance, or block ID 33 is Piston (well, used to be. Now there's something more complicated called dynamic assignment that happens with blocks... they still have ID's those ID's just change for each world.)? Means that if you assign Magical Forest and Plains to biome ID 1, minecraft will get very confused. This can cause all kinds of errors. Hence the crash and error telling you to change them and not post here.

As for how to change them, I'm going to assume you've been using the curse launcher because if you knew how to add mods manually you probably would have noticed the "config" folder. If you use something else, let me know. The basics are to find where your mods are being added, and go one folder "up" to .minecraft or whatever your instance/profile is called, then enter the config folder, and finally either "biomesoplenty" or "Reika" and then find the ids.cfg for Biomes O'Plenty or ChromatiCraft.cfg for ChromatiCraft. And change the conflicting ID.

There is another mod you could add if you're willing to remove whichever of BoP or Reika's mods you just installed (probably Reika's mods) that will make this process easier on you, because manually moving ID's around without knowing what is assigned where means you'll get to reboot... a lot.

This mod is called AntiIDConflict found here: https://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2387300

**Comment by TomeWyrm** [comment]
If you have any questions, my suggestion would be posting to the FTB subreddit, FTB Forums, or Minecraft forums in the appropriate sections for the two forums a post requesting help on learning the basics of being a pack developer. Something similar to "I'm making my first modpack, could I get a tutorial?". Or if you can understand spoken English (your crash log has Chinese characters in it, so I assume that's your first language) this series will likely help you take your first steps. https://www.youtube.com/watch?v=LQqAAdcUltc&list=PLEFA7XVG9rFo5wqRmswRKn60fBPhxIv_8

If you pay attention and ask polite, intelligent questions? This community will teach you many things very gladly. However the vast majority of us are overly tired with people putting in little to no effort of their own and expecting everything of us. Hence the initial reaction you got on this issue.

Please don't hesitate to send me a PM on FTB Forums, Reddit, or Minecraft Forums (I'm TomeWyrm on all 3) when you do make a thread, I'd be glad to help. I've been making mod packs for over 5 years, I've made every common mistake that you usually encounter, and quite a few ones that are my own special brand of stupid. I can help you not make the same mistakes I did ^.^
