### ISSUE TITLE
Chromaticraft elemental sonar causes crash

### ISSUE THREAD

**Issue by GegiO** [ReikaKalseki/Reika_Mods_Issues#938]
Crash report: http://pastebin.com/FTAdftBd

When i activate the sonar it works normally at first. A few seconds later loud pinging sounds start playing and overlaying with each other, and then the game crashes. Sometimes on the edge of the radar i can see one of the symbols blinking quickly.

**Comment by ReikaKalseki** [comment]
Someone reported this recently, but I can do nothing about a crash I cannot trigger.

**Comment by HellFirePvP** [comment]
Getting the same issue with ChromatiCraft 14c, DragonApi 14c, journeymap 5.1.4, openblocks 1.5.1 - appears to happen 100% whenever you cast dimping.

Works fine until the last symbol appears (symbol seems to get "found"/highlighted repeatedly? I'll have a look though CC's src and see if i can find something...), however it doesn't crash for me just by itself. Triggering other sounds causes the same issue as reported above.

**Comment by ReikaKalseki** [comment]
Having used the ability some 200+ times in the last month, _with Optifine, Liteloader, and FastCraft present at that_ - I do not know what to tell you.

**Comment by HellFirePvP** [comment]
i'll create a clone of your project locally if you don't mind, doing some testing and i'll see if i can narrow it down.

**Comment by HellFirePvP** [comment]
Found the source of the issue. It comes from the TickScheduler, changed 3 days ago in DragonAPI -

http://pastebin.com/stKSrsgY

Hope this provides enough information.

Edit: God that took me hours to find this.. Eventhough you might be unable to reproduce it, the bug in the TickScheduler is clearly visible i guess. Comments added to highlight the actual problem for you.

**Comment by ReikaKalseki** [comment]
Looking at your comments, I do not understand what you mean. Every tick, data is reset and populated with the decremented values.

**Comment by HellFirePvP** [comment]
Looking at the data, it's only cleared/reset if both 

!data.isEmpty() && !map.isEmpty()

are true. Given the example in the comment, that's not the case if only 1 sheduledTickEvent of the dimping (the outermost structure) is left in the data. it doesn't get removed and it stays at "1" tick - meaning it will fire every tick from then on. It doesn't get removed from the "data" if there's only 1 value left.

To describe the process more clearly:
for (ScheduledTickEvent evt : data.keySet()) - only runs once (lets assume that since we're looking at the outermost dimping structure)

int val = data.get(evt);
val--;
if (val == 0) - will be 0 now since the dimping reached the outermost structure.

evt.fire(); - event fires as expected.

for-loop ends
if (!data.isEmpty() && !map.isEmpty()) -> data is not empty (true) && map is empty (false) -> false -> data does not get cleared and filled with entries of "map" -> data still contains the last dimping structure sheduled the next tick

This repeates infinitely.

**Comment by ReikaKalseki** [comment]
OH.

**Comment by HellFirePvP** [comment]
No problem.
