### ISSUE TITLE
[Minetweaker] Fluid Registry name issues

### ISSUE THREAD

**Issue by ProxyPlayerHD** [ReikaKalseki/Reika_Mods_Issues#948]
Rotarycraft has "Special" names for its Liquids in the Registry... there are Spaces in the names:
![511653d306ed315ff93aeab7b7a128c6](https://cloud.githubusercontent.com/assets/13576843/15973794/8fba69c2-2f45-11e6-8736-fa21b1b055b2.png)
and Minetweaker doesn't like that. me neither.
![189874c8e915696bf5028422c229ca77](https://cloud.githubusercontent.com/assets/13576843/15973861/d9ee0c92-2f45-11e6-8636-44c43f3681e7.png)

so before i request the Change of the names to include no Spaces, i ask first if there's a way around that. can i get Minetweakers to accept the Whole name with Spaces?

if any Infos are missing i'm playing with the Newest Version (V14d) and Optifine.
also, even thou it's off topic, sometimes Multiblocks like Turbines randomly start Flashing, no idea why. but it's Ignorable.

sry if i messed something up.

**Comment by ReikaKalseki** [comment]
This has been reported before; I know of no way to get MT to accept spaces, but this is a limitation and a design fault on their end. I am not going to change the names, especially since that breaks existing worlds.

As for the flashing turbines: Read the FAQ.

**Comment by Builderb0y** [comment]
Few things in minecraft (especially modded minecraft) are coded to accept spaces in IDs, and very few mods actually add them either. Remember how you can't "/summon Void Monster" and you added specific compatibility for that in dragonAPI's /spawnmobs command? (also applies to most entities in critter pets). Spaces in IDs can cause similar issues all over the place, weather they're entity IDs, fluid IDs, or item IDs. Bibliocraft's armor stand has a space in its item ID as well, making it impossible to /give them. (This may have been fixed already, not sure.)

As nice as it would be to have vanilla commands magically handle spaces acting as both a separator for arguments AND a valid character in said arguments at the same time, the entire command parser would have to be re-written to accommodate that.

There certainly are ways of fixing this on vanilla's and minetweaker's end; either by requiring commas (or some other character) to separate arguments, or by using backslashes to insert a space without treating it as an argument separator, or by replacing spaces with underscores, or some other solution entirely; however, the simple fact is that asking vanilla, and every mod that fails to handle this to suddenly re-design potentially large sections of code in order to accommodate something that rarely ever happens in the first place sounds like a very unreasonable request if you ask me.

I'm not trying to say that other mods shouldn't have to handle spaces in IDs sanely (they should), but I am saying that if fixing the IDs for your fluids/entities didn't break existing worlds, then it absolutely would be something worth fixing on your end too. Perhaps this can be looked into further when you update to 1.9? (or 1.10, since that's already been released too) It may turn out that current worlds may not be updatable at all without getting corrupted, at which point fixing the IDs won't make a difference. If the world can't be updated, then it can't be broken by ID changes.

**Comment by TomeWyrm** [comment]
ID fixers are also a possibility. There have been many mods that do that on first load of a world when forced to make breaking changes.
