### ISSUE TITLE
Control click in DragonAPI update message on OS X does not work

### ISSUE THREAD

**Issue by za3k** [ReikaKalseki/Reika_Mods_Issues#960]
(Reproduced in Space Astronomy pack, v1.4.5) When DragonAPI needs updated, it displays a little box on the upper-left corner of the screen. The mouse cursor is not visible until this is dismissed, and crafting is forced to work on (this may be a mod conflict, I'm not sure). However, it's also impossible to dismiss the box on OS X, because holding control doesn't do anything. Control-clicking is bound to right-click for me, probably related. Please provide an alternative?

Sadly reproduced with Java 1.7u79 (I've been unable to find a way to install java 1.8 on an x64 OS X machine).

**Comment by TomeWyrm** [comment]
You are using v9b. @MJRLegends hasn't updated the pack. Complain to him.

**Comment by TomeWyrm** [comment]
Incidentally... this was a pain to track down. In the future include the versions you are using in the post.

I would also like to request @MJRLegends give a mod list WITH VERSIONS instead of just mod list, and include version changes in the changelog... it's not very helpful to have to download your pack when users that haven't been exposed to support topics before think they're being helpful but instead are giving us a 5-minute puzzle to solve what should have been a 10-second puzzle.

I knew this had been an issue before, but should have been fixed. So my first step was to figure out if za3k was using a pre-fix version of DragonAPI (et al). If it had been provided here, that would have taken seconds; if it had been on your thread, it would have taken maybe a minute; instead I had to boot up a launcher I rarely use (I could have even had to install it, but I do actually use Curse and FTB just to obtain the packs, simply because it's the only reasonable way to do so. I use MultiMC as my launcher of choice because it's better in SO many ways for day-to-day running, organization, management, and troubleshooting) download your pack, and then check the files for versions (luckily Curse let me do that in the launcher).

There's a reason the major packs do things in a certain way, it gives useful information to everyone :-)

**Comment by ReikaKalseki** [comment]
@MJRLegends: You came and complained on this issue tracker about this issue. **_Why the hell have you not yet updated to the fixed version, released 7 months ago**_? And you have updated the pack since then, _last month_; why did you _deliberately_ exclude my mods from that? This is how modpacks get their permission revoked.

**Comment by MJRLegends** [comment]
@ReikaKalseki no i changed the theme of the mod pack a fair bit, in the progress removed a few mods (not just yours) and to bring more a focus to other mods in the mod pack that the whole mod pack is based around e.g galacticraft, as for the update for dragon api i will update at some point but if its not broken why change it you know. I understand this issue has been posted here but i didnt ask them :P i will look in to getting it updated for you in then next version if it doesn't have any issues with other mods i have in the mod pack and if it does i will be in touch

**Comment by MJRLegends** [comment]
@ReikaKalseki and i fully understand that any issue with the mod (because im using a older version) is on me and shouldnt be reported to you if the issue has already been fixed :)

**Comment by ReikaKalseki** [comment]
If you are not using the mods, remove them. And as long as you _are_ using them, it is your duty to update them. Now make your choice.

**Comment by MJRLegends** [comment]
@ReikaKalseki i said i will look at updating so give me the benefit of a doubt that i will try....

**Comment by TomeWyrm** [comment]
Except you didn't remove them like you said you did in the changelog. They're still in there... so... I don't get it

**Comment by MJRLegends** [comment]
i said i will look at updating the dragon api for the next update for the mod pack (dont know when the mod pack update will be probably in the next month maybe less as im very busy)

**Comment by ReikaKalseki** [comment]
What makes me angry is that you had at least one update cycle where you outright ignored my updates, and from what I hear from others you even started using third-party downloads to subvert the Curse system, a **direct** violation of modpack rule #6, which also states as follows:

> **Deliberate use of unauthorized releases is grounds for permanent denial of pack permission.**

**Comment by TomeWyrm** [comment]
Especially because you can just update fastcraft and dragonapi, break no mods in any way, and release that version of the pack, in less time than it took you to respond to this issue tracker in the first place.

**Comment by mystise** [comment]
Related to the original post but not to the followups: Somehow holding Command on the Mac works as Ctrl but only in Reika's mods. Don't ask me why. _shrug_ So you should be able to dismiss the notifications by holding command to detach the mouse then clicking the X.

**Comment by ReikaKalseki** [comment]
I use `GuiScreen.isCtrlKeyDown()`. It explicitly handles Mac.

**Comment by TomeWyrm** [comment]
Didn't you use another call in v9? I recall this being an issue when you released v10, and then fixed in v10

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by MJRLegends** [comment]
@ReikaKalseki your be pleased to know that i have removed the dragon api from the mod pack :P

**Comment by TomeWyrm** [comment]
We are all happy you decided to stop being in violation of the rules. We're sorry to see you stop using Reika's mods, but greatly prefer that outcome to you using outdated versions. Thank you for making a choice and taking action @MJRLegends
