### ISSUE TITLE
[DragonAPI] Bad Resource Reload Timing When Liteloader is Present

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#97]
Edit: DragonAPI reloads the resources at the wrong time when liteloader is present. Fix: reload upon world entry instead of onGameLoaded

**Comment by ReikaKalseki** [comment]
What is your MagicCrops version?

**Comment by Zedrimar** [comment]
none, don't have it this time :/

**Comment by Ianaver** [comment]
If you really should know my mod list here it is, no magical crops XD

![mods](https://cloud.githubusercontent.com/assets/8153290/8147579/b8ee1a24-1226-11e5-8825-e3d8525893c1.PNG)

**Comment by madolinn** [comment]
I have a feeling it's an issue with the newer CodeChickenCore lib.

> ```
>    at Reika.RotaryCraft.ModInterface.NEI.LavaMakerHandler.loadUsageRecipes(LavaMakerHandler.java:137)
>     at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
> ```

It's weird that it keeps bouncing back and forth between these two functions. It only does it twice, but I suspect that they're doing nearly the same thing and it's causing an issue.

**Comment by Zedrimar** [comment]
yeah but whats weird is that it doesn't do it for all items...

**Comment by Zedrimar** [comment]
@ReikaKalseki I did find that the recommended version of codechicken core and NEI did fix the flake and usage crash.... for now. Someone who knows where to report issues to code chicken should do that as I don't know where to. Keep this open for now, I have some research to do on the matter before I consider this fixed.

**Comment by Zedrimar** [comment]
I consider this fixed IF recommended versions of NEI and codechicken core are used however I am not sure what mod is conflicting here

**Comment by Zedrimar** [comment]
@ReikaKalseki @1Matthias I have found the following to be conflicting mod(s) that cause this

Railcraft
EnderIO
Ichun
liteloader

if EIO or RC or ichun is present wih RoC (and cores) and liteloader the issue exists.

**Comment by ReikaKalseki** [comment]
I doubt LiteLoader is responsible.

**Comment by Zedrimar** [comment]
@ReikaKalseki Well I did test it multiple times and that mod combo only when liteloader was present caused the crash.. I told mumfrey in case he might find the solution. It could just be an error that as a side effect causes the crash.

**Comment by ReikaKalseki** [comment]
I fail to see how liteloader would trigger an NEI crash.

**Comment by Zedrimar** [comment]
me too but all I know is that something is being weird....

**Comment by Zedrimar** [comment]
@ReikaKalseki You were right on the fact that liteloader it self was making the crash (I never doubted you) however after talking to mumfrey on the situation, he showed me a snippet of code here: https://github.com/ReikaKalseki/DragonAPI/blob/17e7da9bba9b0bb8eafa249512666876cfc0e84b/DragonAPIInit.java#L475-L476 and it shows that although you did take the right action, it was simply timed badly. You instead should have the resources reload upon world entry (I tested this by forcing a reload when I entered my test world) and after doing that everything worked as it should with no crashes what so ever!

Edit: I did get the crash on my pack after doing the reload.... not sure what happened there just threw another misuse exception but this one may be on NEI's end... It seems again that DragonAPI is repeating a function already used by NEI and the redundant function should be removed on your end.

http://pastebin.com/1w1TYxVX

**Comment by ReikaKalseki** [comment]
Resource reloading causes a 30-second game freeze. Doing it once on loading is fine. Doing it every time I load a world or log into a server is not.

Also, I specifically added that code _because_ of LiteLoader, and have had no issues with it myself.

**Comment by Zedrimar** [comment]
@ReikaKalseki well I guess it hates me and I can't do anything about it, but is there anything that can prevent the two functions from overlapping and causing the crash (NEI and DragonAPI)?

**Comment by ReikaKalseki** [comment]
Bring mumfrey here so we can discuss this directly.

**Comment by Zedrimar** [comment]
done, I PM'd him on minecraft forum so just wait a bit

**Comment by Mumfrey** [comment]
You could have just @mentioned me, I track my github notifications pretty closely.

As for the error, I have absolutely no idea what's going on as I don't deal with any Forge stuff, I just remember from a while back someone saying that resource reload was breaking when people were using DragonAPI and I assumed you fixed it your end because eventually people stopped complaining about it.

For its part, liteloader isn't particularly picky about resource reloading, it basically registers mod containers as resource packs at `preinit` (discovery) time, and then does a single hit of resource reload during the `init` phase (not sure where that happens in relation to Forge's init stages, it's basically called from right after EntityRenderer gets bootstrapped). Basically as long as that happens then litemods are happy.

What's confusing me is why this is happening at all, liteloader basically shouldn't do anything that could cause this, which is why I wondered if the fix for the resource issue was actually the problem. As in, it's potentially the _correct_ fix but maybe where it's happening in the startup phases is causing something else (maybe in NEI or another mod) to get initialised too soon, and be null. If that makes any sense.

Would it be worth removing the fix for liteloader and seeing if the issue goes away, and if it does then maybe move the fix somewhere else? If it _doesn't_ go away then I can look into things in liteloader, but I honestly wouldn't really know where to start with that because I don't even touch items or anything of that ilk, liteloader's basically a client-side framework so it doesn't touch world items at all.

**Comment by ReikaKalseki** [comment]
I added the call because I noticed - both firsthand and from other people - that LiteLoader, for some reason, causes some resource issues with my mods. I do some weird things with the resource engine, [the sound registry in particular](https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/DirectResourceManager.java), so this is not so much of a surprise. However, causing a reload fixes the issue so long as it happens _after_ all of LL's code runs.

But this triggering a crash, much less one in NEI, makes zero sense.

**Comment by Mumfrey** [comment]
> But this triggering a crash, much less one in NEI, makes zero sense.

Exactly, I have literally no idea what's causing it to happen.

**Comment by Ianaver** [comment]
@Mumfrey @ReikaKalseki There are a few mods that I have found that when added to the mix with reika's mods, NEI and liteloader cause the crash:

EnderIO
Railcraft
Torched (Ichun)

**Comment by Zedrimar** [comment]
@Mumfrey @ReikaKalseki 

Good news: 

Its gone, even with my large pack. I updated some mods even liteloader and I guess that fixed it for now.

Bad news: 

we shall never know what caused this in the first place...
Edit: likely a corrupted mod

**Comment by Bogdan-G** [comment]
@Ianaver, anomaly, without a very detailed debug may not be able to keep track.

---

These anomalies have become frequent occurrence it would be time to alter the system or make it more orderly.  The farther away the more than newer and more game mods, then harder and harder all. This is not good. Members more mods install the game, more and more mods change. It takes a more global solution.

**Comment by Zedrimar** [comment]
@Bogdan-G yeah I know that however I can't reproduce this anymore, so no logs or debug sadly...
