### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by leytilera** [ReikaKalseki/Reika_Mods_Issues#986]
when i start minecraft there is a crash. i can see that chromaticraft issuses the crash but not why. http://pastebin.com/S413Kqrr

**Comment by redelman** [comment]
I don't see what makes you think this is Chromaticraft related since it isn't mentioned in the stack trace at all, but here's a couple of things:

Update Reika's mods. v13b is old and unsupported. I see since you have EnderIO 2.3.0.t3_beta, you're aware of the bug regarding the staff of travelling (or at least, your pack maker is). However, t3 wasn't an official release, so update that to at least build 426, and endercore while you are at it.

And update your Java. That won't fix anything, but 1.8.0u25 is really out of date.

**Comment by leytilera** [comment]
it dont works. the same crash

**Comment by ReikaKalseki** [comment]
This issue is entirely one in Equivalent Energistics.

**Comment by redelman** [comment]
I saw that immediately myself, but figured I'd take the time to get someone
to upgrade some old things. :D :D :D
