### ISSUE TITLE
Interaction with Harder Wildlife Seasons

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#991]
During Harder Wildlife's winter months, ocean chunks generate with ice covering the top layer. In nicer weather, these melt into water; however, at this point, I believe it's already interfered with CrC dungeon generation, as [these](https://github.com/ReikaKalseki/ChromatiCraft/blob/ab50161a0c3c02b084ba50ab34507ebcc2f825fb/World/DungeonGenerator.java#L151-L157) lines from DungeonGenerator only check for water and flowing water. Perhaps it could be expanded to include ice as well, to account for a winter ocean?

**Comment by ReikaKalseki** [comment]
That would put the depth tests on the surface, and not the ocean floor, necessitating more special-casing. On top of that, I would need to add yet more special handling for cases where ice makes the ocean too shallow to safely generate in. And on top of _that_, what about a hypothetical case where the ice is more than one block thick?

**Comment by redelman** [comment]
It's really only a little special casing, and Harder Wildlife is pretty
popular. It definitely makes the game more interesting, and your other mods
harder, believe it or not. As for the second case (ice making the ocean too
shallow to generate), I'd say simply generate anyway. The ice is only there
in the colder months, otherwise it's a water block. If the ice makes the
ocean too shallow, then it would be too shallow even during the warm months
where the ice would have been water. The third case is purely hypothetical,
as I'm near completely positive that Harder Wildlife only ever places 1 ice
block.

**Comment by ReikaKalseki** [comment]
It significantly complicates an already-complicated method.

**Comment by Haggle1996** [comment]
And here I thought it was as simple as adding Block.ice to the two conditionals. :P

**Comment by ReikaKalseki** [comment]
No, because then it would simply try generating on top of the ice. I would need to check for "ice with water below, but if so, then move the checks downward until it was the ocean floor".

`getTopSolidOrLiquidBlock`, stupidly, does not return the top liquid block. It returns the ocean floor.

**Comment by TomeWyrm** [comment]
goddamnit Mojang...
